restart-prompt-question = { -brand-short-name }'u yeniden başlatmak istediğinizden emin misiniz?
restart-prompt-title = { -brand-short-name }'u yeniden başlatın
appmenuitem-restart-browser =
    .label = Yeniden başlat
copy-all-urls =
    .label = Tüm Sekme Bağlantılarını Kopyala
copy-url =
    .label = Sekme Bağlantısını Kopyala
unload-tab =
    .label = Sekmeyi Kapat
new-private-tab =
    .label = Yeni Özel Sekme
    .tooltiptext = Yeni özel sekme aç
open-all-links-private =
    .label = Tüm Bağlantıları Özel Sekmelerde Aç
open-all-private =
    .label = Tümünü Özel Sekmelerde Aç
open-link-private =
    .label = Bağlantıyı Yeni Özel Sekmede Aç
open-private-tab =
    .label = Yeni Özel Sekmede Aç
private-tab =
    .label =
        { $isPrivate ->
            [true] Özel Sekmeden Çık
           *[false] Özel Sekme Oluştur
        }
status-bar =
    .label = Durum Çubuğu
update-application-manual =
    .label = Güncellemeleri asla kontrol etme (önerilmez)
    .accesskey = N
bookmarks-bar-position-header = Sık Kullanılanlar Çubuğu Konumu
bookmarks-position-bottom =
    .label = Alt
bookmarks-position-top =
    .label = Üst
dynamic-theme-header = Dinamik Temalar
dynamic-theme-auto =
    .label = Dinamik Olarak Açık/Koyu Modunu Ayarla
dynamic-theme-dark =
    .label = Karanlık Modu Zorla
dynamic-theme-light =
    .label = Açık Modu Zorla
geolocation-api-header = Coğrafi Konum API'si
geolocation-description = Bazı web siteleri çalışabilmek için konum bilginize ihtiyaç duyar. Eğer bir web sitesi konumunuzu bulamadığı için çalışmıyorsa, lütfen bu seçeneği etkinleştirin ve tekrar deneyin.
geolocation-api-enabled =
    .label = Etkinleştir
geolocation-api-disabled =
    .label = Devre Dışı Bırak
restart-header = Menü Öğesini Yeniden Başlat
restart-purge-cache =
    .label = Tarayıcı yeniden başlatıldığında hızlı yeniden başlatma önbelleğini temizle
restart-require-confirmation =
    .label = Yeniden başlatma onayı gerektir
restart-show-button =
    .label = Panel kullanıcı arayüzünde yeniden başlat düğmesini göster
statusbar-header = Durum Çubuğu
statusbar-contrast-text =
    .label = Kontrast durum çubuğu metin rengi
statusbar-enabled =
    .label = Durum Çubuğunu Göster
statusbar-show-links =
    .label = Bağlantıları göster
tab-additional-header = Ek Sekme Tercihleri
insert-after-current =
    .label = Geçerli sekmeden sonra yeni sekme ekle
insert-related-after-current =
    .label = Geçerli sekmeden sonra ilgili yeni sekmeyi ekle
pinned-icon-only =
    .label = Sabitlenmiş sekmeleri küçültüp yalnızca site simgesini göster
tab-feature-header = Sekme Bağlam Menüsü
enable-copy-active-tab =
    .label = Yalnızca etkin sekmeden URL'yi kopyala
show-copy-all-urls =
    .label = Tüm sekme URL'lerini kopyala menü öğesini göster
show-copy-url =
    .label = Kopyala sekmesi URL menü öğesini göster
show-duplicate-tab =
    .label = Yinelenen sekme menü öğesini göster
show-unload-tab =
    .label = Boşalt sekmesi menü öğesini göster
tab-position-header = Sekme Çubuğu Konumu
tab-bar-bottom-above =
    .label = Durum çubuğunun üstünde
tab-bar-bottom-below =
    .label = Durum çubuğunun altında
tab-bar-top-above =
    .label = Adres çubuğunun üstünde
tab-bar-top-below =
    .label = Adres çubuğunun altında
enable-javascript =
    .label = JavaScript'i Etkinleştir
load-images =
    .label = Resimleri otomatik olarak yükle
preferences-doh-setting-ultra =
    .label = Ultra Koruma
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name }, maksimum koruma için Waterfox'un gizlilik rölesi aracılığıyla Oblivious HTTP ile güvenli DNS kullanacaktır.
preferences-doh-ultra-detailed-desc-1 = DNS sorgularını DNS sağlayıcısından bile gizlemek için Waterfox'un Oblivious HTTP rölesini kullanır
preferences-doh-ultra-detailed-desc-2 = HTTPS üzerinden standart DNS'nin ötesinde ek bir şifreleme katmanı sağlar
preferences-doh-ultra-detailed-desc-3 = Maksimum DNS gizlilik koruması - ziyaret ettiğiniz siteleri kimse göremez
preferences-doh-ultra-fallback-mode = Yedek davranış:
preferences-doh-ultra-fallback-allowed = Güvenli DNS başarısız olursa sistem DNS'ine geri dönülmesine izin ver
preferences-doh-ultra-fallback-disabled = Asla sistem DNS'ine geri dönmeyin (güvenli DNS başarısız olursa siteler yüklenmeyebilir)
ref-header = HTTP Yönlendirici Başlığı
send-referrer-header-0 =
    .label = Yönlendirici başlığını asla gönderme
send-referrer-header-1 =
    .label = Yalnızca bağlantılara ve benzer öğelere tıklandığında yönlendirici başlığını gönder
send-referrer-header-2 =
    .label = Tüm isteklerde yönlendirici başlığını gönder (Varsayılan)
webrtc-header = WebRTC eş bağlantısı
enable-webrtc-p2p =
    .label = WebRTC eş bağlantısını etkinleştir
pane-theme-title = Görünüm & His
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animasyonlar
appearance-header = Görünüm
autohide-hidden-header = Otomatik Gizle & Gizli
bookmark-header = Sık Kullanılanlar Çubuğu
center-header = Merkez
font-header = Yazı tipleri
full-screen-header = Tam ekran
icons-header = Simgeler
interface-component-header = Arayüz Bileşenleri
media-player-header = Medya Oynatıcı
nav-bar-header = Gezinme Çubuğu
panels-header = Paneller
rounding-header = Yuvarlama
sidebar-header = Kenar çubuğu
tab-bar-header = Sekme Çubuğu
theme-header = Tema
preset-title = Ön Ayarlar
lepton-style =
    .label = Lepton Stili
proton-style =
    .label = Proton Stili
waterfox-defaults =
    .label = Waterfox Varsayılanları
auto-blur-tabs =
    .label = Sekmeleri Otomatik Bulanıklaştır
auto-hide-back =
    .label = Geri Düğmesini Otomatik Gizle
auto-hide-bookmarkbar =
    .label = Sık Kullanılanlar Çubuğunu Otomatik Gizle
auto-hide-forward =
    .label = İleri Düğmesini Otomatik Gizle
auto-hide-navbar =
    .label = Gezinme Çubuğunu Otomatik Gizle
auto-hide-pageaction =
    .label = Sayfa Eylemini Otomatik Gizle
auto-hide-sidebar =
    .label = Kenar Çubuğunu Otomatik Gizle
auto-hide-tabbar =
    .label = Sekme Çubuğunu Otomatik Gizle
auto-hide-tabs =
    .label = Sekmeleri Otomatik Gizle
center-navbar-text =
    .label = Merkez Gezinme Çubuğu Metni
center-tab-content =
    .label = Merkez Sekme İçeriği
center-tab-label =
    .label = Yalnızca Merkez Sekme Etiketi
close-button-hover =
    .label = Birden fazla sekme açıkken seçili sekmenin üzerine gelindiğinde sekmeyi kapat düğmesini göster
compact-bookmark-menu =
    .label = Sık Kullanılanlar Menüsü Dolgusunu Azalt
compact-context-menu =
    .label = Bağlam Menüsü Dolgusunu Azalt
compact-navbar-popup =
    .label = Navigasyon Çubuğu Açılır Penceresi Dolgusunu Azalt
compact-panel-header =
    .label = Panel Başlığı Dolgusunu Azalt
disable-panel-animate =
    .label = Uygulama menüsü paneli animasyonunu devre dışı bırak
disable-sidebar-animate =
    .label = Kenar çubuğu paneli animasyonunu devre dışı bırak
drag-space =
    .label = Sabit Sürükleme Alanını Etkinleştir
enable-cyan-accent-color =
    .label = Camgöbeği Vurgu Rengi
enable-default-accent-color =
    .label = Varsayılan Vurgu Rengi
enable-menu-transparency =
    .label = Menü şeffaflığını etkinleştir
enable-panel-transparency =
    .label = Panel şeffaflığını etkinleştir
enable-system-accent-color =
    .label = Sistem Vurgu Rengi
enable-waterfox-theme-0 =
    .label = Tüm temalarda Waterfox tema özelleştirmelerini etkinleştir
enable-waterfox-theme-1 =
    .label = Waterfox temalarında Waterfox tema özelleştirmelerini etkinleştir
enable-waterfox-theme-2 =
    .label = Waterfox tema özelleştirmelerini devre dışı bırak
full-panel-strip =
    .label = Tam Genişlikte Uygulama Menüsü Ayırıcı
remove-panel-strip =
    .label = Renkli Uygulama Menüsü Ayırıcısını Kaldır
hide-all-icons =
    .label = Tüm Simgeleri Gizle
hide-bookmarkbar-icon =
    .label = Sık Kullanılanlar Çubuğu Simgelerini Gizle
hide-bookmarkbar-label =
    .label = Sık Kullanılanlar Çubuğu Etiketlerini Gizle
hide-disabled-menuitems =
    .label = Devre Dışı Bırakılmış Menü Öğelerini Gizle
hide-sidebar-header =
    .label = Kenar Çubuğu Başlığını Gizle
hide-tab-icons =
    .label = Sekme Simgelerini Gizle
tree-auto-attach-same-site-orphan-caption =
    .value = Konum çubuğundan, sık kullanılanlardan, geçmişten veya diğer durumlardan geçerli sekmeyle aynı web sitesine sahip yeni sekme: Birlikte aç
    .accesskey = w
hide-urlbar-iconbox =
    .label = URL Çubuğu Simge Kutusunu Gizle
monospace-font =
    .label = Sayfa için tek aralıklı yazı tipini etkinleştir
monospace-font-theme =
    .label = Tema için tek aralıklı yazı tipini etkinleştir
show-mac-menu-icons =
    .label = Mac Menü Simgelerini Göster
show-menu-icons =
    .label = Menü Simgelerini Göster
square-button-edges =
    .label = Kare Düğme Köşeleri
square-checkbox =
    .label = Kare Onay Kutusu
square-field =
    .label = Kare Giriş Alanı Köşeleri
square-menu-item =
    .label = Kare Bağlam Menüsü Öğesi Köşeleri
square-menu-panel =
    .label = Kare Uygulama Menüsü Panel Köşeleri
square-menu-popup =
    .label = Kare Bağlam Menüsü Paneli Köşeleri
square-panel-item =
    .label = Kare Uygulama Menüsü Öğesi Köşeleri
square-tab-edges =
    .label = Kare Sekme Köşeleri
tab-context-line =
    .label = Sekme Bağlam Satırı
telemetry-page-subtitle = Waterfox, kurulumunuzla ilgili telemetri verilerini toplamaz - tarayıcı oluşturulurken tüm telemetri modülleri devre dışı bırakılır. Tarayıcınızda yaptıklarınız sadece sizin tarafınızdan bilinir.
telemetry-privacy-policy = Gizlilik Politikası
onboarding-grassroots-title = Taban hareketlerini desteklemek
onboarding-grassroots-subtitle = Bağımsız ve tabandan gelen bir tarayıcı olan Waterfox'u kullandığınız için teşekkür ederiz. Desteğinizle, piyasadaki büyük oyunculara sürdürülebilir bir alternatif oluşturuyoruz.
tabbrowser-confirm-session-restore-checkbox = Önceki pencereleri ve sekmeleri aç
pane-tree-title = Ağaç Yapılı Dikey Sekmeler
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Ağaç yapılı dikey sekmeler
sidebar-tree-vertical-tabs =
    .label = Ağaç yapılı dikey sekmeler
tree-header = Ağaç Yapılı Dikey Sekmeler
tree-appearance-header = Görünüm
tree-sticky-active-tab =
    .label = Aktif Sekme
    .accesskey = k
tree-behavior-header = Sekmelerin ağaç görünümü
tree-drop-links-on-tab-behavior-load =
    .label = Sekmeye yükle
tree-drop-links-on-tab-behavior-newtab =
    .label = Yeni alt sekme aç
tree-successor-tab-control-level-in-tree =
    .label = Ağaç yapısındaki önceki sekmeye odaklan
tree-drop-links-on-tab-behavior-ask =
    .label = Nasıl işlem yapılacağını her zaman bana sor
tree-successor-tab-control-level-caption =
    .value = Geçerli sekme son alt sekme olarak kapatıldığında
    .accesskey = h
tree-successor-tab-control-level-never =
    .label = Her zaman bir sonraki sekmeye odaklan (tarayıcı veya diğer uzantıların kontrolüne saygı göster)
tree-successor-tab-control-level-simulate-default =
    .label = Her zaman bir sonraki sekmeye odaklan
tree-tree-double-click-behavior-caption =
    .value = Bir sekmeye çift tıklandığında
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Sekmeyi kapat
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Ağaç yapısını daralt/genişlet
tree-tree-double-click-behavior-toggle-none =
    .label = Hiçbir şey yapma
tree-tree-double-click-behavior-toggle-sticky =
    .label = Sekme çubuğunun kenarlarına yapıştır / Sekme çubuğunun kenarlarından ayır
tree-auto-attach-header = Sekme ağacının otomatik düzenlenmesi
tree-auto-attach-child-end =
    .label = Ana sekmenin son alt öğesi
tree-auto-attach-child-next-to-last-related-tab =
    .label = Ana sekmenin alt sekmesi, son açılan alt sekmenin yanında
tree-auto-attach-child-top =
    .label = Ana sekmenin ilk alt sekmesi
tree-auto-attach-independent =
    .label = Bağımsız sekme
tree-auto-attach-next-sibling =
    .label = Ana sekmenin bir sonraki kardeş sekmesi
tree-auto-attach-no-control =
    .label = (kontrol yok)
tree-auto-attach-sibling =
    .label = Ana sekmenin kardeş sekmesi
tree-auto-attach-on-any-other-trigger-caption =
    .value = Diğer tetikleyicilerden sekmeler: Birlikte aç
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = Sekmeyi şu şekilde çoğalt
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Orta tıklama için, yeni boş sekme aç
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Yeni boş sekme aç
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Diğer Uygulamalardan Yeni Sekme: Birlikte aç
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = Mevcut sekmeden bir sekme açıldığında, onu şu şekilde aç:
    .accesskey = D
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Sabitlenmiş sekmelerden yeni alt sekmelerin eklenme konumu (kök sekmeler olarak görünecektir)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Ağaç yapısının sonu
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Son açılan alt öğenin yanında veya açık olan öğenin yanında
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Kontrol yok (tarayıcı veya diğer sekme uzantılarının kararına saygı gösterin)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = Ağaç yapısının en üst kısmı (açık olana yakın)
tree-auto-sticky-header = Sekme çubuğu aşağı kaydırıldığında sekmeler kenarlara yapışık kalır
tree-faviconize-pinned-tabs =
    .label = Sabitlenmiş sekmeleri sadece simgeleriyle göster
    .accesskey = S
tree-sticky-sharing-tab =
    .label = Sekmelerin Paylaşımı Kamera/Mikrofon/Ekran
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Ses Çalınan Sekmeler
    .accesskey = y
tree-auto-collapse-expand-subtree-on-attach =
    .label = Yeni bir ağaç yapısı göründüğünde, diğerlerini otomatik olarak daralt
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Bir sekmeye odaklanıldığında, onun ağaç yapısını genişlet ve diğerlerini otomatik olarak daralt
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = Bir bağlantı veya URL dizesi sekmeye bırakıldığında
    .accesskey = l
waterfox-blocker-header = Reklam Engelleme
waterfox-blocker-intro-description = Reklamları, takip kodlarını ve diğer gereksiz istekleri daha iyi sayfa yüklemeleri ve daha az dikkat dağınıklığı için engeller.
waterfox-blocker-setting-on =
    .label = Açık
waterfox-blocker-setting-on-summary = Sayfa yüklemelerine minimal etki ile reklamları ve takipçileri engeller.
waterfox-blocker-setting-on-description = Waterfox aşağıdakileri engeller:
