; This Source Code Form is subject to the terms of the BrowserWorks Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at http://mozilla.org/MPL/2.0/.
; This file is in the UTF-8 encoding
; All strings must be less than 600 chars.
[Strings]
TitleText=Ukuvuselela kwe-%MOZ_APP_DISPLAYNAME%
InfoText=I-%MOZ_APP_DISPLAYNAME% ifaka ukuvuselelwa kwakho futhi kuzoqala maduze…
BrowserWorksMaintenanceDescription=Isevisi ye-BrowserWorks Maintenance iqinisekisa ukuthi unenguqulo yakamuva futhi ephephile ye-Waterfox kukhompyutha yakho. Ukugcina i-Waterfox isesikhathini kubaluleke kakhulu ngokuphepha kwakho kokuxhunyiwe, futhi i-BrowserWorks incoma kakhulu ukuthi ugcine lesevisi inikwe amandla.
