restart-prompt-title = Genstart { -brand-short-name }
restart-prompt-question = Er du sikker på, at du vil genstarte { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Genstart
copy-url =
    .label = Kopiér Faneblad Link
copy-all-urls =
    .label = Kopiér Alle Faneblad Links
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Åbn alle i private faneblade
open-all-links-private =
    .label = Åbn alle links i private faneblade
open-private-tab =
    .label = Åbn i en ny privat fane
new-private-tab =
    .label = Nyt Privat Faneblad
    .tooltiptext = Åbn en ny privat fane
open-link-private =
    .label = Åbn link i nyt privat faneblad
status-bar =
    .label = Status Bjælke
tab-position-header = Placering Af Fanebjælke
tab-bar-top-above =
    .label = Top over adresselinje
tab-bar-top-below =
    .label = Top under adresselinje
tab-bar-bottom-above =
    .label = Nederst over statuslinjen
tab-bar-bottom-below =
    .label = Nederst under statuslinjen
tab-additional-header = Yderligere Faneblad Indstillinger
pinned-icon-only =
    .label = Formindsk fastgjorte faner for kun at vise site-ikonet
insert-after-current =
    .label = Indsæt nyt faneblad efter nuværende faneblad
insert-related-after-current =
    .label = Indsæt relateret nyt faneblad efter nuværende faneblad
dynamic-theme-header = Dynamiske Temaer
dynamic-theme-dark =
    .label = Gennemtving Mørk Tilstand
dynamic-theme-light =
    .label = Tving Lystilstand
dynamic-theme-auto =
    .label = Dynamisk Set Lys/Mørk Tilstand
restart-header = Genstart Menupunkt
restart-show-button =
    .label = Vis genstart knap i PanelUI
restart-purge-cache =
    .label = Ryd hurtig genstart af cache ved genstart af browseren
restart-require-confirmation =
    .label = Kræv genstart bekræftelse
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Vis kopiér fane url menupunkt
enable-copy-active-tab =
    .label = Kopier kun URL fra aktiv fane
show-copy-all-urls =
    .label = Vis kopiér alle faneblade URL'er menupunkt
show-unload-tab =
    .label = Vis afindlæs fane menupunkt
statusbar-enabled =
    .label = Vis Statuslinje
statusbar-show-links =
    .label = Vis links
statusbar-contrast-text =
    .label = Kontrast statuslinje tekstfarve
bookmarks-bar-position-header = Bogmærker Værktøjslinje Position
bookmarks-position-top =
    .label = Øverst
bookmarks-position-bottom =
    .label = Bund
geolocation-api-header = Geolocation API
geolocation-description = Nogle websteder kræver, at din placering fungerer. Hvis et websted ikke fungerer som følge af, at det ikke er muligt at finde din placering, skal du aktivere denne præference og prøve igen.
geolocation-api-enabled =
    .label = Aktiver
geolocation-api-disabled =
    .label = Deaktivér
send-referrer-header-0 =
    .label = Send aldrig referrer header
send-referrer-header-1 =
    .label = Send kun referrer-headeren, når du klikker på links og lignende elementer
send-referrer-header-2 =
    .label = Send referrer header på alle forespørgsler (Standard)
enable-webrtc-p2p =
    .label = Aktiver WebRTC peer connection
load-images =
    .label = Indlæs billeder automatisk
enable-javascript =
    .label = Aktiver JavaScript
webrtc-header = WebRTC peer forbindelse
ref-header = Http Referrer Header
statusbar-header = Status Bjælke
private-tab =
    .label =
        { $isPrivate ->
            [true] Afslut Privat Faneblad
           *[false] Gør Privat Faneblad
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
pane-theme-title = Look & Feel
category-theme =
    .tooltiptext = { pane-theme-title }
waterfox-defaults =
    .label = Waterfox Defaults
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-blur-tabs =
    .label = Auto Blur Tabs
auto-hide-back =
    .label = Auto Hide Back Button
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
hide-sidebar-header =
    .label = Hide Sidebar Header
center-tab-label =
    .label = Center Tab Label Only
square-tab-edges =
    .label = Square Tab Corners
center-navbar-text =
    .label = Center Nav Bar Text
square-button-edges =
    .label = Square Button Corners
square-menu-item =
    .label = Square Context Menu Item Corners
square-menu-popup =
    .label = Square Context Menu Panel Corners
show-mac-menu-icons =
    .label = Show Mac Menu Icons
drag-space =
    .label = Enable Fixed Drag Space
monospace-font =
    .label = Enable monospaced font for page
compact-context-menu =
    .label = Reduce Context Menu Padding
tab-bar-header = Tab Bar
panels-header = Panels
media-player-header = Media Player
telemetry-privacy-policy = Privacy Policy
full-screen-header = Full screen
onboarding-grassroots-title = Supporting the grassroots
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
preset-title = Presets
font-header = Fonts
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
