restart-prompt-title = Επανεκκίνηση { -brand-short-name }
restart-prompt-question = Είστε βέβαιοι ότι θέλετε να κάνετε επανεκκίνηση του { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Επανεκκίνηση
copy-url =
    .label = Αντιγραφή Συνδέσμου Καρτέλας
copy-all-urls =
    .label = Αντιγραφή Όλων Των Συνδέσμων Καρτέλας
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Άνοιγμα όλων σε ιδιωτικές καρτέλες
open-all-links-private =
    .label = Άνοιγμα όλων των συνδέσμων σε ιδιωτικές καρτέλες
open-private-tab =
    .label = Άνοιγμα σε νέα ιδιωτική καρτέλα
new-private-tab =
    .label = Νέα Ιδιωτική Καρτέλα
    .tooltiptext = Άνοιγμα νέας ιδιωτικής καρτέλας
open-link-private =
    .label = Άνοιγμα συνδέσμου σε νέα ιδιωτική καρτέλα
status-bar =
    .label = Γραμμή Κατάστασης
tab-position-header = Θέση Γραμμής Καρτέλας
tab-bar-top-above =
    .label = Πάνω από τη γραμμή διευθύνσεων
tab-bar-top-below =
    .label = Πάνω κάτω από τη γραμμή διευθύνσεων
tab-bar-bottom-above =
    .label = Κάτω πάνω από τη γραμμή κατάστασης
tab-bar-bottom-below =
    .label = Κάτω κάτω από τη γραμμή κατάστασης
tab-additional-header = Πρόσθετες Προτιμήσεις Καρτέλας
pinned-icon-only =
    .label = Σμίκρυνση καρφιτσωμένων καρτελών για εμφάνιση μόνο του εικονιδίου της ιστοσελίδας
insert-after-current =
    .label = Εισαγωγή νέας καρτέλας μετά την τρέχουσα καρτέλα
insert-related-after-current =
    .label = Εισαγωγή νέας καρτέλας μετά την τρέχουσα καρτέλα
dynamic-theme-header = Δυναμικά Θέματα
dynamic-theme-dark =
    .label = Εξαναγκασμός Σκοτεινής Λειτουργίας
dynamic-theme-light =
    .label = Λειτουργία Φωτισμού
dynamic-theme-auto =
    .label = Δυναμική Ρύθμιση Φωτός/Σκοτεινής Λειτουργίας
restart-header = Επανεκκίνηση Στοιχείου Μενού
restart-show-button =
    .label = Εμφάνιση κουμπιού επανεκκίνησης στον Πίνακα
restart-purge-cache =
    .label = Εκκαθάριση προσωρινής μνήμης γρήγορης επανεκκίνησης κατά την επανεκκίνηση του περιηγητή
restart-require-confirmation =
    .label = Απαιτείται επιβεβαίωση επανεκκίνησης
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Εμφάνιση αντιγράφου καρτέλας στοιχείο μενού url
enable-copy-active-tab =
    .label = Αντιγραφή URL μόνο από την ενεργή καρτέλα
show-copy-all-urls =
    .label = Εμφάνιση αντιγραφής όλων των στοιχείων μενού urls καρτέλας
show-unload-tab =
    .label = Εμφάνιση ξεφόρτωσης στοιχείου μενού καρτέλας
statusbar-enabled =
    .label = Εμφάνιση Γραμμής Κατάστασης
statusbar-show-links =
    .label = Εμφάνιση συνδέσμων
statusbar-contrast-text =
    .label = Χρώμα κειμένου γραμμής κατάστασης αντίθεσης
bookmarks-bar-position-header = Θέση Γραμμής Εργαλείων Σελιδοδεικτών
bookmarks-position-top =
    .label = Πάνω
bookmarks-position-bottom =
    .label = Κάτω
geolocation-api-header = Geolocation API
geolocation-description = Ορισμένες ιστοσελίδες απαιτούν την τοποθεσία σας για να λειτουργήσει. Αν ένας ιστότοπος δεν λειτουργεί ως αποτέλεσμα του να μην είναι σε θέση να βρει την τοποθεσία σας, παρακαλώ ενεργοποιήστε αυτήν την προτίμηση και προσπαθήστε ξανά.
geolocation-api-enabled =
    .label = Ενεργοποίηση
geolocation-api-disabled =
    .label = Απενεργοποίηση
send-referrer-header-0 =
    .label = Ποτέ μην στέλνετε την κεφαλίδα παραπομπής
send-referrer-header-1 =
    .label = Στείλτε την κεφαλίδα παραπομπής μόνο όταν κάνετε κλικ σε συνδέσμους και παρόμοια στοιχεία
send-referrer-header-2 =
    .label = Αποστολή της κεφαλίδας παραπομπής σε όλες τις αιτήσεις (Προεπιλογή)
enable-webrtc-p2p =
    .label = Ενεργοποίηση σύνδεσης WebRTC peer
load-images =
    .label = Αυτόματη φόρτωση εικόνων
enable-javascript =
    .label = Ενεργοποίηση JavaScript
webrtc-header = Σύνδεση μέσω δικτύου WebRTC
ref-header = Κεφαλίδα Αναφορών HTTP
statusbar-header = Γραμμή Κατάστασης
private-tab =
    .label =
        { $isPrivate ->
            [true] Έξοδος Ιδιωτικής Καρτέλας
           *[false] Δημιουργία Ιδιωτικής Καρτέλας
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
disable-sidebar-animate =
    .label = Disable sidebar panel animation
waterfox-defaults =
    .label = Waterfox Defaults
enable-menu-transparency =
    .label = Enable menu transparency
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
hide-sidebar-header =
    .label = Hide Sidebar Header
auto-hide-forward =
    .label = Auto Hide Forward Button
square-button-edges =
    .label = Square Button Corners
center-tab-label =
    .label = Center Tab Label Only
square-tab-edges =
    .label = Square Tab Corners
center-navbar-text =
    .label = Center Nav Bar Text
show-mac-menu-icons =
    .label = Show Mac Menu Icons
panels-header = Panels
drag-space =
    .label = Enable Fixed Drag Space
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
onboarding-grassroots-title = Supporting the grassroots
media-player-header = Media Player
monospace-font =
    .label = Enable monospaced font for page
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
compact-context-menu =
    .label = Reduce Context Menu Padding
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
square-checkbox =
    .label = Square Checkbox
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
