restart-prompt-title = Restart przeglądarki { -brand-short-name }
restart-prompt-question = Czy na pewno chcesz ponownie uruchomić przeglądarkę { -brand-short-name } ?
appmenuitem-restart-browser =
    .label = Zrestartuj
copy-url =
    .label = Kopiuj URL karty
copy-all-urls =
    .label = Kopiuj URL wszystkich kart
unload-tab =
    .label = Usuń z pamięci
open-all-private =
    .label = Otwórz wszystkie w prywatnych kartach
open-all-links-private =
    .label = Otwórz wszystkie odnośniki w prywatnych kartach
open-private-tab =
    .label = Otwórz w nowej prywatnej karcie
new-private-tab =
    .label = Nowa prywatna karta
    .tooltiptext = Otwórz nową prywatną kartę
open-link-private =
    .label = Otwórz odnośnik w nowej prywatnej karcie
status-bar =
    .label = Pasek stanu
tab-position-header = Pozycja paska kart
tab-bar-top-above =
    .label = Na górze nad paskiem adresu
tab-bar-top-below =
    .label = Na górze pod paskiem adresu
tab-bar-bottom-above =
    .label = Na dole nad paskiem stanu
tab-bar-bottom-below =
    .label = Na dole pod paskiem stanu
tab-additional-header = Dodatkowe preferencje kart
pinned-icon-only =
    .label = Wyświetlaj tylko ikonę przypiętych kart
insert-after-current =
    .label = Nowa karta za aktualną kartą
insert-related-after-current =
    .label = Nowa powiązana karta za aktualną kartą
dynamic-theme-header = Dynamiczne motywy
dynamic-theme-dark =
    .label = Wymuś Tryb Ciemny
dynamic-theme-light =
    .label = Wymuś Tryb Jasny
dynamic-theme-auto =
    .label = Automatycznie zmień tryb jasny/ciemny
restart-header = Opcja restart w menu
restart-show-button =
    .label = Wyświetlaj przycisk restartu na panelu
restart-purge-cache =
    .label = Czyść pamięć podręczną szybkiego restartu podczas restartu przeglądarki
restart-require-confirmation =
    .label = Wymagaj potwierdzenia restartu
tab-feature-header = Menu kontekstowe kart
show-duplicate-tab =
    .label = Wyświetlaj opcję 'duplikuj kartę'
show-copy-url =
    .label = Wyświetlaj opcję 'kopiuj adres URL karty'
enable-copy-active-tab =
    .label = Kopiuj adres URL jedynie z aktywnej karty
show-copy-all-urls =
    .label = Wyświetlaj opcję 'kopiuj adresy URL wszystkich kart'
show-unload-tab =
    .label = Wyświetlaj opcję 'usuń z pamięci'
statusbar-enabled =
    .label = Wyświetlaj pasek stanu
statusbar-show-links =
    .label = Wyświetlaj linki na pasku stanu
statusbar-contrast-text =
    .label = Kontrastowy kolor adresu URL na pasku stanu
bookmarks-bar-position-header = Położenie paska zakładek
bookmarks-position-top =
    .label = Na górze
bookmarks-position-bottom =
    .label = Na dole
geolocation-api-header = Geolokalizacja
geolocation-description = Niektóre strony internetowe wymagają twojej lokalizacji do poprawnego działania. Jeżeli strona nie działa prawidłowo z powodu problemu z ustaleniem lokalizacji, włącz geolokalizację i spróbuj ponownie wczytać stronę.
geolocation-api-enabled =
    .label = Włącz
geolocation-api-disabled =
    .label = Wyłącz
send-referrer-header-0 =
    .label = Nigdy nie będzie wysyłał nagłówka odsyłającego
send-referrer-header-1 =
    .label = Będzie wysyłał nagłówek odsyłający, jedynie podczas klikania na linki i podobne elementy
send-referrer-header-2 =
    .label = Będzie wysyłał nagłówek odsyłający w przypadku wszystkich żądań (Domyślnie)
enable-webrtc-p2p =
    .label = Włącz połączenie WebRTC P2P
load-images =
    .label = Automatycznie wczytuj obrazy
enable-javascript =
    .label = Włącz obsługę JavaScript
webrtc-header = Połączenie WebRTC P2P
ref-header = Nagłówek HTTP odsyłający
statusbar-header = Pasek stanu
private-tab =
    .label =
        { $isPrivate ->
            [true] Ustaw jako zwykłą kartę
           *[false] Ustaw jako prywatną kartę
        }
preset-title = Szablony
waterfox-defaults =
    .label = Domyślne ustawienia Waterfox
rounded-corners =
    .label =
        { $isRounded ->
            [true] Włącz kwadratowe rogi
           *[false] Włącz zaokrąglone rogi
        }
auto-hide-tabbar =
    .label = Automatycznie ukrywaj pasek kart
auto-hide-back =
    .label = Automatycznie ukrywaj przycisk powrotu
square-button-edges =
    .label = Kwadratowe rogi przycisków
hide-tab-icons =
    .label = Ukryj ikony kart
center-tab-label =
    .label = Center Tab Label Only
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
panels-header = Panele
onboarding-grassroots-title = Supporting the grassroots
media-player-header = Odtwarzanie multimediów
show-mac-menu-icons =
    .label = Show Mac Menu Icons
auto-hide-sidebar =
    .label = Automatyczne ukrywanie paska bocznego
hide-all-icons =
    .label = Ukryj wszystkie ikony
disable-sidebar-animate =
    .label = Disable sidebar panel animation
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
enable-menu-transparency =
    .label = Włącz przezroczystość menu
drag-space =
    .label = Enable Fixed Drag Space
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Kwadratowe rogi kart
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
telemetry-privacy-policy = Polityka prywatności
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Ukryj nagłówek paska bocznego
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Pasek górny
full-screen-header = Pełny ekran
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Kwadratowy przycisk wyboru
enable-waterfox-theme-2 =
    .label = Wyłącz dostosowywanie wyglądu Waterfox
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
auto-blur-tabs =
    .label = Automatyczne rozmywanie kart
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Pokaż ikony menu
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Pasek nawigacyjny
sidebar-header = Pasek boczny
enable-panel-transparency =
    .label = Włącz przezroczystość panelu
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Zastosuj dostosowywanie wyglądu Waterfox dla wszystkich motywów
auto-hide-navbar =
    .label = Automatycznie ukrywaj pasek nawigacyjny
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Zastosuj dostosowywanie wyglądu tylko dla motywów Waterfox
bookmark-header = Pasek zakładek
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Wygląd
font-header = Czcionki
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Wyłącz automatyczne chowanie
           *[false] Włącz automatyczne chowanie
        }
center-tab-content =
    .label = Wyśrodkuj zawartość karty
auto-hide-tabs =
    .label = Automatyczne ukrywanie kart
auto-hide-bookmarkbar =
    .label = Automatycznie ukrywaj pasek zakładek
center-all =
    .label =
        { $isCentered ->
            [true] Wyłącz środkowanie
           *[false] Włącz środkowanie
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Wyłącz tryb kompaktowy
           *[false] Włącz tryb kompaktowy
        }
icons-header = Ikony
tabbrowser-confirm-session-restore-checkbox = Otwórz poprzednio otwarte okna i karty
tab-context-line =
    .label = Tab Context Line
