restart-prompt-title = 重启 { -brand-short-name }
restart-prompt-question = 您确定要重启 { -brand-short-name } 吗？
appmenuitem-restart-browser =
    .label = 重新启动
copy-url =
    .label = 复制标签链接
copy-all-urls =
    .label = 复制所有标签链接
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = 在私有标签中打开所有
open-all-links-private =
    .label = 在私有标签中打开所有链接
open-private-tab =
    .label = 在新的私人选项卡中打开
new-private-tab =
    .label = 新建私人选项卡
    .tooltiptext = 打开新的私有标签页
open-link-private =
    .label = 在新的隐私选项卡中打开链接
status-bar =
    .label = 状态栏
tab-position-header = 标签栏位置
tab-bar-top-above =
    .label = 顶部地址栏
tab-bar-top-below =
    .label = 顶部地址栏
tab-bar-bottom-above =
    .label = 状态栏上方底部
tab-bar-bottom-below =
    .label = 底部状态栏下
tab-additional-header = 附加标签首选项
pinned-icon-only =
    .label = 收缩置顶的标签页以只显示站点图标
insert-after-current =
    .label = 在当前标签后插入新标签
insert-related-after-current =
    .label = 在当前标签后插入相关的新标签
dynamic-theme-header = 动态主题
dynamic-theme-dark =
    .label = 强制暗色模式
dynamic-theme-light =
    .label = 强制光线模式
dynamic-theme-auto =
    .label = 动态设置灯光/暗色模式
restart-header = 重启菜单项
restart-show-button =
    .label = 在面板界面中显示重启按钮
restart-purge-cache =
    .label = 浏览器重启时清理快速重启缓存
restart-require-confirmation =
    .label = 需要重新启动确认
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = 显示复制标签 url 菜单项
enable-copy-active-tab =
    .label = 仅从活动标签中复制 URL
show-copy-all-urls =
    .label = 显示复制所有标签页地址菜单项
show-unload-tab =
    .label = 显示卸载标签菜单项
statusbar-enabled =
    .label = 显示状态栏
statusbar-show-links =
    .label = 显示链接
statusbar-contrast-text =
    .label = 对比状态栏文本颜色
bookmarks-bar-position-header = 书签工具栏位置
bookmarks-position-top =
    .label = 顶端
bookmarks-position-bottom =
    .label = 底部
geolocation-api-header = 地理位置API
geolocation-description = 某些网站需要您的位置才能运行。 如果一个网站因无法找到您的位置而无法运行，请启用此选项并重试。
geolocation-api-enabled =
    .label = 启用
geolocation-api-disabled =
    .label = 禁用
send-referrer-header-0 =
    .label = 从不发送推荐信头
send-referrer-header-1 =
    .label = 仅当点击链接和类似元素时发送推荐信头
send-referrer-header-2 =
    .label = 发送所有请求的推荐信头(默认)
enable-webrtc-p2p =
    .label = 启用 WebRTC 节点连接
load-images =
    .label = 自动加载图像
enable-javascript =
    .label = 启用 JavaScript
webrtc-header = WebRTC 节点连接
ref-header = HTTP 推荐信头
statusbar-header = 状态栏
private-tab =
    .label =
        { $isPrivate ->
            [true] 退出私有选项卡
           *[false] 创建私人标签
        }
auto-blur-tabs =
    .label = Auto Blur Tabs
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
hide-sidebar-header =
    .label = Hide Sidebar Header
square-button-edges =
    .label = Square Button Corners
drag-space =
    .label = Enable Fixed Drag Space
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font =
    .label = Enable monospaced font for page
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
center-tab-label =
    .label = Center Tab Label Only
disable-sidebar-animate =
    .label = Disable sidebar panel animation
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
panels-header = Panels
enable-menu-transparency =
    .label = Enable menu transparency
onboarding-grassroots-title = Supporting the grassroots
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = Media Player
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
