restart-prompt-title = 重启 { -brand-short-name }
restart-prompt-question = 您确定要重启 { -brand-short-name } 吗？
appmenuitem-restart-browser =
    .label = 重新启动
copy-url =
    .label = 复制标签链接
copy-all-urls =
    .label = 复制所有标签链接
unload-tab =
    .label = 卸载标签页
open-all-private =
    .label = 在私有标签中打开所有
open-all-links-private =
    .label = 在私有标签中打开所有链接
open-private-tab =
    .label = 在新的私人选项卡中打开
new-private-tab =
    .label = 新建私人选项卡
    .tooltiptext = 打开新的私有标签页
open-link-private =
    .label = 在新的隐私选项卡中打开链接
status-bar =
    .label = 状态栏
tab-position-header = 标签栏位置
tab-bar-top-above =
    .label = 顶部地址栏
tab-bar-top-below =
    .label = 顶部地址栏
tab-bar-bottom-above =
    .label = 状态栏上方底部
tab-bar-bottom-below =
    .label = 底部状态栏下
tab-additional-header = 附加标签首选项
pinned-icon-only =
    .label = 收缩置顶的标签页以只显示站点图标
insert-after-current =
    .label = 在当前标签后插入新标签
insert-related-after-current =
    .label = 在当前标签后插入相关的新标签
dynamic-theme-header = 动态主题
dynamic-theme-dark =
    .label = 强制暗色模式
dynamic-theme-light =
    .label = 强制光线模式
dynamic-theme-auto =
    .label = 动态设置灯光/暗色模式
restart-header = 重启菜单项
restart-show-button =
    .label = 在面板界面中显示重启按钮
restart-purge-cache =
    .label = 浏览器重启时清理快速重启缓存
restart-require-confirmation =
    .label = 需要重新启动确认
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = 显示"复制标签页"菜单项
show-copy-url =
    .label = 显示复制标签 url 菜单项
enable-copy-active-tab =
    .label = 仅从活动标签中复制 URL
show-copy-all-urls =
    .label = 显示复制所有标签页地址菜单项
show-unload-tab =
    .label = 显示卸载标签菜单项
statusbar-enabled =
    .label = 显示状态栏
statusbar-show-links =
    .label = 显示链接
statusbar-contrast-text =
    .label = 对比状态栏文本颜色
bookmarks-bar-position-header = 书签工具栏位置
bookmarks-position-top =
    .label = 顶端
bookmarks-position-bottom =
    .label = 底部
geolocation-api-header = 地理位置API
geolocation-description = 某些网站需要您的位置才能运行。 如果一个网站因无法找到您的位置而无法运行，请启用此选项并重试。
geolocation-api-enabled =
    .label = 启用
geolocation-api-disabled =
    .label = 禁用
send-referrer-header-0 =
    .label = 从不发送推荐信头
send-referrer-header-1 =
    .label = 仅当点击链接和类似元素时包含来源标头
send-referrer-header-2 =
    .label = 在所有请求中包含来源标头（默认）
enable-webrtc-p2p =
    .label = 启用 WebRTC 节点连接
load-images =
    .label = 自动加载图像
enable-javascript =
    .label = 启用 JavaScript
webrtc-header = WebRTC 节点连接
ref-header = HTTP 推荐信头
statusbar-header = 状态栏
private-tab =
    .label =
        { $isPrivate ->
            [true] 退出私有选项卡
           *[false] 创建私人标签
        }
update-application-manual =
    .label = 从不检查更新（不建议）
    .accesskey = N
preferences-doh-setting-ultra =
    .label = 高级保护
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } 将通过 Waterfox 的隐私中继使用基于 OHTTP 的安全 DNS，以提供最高级别的保护。
preferences-doh-ultra-detailed-desc-1 = 使用 Waterfox 的 OHTTP 中继，对 DNS 提供商隐藏 DNS 查询
preferences-doh-ultra-detailed-desc-2 = 在基于HTTPS的DNS之外提供额外的加密层
preferences-doh-ultra-detailed-desc-3 = 最大DNS隐私保护——没有人能看到你访问的网站
preferences-doh-ultra-fallback-mode = 回退行为：
preferences-doh-ultra-fallback-allowed = 如果安全DNS不可用，允许回退到系统DNS
preferences-doh-ultra-fallback-disabled = 永远不回退到系统DNS（如果安全DNS不可用，网站将无法加载）
pane-theme-title = 外观
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = 动画
appearance-header = 外观
autohide-hidden-header = 自动影响
bookmark-header = 书签栏
center-header = 中心
font-header = 字体
full-screen-header = 全屏
icons-header = 图标
interface-component-header = 组件接口
media-player-header = 媒体播放器
nav-bar-header = 导航条
panels-header = 面板
rounding-header = 圆角
sidebar-header = 侧栏
tab-bar-header = 菜单
theme-header = 主题
preset-title = 默认值
lepton-style =
    .label = Lepton 风格
proton-style =
    .label = Proton 风格
waterfox-defaults =
    .label = Waterfox 默认
auto-blur-tabs =
    .label = 标签自动模糊
auto-hide-back =
    .label = 自动隐藏后退按钮
auto-hide-bookmarkbar =
    .label = 自动隐藏书签栏
auto-hide-forward =
    .label = 自动隐藏前进按钮
auto-hide-navbar =
    .label = 自动隐藏导航栏
auto-hide-pageaction =
    .label = 自动隐藏页面操作
auto-hide-sidebar =
    .label = 自动隐藏侧栏
auto-hide-tabbar =
    .label = 自动隐藏标签栏
auto-hide-tabs =
    .label = 自动隐藏标签页
center-navbar-text =
    .label = 使导航栏文字居中
center-tab-content =
    .label = 使页面内容居中
hide-all-icons =
    .label = 隐藏所有图标
hide-bookmarkbar-icon =
    .label = 隐藏书签栏图标
hide-bookmarkbar-label =
    .label = 隐藏书签栏标签
hide-disabled-menuitems =
    .label = 隐藏禁用的菜单项
hide-sidebar-header =
    .label = 隐藏侧栏标题
hide-tab-icons =
    .label = 隐藏标签页图标
hide-urlbar-iconbox =
    .label = 隐藏地址栏图标框
monospace-font =
    .label = 对页面启用等宽字体
monospace-font-theme =
    .label = 对主题启用等宽字体
show-mac-menu-icons =
    .label = 显示 Mac 菜单图标
show-menu-icons =
    .label = 显示菜单图标
square-button-edges =
    .label = 方块按钮边角
square-checkbox =
    .label = 方形复选框
square-field =
    .label = 方形条目字段边角
center-tab-label =
    .label = 仅居中标签页标签
close-button-hover =
    .label = 在打开多个标签页时当悬停于选定标签页时显示关闭标签页按钮
pane-tree-title = 树状垂直标签页
browser-layout-tree-vertical-tabs =
    .label = 树状垂直标签页
sidebar-tree-vertical-tabs =
    .label = 树状垂直标签页
tree-header = 树状垂直标签页
tree-sticky-active-tab =
    .label = 活动标签页
    .accesskey = k
tree-successor-tab-control-level-caption =
    .value = 在当前标签页作为最后的子标签页关闭时
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = 聚焦到树中的上一个标签页
tree-successor-tab-control-level-never =
    .label = 始终聚焦到下一个标签页（遵循浏览器或其它扩展的控制）
tree-successor-tab-control-level-simulate-default =
    .label = 始终聚焦到下一个标签页
enable-menu-transparency =
    .label = 启用菜单透明
enable-panel-transparency =
    .label = 启用面板透明化
enable-waterfox-theme-0 =
    .label = 在所有主题上启用 Waterfox 主题定制
enable-waterfox-theme-1 =
    .label = 在 Waterfox 主题上启用 Waterfox 主题定制
enable-waterfox-theme-2 =
    .label = 禁用 Waterfox 主题定制
full-panel-strip =
    .label = 全宽应用菜单分隔符
remove-panel-strip =
    .label = 移除彩色应用菜单分隔符
square-menu-item =
    .label = 方形上下文菜单项边角
square-menu-panel =
    .label = 方形应用菜单面板边角
square-menu-popup =
    .label = 方形上下文菜单边角
square-panel-item =
    .label = 方形应用菜单项边角
square-tab-edges =
    .label = 方形标签页边角
tab-context-line =
    .label = 标签页上下文行
telemetry-page-subtitle = Waterfox 不收集有关您的安装的遥测数据 - 当构建浏览器时禁用了任何的遥测模块。您在浏览中所作所为仅您自己知道。
telemetry-privacy-policy = 隐私政策
tabbrowser-confirm-session-restore-checkbox = 打开先前的窗口和标签页
tree-appearance-header = 外观
tree-faviconize-pinned-tabs =
    .label = 仅用标签页的图标显示固定的标签页
    .accesskey = S
tree-sticky-sharing-tab =
    .label = 标签页分享摄像头/麦克风/屏幕
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = 声音播放标签页
    .accesskey = y
tree-behavior-header = 标签页的树状视图
tree-auto-collapse-expand-subtree-on-attach =
    .label = 在出现新树时，自动折叠其它的
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = 当标签页获得焦点时，自动展开它所在的树并折叠其它的
    .accesskey = x
compact-bookmark-menu =
    .label = 缩小书签菜单间距
compact-context-menu =
    .label = 缩小右键菜单间距
compact-navbar-popup =
    .label = 缩小导航栏弹出菜单间距
compact-panel-header =
    .label = 缩小面板标题栏间距
disable-panel-animate =
    .label = 关闭应用菜单面板动画效果
disable-sidebar-animate =
    .label = 关闭侧边栏面板动画效果
drag-space =
    .label = 启用固定拖动区域
enable-cyan-accent-color =
    .label = 青色主题强调色
enable-default-accent-color =
    .label = 默认主题强调色
enable-system-accent-color =
    .label = 跟随系统强调色
onboarding-grassroots-title = 支持草根事业
onboarding-grassroots-subtitle = 感谢您使用 Waterfox，一款独立、扎根社区的浏览器。在您的支持下，我们正在打造一个可持续发展的替代选择，以抗衡市面上的那些巨头。
category-tree =
    .tooltiptext = { pane-tree-title }
tree-auto-sticky-header = 标签页滚动超出时吸附在标签栏边缘
tree-drop-links-on-tab-behavior-caption =
    .value = 当链接或 URL 字符串拖放到标签页上时
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = 始终询问我如何处理
tree-drop-links-on-tab-behavior-load =
    .label = 加载到标签页
tree-drop-links-on-tab-behavior-newtab =
    .label = 新建子标签页
tree-tree-double-click-behavior-caption =
    .value = 双击标签页
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = 关闭标签页
tree-tree-double-click-behavior-toggle-collapsed =
    .label = 折叠/展开标签树
tree-tree-double-click-behavior-toggle-none =
    .label = 无操作
tree-tree-double-click-behavior-toggle-sticky =
    .label = 贴靠标签栏边缘 / 取消贴靠
tree-auto-attach-header = 自动整理标签树
tree-auto-attach-child-end =
    .label = 父标签页的最后一个子标签页
tree-auto-attach-child-next-to-last-related-tab =
    .label = 父标签页的子标签页，紧邻最近打开的子标签页
tree-auto-attach-child-top =
    .label = 父标签页的第一个子标签页
tree-auto-attach-independent =
    .label = 独立标签页
tree-auto-attach-next-sibling =
    .label = 父标签页的下一个同级标签页
tree-auto-attach-no-control =
    .label = （无控制）
tree-auto-attach-sibling =
    .label = 父标签页的同级标签页
tree-auto-attach-on-any-other-trigger-caption =
    .value = 来自其他任何触发方式的标签页：打开为
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = 将标签页复制为
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = 对于中键点击，打开新的空白标签页为
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = 打开新的空白标签页为
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = 来自其他应用程序的新标签页：打开为
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = 从现有标签页打开新标签页时，打开为
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = 从地址栏、书签、历史记录或其他位置打开与当前标签页相同网站的新标签页时：打开为
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = 来自固定标签页的新子标签页插入位置（将显示为根标签页）
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = 树形结构的末尾
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = 紧邻最近打开的子标签页，或靠近打开源标签页
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = 无控制（遵循浏览器或其他标签页扩展的决定）
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = 树形结构的顶部（靠近打开源标签页）
waterfox-blocker-header = 广告拦截
waterfox-blocker-intro-description = 拦截广告、跟踪脚本和其他不必要的请求，以加快页面加载速度并减少干扰。
waterfox-blocker-setting-on =
    .label = 开启
waterfox-blocker-setting-on-description = Waterfox 拦截了以下内容：
waterfox-blocker-setting-off =
    .label = 关闭
waterfox-blocker-setting-off-description = Waterfox 不拦截任何广告或跟踪器。第三方扩展仍可独立拦截内容。
waterfox-blocker-dropdown-label =
    .value = 搜索合作伙伴广告：
waterfox-blocker-dropdown-option-partner-exception =
    .label = 允许 Waterfox 搜索合作伙伴的广告
waterfox-blocker-dropdown-option-block-everything =
    .label = 禁止 Waterfox 搜索合作伙伴的广告
waterfox-blocker-manage-filter-lists =
    .label = 管理过滤器列表…
waterfox-blocker-filter-lists-window =
    .title = 广告拦截过滤列表
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = 保存更改
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = 选择要启用的过滤列表。
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } / { $totalCount } 已启用
waterfox-blocker-filter-lists-column-enabled =
    .label = 已启用
waterfox-blocker-filter-lists-column-name =
    .label = 过滤器列表
waterfox-blocker-filter-lists-column-category =
    .label = 类别
waterfox-blocker-filter-lists-enable =
    .label = 启用
waterfox-blocker-filter-lists-disable =
    .label = 关闭
waterfox-blocker-extension-detected = Waterfox 现已内置广告拦截功能。您可以在设置中查看您的配置。
waterfox-blocker-extension-detected-learn-more =
    .label = 了解更多
waterfox-blocker-extension-detected-dismiss =
    .label = 不再显示
waterfox-blocker-extension-install-warning = Waterfox 已内置广告拦截器。同时运行两个广告拦截器可能导致页面出错或加载缓慢。
waterfox-blocker-extension-install-got-it =
    .label = 知道了
waterfox-blocker-extension-install-learn-more =
    .label = 了解更多
waterfox-blocker-third-party-notice-description = { $extensionName } 也在拦截广告。同时运行两个广告拦截器可能会引发问题。
waterfox-blocker-filter-lists-category-core = 默认
waterfox-blocker-filter-lists-category-annoyances = 干扰元素
waterfox-blocker-filter-lists-category-optional = 可选
waterfox-blocker-filter-lists-category-regional = 特定语言
waterfox-blocker-filter-lists-empty-state = 没有可用的过滤列表。
waterfox-blocker-extension-fallback-name-this = 此扩展
waterfox-blocker-extension-fallback-name-your = 您的扩展
waterfox-blocker-spotlight-title = Waterfox 现已包含广告拦截功能
waterfox-blocker-spotlight-subtitle = 我们注意到您安装了 { $extensionName }。Waterfox 现已内置广告拦截器。使用内置拦截器有助于支持 Waterfox，但最终由您决定。
waterfox-blocker-spotlight-primary-button = 保留我当前的设置
waterfox-blocker-spotlight-secondary-button = 查看设置
waterfox-blocker-prompt-title = Waterfox 广告拦截
waterfox-blocker-reenable-conflict-message = 同时运行 Waterfox 广告拦截和"{ $extensionName }"可能导致页面出错。您想保留哪一个？
waterfox-blocker-filter-lists-category-privacy = 隐私
waterfox-blocker-reenable-use-built-in = 使用内置拦截器
waterfox-blocker-reenable-keep-extension = 保留扩展拦截器
waterfox-blocker-extension-install-manage-settings = 您可以在"设置 > 隐私与安全"中管理广告拦截。
waterfox-blocker-extension-install-anyway = 仍然安装
waterfox-blocker-extension-install-keep-built-in = 继续使用内置拦截器
waterfox-blocked-page-title = Waterfox 拦截了此页面
waterfox-blocked-page-heading = Waterfox 拦截了此页面
waterfox-blocked-page-description = 此页面被广告拦截过滤规则拦截。
waterfox-blocked-page-details =
    .aria-label = 已拦截页面详情
waterfox-blocked-page-blocked-url-label = 已拦截的网址
waterfox-blocked-page-matched-rule-label = 匹配规则
waterfox-blocked-page-unavailable = 不可用
waterfox-blocked-page-hint = "仍然加载"将在此会话期间临时允许该网站。
waterfox-blocked-page-go-back = 返回
waterfox-blocked-page-load-anyway = 仍然加载
waterfox-blocker-toolbar-button =
    .label = 广告拦截
    .tooltiptext = 广告拦截
waterfox-blocker-panel-not-available = 此页面不可用
waterfox-blocker-panel-toggle =
    .label = 此网站的广告拦截
    .description = 拦截此网站上的广告和跟踪器。
waterfox-blocker-panel-disabled = 广告拦截已关闭
waterfox-blocker-panel-site-excepted = 允许此网站显示广告
waterfox-blocker-panel-partner-allowed = 允许搜索合作伙伴显示广告
waterfox-blocker-stats =
    { $count ->
        [one] 已在此网站拦截 { $count } 个广告
       *[other] 已在此网站拦截 { $count } 个广告
    }
waterfox-blocker-panel-settings-button = 广告拦截设置
waterfox-blocker-show-badge-pref =
    .label = 在工具栏按钮上显示已拦截数量
waterfox-blocker-setting-on-summary = 拦截广告和跟踪器，对页面加载影响最小。
waterfox-data-collection-header = { -brand-short-name } 数据收集与使用
    .searchkeywords = 隐私 遥测 数据收集 隐私声明
waterfox-data-collection-description = { -brand-short-name } 不会收集遥测或使用数据。可选服务（如同步）可能受其各自的隐私声明约束。此处提供了 <a data-l10n-name="privacy-notice">隐私声明</a> 以便查阅。
waterfox-blocker-blocks-ads = 广告和广告网络请求
waterfox-blocker-blocks-tracking = 跟踪脚本和像素
waterfox-blocker-blocks-annoyances = 干扰弹窗和覆盖层（启用干扰元素列表后）
waterfox-blocker-partner-funding-title = 支持 Waterfox 的开发
waterfox-blocker-partner-funding-description = Waterfox 是免费、开源且独立的浏览器。允许搜索合作伙伴页面上的广告是 Waterfox 为开发和基础设施提供资金的方式。您可以随时关闭此功能，但保持开启是支持该项目的最简单方式。
waterfox-blocker-custom-filter-lists =
    .label = 自定义过滤列表…
permissions-exceptions-waterfox-blocker-window2 =
    .title = 广告拦截例外
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = 您可以指定哪些网站关闭广告拦截。输入要管理的网站的确切地址，然后点击添加例外。
waterfox-blocker-filter-lists-search =
    .placeholder = 搜索过滤列表…
waterfox-blocker-filter-lists-refresh-now =
    .label = 立即刷新
waterfox-blocker-filter-lists-last-updated = 更新于 { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = 尚未更新
waterfox-blocker-filter-lists-next-refresh =
    .value = 下次刷新时间：{ $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = 下次刷新时间：未知
waterfox-blocker-custom-filter-lists-window =
    .title = 自定义过滤列表
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = 保存更改
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = 添加自定义过滤列表的网址。这些列表将被获取并与内置过滤器一起应用。
waterfox-blocker-filter-lists-custom-heading =
    .value = 自定义过滤列表
waterfox-blocker-filter-lists-custom-input =
    .placeholder = 输入过滤列表网址…
waterfox-blocker-filter-lists-custom-url-label =
    .value = 过滤列表网址
waterfox-blocker-filter-lists-custom-col =
    .label = 网址
waterfox-blocker-filter-lists-custom-add =
    .label = 添加
waterfox-blocker-filter-lists-custom-remove =
    .label = 删除
waterfox-blocker-filter-lists-custom-remove-all =
    .label = 删除所有
waterfox-blocker-filter-lists-custom-empty =
    .value = 未添加自定义过滤列表。
waterfox-blocker-custom-filters =
    .label = 我的过滤器…
waterfox-blocker-custom-filters-window =
    .title = 我的过滤器
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = 保存修改
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = 添加您自己的广告拦截规则。这些规则使用标准的 uBlock Origin 过滤语法，并与您已启用的过滤列表一起应用。
waterfox-blocker-custom-filters-empty =
    .value = 没有自定义过滤器。
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] 没有自定义过滤器。
        [one] 1 条自定义过滤器。
       *[other] { $count } 条自定义过滤器。
    }
waterfox-blocker-custom-filters-status-unsaved = 有未保存的更改。
waterfox-blocker-custom-filters-import =
    .label = 导入…
waterfox-blocker-custom-filters-export =
    .label = 导出…
waterfox-blocker-custom-filters-load-error-title = 加载失败
waterfox-blocker-custom-filters-load-error = 无法加载自定义过滤器。
waterfox-blocker-custom-filters-save-error-title = 保存失败
waterfox-blocker-custom-filters-save-error = 无法保存自定义过滤器。
waterfox-blocker-custom-filters-import-error-title = 导入失败
waterfox-blocker-custom-filters-import-error = 无法导入所选文件。
waterfox-blocker-custom-filters-export-error-title = 导出失败
waterfox-blocker-custom-filters-export-error = 无法导出自定义过滤器。
waterfox-blocker-custom-filters-import-picker-title = 导入自定义过滤器
waterfox-blocker-custom-filters-export-picker-title = 导出自定义过滤器
waterfox-blocker-custom-filters-import-replace-title = 是否替换当前过滤器？
waterfox-blocker-custom-filters-import-replace-message = 导入将替换编辑器中的所有当前内容。
