restart-prompt-question = Ĉu vi certas, ke vi volas restartigi “{ -brand-short-name }”?
restart-prompt-title = Restartigi “{ -brand-short-name }”
appmenuitem-restart-browser =
    .label = Restartigi
copy-all-urls =
    .label = Kopii ligilojn de ĉiuj langetoj
copy-url =
    .label = Kopii ligilon de langeto
unload-tab =
    .label = Malŝarĝi langeton
new-private-tab =
    .label = Nova privata langeto
    .tooltiptext = Malfermi novan privatan langeton
open-all-links-private =
    .label = Malfermi ĉiujn ligilojn en privataj langetoj
open-all-private =
    .label = Malfermi ĉiujn en privataj langetoj
open-link-private =
    .label = Malfermi ligilon en nova privata langeto
open-private-tab =
    .label = Malfermi en nova privata langeto
private-tab =
    .label =
        { $isPrivate ->
            [true] Malprivatigi langeton
           *[false] Privatigi langeton
        }
status-bar =
    .label = Statobreto
update-application-manual =
    .label = Neniam kontroli por ĝisdatigoj (ne rekomendita)
    .accesskey = N
bookmarks-bar-position-header = Pozicio de legosigna ilobreto
bookmarks-position-bottom =
    .label = Malsupro
bookmarks-position-top =
    .label = Supro
dynamic-theme-header = Dinamikaj etosoj
dynamic-theme-auto =
    .label = Dinamike agordi (mal)helan reĝimon
dynamic-theme-dark =
    .label = Devigi malhelan reĝimon
dynamic-theme-light =
    .label = Devigi helan reĝimon
geolocation-api-header = Interfaco de geolokigo
geolocation-description = Iuj retejoj bezonas scii vian lokoj por funkcii. Se retejo ne funkcias pro neebleco trovi vian lokon, bonvolu ŝalti tiun ĉi agordon kaj provi denove.
geolocation-api-enabled =
    .label = Ŝalti
geolocation-api-disabled =
    .label = Malŝalti
restart-header = Menuaro de restartigo
restart-purge-cache =
    .label = Forigi kaŝmemoron de rapida restarto dum restarto de retumilo
restart-require-confirmation =
    .label = Postuli konfirmon antaŭ restarto
restart-show-button =
    .label = Montri restartigo-butonon en panela interfaco
statusbar-header = Statobreto
statusbar-contrast-text =
    .label = Kontrasti koloron de statobreta teksto
statusbar-enabled =
    .label = Montri statobreton
statusbar-show-links =
    .label = Montri ligilojn
tab-additional-header = Aldonaj agordoj de langetoj
insert-after-current =
    .label = Enmeti novan langeton post aktuala langeto
insert-related-after-current =
    .label = Enmeti rilatan novan langeton post aktuala langeto
pinned-icon-only =
    .label = Malgrandigi alpinglitajn langetojn, montrante nur bildeton de retejo
tab-feature-header = Kunteksta menuo de langeto
enable-copy-active-tab =
    .label = Kopii adreson nur el aktiva langeto
show-copy-all-urls =
    .label = Montri menuaron por kopiado de ĉiuj adresoj de langetoj
show-copy-url =
    .label = Montri menuaron por kopiado de adreso de langeto
show-duplicate-tab =
    .label = Montri menuaron por duobligo de langeto
show-unload-tab =
    .label = Montri menuaron por malŝarĝado de langeto
tab-position-header = Pozicio de langetaro
tab-bar-bottom-above =
    .label = Subo, super statobreto
tab-bar-bottom-below =
    .label = Subo, sub statobreto
tab-bar-top-above =
    .label = Supro, super adresobreto
tab-bar-top-below =
    .label = Supro, sub adresobreto
waterfox-data-collection-header = Kolektado kaj uzado de datumoj per { -brand-short-name }
    .searchkeywords = privateco telemetrio kolekto datumoj privateca rimarko
waterfox-data-collection-description = { -brand-short-name } ne kolektas telemetriajn aŭ uzadajn datumojn. Opciaj servoj, kiaj ekzemple Sync, povas esti regita de propraj privatecaj rimarkoj. La <a data-l10n-name="privacy-notice">privateca rimarko</a> estas provizita tie por simpla referencado.
enable-javascript =
    .label = Ŝalti skriptojn JavaScript
load-images =
    .label = Ŝarĝi bildojn aŭtomate
preferences-doh-setting-ultra =
    .label = Ultra-protekto
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } uzos sekuran servon DNS kun protokolo Oblivious HTTP tra privateca prokurila servo de Waterfox por plej forta protekto.
preferences-doh-ultra-detailed-desc-1 = Uzas prokurilan servon de Waterfox kun protokolo Oblivious HTTP por kaŝi DNS-petojn eĉ de provizanto de servo DNS
preferences-doh-ultra-detailed-desc-2 = Provizas aldonan nivelon de ĉifrado preter norma DNS-per-HTTPS
preferences-doh-ultra-detailed-desc-3 = Maksimuma protekto de privateco por DNS - neniu povas vidi, kiujn retejojn vi vizitas
preferences-doh-ultra-fallback-mode = Konduto dum eraro:
preferences-doh-ultra-fallback-allowed = Permesi uzadon de sistema servo DNS, se sekura DNS eraras
preferences-doh-ultra-fallback-disabled = Neniam uzi sisteman servon DNS (retejoj povas ne ŝarĝiĝi, se sekura DNS ne funkcias)
ref-header = Referencila kapo (Referrer) de HTTP
send-referrer-header-0 =
    .label = Neniam sendi referencilan kapon
send-referrer-header-1 =
    .label = Inkluzivi referencilan kapon nur dum klakado sur ligiloj kaj similaj elementoj
send-referrer-header-2 =
    .label = Inkluzivi referencilan kapon por ĉiuj petoj (defaŭlto)
pane-theme-title = Tajlorado
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animacioj
appearance-header = Aspekto
autohide-hidden-header = Aŭtomata kaŝado kaj kaŝitaj
bookmark-header = Ilaro de legosignoj
center-header = Centra
font-header = Tiparoj
full-screen-header = Plenekrana reĝimo
icons-header = Bildetoj
interface-component-header = Komponantoj de interfaco
media-player-header = Ludado de plurmedioj
nav-bar-header = Navigacia breto
panels-header = Paneloj
rounding-header = Rondigo
sidebar-header = Flanka breto
tab-bar-header = Langetaro
theme-header = Etoso
preset-title = Antaŭagordoj
lepton-style =
    .label = Etoso “Leptono”
proton-style =
    .label = Etoso “Protono”
waterfox-defaults =
    .label = Defaŭltoj de Waterfox
auto-blur-tabs =
    .label = Aŭtomate malklarigi langetojn
auto-hide-back =
    .label = Aŭtomate kaŝi butonon “malantaŭen”
auto-hide-bookmarkbar =
    .label = Aŭtomate kaŝi ilaron de legosignoj
auto-hide-forward =
    .label = Aŭtomate kaŝi butonon “antaŭen”
auto-hide-navbar =
    .label = Aŭtomate kaŝi navigacian breton
auto-hide-sidebar =
    .label = Aŭtomate kaŝi flankan strion
auto-hide-tabbar =
    .label = Aŭtomate kaŝi langetaron
auto-hide-tabs =
    .label = Aŭtomate kaŝi langetojn
center-navbar-text =
    .label = Centrigi tekston de navigacia breto
center-tab-content =
    .label = Centrigi enhavon de langetoj
center-tab-label =
    .label = Centrigi nur etikedon de langetoj
close-button-hover =
    .label = Montri butonon por fermado de langetoj dum musumado super elektita langeto, dum multaj langetoj estas malfermitaj
webrtc-header = Samtavola konekto per WebRTC
enable-webrtc-p2p =
    .label = Ŝalti samtavolajn konektojn per WebRTC
auto-hide-pageaction =
    .label = Aŭtomate kaŝi paĝajn agojn
compact-bookmark-menu =
    .label = Malpliigi marĝenojn en menuo de legosignoj
compact-context-menu =
    .label = Malpliigi marĝenojn en kunteksta menuo
compact-navbar-popup =
    .label = Malpliigi marĝenojn en ŝprucfenestro de navigacia breto
compact-panel-header =
    .label = Malpliigi marĝenojn de panelaj kapoj
disable-panel-animate =
    .label = Malŝalti animacion de panelo de aplikaĵa menuo
disable-sidebar-animate =
    .label = Malŝalti animacion de panelo de flanka strio
drag-space =
    .label = Ŝalti fiksitan spacon por trenado
enable-cyan-accent-color =
    .label = Cejana akcenta koloro
enable-default-accent-color =
    .label = Defaŭlta akcenta koloro
enable-menu-transparency =
    .label = Ŝalti travideblecon de menuoj
enable-panel-transparency =
    .label = Ŝalti travideblecon de paneloj
enable-system-accent-color =
    .label = Operaciuma akcenta koloro
enable-waterfox-theme-0 =
    .label = Ŝalti etosajn alĝustigojn de Waterfox por ĉiuj etosoj
enable-waterfox-theme-1 =
    .label = Ŝalti etosajn alĝustigojn de Waterfox por etosoj de Waterfox
enable-waterfox-theme-2 =
    .label = Malŝalti etosajn alĝustigojn de Waterfox
full-panel-strip =
    .label = Plenlarĝaj apartigiloj en aplikaĵaj menuoj
remove-panel-strip =
    .label = Forigi koloran aparigilon de aplikaĵa menuo
hide-all-icons =
    .label = Kaŝi ciujn bildetojn
hide-bookmarkbar-icon =
    .label = Kaŝi bildetojn de ilaro de legosignoj
hide-bookmarkbar-label =
    .label = Kaŝi etikedojn de ilaro de legosignoj
hide-disabled-menuitems =
    .label = Kaŝi malebligitajn menuerojn
hide-sidebar-header =
    .label = Kaŝi kapon de flanka strio
hide-tab-icons =
    .label = Kaŝi bildetojn de langetoj
hide-urlbar-iconbox =
    .label = Kaŝi bildetujon de adresa strio
monospace-font =
    .label = Ŝalti unularĝan tiparon por paĝo
monospace-font-theme =
    .label = Ŝalti unularĝan tiparon por etoso
show-mac-menu-icons =
    .label = Montri bildetojn de menuo Mac
show-menu-icons =
    .label = Montri bildetojn de menuoj
square-button-edges =
    .label = Kvadrataj anguloj de butonoj
square-checkbox =
    .label = Kvadrataj markobutonoj
square-field =
    .label = Kvadrataj anguloj de enigaj kampoj
square-menu-item =
    .label = Kvadrataj anguloj de menueroj de kunteksta menuo
square-menu-panel =
    .label = Kvadrataj anguloj de panelo de aplikaĵa menuo
square-menu-popup =
    .label = Kvadrataj anguloj de panelo de kunteksta menuo
square-panel-item =
    .label = Kvadrataj anguloj de menueroj de aplikaĵa menuo
square-tab-edges =
    .label = Kvadrataj anguloj de langetoj
tab-context-line =
    .label = Kunteksta linio de langetoj
telemetry-page-subtitle = Waterfox ne kolektas telemetriajn datumojn pri via instalo - ĉiuj moduloj de telemetrio estas malŝaltitaj dum kunmetado de retumilo. Nur vi scias, kion vi faras en via retumilo.
telemetry-privacy-policy = Politiko de privateco
onboarding-grassroots-title = Subteno de sendependaj iniciatoj
onboarding-grassroots-subtitle = Dankon por uzado de Waterfox, sendependa kaj homo-evoluigata retumilo. Kun via subteno, ni konstruas daŭropovan alternativon al la grandaj konkurantoj ĉe la merkato.
tabbrowser-confirm-session-restore-checkbox = Malfermi lastajn fenestrojn kaj langetojn
pane-tree-title = Arbovidaj vertikalaj langetoj
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Arbovidaj vertikalaj langetoj
sidebar-tree-vertical-tabs =
    .label = Arbovidaj vertikalaj langetoj
tree-header = Arbovidaj vertikalaj langetoj
tree-appearance-header = Aspekto
tree-auto-sticky-header = Langetoj alpinglitaj al randoj de la langetaro, kiam ili estas rulumitaj ekster la vido
tree-faviconize-pinned-tabs =
    .label = Montri alpinglitajn langetojn per nur emblemo
    .accesskey = M
tree-sticky-active-tab =
    .label = Aktiva langeto
    .accesskey = k
tree-sticky-sharing-tab =
    .label = Langetoj, kaptantaj kameraon/mikrofonon/ekranon
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Langetoj, ludantaj sonon
    .accesskey = j
tree-behavior-header = Arbeca vido de langetoj
tree-auto-collapse-expand-subtree-on-attach =
    .label = Maletendi aliajn arbojn, kiam nova aperos
    .accesskey = M
tree-auto-collapse-expand-subtree-on-select =
    .label = Etendi la arbon kaj maletendi aliajn, kiam langeto ricevas fokuson
    .accesskey = E
tree-drop-links-on-tab-behavior-caption =
    .value = Kiam ligilo aŭ retadreso estas demetita sur langeto
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Ĉiam peti pro traktado
tree-drop-links-on-tab-behavior-load =
    .label = Ŝarĝi en la langeto
tree-drop-links-on-tab-behavior-newtab =
    .label = Malfermi novan idan langeton
tree-successor-tab-control-level-caption =
    .value = Kiam aktuala langeto estas fermita kiel lasta ido
    .accesskey = f
tree-successor-tab-control-level-in-tree =
    .label = Movi fokuson al la antaŭa langeto en la arbo
tree-successor-tab-control-level-never =
    .label = Ĉiam movi fokuson al la sekva langeto (laŭ agordoj de retumilo aŭ aliaj etendaĵoj)
tree-successor-tab-control-level-simulate-default =
    .label = Ĉiam movi fokuson al la sekva langeto
tree-tree-double-click-behavior-caption =
    .value = Duobla alklako sur langeto
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Fermi langeton
tree-tree-double-click-behavior-toggle-collapsed =
    .label = (Mal)etendi arbon
tree-tree-double-click-behavior-toggle-none =
    .label = Fari nenion
tree-tree-double-click-behavior-toggle-sticky =
    .label = (Alpingli al / Depingli de) randoj de langetaro
tree-auto-attach-header = Aŭtomata organizado de langeta arbo
tree-auto-attach-child-end =
    .label = Lasta ido de la parenca langeto
tree-auto-attach-child-next-to-last-related-tab =
    .label = Ido de la parenca langeto, proksima al la lastatempe malfermita ido
tree-auto-attach-child-top =
    .label = Unua ido de la parenca langeto
tree-auto-attach-independent =
    .label = Sendependa langeto
tree-auto-attach-next-sibling =
    .label = Sekva frato de la parenca langeto
tree-auto-attach-no-control =
    .label = (neniu kontrolo)
tree-auto-attach-sibling =
    .label = Frato de la parenca langeto
tree-auto-attach-on-any-other-trigger-caption =
    .value = Langetoj de iu ajn alia ago: Malfermi kiel
    .accesskey = l
tree-auto-attach-on-duplicated-caption =
    .value = Duobligi langeton kiel
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Por mezbutona alklako, malfermi novan malplenan langeton kiel
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Malfermi novan malplenan langeton kiel
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Nova langeto el aliaj aplikaĵoj: Malfermi kiel
    .accesskey = a
tree-auto-attach-on-opened-with-owner-caption =
    .value = Kiam langeto estas malfermita el ekzistanta langeto, malfermi ĝin kiel
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Nova langeto kun la sama retejo kiel nuna langeto de adresa strio, legosignoj, historioj, aŭ aliaj kazoj: Malfermi kiel
    .accesskey = r
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Pozicio de enmeto de novaj idaj langetoj el alpinglitaj langetoj (aperos kiel radikaj langetoj)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = La fino de la arbo
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Post la lastatempe malfermita ido, aŭ post la malfermanto
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Neniu kontrolo (laŭ decido de la retumilo aŭ aliaj langetaj etendaĵoj)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = La supro de la arbo (proksime al la malfermanto)
waterfox-blocker-header = Blokado de reklamoj
waterfox-blocker-intro-description = Blokas reklamojn, spurantajn skriptojn, kaj aliajn nedeziratajn petojn por plirapidigi ŝarĝadon de paĝoj kaj malpliigi distraĵojn.
waterfox-blocker-setting-on =
    .label = Ŝaltita
waterfox-blocker-setting-on-summary = Blokas reklamojn kaj spurilojn kun minimuma efiko por funkciado de paĝoj.
waterfox-blocker-setting-on-description = Waterfox blokas tiujn:
waterfox-blocker-blocks-ads = Reklamoj kaj petoj al reklamaj retoj
waterfox-blocker-blocks-tracking = Spurilaj skriptoj kaj bilderoj
waterfox-blocker-blocks-annoyances = Ĝenaj ŝprucfenestroj kaj surmetaĵoj (kun listoj de ĝenaĵoj ŝaltitaj)
waterfox-blocker-partner-funding-title = Subtenu evoluigadon de Waterfox
waterfox-blocker-partner-funding-description = Waterfox estas libera, malfermit-koda, kaj sendependa programo. Permesado de reklamoj sur paĝoj de kunkomercantoj estas kiel Waterfox financas siajn evoluigadon kaj infrastrukturon. Vi povas malŝalti ĉi tiun ĉiam, sed resti ĝin ŝaltita estas la plej simpla rimedo subteni la projekton.
waterfox-blocker-setting-off =
    .label = Malŝaltita
waterfox-blocker-setting-off-description = Neniuj reklamoj aŭ spuriloj estas blokata de Waterfox. Eksteraj aldonaĵoj povas tamen sendepende bloki enhavon.
waterfox-blocker-dropdown-label =
    .value = Reklamoj de serĉaj kunkomercantoj:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Permesi sur retejoj de serĉaj kunkomercantoj de Waterfox
waterfox-blocker-dropdown-option-block-everything =
    .label = Malpermesi sur retejoj de serĉaj kunkomercantoj de Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Administri filtrilajn listojn…
waterfox-blocker-custom-filter-lists =
    .label = Propraj filtrilaj listoj…
waterfox-blocker-filter-lists-window =
    .title = Filtrilaj listoj de reklamblokado
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Konservi ŝanĝojn
    .buttonaccesskeyaccept = K
waterfox-blocker-filter-lists-description =
    .value = Elektu, kiuj filtrilaj listoj estos aktivaj.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } de { $totalCount } aktiva
waterfox-blocker-filter-lists-column-enabled =
    .label = Ŝaltita
waterfox-blocker-filter-lists-column-name =
    .label = Filtrila listo
waterfox-blocker-filter-lists-column-category =
    .label = Kategorio
waterfox-blocker-filter-lists-enable =
    .label = Ŝalti
waterfox-blocker-filter-lists-disable =
    .label = Malŝalti
waterfox-blocker-extension-detected = Waterfox nun havas integritan blokadon de reklamoj. Vi povas revizii vian agordaĵon en agordoj de la aplikaĵo.
waterfox-blocker-extension-detected-learn-more =
    .label = Lerni pli
waterfox-blocker-extension-detected-dismiss =
    .label = Ne montri denove
waterfox-blocker-extension-install-warning = Waterfox ankaŭ havas integritan blokilon de reklamoj. Funkciado de du blokiloj povas difekti aŭ malrapidigi funkciadon de paĝoj.
waterfox-blocker-extension-install-got-it =
    .label = Komprenita
waterfox-blocker-extension-install-learn-more =
    .label = Lerni pli
waterfox-blocker-third-party-notice-description = { $extensionName } ankaŭ blokas reklamojn. Funkciado de du blokiloj povas kaŭzi problemojn.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Esceptoj por blokado de reklamoj
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Vi povas specifi, por kiuj retejoj blokado de reklamoj estos malŝaltita. Tajpu la precizan adreson de la retejo, kiun vi volas administri, kaj alklaku sur butono “Aldoni escepton”.
waterfox-blocker-toolbar-button =
    .label = Blokado de reklamoj
    .tooltiptext = Blokado de reklamoj
waterfox-blocker-panel-not-available = Ne disponebla sur tiu ĉi paĝo
waterfox-blocker-panel-toggle =
    .label = Blokado de reklamoj en tiu ĉi retejo
    .description = Bloki reklamojn kaj spurilojn en tiu ĉi retejo.
waterfox-blocker-panel-disabled = Blokado de reklamoj estas malŝaltita
waterfox-blocker-panel-site-excepted = Reklamoj permesitaj en tiu ĉi retejo
waterfox-blocker-panel-partner-allowed = Reklamoj permesitaj por serĉaj kunkomercantoj
waterfox-blocker-stats =
    { $count ->
        [one] { $count } reklamo blokita en tiu ĉi retejo
       *[other] { $count } reklamoj blokitaj en tiu ĉi retejo
    }
waterfox-blocker-panel-settings-button = Agordoj de blokado de reklamoj
waterfox-blocker-show-badge-pref =
    .label = Montri nombron de blokitaj eroj sur ilara butono
waterfox-blocker-filter-lists-category-core = Defaŭltaj
waterfox-blocker-filter-lists-category-privacy = Privateco
waterfox-blocker-filter-lists-category-annoyances = Ĝenaĵoj
waterfox-blocker-filter-lists-category-optional = Opciaj
waterfox-blocker-filter-lists-category-regional = Regionaj
waterfox-blocker-filter-lists-search =
    .placeholder = Serĉi filtrilajn listojn…
waterfox-blocker-filter-lists-empty-state = Neniuj filtrilaj listoj disponeblaj.
waterfox-blocker-filter-lists-refresh-now =
    .label = Reŝarĝi nun
waterfox-blocker-filter-lists-last-updated = Ĝisdatigita je { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Ankoraŭ ne ĝisdatigita
waterfox-blocker-filter-lists-next-refresh =
    .value = Sekva reŝarĝo: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Sekva reŝarĝo: nekonata
waterfox-blocker-custom-filter-lists-window =
    .title = Propraj filtrilaj listoj
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Konservi ŝanĝojn
    .buttonaccesskeyaccept = K
waterfox-blocker-custom-filter-lists-description = Aldonu adresojn de propraj filtrilaj listoj. Listoj estos ŝarĝitaj kaj aplikitaj aldone al integritaj filtriloj.
waterfox-blocker-filter-lists-custom-heading =
    .value = Propraj filtrilaj listoj
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Enigu adreson de filtrila listo…
waterfox-blocker-filter-lists-custom-url-label =
    .value = Adreso de filtrila listo
waterfox-blocker-filter-lists-custom-col =
    .label = Adreso
waterfox-blocker-filter-lists-custom-add =
    .label = Aldoni
waterfox-blocker-filter-lists-custom-remove =
    .label = Forigi
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Forigi ĉiujn
waterfox-blocker-filter-lists-custom-empty =
    .value = Neniuj propraj filtrilaj listoj aldonitaj.
waterfox-blocker-custom-filters =
    .label = Miaj filtriloj…
waterfox-blocker-custom-filters-window =
    .title = Miaj filtriloj
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Konservi ŝanĝojn
    .buttonaccesskeyaccept = K
waterfox-blocker-custom-filters-description = Aldonu viajn proprajn regulojn por blokado de reklamoj. Ili uzas norman sintakson de uBlock Origin kaj estas aplikitaj aldone al viaj ŝaltitaj filtrilaj listoj.
waterfox-blocker-custom-filters-empty =
    .value = Neniuj propraj filtriloj.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Neniuj propraj filtriloj.
        [one] 1 propra filtrilo.
       *[other] { $count } propraj filtriloj.
    }
waterfox-blocker-custom-filters-status-unsaved = Nekonservitaj ŝanĝoj.
waterfox-blocker-custom-filters-import =
    .label = Enporti…
waterfox-blocker-custom-filters-export =
    .label = Elporti…
waterfox-blocker-custom-filters-load-error-title = Ŝarĝado malsukcesis
waterfox-blocker-custom-filters-load-error = Propraj filtriloj ne povas esti ŝarĝitaj.
waterfox-blocker-custom-filters-save-error-title = Konservado malsukcesis
waterfox-blocker-custom-filters-save-error = Propraj filtriloj ne povas esti konservitaj.
waterfox-blocker-custom-filters-import-error-title = Enportado malsukcesis
waterfox-blocker-custom-filters-import-error = La elektita dosiero ne povas esti enportita.
waterfox-blocker-custom-filters-export-error-title = Elportado malsukcesis
waterfox-blocker-custom-filters-export-error = Propraj filtriloj ne povas esti elportitaj.
waterfox-blocker-custom-filters-import-picker-title = Enporti proprajn filtrilojn
waterfox-blocker-custom-filters-export-picker-title = Elporti proprajn filtrilojn
waterfox-blocker-custom-filters-import-replace-title = Ĉu anstataŭigi proprajn filtrilojn?
waterfox-blocker-custom-filters-import-replace-message = Enportado anstataŭigos ĉion, kio estas nune en la redaktilo.
waterfox-blocker-extension-fallback-name-this = ĉi tiu etendaĵo
waterfox-blocker-extension-fallback-name-your = via etendaĵo
waterfox-blocker-spotlight-title = Waterfox nun inkluzivas blokadon de reklamoj
waterfox-blocker-spotlight-subtitle = Ni rimarkis, ke vi havas instalitan etendaĵon { $extensionName }. Waterfox nun enhavas sian propran blokilon de reklamoj. Uzado de ĝi helpas subteni la retumilon Waterfox, sed vi ĉiam povas fari vian propran elekton.
waterfox-blocker-spotlight-primary-button = Teni mian nunan agordon
waterfox-blocker-spotlight-secondary-button = Revizii agordojn
waterfox-blocker-prompt-title = Blokado de reklamoj de Waterfox
waterfox-blocker-reenable-conflict-message = Funkciado de ambaŭ integrita blokilo de reklamoj de Waterfox kaj la etendaĵo “{ $extensionName }” povas kaŭzi difektojn en paĝoj. Kiun vi volas teni?
waterfox-blocker-reenable-use-built-in = Uzi integritan blokilon
waterfox-blocker-reenable-keep-extension = Teni blokilan etendaĵon
waterfox-blocker-extension-install-manage-settings = Vi povas administri blokadon de reklamoj en “Agordoj” > “Privateco kaj sekureco”.
waterfox-blocker-extension-install-anyway = Instali tamen
waterfox-blocker-extension-install-keep-built-in = Daŭri uzi integritan blokilon
waterfox-blocked-page-title = Waterfox blokis tiun ĉi paĝon
waterfox-blocked-page-heading = Waterfox blokis tiun ĉi paĝon
waterfox-blocked-page-description = Tiu ĉi paĝo estis blokita de filtrila regulo de blokilo de reklamoj.
waterfox-blocked-page-details =
    .aria-label = Detaloj pri blokita paĝo
waterfox-blocked-page-blocked-url-label = Blokita adreso
waterfox-blocked-page-matched-rule-label = Kongrua regulo
waterfox-blocked-page-unavailable = Ne disponebla
waterfox-blocked-page-hint = “Ŝarĝi tamen” portempe permesas ĉi tiun retejon ĝis la fino de via seanco.
waterfox-blocked-page-go-back = Iri malantaŭen
waterfox-blocked-page-load-anyway = Ŝarĝi tamen
