# This Source Code Form is subject to the terms of the BrowserWorks Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This file is in the UTF-8 encoding
[Strings]
TitleText=Actualización de %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% está instalando as súas actualizacións e iniciarase nun intre…
BrowserWorksMaintenanceDescription=O servizo de mantemento de BrowserWorks asegúralle que ten a última versión e a máis segura do navegador Waterfox no seu computador. Manter o Waterfox actualizado é moi importante para a súa seguridade en liña, e BrowserWorks recomenda encarecidamente que manteña este servizo activado.
