# This Source Code Form is subject to the terms of the BrowserWorks Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This file is in the UTF-8 encoding
[Strings]
TitleText=Aktualizacija %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% waše aktualizacije instalěrujo a buźo za mało wokognuśow startowaś…
BrowserWorksMaintenanceDescription=Wótwardowańska słužba BrowserWorks zawěsćujo, až maśo nejnowšu a nejwěsćejšu wersiju Waterfox na wašom licadle. Jo wjelgin wažne za wašu wěstotu online, Waterfox aktualny źaržaś, a BrowserWorks pśiraźujo wuraznje, až wóstajaśo toś tu słužbu zmóžnjonu.
