restart-prompt-title = Omstart av { -brand-short-name }
restart-prompt-question = Er du sikker på at du vil starte { -brand-short-name } på nytt?
appmenuitem-restart-browser =
    .label = Omstart
copy-url =
    .label = Kopier fanelink
copy-all-urls =
    .label = Kopier alle fanelenker
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Åpne alle i private faner
open-all-links-private =
    .label = Åpne alle koblinger i private faner
open-private-tab =
    .label = Åpne i en ny privat fane
new-private-tab =
    .label = Ny privat fane
    .tooltiptext = Åpne ny privat fane
open-link-private =
    .label = Åpne kobling i ny privat fane
status-bar =
    .label = Statuslinje
tab-position-header = Plassering av fanelinje
tab-bar-top-above =
    .label = Øverst over adresselinje
tab-bar-top-below =
    .label = Øverst under adresselinje
tab-bar-bottom-above =
    .label = Nederst over statuslinjen
tab-bar-bottom-below =
    .label = Nederst under statuslinjen
tab-additional-header = Preferanser for tilleggsfane
pinned-icon-only =
    .label = Forkortes festede faner for å vise bare nettstedsikonet
insert-after-current =
    .label = Sett inn ny fane etter denne fane
insert-related-after-current =
    .label = Sett inn relatert ny fane etter denne fane
dynamic-theme-header = Dynamiske temaer
dynamic-theme-dark =
    .label = Tving mørk modus
dynamic-theme-light =
    .label = Tving lys modus
dynamic-theme-auto =
    .label = Dynamisk sett lys/mørk modus
restart-header = Restart menyelement
restart-show-button =
    .label = Vis start på nytt-knappen i PanelUI
restart-purge-cache =
    .label = Fjern hurtigstart på nytt når nettleseren starter
restart-require-confirmation =
    .label = Krev bekreftelse på nytt
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Vis 'Kopier fane url'-menypunkt
enable-copy-active-tab =
    .label = Kopier URL kun fra aktiv fane
show-copy-all-urls =
    .label = Vis kopi av alle fanene urlerer menyelement
show-unload-tab =
    .label = Vis menypunkt for avlast
statusbar-enabled =
    .label = Vis statuslinjen
statusbar-show-links =
    .label = Vis linker
statusbar-contrast-text =
    .label = Kontrast statuslinje tekstfarge
bookmarks-bar-position-header = Plassering av bokmerkelinje
bookmarks-position-top =
    .label = Topp
bookmarks-position-bottom =
    .label = Bunn
geolocation-api-header = Geolocation API
geolocation-description = Noen nettsteder krever posisjonen din for å fungere. Hvis et nettsted ikke fungerer som et resultat av at posisjonen din ikke kan finnes, kan du aktivere denne innstillingen og prøve på nytt.
geolocation-api-enabled =
    .label = Aktiver
geolocation-api-disabled =
    .label = Deaktiver
send-referrer-header-0 =
    .label = Send aldri referent-hodet
send-referrer-header-1 =
    .label = Send toppteksten for henviser bare når du klikker på linker og lignende elementer
send-referrer-header-2 =
    .label = Send referanselinjen på alle forespørsler (standard)
enable-webrtc-p2p =
    .label = Aktiver WebRTC kilde-tilkobling
load-images =
    .label = Last bilder automatisk
enable-javascript =
    .label = Aktiver JavaScript
webrtc-header = WebRTC kilde-tilkobling
ref-header = HTTP Referrer topptekst
statusbar-header = Statuslinje
private-tab =
    .label =
        { $isPrivate ->
            [true] Avslutt privat fane
           *[false] Gjør privat fane
        }
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
enable-panel-transparency =
    .label = Enable panel transparency
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-blur-tabs =
    .label = Auto Blur Tabs
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-button-edges =
    .label = Square Button Corners
drag-space =
    .label = Enable Fixed Drag Space
monospace-font-theme =
    .label = Enable monospaced font for theme
monospace-font =
    .label = Enable monospaced font for page
tab-context-line =
    .label = Tab Context Line
show-mac-menu-icons =
    .label = Show Mac Menu Icons
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
panels-header = Panels
onboarding-grassroots-title = Supporting the grassroots
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = Media Player
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
