restart-prompt-title = Перезапуск { -brand-short-name }
restart-prompt-question = Вы уверены, что хотите перезапустить { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Перезапуск
copy-url =
    .label = Скопировать ссылку вкладки
copy-all-urls =
    .label = Скопировать все ссылки вкладок
unload-tab =
    .label = Выгрузить вкладку
open-all-private =
    .label = Открыть всё в приватных вкладках
open-all-links-private =
    .label = Открыть все ссылки в приватных вкладках
open-private-tab =
    .label = Открыть в новой приватной вкладке
new-private-tab =
    .label = Новая приватная вкладка
    .tooltiptext = Открыть новую приватную вкладку
open-link-private =
    .label = Открыть ссылку в новой приватной вкладке
status-bar =
    .label = Строка состояния
tab-position-header = Расположение панели вкладок
tab-bar-top-above =
    .label = Наверху над адресной строкой
tab-bar-top-below =
    .label = Наверху под адресной строкой
tab-bar-bottom-above =
    .label = Внизу над строкой состояния
tab-bar-bottom-below =
    .label = Внизу под строкой состояния
tab-additional-header = Дополнительные настройки вкладок
pinned-icon-only =
    .label = Сжать закреплённые вкладки для отображения только значка сайта
insert-after-current =
    .label = Вставить новую вкладку после текущей
insert-related-after-current =
    .label = Вставить связанную новую вкладку после текущей
dynamic-theme-header = Динамические темы
dynamic-theme-dark =
    .label = Принудительно тёмный режим
dynamic-theme-light =
    .label = Принудительно светлый режим
dynamic-theme-auto =
    .label = Динамически устанавливать светлый/тёмный режим
restart-header = Пункт меню перезапуска
restart-show-button =
    .label = Показывать кнопку перезапуска в PanelUI
restart-purge-cache =
    .label = Очистить кэш быстрого перезапуска при перезагрузке браузера
restart-require-confirmation =
    .label = Спрашивать разрешение на перезапуск
tab-feature-header = Контекстное меню вкладки
show-duplicate-tab =
    .label = Показывать пункт меню "Дублировать вкладку"
show-copy-url =
    .label = Показывать пункт меню "Скопировать ссылку вкладки"
enable-copy-active-tab =
    .label = Копировать URL только из активной вкладки
show-copy-all-urls =
    .label = Показывать пункт меню "Скопировать все ссылки вкладок"
show-unload-tab =
    .label = Показывать пункт меню "Выгрузить вкладку"
statusbar-enabled =
    .label = Показывать строку состояния
statusbar-show-links =
    .label = Показывать ссылки
statusbar-contrast-text =
    .label = Контрастный цвет текста строки состояния
bookmarks-bar-position-header = Расположение панели закладок
bookmarks-position-top =
    .label = Наверху
bookmarks-position-bottom =
    .label = Внизу
geolocation-api-header = API геолокации
geolocation-description = Для работы некоторых веб-сайтов требуется ваше местоположение. Если сайт не функционирует в результате невозможности найти ваше местоположение, пожалуйста, включите эту настройку и повторите попытку.
geolocation-api-enabled =
    .label = Включено
geolocation-api-disabled =
    .label = Отключено
send-referrer-header-0 =
    .label = Никогда не отправлять заголовок источника запроса
send-referrer-header-1 =
    .label = Отправлять заголовок источника запроса только при открытии ссылок и похожих элементов
send-referrer-header-2 =
    .label = Отправлять заголовок источника запроса по всем запросам (по умолчанию)
enable-webrtc-p2p =
    .label = Включить peer-соединения WebRTC
load-images =
    .label = Автоматически загружать изображения
enable-javascript =
    .label = Включить JavaScript
webrtc-header = Peer-соединения WebRTC
ref-header = HTTP заголовок источника запроса
statusbar-header = Строка состояния
private-tab =
    .label =
        { $isPrivate ->
            [true] Сделать обычной вкладкой
           *[false] Сделать приватной вкладкой
        }
disable-sidebar-animate =
    .label = Disable sidebar panel animation
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
hide-tab-icons =
    .label = Hide Tab Icons
square-button-edges =
    .label = Square Button Corners
center-tab-label =
    .label = Center Tab Label Only
square-menu-item =
    .label = Square Context Menu Item Corners
square-menu-popup =
    .label = Square Context Menu Panel Corners
square-checkbox =
    .label = Square Checkbox
square-field =
    .label = Square Entry Field Corners
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
show-mac-menu-icons =
    .label = Show Mac Menu Icons
show-menu-icons =
    .label = Show Menu Icons
tab-bar-header = Tab Bar
panels-header = Panels
media-player-header = Media Player
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-all-icons =
    .label = Hide All Icons
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
enable-menu-transparency =
    .label = Enable menu transparency
drag-space =
    .label = Enable Fixed Drag Space
onboarding-grassroots-title = Supporting the grassroots
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
