restart-prompt-title = Перезапуск { -brand-short-name }
restart-prompt-question = Вы уверены, что хотите перезапустить { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Перезапуск
copy-url =
    .label = Скопировать ссылку вкладки
copy-all-urls =
    .label = Скопировать все ссылки вкладок
unload-tab =
    .label = Выгрузить вкладку
open-all-private =
    .label = Открыть всё в приватных вкладках
open-all-links-private =
    .label = Открыть все ссылки в приватных вкладках
open-private-tab =
    .label = Открыть в новой приватной вкладке
new-private-tab =
    .label = Новая приватная вкладка
    .tooltiptext = Открыть новую приватную вкладку
open-link-private =
    .label = Открыть ссылку в новой приватной вкладке
status-bar =
    .label = Строка состояния
tab-position-header = Расположение панели вкладок
tab-bar-top-above =
    .label = Наверху над адресной строкой
tab-bar-top-below =
    .label = Наверху под адресной строкой
tab-bar-bottom-above =
    .label = Внизу над строкой состояния
tab-bar-bottom-below =
    .label = Внизу под строкой состояния
tab-additional-header = Дополнительные настройки вкладок
pinned-icon-only =
    .label = Сжать закреплённые вкладки для отображения только значка сайта
insert-after-current =
    .label = Вставить новую вкладку после текущей
insert-related-after-current =
    .label = Вставить связанную новую вкладку после текущей
dynamic-theme-header = Динамические темы
dynamic-theme-dark =
    .label = Принудительно тёмный режим
dynamic-theme-light =
    .label = Принудительно светлый режим
dynamic-theme-auto =
    .label = Динамически устанавливать светлый/тёмный режим
restart-header = Пункт меню перезапуска
restart-show-button =
    .label = Показывать кнопку перезапуска в PanelUI
restart-purge-cache =
    .label = Очистить кэш быстрого перезапуска при перезагрузке браузера
restart-require-confirmation =
    .label = Спрашивать разрешение на перезапуск
tab-feature-header = Контекстное меню вкладки
show-duplicate-tab =
    .label = Показывать пункт меню "Дублировать вкладку"
show-copy-url =
    .label = Показывать пункт меню "Скопировать ссылку вкладки"
enable-copy-active-tab =
    .label = Копировать URL только из активной вкладки
show-copy-all-urls =
    .label = Показывать пункт меню "Скопировать все ссылки вкладок"
show-unload-tab =
    .label = Показывать пункт меню "Выгрузить вкладку"
statusbar-enabled =
    .label = Показывать строку состояния
statusbar-show-links =
    .label = Показывать ссылки
statusbar-contrast-text =
    .label = Контрастный цвет текста строки состояния
bookmarks-bar-position-header = Расположение панели закладок
bookmarks-position-top =
    .label = Наверху
bookmarks-position-bottom =
    .label = Внизу
geolocation-api-header = API геолокации
geolocation-description = Некоторые веб-сайты требуют ваше местоположение. Если веб-сайт не функционирует в результате невозможности найти ваше местоположение, пожалуйста, включите эту настройку и повторите попытку.
geolocation-api-enabled =
    .label = Включено
geolocation-api-disabled =
    .label = Отключено
send-referrer-header-0 =
    .label = Никогда не отправлять заголовок источника запроса
send-referrer-header-1 =
    .label = Отправлять заголовок источника запроса только при открытии ссылок и похожих элементов
send-referrer-header-2 =
    .label = Отправлять заголовок источника запроса по всем запросам (по умолчанию)
enable-webrtc-p2p =
    .label = Включить peer-соединения WebRTC
load-images =
    .label = Автоматически загружать изображения
enable-javascript =
    .label = Включить JavaScript
webrtc-header = Peer-соединения WebRTC
ref-header = HTTP заголовок источника запроса
statusbar-header = Строка состояния
private-tab =
    .label =
        { $isPrivate ->
            [true] Сделать обычной вкладкой
           *[false] Сделать приватной вкладкой
        }
update-application-manual =
    .label = Никогда не проверять наличие обновлений (не рекомендовано)
    .accesskey = N
preferences-doh-ultra-desc = { -brand-short-name } будет использовать безопасный DNS с Oblivious HTTP через приватный ретранслятор Waterfox для максимальной защиты.
preferences-doh-ultra-detailed-desc-1 = Использовать ретранслятор Waterfox Oblivious HTTP, чтобы скрыть DNS-запросы даже от провайдера DNS
preferences-doh-ultra-detailed-desc-2 = Предоставляет дополнительный слой шифрования за пределами стандартного DNS по HTTPS
preferences-doh-ultra-detailed-desc-3 = Максимальная защита конфиденциальности DNS - никто не может видеть, какие сайты вы посещаете
preferences-doh-ultra-fallback-mode = Поведение по умолчанию:
preferences-doh-ultra-fallback-allowed = Разрешить использование системного DNS в случае сбоя безопасного DNS
preferences-doh-ultra-fallback-disabled = Никогда не возвращаться к системному DNS (сайты могут не загружаться, если безопасный DNS не сработает)
pane-theme-title = Внешний вид и ощущения
animation-header = Анимации
appearance-header = Внешний вид
autohide-hidden-header = Автоскрытие и скрытие
bookmark-header = Панель закладок
center-header = Центр
font-header = Шрифты
full-screen-header = Полный экран
icons-header = Иконки
interface-component-header = Компоненты интерфейса
media-player-header = Медиаплеер
nav-bar-header = Панель навигации
panels-header = Панели
rounding-header = Скругление
sidebar-header = Боковая панель
tab-bar-header = Панель вкладок
theme-header = Тема
preset-title = Предустановки
lepton-style =
    .label = Стиль лептона
proton-style =
    .label = Стиль протона
waterfox-defaults =
    .label = Умолчания Waterfox
auto-blur-tabs =
    .label = Авторазмытие вкладок
auto-hide-back =
    .label = Автоскрытие кнопки «Назад»
auto-hide-bookmarkbar =
    .label = Автоскрытие панели закладок
auto-hide-forward =
    .label = Автоскрытие кнопки "Вперёд"
auto-hide-navbar =
    .label = Автоскрытие панели навигации
auto-hide-pageaction =
    .label = Автоскрытие действий страницы
auto-hide-sidebar =
    .label = Автоскрытие боковой панели
auto-hide-tabbar =
    .label = Автоскрытие панели закладок
auto-hide-tabs =
    .label = Автоскрытие вкладок
center-navbar-text =
    .label = Центрировать текст панели навигации
center-tab-content =
    .label = Центрировать содержимое вкладки
center-tab-label =
    .label = Только метка центральной вкладки
close-button-hover =
    .label = Показывать кнопку закрытия вкладки при наведении на выбранную вкладку, когда открыто много вкладок
compact-bookmark-menu =
    .label = Уменьшить отступы в меню закладок
compact-context-menu =
    .label = Уменьшить отступы контекстного меню
hide-all-icons =
    .label = Скрывать все иконки
hide-bookmarkbar-icon =
    .label = Скрывать иконки панели закладок
hide-tab-icons =
    .label = Скрывать иконки вкладок
square-button-edges =
    .label = Квадратные углы кнопок
square-checkbox =
    .label = Квадратные чекбоксы
square-tab-edges =
    .label = Квадратные углы вкладок
telemetry-page-subtitle = Waterfox не собирает телеметрию о вашей установке — любые модули телеметрии отключены при сборке браузера. То, что вы делаете в браузере, известно только вам.
telemetry-privacy-policy = Политика конфиденциальности
onboarding-grassroots-title = Поддержка народных инициатив
onboarding-grassroots-subtitle = Спасибо, что используете Waterfox, независимый, народный браузер. С вашей поддержкой мы создаём устойчивую альтернативу крупным игрокам на рынке.
tabbrowser-confirm-session-restore-checkbox = Открыть предыдущие окна и вкладки
pane-tree-title = Дерево вертикальных вкладок
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Дерево вертикальных вкладок
sidebar-tree-vertical-tabs =
    .label = Дерево вертикальных вкладок
tree-header = Дерево вертикальных вкладок
tree-appearance-header = Внешний вид
tree-auto-sticky-header = Вкладки прилипают к краям панели вкладок, когда они прокручиваются за пределы видимости
tree-faviconize-pinned-tabs =
    .label = Показывать только закрепленные вкладки с их иконкой
    .accesskey = S
tree-sticky-active-tab =
    .label = Активная вкладка
    .accesskey = k
tree-behavior-header = Древовидный вид вкладок
tree-auto-collapse-expand-subtree-on-attach =
    .label = Когда появляется новое дерево, другие сворачиваются автоматически
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Когда вкладка получает фокус, развернуть её дерево и автоматически свернуть другие
    .accesskey = x
tree-drop-links-on-tab-behavior-ask =
    .label = Всегда спрашивать меня как с этим обращаться
tree-drop-links-on-tab-behavior-load =
    .label = Загрузить во вкладку
tree-drop-links-on-tab-behavior-newtab =
    .label = Открыть новую дочернюю вкладку
tree-tree-double-click-behavior-toggle-close =
    .label = Закрыть вкладку
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Свернуть/развернуть дерево
tree-tree-double-click-behavior-toggle-none =
    .label = Ничего не делать
waterfox-blocker-intro-description = Блокирует рекламу, скрипты отслеживания и другие нежелательные запросы для более быстрой загрузки страниц и меньшего количества отвлекающих факторов.
waterfox-blocker-setting-on =
    .label = Вкл
waterfox-blocker-setting-on-summary = Блокирует рекламу и трекеры с минимальным влиянием на загрузку страниц.
waterfox-blocker-setting-on-description = Waterfox блокирует следующее:
waterfox-blocker-blocks-ads = Рекламные объявления и запросы рекламной сети
waterfox-blocker-blocks-tracking = Скрипты и пиксели для отслеживания
waterfox-blocker-blocks-annoyances = Навязчивые всплывающие окна и наложения (с включенными списками раздражителей)
waterfox-blocker-partner-funding-title = Поддержите разработку Waterfox
waterfox-blocker-partner-funding-description = Waterfox бесплатен, с открытым исходным кодом и независим. Размещение рекламы на страницах партнеров по поиску — это способ, которым Waterfox финансирует разработку и инфраструктуру. Вы можете отключить это в любое время, но оставив включенным, вы самым простым образом поддержите проект.
waterfox-blocker-setting-off =
    .label = Выкл
waterfox-blocker-setting-off-description = Waterfox не блокирует рекламу или трекеры. Сторонние расширения по-прежнему могут блокировать контент независимо.
waterfox-blocker-dropdown-label =
    .value = Поиск партнерских объявлений:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Разрешить партнёрский поиск в Waterfox
waterfox-blocker-dropdown-option-block-everything =
    .label = Запретить партнерский поиск в Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Управление списками фильтров…
waterfox-blocker-custom-filter-lists =
    .label = Пользовательские списки фильтров…
waterfox-blocker-filter-lists-window =
    .title = Списки фильтров для блокировки рекламы
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Сохранить изменения
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = Выберите, какие списки фильтров активны.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } активно { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Включено
waterfox-blocker-filter-lists-column-name =
    .label = Список фильтров
waterfox-blocker-filter-lists-column-category =
    .label = Категория
waterfox-blocker-filter-lists-enable =
    .label = Включить
waterfox-blocker-filter-lists-disable =
    .label = Отключить
waterfox-blocker-extension-detected = В Waterfox теперь встроена блокировка рекламы. Вы можете проверить ваши настройки в параметрах.
waterfox-blocker-extension-detected-learn-more =
    .label = Узнать больше
waterfox-blocker-extension-detected-dismiss =
    .label = Не показывать снова
waterfox-blocker-extension-install-warning = Waterfox уже имеет встроенный блокировщик рекламы. Одновременное использование двух блокировщиков рекламы может привести к неправильной работе страниц или их медленной загрузке.
waterfox-blocker-extension-install-got-it =
    .label = Понял
waterfox-blocker-extension-install-learn-more =
    .label = Узнать больше
waterfox-blocker-third-party-notice-description = { $extensionName } также блокирует рекламу. Использование двух блокировщиков рекламы может вызвать проблемы.
waterfox-blocker-exceptions-window =
    .title = Исключения для блокировки рекламы
waterfox-blocker-exceptions-description = Вы можете указать, на каких сайтах блокировка рекламы отключена. Введите точный адрес сайта, который вы хотите настроить, а затем нажмите Добавить.
