# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Téamaí Dinimiciúla
dynamic-theme-auto =
    .label = Socraigh Mód Solas/Dorcha go Dinimiciúil
dynamic-theme-dark =
    .label = Fórsáil Mód Dorcha
dynamic-theme-light =
    .label = Mód Solais Fórsála
waterfox-appearance-statusbar-heading =
    .label = Barra Stádais
waterfox-appearance-statusbar-enabled-toggle =
    .label = Taispeáin barra stádais
    .description = Taispeáin barra uirlisí ag bun na fuinneoige.
waterfox-appearance-statusbar-links-toggle =
    .label = Taispeáin cinn scríbe naisc sa bharra stádais
pane-theme-title = Breathnú & Mothú
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Beochana
appearance-header = Dealramh
autohide-hidden-header = Folaigh & Folaithe go huathoibríoch
bookmark-header = Barra Leabharmharcanna
center-header = Lár
font-header = Clónna
full-screen-header = Lánscáileán
icons-header = Deilbhíní
interface-component-header = Comhpháirteanna Comhéadain
media-player-header = Seinnteoir Meán
nav-bar-header = Barra Loingseoireachta
panels-header = Painéil
rounding-header = Babhtáil
sidebar-header = Barra taobh
tab-bar-header = Barra na gCluaisíní
theme-header = Téama
preset-title = Réamhshocruithe
lepton-style =
    .label = Stíl Lepton
proton-style =
    .label = Stíl Prótóin
waterfox-defaults =
    .label = Réamhshocruithe Waterfox
auto-blur-tabs =
    .label = Doiléiriú Uathoibríoch ar Thaibíní
auto-hide-back =
    .label = An cnaipe "Folaigh Ar Ais" go huathoibríoch
auto-hide-bookmarkbar =
    .label = Barra Leabharmharcanna a Fholach go hUathoibríoch
auto-hide-forward =
    .label = An cnaipe "Folaigh Ar Aghaidh" go huathoibríoch
auto-hide-navbar =
    .label = Barra Loingseoireachta a Fholach go hUathoibríoch
auto-hide-pageaction =
    .label = Gníomh Leathanaigh a Fholach go hUathoibríoch
auto-hide-sidebar =
    .label = Barra Taobh a Fholach go hUathoibríoch
auto-hide-tabbar =
    .label = Barra na gCluaisíní a Fholach go hUathoibríoch
auto-hide-tabs =
    .label = Folaigh Cluaisíní go hUathoibríoch
center-navbar-text =
    .label = Téacs an Bharra Loingseoireachta Láir
center-tab-content =
    .label = Ábhar Lárnach an Chluaisín
center-tab-label =
    .label = Lipéad Cluaisín Láir Amháin
close-button-hover =
    .label = Taispeáin cnaipe dúnta cluaisín nuair a bhíonn an luchóg os cionn an chluaisín roghnaithe nuair a bhíonn go leor cluaisíní oscailte
compact-bookmark-menu =
    .label = Laghdaigh Líonadh Roghchláir Leabharmharcanna
compact-context-menu =
    .label = Laghdaigh an Líonta Roghchláir Chomhthéacsúla
compact-navbar-popup =
    .label = Laghdaigh Líonadh aníos an Bharra Loingseoireachta
compact-panel-header =
    .label = Laghdaigh Líonadh Ceanntásc an Phainéil
disable-panel-animate =
    .label = Díchumasaigh beochan phainéil roghchláir an aip
disable-sidebar-animate =
    .label = Díchumasaigh beochan painéil an bharra taoibh
drag-space =
    .label = Cumasaigh Spás Tarraingthe Seasta
enable-cyan-accent-color =
    .label = Dath Aicinn Cian
enable-default-accent-color =
    .label = Dath Aicinn Réamhshocraithe
enable-menu-transparency =
    .label = Cumasaigh trédhearcacht an roghchláir
enable-panel-transparency =
    .label = Cumasaigh trédhearcacht an phainéil
enable-system-accent-color =
    .label = Dath Aicinn an Chórais
enable-waterfox-theme-0 =
    .label = Cumasaigh saincheaptha téama Waterfox ar gach téama
enable-waterfox-theme-1 =
    .label = Cumasaigh saincheaptha téama Waterfox ar théamaí Waterfox
enable-waterfox-theme-2 =
    .label = Díchumasaigh saincheaptha téama Waterfox
full-panel-strip =
    .label = Deighilteoir Roghchláir Aipe Lánleithead
remove-panel-strip =
    .label = Bain Deighilteoir Daite Roghchláir Aipeanna
hide-all-icons =
    .label = Folaigh Gach Deilbhín
hide-bookmarkbar-icon =
    .label = Folaigh Deilbhíní Barra Leabharmharcanna
hide-bookmarkbar-label =
    .label = Folaigh Lipéid Barra Leabharmharcanna
hide-disabled-menuitems =
    .label = Folaigh Míreanna Roghchláir Díchumasaithe
hide-sidebar-header =
    .label = Folaigh Ceanntásc an Bharra Taoibh
hide-tab-icons =
    .label = Folaigh Deilbhíní Cluaisíní
hide-urlbar-iconbox =
    .label = Folaigh Bosca Deilbhíní Barra URL
monospace-font =
    .label = Cumasaigh cló aonspáisithe don leathanach
monospace-font-theme =
    .label = Cumasaigh cló aonspáis don téama
show-mac-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir Mac
show-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir
square-button-edges =
    .label = Coirnéil Cnaipe Cearnógacha
square-checkbox =
    .label = Bosca Seiceála Cearnógach
square-field =
    .label = Coirnéil Réimse Iontrála Cearnógacha
square-menu-item =
    .label = Cúinní Míre Roghchláir Chomhthéacs Cearnógacha
square-menu-panel =
    .label = Cúinní Painéal Roghchláir Aipe Cearnógacha
square-menu-popup =
    .label = Cúinní Painéil Roghchláir Chomhthéacs Cearnógacha
square-panel-item =
    .label = Cúinní Roghchláir Aipe Cearnógacha
square-tab-edges =
    .label = Coirnéil Tab Cearnógacha
tab-context-line =
    .label = Líne Chomhthéacs Tab
waterfox-appearance-browser-style-group =
    .label = Stíl brabhsálaí
    .description = Roghnaigh cuma fhoriomlán Waterfox.
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = An cuma shínithe Waterfox ar chrome an bhrabhsálaí stoic.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = Stíl nua-aimseartha brabhsálaí stoic.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = Stíl chlasaiceach Waterfox le cróm scagtha.
waterfox-appearance-theme-colors-group =
    .label = Pailéad Dathanna
    .description = Roghnaigh pailéad dathanna Waterfox agus cibé an leanann sé téama do chórais.
waterfox-appearance-theme-mode-picker =
    .label = Mód téama
waterfox-appearance-theme-mode-option-system =
    .label = Córas
waterfox-appearance-theme-mode-option-light =
    .label = Solas
waterfox-appearance-theme-mode-option-dark =
    .label = Dorcha
waterfox-appearance-theme-color-picker =
    .label = Dath an téama
waterfox-appearance-theme-color-option-default =
    .label = Réamhshocrú
waterfox-appearance-theme-color-option-smoke =
    .label = Deatach
waterfox-appearance-theme-color-option-ash =
    .label = Fuinseog
waterfox-appearance-theme-color-option-sun =
    .label = Grian
waterfox-appearance-theme-color-option-spark =
    .label = Splanc
waterfox-appearance-theme-color-option-flame =
    .label = Lasair
waterfox-appearance-theme-color-option-flare =
    .label = Lasadh
waterfox-appearance-theme-color-option-lavender =
    .label = Lavandar
waterfox-appearance-theme-color-option-dusk =
    .label = Luí na gréine
waterfox-appearance-theme-color-option-lagoon =
    .label = Lagún
waterfox-appearance-theme-color-option-tide =
    .label = Taoide
waterfox-appearance-theme-color-option-pine =
    .label = Péine
waterfox-appearance-details-group =
    .label = Tuilleadh roghanna cuma
    .description = Déan comhéadan Waterfox a choigeartú go mín.
waterfox-appearance-transparent-toggle =
    .label = Painéil agus biachláir thrédhearcacha
waterfox-appearance-autohide-tabbar-toggle =
    .label = Folaigh an barra cluaisíní go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Folaigh an barra uirlisí leabharmharcanna go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-sidebar-toggle =
    .label = Folaigh an barra taoibh go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-navigation-toggle =
    .label = Folaigh na cnaipí ar ais agus ar aghaidh nuair nach ndéanann siad aon rud
waterfox-appearance-close-button-hover-toggle =
    .label = Taispeáin an cnaipe dúnta cluaisín amháin nuair a bhíonn an luchóg air
waterfox-appearance-drag-space-toggle =
    .label = Coinnigh spás tarraingthe os cionn na gcluaisíní
