# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Téamaí Dinimiciúla
dynamic-theme-auto =
    .label = Socraigh Mód Solas/Dorcha go Dinimiciúil
dynamic-theme-dark =
    .label = Fórsáil Mód Dorcha
dynamic-theme-light =
    .label = Mód Solais Fórsála
waterfox-appearance-statusbar-heading =
    .label = Barra Stádais
waterfox-appearance-statusbar-enabled-toggle =
    .label = Taispeáin barra stádais
    .description = Taispeáin barra uirlisí ag bun na fuinneoige.
waterfox-appearance-statusbar-links-toggle =
    .label = Taispeáin cinn scríbe naisc sa bharra stádais
pane-theme-title = Breathnú & Mothú
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Beochana
appearance-header = Dealramh
autohide-hidden-header = Folaigh & Folaithe go huathoibríoch
bookmark-header = Barra Leabharmharcanna
center-header = Lár
font-header = Clónna
full-screen-header = Lánscáileán
icons-header = Deilbhíní
interface-component-header = Comhpháirteanna Comhéadain
media-player-header = Seinnteoir Meán
nav-bar-header = Barra Loingseoireachta
panels-header = Painéil
rounding-header = Babhtáil
sidebar-header = Barra taobh
tab-bar-header = Barra na gCluaisíní
theme-header = Téama
preset-title = Réamhshocruithe
lepton-style =
    .label = Stíl Lepton
proton-style =
    .label = Stíl Prótóin
waterfox-defaults =
    .label = Réamhshocruithe Waterfox
auto-blur-tabs =
    .label = Doiléiriú Uathoibríoch ar Thaibíní
auto-hide-back =
    .label = An cnaipe "Folaigh Ar Ais" go huathoibríoch
auto-hide-bookmarkbar =
    .label = Barra Leabharmharcanna a Fholach go hUathoibríoch
auto-hide-forward =
    .label = An cnaipe "Folaigh Ar Aghaidh" go huathoibríoch
auto-hide-navbar =
    .label = Barra Loingseoireachta a Fholach go hUathoibríoch
auto-hide-pageaction =
    .label = Gníomh Leathanaigh a Fholach go hUathoibríoch
auto-hide-sidebar =
    .label = Barra Taobh a Fholach go hUathoibríoch
auto-hide-tabbar =
    .label = Barra na gCluaisíní a Fholach go hUathoibríoch
auto-hide-tabs =
    .label = Folaigh Cluaisíní go hUathoibríoch
center-navbar-text =
    .label = Téacs an Bharra Loingseoireachta Láir
center-tab-content =
    .label = Ábhar Lárnach an Chluaisín
center-tab-label =
    .label = Lipéad Cluaisín Láir Amháin
close-button-hover =
    .label = Taispeáin cnaipe dúnta cluaisín nuair a bhíonn an luchóg os cionn an chluaisín roghnaithe nuair a bhíonn go leor cluaisíní oscailte
compact-bookmark-menu =
    .label = Laghdaigh Líonadh Roghchláir Leabharmharcanna
compact-context-menu =
    .label = Laghdaigh an Líonta Roghchláir Chomhthéacsúla
compact-navbar-popup =
    .label = Laghdaigh Líonadh aníos an Bharra Loingseoireachta
compact-panel-header =
    .label = Laghdaigh Líonadh Ceanntásc an Phainéil
disable-panel-animate =
    .label = Díchumasaigh beochan phainéil roghchláir an aip
disable-sidebar-animate =
    .label = Díchumasaigh beochan painéil an bharra taoibh
drag-space =
    .label = Cumasaigh Spás Tarraingthe Seasta
enable-cyan-accent-color =
    .label = Dath Aicinn Cian
enable-default-accent-color =
    .label = Dath Aicinn Réamhshocraithe
enable-menu-transparency =
    .label = Cumasaigh trédhearcacht an roghchláir
enable-panel-transparency =
    .label = Cumasaigh trédhearcacht an phainéil
enable-system-accent-color =
    .label = Dath Aicinn an Chórais
enable-waterfox-theme-0 =
    .label = Cumasaigh saincheaptha téama Waterfox ar gach téama
enable-waterfox-theme-1 =
    .label = Cumasaigh saincheaptha téama Waterfox ar théamaí Waterfox
enable-waterfox-theme-2 =
    .label = Díchumasaigh saincheaptha téama Waterfox
full-panel-strip =
    .label = Deighilteoir Roghchláir Aipe Lánleithead
remove-panel-strip =
    .label = Bain Deighilteoir Daite Roghchláir Aipeanna
hide-all-icons =
    .label = Folaigh Gach Deilbhín
hide-bookmarkbar-icon =
    .label = Folaigh Deilbhíní Barra Leabharmharcanna
hide-bookmarkbar-label =
    .label = Folaigh Lipéid Barra Leabharmharcanna
hide-disabled-menuitems =
    .label = Folaigh Míreanna Roghchláir Díchumasaithe
hide-sidebar-header =
    .label = Folaigh Ceanntásc an Bharra Taoibh
hide-tab-icons =
    .label = Folaigh Deilbhíní Cluaisíní
hide-urlbar-iconbox =
    .label = Folaigh Bosca Deilbhíní Barra URL
monospace-font =
    .label = Cumasaigh cló aonspáisithe don leathanach
monospace-font-theme =
    .label = Cumasaigh cló aonspáis don téama
show-mac-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir Mac
show-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir
square-button-edges =
    .label = Coirnéil Cnaipe Cearnógacha
square-checkbox =
    .label = Bosca Seiceála Cearnógach
square-field =
    .label = Coirnéil Réimse Iontrála Cearnógacha
square-menu-item =
    .label = Cúinní Míre Roghchláir Chomhthéacs Cearnógacha
square-menu-panel =
    .label = Cúinní Painéal Roghchláir Aipe Cearnógacha
square-menu-popup =
    .label = Cúinní Painéil Roghchláir Chomhthéacs Cearnógacha
square-panel-item =
    .label = Cúinní Roghchláir Aipe Cearnógacha
square-tab-edges =
    .label = Coirnéil Tab Cearnógacha
tab-context-line =
    .label = Líne Chomhthéacs Tab
waterfox-appearance-browser-style-group =
    .label = Stíl brabhsálaí
    .description = Roghnaigh cuma fhoriomlán Waterfox.
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = An cuma shínithe Waterfox ar chrome an bhrabhsálaí stoic.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = Stíl nua-aimseartha brabhsálaí stoic.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = Stíl chlasaiceach Waterfox le cróm scagtha.
waterfox-appearance-theme-colors-group =
    .label = Pailéad dathanna
    .description = Roghnaigh pailéad dathanna Waterfox agus cibé an leanann sé téama do chórais.
waterfox-appearance-theme-mode-picker =
    .label = Mód téama
waterfox-appearance-theme-mode-option-system =
    .label = Córas
waterfox-appearance-theme-mode-option-light =
    .label = Solas
waterfox-appearance-theme-mode-option-dark =
    .label = Dorcha
waterfox-appearance-theme-color-picker =
    .label = Dath an téama
waterfox-appearance-theme-color-option-default =
    .label = Réamhshocrú
waterfox-appearance-theme-color-option-smoke =
    .label = Deatach
waterfox-appearance-theme-color-option-ash =
    .label = Fuinseog
waterfox-appearance-theme-color-option-sun =
    .label = Grian
waterfox-appearance-theme-color-option-spark =
    .label = Splanc
waterfox-appearance-theme-color-option-flame =
    .label = Lasair
waterfox-appearance-theme-color-option-flare =
    .label = Lasadh
waterfox-appearance-theme-color-option-lavender =
    .label = Lavandar
waterfox-appearance-theme-color-option-dusk =
    .label = Luí na gréine
waterfox-appearance-theme-color-option-lagoon =
    .label = Lagún
waterfox-appearance-theme-color-option-tide =
    .label = Taoide
waterfox-appearance-theme-color-option-pine =
    .label = Péine
waterfox-appearance-details-group =
    .label = Tuilleadh roghanna cuma
    .description = Déan comhéadan Waterfox a choigeartú go mín.
waterfox-appearance-transparent-toggle =
    .label = Painéil agus biachláir thrédhearcacha
waterfox-appearance-autohide-tabbar-toggle =
    .label = Folaigh an barra cluaisíní go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Folaigh an barra uirlisí leabharmharcanna go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-sidebar-toggle =
    .label = Folaigh an barra taoibh go dtí go gcuirfidh tú pointe air
waterfox-appearance-autohide-navigation-toggle =
    .label = Folaigh na cnaipí ar ais agus ar aghaidh nuair nach ndéanann siad aon rud
waterfox-appearance-close-button-hover-toggle =
    .label = Taispeáin an cnaipe dúnta cluaisín amháin nuair a bhíonn an luchóg air
waterfox-appearance-drag-space-toggle =
    .label = Coinnigh spás tarraingthe os cionn na gcluaisíní
waterfox-density-group =
    .label = Dlús
    .description = Cé mhéad spáis anála a fhaigheann na barraí uirlisí agus na biachláir.
waterfox-density-compact =
    .label = Dlúth
waterfox-density-normal =
    .label = Gnáth
waterfox-density-touch =
    .label = Teagmháil
waterfox-appearance-interface-customizations-group =
    .label = Saincheaptha comhéadain
    .description = Rialuithe breise le haghaidh cluaisíní, barraí uirlisí, deilbhíní agus ábhar.
waterfox-appearance-chrome-sheet =
    .label = Luchtaigh saincheaptha comhéadain
    .description = Múch chun stílbileog chomhéadain Waterfox a dhíluchtú agus na roghanna a rialaíonn sé a cheilt.
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = Téamaí ionsuite
waterfox-appearance-chrome-sheet-all-themes =
    .label = Gach téama
waterfox-appearance-chrome-sheet-off =
    .label = As
waterfox-opt-tabbar-heading =
    .label = Barra cluaisíní
    .description = Méid, spásáil agus infheictheacht na stiall ina bhfuil do chluaisíní suite.
waterfox-opt-tabbar-fill-width =
    .label = Sín na cluaisíní chun an leithead a líonadh
waterfox-opt-tabbar-as-titlebar =
    .label = Taispeáin an cluaisín reatha amháin sa bharra teidil
waterfox-opt-hidden-tabbar =
    .label = Folaigh an barra cluaisíní
waterfox-opt-hidden-titlebar-container =
    .label = Folaigh an coimeádán barra teidil
waterfox-opt-autohide-tab =
    .label = Laghdaigh na cluaisíní cúlra go dtí go gcuireann tú pointe orthu
waterfox-opt-autohide-tab-opacity =
    .label = Céimnigh amach iad chomh maith
waterfox-opt-autohide-tab-blur =
    .label = Doiléir iad chomh maith
waterfox-opt-padding-tabbar-width =
    .label = Cúngaigh an barra cluaisíní
waterfox-opt-padding-tabbar-height =
    .label = Giorraigh an barra cluaisíní
waterfox-opt-padding-first-tab =
    .label = Fág bearna roimh an gcéad chluaisín
waterfox-opt-padding-first-tab-always =
    .label = Coinnigh an bhearna fiú nuair a bhíonn sé uasmhéadaithe
waterfox-opt-padding-drag-space =
    .label = Coinnigh spás tarraingthe os cionn na gcluaisíní
waterfox-opt-padding-drag-space-maximized =
    .label = Coinnigh é nuair a bhíonn sé uasmhéadaithe freisin
waterfox-opt-centered-tab =
    .label = Lárnaigh ábhar an chluaisín
waterfox-opt-centered-tab-label =
    .label = Lárnaigh an lipéad amháin
waterfox-opt-counter-tab =
    .label = Taispeáin comhaireamh cluaisíní
waterfox-opt-tabs-heading =
    .label = Cluaisíní
    .description = Cruth cluaisín agus a thaispeánann sé.
waterfox-opt-tab-connect-to-window =
    .label = Ceangail an cluaisín roghnaithe leis an mbarra uirlisí thíos
waterfox-opt-tab-color-like-toolbar =
    .label = Dathúigh an cluaisín roghnaithe cosúil leis an mbarra uirlisí
waterfox-opt-tab-box-shadow =
    .label = Caith scáth faoin táb roghnaithe
waterfox-opt-tab-selected-bold =
    .label = Cuir lipéad an chluaisín roghnaithe i gcló trom
waterfox-opt-tab-blue-accent =
    .label = Úsáid béim ghorm ar an táb roghnaithe
waterfox-opt-tab-contextline-blue-accent =
    .label = Bain úsáid as béim ghorm ar an líne chomhthéacs
waterfox-opt-tab-bottom-rounded-corner =
    .label = Babhtaigh coirnéil íochtaracha an chluaisín roghnaithe
waterfox-opt-tab-bottom-rounded-corner-all =
    .label = Cuir coirnéil chothromú i bhfeidhm ar gach cluaisín
waterfox-opt-tab-multi-selected =
    .label = Aibhsigh cluaisíní ilroghnaithe níos láidre
waterfox-opt-tab-letters-cleary =
    .label = Coinnigh lipéid inléite ar chluaisíní cúnga
waterfox-opt-hidden-tab-icon =
    .label = Folaigh deilbhíní cluaisín
waterfox-opt-hidden-tab-icon-always =
    .label = Folaigh iad fiú ar chluaisíní bioráilte
waterfox-opt-tab-close-button-at-hover =
    .label = Taispeáin an cnaipe dúnta amháin nuair a bhíonn an luchóg air
waterfox-opt-tab-close-button-at-hover-always =
    .label = Déan é is cuma cé mhéad cluaisín atá oscailte
waterfox-opt-tab-close-button-at-hover-with-selected =
    .label = Cuir an cluaisín roghnaithe san áireamh
waterfox-opt-tab-close-button-at-pinned =
    .label = Taispeáin cnaipe dúnta ar chluaisíní bioráilte
waterfox-opt-tab-close-button-at-pinned-always =
    .label = Taispeáin é gan an luchóg a chur air
waterfox-opt-tab-close-button-at-pinned-background =
    .label = Tabhair cúlra dó
waterfox-opt-tab-container =
    .label = Marcáil cluaisíní coimeádáin lena ndath
waterfox-opt-tab-container-on-top =
    .label = Cuir an marcóir os cionn an chluaisín
waterfox-opt-tab-container-always-long =
    .label = Rith é ar leithead iomlán an chluaisín
waterfox-opt-tab-sound-with-favicons =
    .label = Taispeáin an táscaire fuaime os cionn an deilbhín cluaisín
waterfox-opt-tab-sound-with-favicons-on-center =
    .label = Cuir i lár é ar an deilbhín
waterfox-opt-tab-unloaded =
    .label = Céimnigh na cluaisíní díluchtaithe
waterfox-opt-tab-crashed =
    .label = Taispeáin an táscaire tuairteála ar chluaisíní tuairteáilte amháin
waterfox-opt-tab-pip =
    .label = Marcáil cluaisíní ag imirt pictiúr-i-bpictiúr
waterfox-opt-tab-padding =
    .label = Líonta cluaisíní
waterfox-opt-tab-padding-default =
    .label = Réamhshocrú
waterfox-opt-tab-padding-lepton =
    .label = Spásúil
waterfox-opt-tab-padding-photon =
    .label = Dlúth
waterfox-opt-tab-separator =
    .label = Deighilteoir idir cluaisíní
waterfox-opt-tab-separator-none =
    .label = Gan aon cheann
waterfox-opt-tab-separator-dynamic =
    .label = Idir cluaisíní neamhroghnaithe amháin
waterfox-opt-tab-separator-static =
    .label = Idir gach cluaisín
waterfox-opt-tab-separator-bar =
    .label = Barra lánairde
waterfox-opt-tab-newtab-button =
    .label = Cnaipe cluaisín nua
waterfox-opt-tab-newtab-button-default =
    .label = Réamhshocrú
waterfox-opt-tab-newtab-button-like-tab =
    .label = Cruth cluaisín
waterfox-opt-tab-newtab-button-smaller =
    .label = Níos lú
waterfox-opt-tab-newtab-button-proton =
    .label = Prótón
waterfox-opt-tab-contextline =
    .label = Táscaire cluaisín roghnaithe
waterfox-opt-tab-contextline-none =
    .label = Gan aon cheann
waterfox-opt-tab-contextline-photon =
    .label = Líne os cionn an chluaisín
waterfox-opt-tab-contextline-supernova =
    .label = Líne faoin táb
waterfox-opt-tab-corner-style =
    .label = Cruth cúinne bun
waterfox-opt-tab-corner-style-default =
    .label = Réamhshocrú
waterfox-opt-tab-corner-style-australis =
    .label = Australis
waterfox-opt-tab-corner-style-chrome =
    .label = Chrome
waterfox-opt-tab-corner-style-chrome-legacy =
    .label = Chrome (seanleagan)
waterfox-opt-tab-corner-style-edge =
    .label = Edge
waterfox-opt-tab-corner-style-wave =
    .label = Tonn
waterfox-opt-tab-static-separator-selected-accent =
    .label = Cuir béim ar an deighilteoir in aice leis an táb roghnaithe
waterfox-opt-toolbars-heading =
    .label = Barraí Uirlisí
    .description = Cnaipí nascleanúna, spásáil idir na barraí uirlisí agus a bhfuil i bhfolach.
waterfox-opt-hidden-navbar =
    .label = Folaigh an barra uirlisí nascleanúna
waterfox-opt-autohide-navbar =
    .label = Folaigh é go dtí go gcuirfidh tú pointe air
waterfox-opt-autohide-back-button =
    .label = Folaigh an cnaipe ar ais nuair nach ndéanann sé tada
waterfox-opt-autohide-forward-button =
    .label = Folaigh an cnaipe ar aghaidh nuair nach ndéanann sé tada
waterfox-opt-combined-nav-button =
    .label = Grúpáil na cnaipí nascleanúna le chéile
waterfox-opt-combined-nav-button-home-button =
    .label = Cuir an cnaipe baile san áireamh
waterfox-opt-padding-toolbar-button =
    .label = Déan spásáil na gcnaipí idir na barraí uirlisí a dhéanamh níos doichte
waterfox-opt-padding-toolbar-button-compact =
    .label = Déan níos mó teannta é
waterfox-opt-autohide-toolbar-overlap =
    .label = Lig do bharraí uirlisí atá i bhfolach go huathoibríoch forluí a dhéanamh ar an leathanach
waterfox-opt-autohide-infobar =
    .label = Folaigh barraí fógra go dtí go gcuirfidh tú pointe orthu
waterfox-opt-padding-infobar =
    .label = Déan líonadh an bharra fógraí a dhéanamh níos doichte
waterfox-opt-findbar-floating-on-top =
    .label = Snámh an barra cuardaigh thar an leathanach
waterfox-opt-padding-global-menubar =
    .label = Déan an barra roghchláir a theannú
waterfox-opt-centered-urlbar =
    .label = Lárnaigh téacs an bharra seoltaí
waterfox-opt-autohide-fill-urlbar =
    .label = Líon an barra uirlisí leis an mbarra seoltaí go dtí go gcuireann tú pointe air
waterfox-opt-autohide-page-action =
    .label = Folaigh cnaipí gníomhaíochta leathanaigh go dtí go gcuirfidh tú pointe orthu
waterfox-opt-urlbar-always-show-page-actions =
    .label = Taispeáin cnaipí gníomhaíochta leathanaigh i gcónaí
waterfox-opt-hidden-urlbar-iconbox =
    .label = Folaigh an bosca aitheantais suímh
waterfox-opt-hidden-urlbar-iconbox-label-only =
    .label = Folaigh a lipéad amháin
waterfox-opt-urlbar-iconbox-with-separator =
    .label = Deighil an bosca aitheantais le líne
waterfox-opt-urlview-focus-item-border =
    .label = Déan cur síos ar an toradh fócasaithe
waterfox-opt-padding-urlview-result =
    .label = Déan sraitheanna torthaí a dhéanamh níos doichte
waterfox-opt-rounding-square-urlview-item =
    .label = Cearnóg coirnéil an toraidh
waterfox-opt-bookmarks-heading =
    .label = Leabharmharcanna
    .description = An barra uirlisí leabharmharcanna agus an roghchlár leabharmharcanna.
waterfox-opt-bookmarkbar-multi-row =
    .label = Fill an barra uirlisí leabharmharcanna ar roinnt sraitheanna
waterfox-opt-autohide-bookmarkbar =
    .label = Folaigh an barra uirlisí leabharmharcanna go dtí go gcuirfidh tú pointe air
waterfox-opt-centered-bookmarkbar =
    .label = Lárnaigh barra uirlisí na leabharmharcanna
waterfox-opt-padding-bookmarkbar =
    .label = Déan barra uirlisí na leabharmharcanna a theannú
waterfox-opt-hidden-bookmarkbar-icon =
    .label = Folaigh deilbhíní leabharmharcanna
waterfox-opt-hidden-bookmarkbar-label =
    .label = Folaigh lipéid leabharmharcanna
waterfox-opt-padding-bookmark-menu =
    .label = Déan an roghchlár leabharmharcanna a dhéanamh níos doichte
waterfox-opt-padding-bookmark-menu-compact =
    .label = Déan níos mó teannta é
waterfox-opt-counter-bookmark-menu =
    .label = Taispeáin comhaireamh sa roghchlár leabharmharcanna
waterfox-opt-decoration-disable-sidebar-animate =
    .label = Múch beochan an bharra taoibh
waterfox-opt-icons-heading =
    .label = Deilbhíní
    .description = Cá bhfuil deilbhíní le feiceáil agus cé chomh mór is atá siad.
waterfox-opt-icon-disabled =
    .label = Folaigh na deilbhíní roghchláir agus painéil go léir
waterfox-opt-icon-menu =
    .label = Taispeáin deilbhíní i roghchláir
waterfox-opt-icon-menu-full =
    .label = Taispeáin iad ar gach mír ar an roghchlár
waterfox-opt-icon-context-menu =
    .label = Taispeáin deilbhíní i roghchláir chomhthéacs
waterfox-opt-icon-global-menu =
    .label = Taispeáin deilbhíní i mbarra roghchláir
waterfox-opt-icon-global-menu-mac =
    .label = Taispeáin iad ar macOS freisin
waterfox-opt-icon-global-menubar =
    .label = Taispeáin deilbhíní sa bharra roghchláir
waterfox-opt-icon-panel =
    .label = Taispeáin deilbhíní sna painéil
waterfox-opt-icon-library =
    .label = Taispeáin deilbhíní sa leabharlann
waterfox-opt-icon-1-25px-stroke =
    .label = Úsáid strócanna deilbhín níos tibhe
waterfox-opt-icon-account-image-to-right =
    .label = Cuir pictiúr an chuntais ar dheis
waterfox-opt-icon-account-label-to-right =
    .label = Cuir ainm an chuntais ar dheis
waterfox-opt-panel-icons =
    .label = Deilbhíní roghchláir aipeanna
    .description = Cé mhéad sraith den phríomhroghchlár a thugann Waterfox d'íocón.
waterfox-opt-panel-icons-photon =
    .label = Príomh-mhíreanna amháin
waterfox-opt-panel-icons-full =
    .label = Gach mír
waterfox-opt-rounding-heading =
    .label = Coirnéil
    .description = Déan na coirnéil chruinne timpeall an chomhéadain a chearnú.
waterfox-opt-rounding-square-tab =
    .label = Cearnóg coirnéil an chluaisín
waterfox-opt-rounding-square-toolbar =
    .label = Cearnóg coirnéil an bharra uirlisí
waterfox-opt-rounding-square-button =
    .label = Cearnóg coirnéil na gcnaipe
waterfox-opt-rounding-square-field =
    .label = Cearnóg coirnéil an réimse téacs
waterfox-opt-rounding-square-checklabel =
    .label = Cearnóg coirnéil an bhosca seiceála
waterfox-opt-rounding-square-dialog =
    .label = Cearnóg coirnéil an dialóige
waterfox-opt-rounding-square-infobox =
    .label = Cearnóg coirnéil an fhógra
waterfox-opt-rounding-square-panel =
    .label = Cearnóg coirnéil an phainéil
waterfox-opt-rounding-square-panelitem =
    .label = Cearnóg coirnéil mhír an phainéil
waterfox-opt-rounding-square-menupopup =
    .label = Cearnóg coirnéil an roghchláir
waterfox-opt-rounding-square-menuitem =
    .label = Cearnóg coirnéil mhír an roghchláir
waterfox-opt-theme-heading =
    .label = Téama agus éifeachtaí
    .description = Dath, trédhearcacht agus beochan ar fud an chomhéadain.
waterfox-opt-theme-proton-color =
    .label = Úsáid pailéad dathanna Proton ar leathanaigh ionsuite.
    .description = Baineann sé seo le leathanaigh faoi: agus radhairc ionsuite eile, ní le fráma an bhrabhsálaí.
waterfox-opt-theme-proton-chrome =
    .label = Cuir i bhfeidhm é ar dhialóga agus ar fhuinneoga Leabharlainne
waterfox-opt-theme-fully-color =
    .label = Cuir i bhfeidhm é i ngach áit
waterfox-opt-theme-fully-dark =
    .label = Cosc a chur ar splancanna solais i mód dorcha
waterfox-opt-theme-built-in-contrast =
    .label = Ardaigh codarsnacht na dtéamaí ionsuite
waterfox-opt-theme-system-default =
    .label = Lean téama an chórais
waterfox-opt-theme-private =
    .label = Tint fuinneoga príobháideacha
waterfox-opt-hidden-private-indicator =
    .label = Folaigh an táscaire brabhsála príobháideach
waterfox-opt-theme-transparent-panel =
    .label = Déan painéil trédhearcach
waterfox-opt-theme-transparent-frame =
    .label = Déan fráma na fuinneoige trédhearcach
waterfox-opt-theme-monospace =
    .label = Úsáid cló aonspáisithe sa chomhéadan
waterfox-opt-decoration-animate =
    .label = Beochan athruithe comhéadain
waterfox-opt-decoration-disable-panel-animate =
    .label = Múch beochan roghchláir an aip
waterfox-opt-content-heading =
    .label = Leathanaigh ghréasáin
    .description = Cuirtear stíliú Waterfox i bhfeidhm ar bharr leathanaigh ghréasáin.
waterfox-opt-page-monospace =
    .label = Úsáid cló aonspáisithe ar leathanaigh ionsuite
waterfox-opt-page-dark-mode-pdf =
    .label = Déan PDFanna a dhorchú agus téama dorcha á úsáid
waterfox-opt-newtab-heading =
    .label = Leathanach cluaisín nua
    .description = Cuma an leathanaigh a dtiocfaidh tú air i gcluaisín nua.
waterfox-opt-newtab-hidden-logo =
    .label = Folaigh an lógó
waterfox-opt-newtab-full-icon =
    .label = Líon na tíleanna aicearra lena n-íocón
waterfox-opt-newtab-background-image =
    .label = Taispeáin íomhá chúlra
waterfox-opt-newtab-animate =
    .label = Beochan na tíleanna
waterfox-opt-player-heading =
    .label = Imreoir físe
    .description = Rialuithe agus méide don imreoir físe ionsuite.
waterfox-opt-player-ui =
    .label = Athstíligh na rialuithe físe ionsuite
waterfox-opt-player-ui-twoline =
    .label = Leag na rialuithe amach ar dhá líne
waterfox-opt-player-icon =
    .label = Úsáid deilbhíní rialaithe Waterfox
waterfox-opt-player-size =
    .label = Méadaigh na rialuithe
waterfox-opt-player-noaudio =
    .label = Folaigh an rialú toirte nuair nach bhfuil aon fhuaim i bhfíseán
waterfox-opt-player-click-to-play =
    .label = Stíl an fhorleagan cliceáil-le-súgradh
    .description = Cuireann sé stíliú luiche agus cúrsóir pointeora leis an bhforleagan atá ann cheana féin.
waterfox-opt-player-animate =
    .label = Beochan na rialuithe
