# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

waterfox-blocker-header = Blocáil Fógraí
waterfox-blocker-intro-description = Cuireann sé bac ar fhógraí, ar scripteanna rianaithe, agus ar iarratais eile nach dteastaíonn uait le haghaidh lódálacha leathanaigh níos tapúla agus níos lú seachrán.
waterfox-blocker-setting-on =
    .label = Ar
waterfox-blocker-setting-on-summary = Blocann sé fógraí agus rianaitheoirí le tionchar íosta ar luchtú leathanaigh.
waterfox-blocker-setting-on-description = Cuireann Waterfox bac ar na nithe seo a leanas:
waterfox-blocker-blocks-ads = Fógraí agus iarratais líonra fógraí
waterfox-blocker-blocks-tracking = Scripteanna rianaithe agus picteilíní
waterfox-blocker-blocks-annoyances = Fuinneoga aníos agus forleagan míchaoithiúlachta (le liostaí míchaoithiúlachta cumasaithe)
waterfox-blocker-partner-funding-title = Tacaigh le forbairt Waterfox
waterfox-blocker-partner-funding-description = Tá Waterfox saor in aisce, foinse oscailte agus neamhspleách. Is trí fhógraí a cheadú ar leathanaigh chomhpháirtithe cuardaigh a mhaoiniú a dhéanann Waterfox forbairt agus bonneagar. Is féidir leat é seo a mhúchadh am ar bith, ach is é an bealach is fusa chun tacú leis an tionscadal ná é a choinneáil ar siúl.
waterfox-blocker-setting-off =
    .label = As
waterfox-blocker-setting-off-description = Ní chuireann Waterfox bac ar aon fhógraí ná rianaitheoirí. Is féidir le síntí tríú páirtí ábhar a bhlocáil go neamhspleách fós.
waterfox-blocker-dropdown-label =
    .value = Fógraí comhpháirtíochta cuardaigh:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Ceadaigh ar chomhpháirtithe cuardaigh Waterfox
waterfox-blocker-dropdown-option-block-everything =
    .label = Toirmeasc ar chomhpháirtithe cuardaigh Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Bainistigh Liostaí Scagaire…
waterfox-blocker-custom-filter-lists =
    .label = Liostaí Scagaire Saincheaptha…
waterfox-blocker-filter-lists-window =
    .title = Liostaí scagairí blocála fógraí
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Sábháil Athruithe
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = Roghnaigh cé na liostaí scagaire atá gníomhach.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } gníomhach de { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Cumasaithe
waterfox-blocker-filter-lists-column-name =
    .label = Liosta Scagaire
waterfox-blocker-filter-lists-column-category =
    .label = Catagóir
waterfox-blocker-filter-lists-enable =
    .label = Cumasaigh
waterfox-blocker-filter-lists-disable =
    .label = Díchumasaigh
waterfox-blocker-extension-detected = Tá blocáil fógraí ionsuite ag Waterfox anois. Is féidir leat athbhreithniú a dhéanamh ar do shocrú sna socruithe.
waterfox-blocker-extension-detected-learn-more =
    .label = Foghlaim níos mó
waterfox-blocker-extension-detected-dismiss =
    .label = Ná taispeáin arís
waterfox-blocker-extension-install-warning = Tá blocálaí fógraí ionsuite ag Waterfox cheana féin. Má ritheann tú dhá bhacálaí fógraí, d’fhéadfadh sé go mbeadh leathanaigh ag briseadh nó ag luchtú go mall.
waterfox-blocker-extension-install-got-it =
    .label = Tuigim
waterfox-blocker-extension-install-learn-more =
    .label = Foghlaim níos mó
waterfox-blocker-third-party-notice-description = Tá { $extensionName } ag blocáil fógraí chomh maith. Is féidir fadhbanna a chruthú má ritheann tú dhá bhacadóir fógraí.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Eisceachtaí maidir le Blocáil Fógraí
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Is féidir leat a shonrú cé na suíomhanna gréasáin a bhfuil blocáil fógraí múchta orthu. Clóscríobh seoladh cruinn an tsuímh ar mhaith leat a bhainistiú agus ansin cliceáil Cuir Eisceacht leis.
waterfox-blocker-toolbar-button =
    .label = Blocáil fógraí
    .tooltiptext = Blocáil fógraí
waterfox-blocker-panel-not-available = Níl sé ar fáil ar an leathanach seo
waterfox-blocker-panel-toggle =
    .label = Blocáil fógraí ar an suíomh seo
    .description = Blocáil fógraí agus rianaitheoirí ar an suíomh seo.
waterfox-blocker-panel-disabled = Tá blocáil fógraí múchta
waterfox-blocker-panel-site-excepted = Fógraí ceadaithe ar an suíomh seo
waterfox-blocker-panel-partner-allowed = Fógraí ceadaithe do chomhpháirtithe cuardaigh
waterfox-blocker-stats =
    { $count ->
        [one] { $count } fógra blocáilte ar an suíomh seo
       *[other] { $count } fógra blocáilte ar an suíomh seo
    }
waterfox-blocker-panel-settings-button = Socruithe blocála fógraí
waterfox-blocker-show-badge-pref =
    .label = Taispeáin comhaireamh blocáilte ar chnaipe an bharra uirlisí
waterfox-blocker-filter-lists-category-core = Réamhshocrú
waterfox-blocker-filter-lists-category-privacy = Príobháideacht
waterfox-blocker-filter-lists-category-annoyances = Crá croí
waterfox-blocker-filter-lists-category-optional = Roghnach
waterfox-blocker-filter-lists-category-regional = Réigiúnach
waterfox-blocker-filter-lists-search =
    .placeholder = Cuardaigh liostaí scagaire…
waterfox-blocker-filter-lists-empty-state = Níl aon liostaí scagaire ar fáil.
waterfox-blocker-filter-lists-refresh-now =
    .label = Athnuachan Anois
waterfox-blocker-filter-lists-last-updated = Nuashonraithe { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Níor nuashonraíodh fós
waterfox-blocker-filter-lists-next-refresh =
    .value = An chéad athnuachan eile: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = An chéad athnuachan eile: anaithnid
waterfox-blocker-custom-filter-lists-window =
    .title = Liostaí Scagaire Saincheaptha
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Sábháil Athruithe
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = Cuir URLanna liostaí scagaire saincheaptha leis. Gheofar liostaí agus cuirfear i bhfeidhm iad taobh le scagairí ionsuite.
waterfox-blocker-filter-lists-custom-heading =
    .value = Liostaí Scagaire Saincheaptha
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Cuir isteach URL an liosta scagairí…
waterfox-blocker-filter-lists-custom-url-label =
    .value = URL liosta scagaire
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Cuir leis
waterfox-blocker-filter-lists-custom-remove =
    .label = Bain
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Bain Gach Rud
waterfox-blocker-filter-lists-custom-empty =
    .value = Níor cuireadh aon liostaí scagaire saincheaptha leis.
waterfox-blocker-custom-filters =
    .label = Mo Scagairí…
waterfox-blocker-custom-filters-window =
    .title = Mo Scagairí
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Sábháil Athruithe
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = Cuir do rialacha blocála fógraí féin leis. Úsáideann siad seo comhréir chaighdeánach scagaire uBlock Origin agus cuirtear i bhfeidhm iad taobh le do liostaí scagaire cumasaithe.
waterfox-blocker-custom-filters-empty =
    .value = Gan aon scagairí saincheaptha.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Gan aon scagairí saincheaptha.
        [one] 1 scagaire saincheaptha.
       *[other] { $count } scagairí saincheaptha.
    }
waterfox-blocker-custom-filters-status-unsaved = Athruithe gan sábháil.
waterfox-blocker-custom-filters-import =
    .label = Iompórtáil…
waterfox-blocker-custom-filters-export =
    .label = Easpórtáil…
waterfox-blocker-custom-filters-load-error-title = Theip ar an luchtú
waterfox-blocker-custom-filters-load-error = Níorbh fhéidir scagairí saincheaptha a luchtú.
waterfox-blocker-custom-filters-save-error-title = Theip ar shábháil
waterfox-blocker-custom-filters-save-error = Níorbh fhéidir na scagairí saincheaptha a shábháil.
waterfox-blocker-custom-filters-import-error-title = Theip ar an allmhairiú
waterfox-blocker-custom-filters-import-error = Níorbh fhéidir an comhad roghnaithe a allmhairiú.
waterfox-blocker-custom-filters-export-error-title = Theip ar an easpórtáil
waterfox-blocker-custom-filters-export-error = Níorbh fhéidir scagairí saincheaptha a easpórtáil.
waterfox-blocker-custom-filters-import-picker-title = Scagairí saincheaptha a allmhairiú
waterfox-blocker-custom-filters-export-picker-title = Easpórtáil scagairí saincheaptha
waterfox-blocker-custom-filters-import-replace-title = Scagairí reatha a athsholáthar?
waterfox-blocker-custom-filters-import-replace-message = Cuirfidh an t-iompórtáil gach rud atá san eagarthóir faoi láthair in ionad an ruda eile.
waterfox-blocker-extension-fallback-name-this = an síneadh seo
waterfox-blocker-extension-fallback-name-your = do shíneadh
waterfox-blocker-spotlight-title = Tá blocáil fógraí san áireamh i Waterfox anois
waterfox-blocker-spotlight-subtitle = Thugamar faoi deara go bhfuil { $extensionName } suiteáilte agat. Tá blocálaí fógraí féin ag Waterfox anois. Cuidíonn sé le Waterfox a thacú, ach is leatsa an cinneadh.
waterfox-blocker-spotlight-primary-button = Coinnigh mo shocrú reatha
waterfox-blocker-spotlight-secondary-button = Socruithe athbhreithnithe
waterfox-blocker-prompt-title = Blocáil fógraí Waterfox
waterfox-blocker-reenable-conflict-message = Is féidir le blocáil fógraí Waterfox agus “{ $extensionName }” araon briseadh sna leathanaigh. Cé acu ceann ar mhaith leat a choinneáil?
waterfox-blocker-reenable-use-built-in = Bain úsáid as bacadóir ionsuite
waterfox-blocker-reenable-keep-extension = Coinnigh bacóir síneadh
waterfox-blocker-extension-install-manage-settings = Is féidir leat blocáil fógraí a bhainistiú i Socruithe > Príobháideacht & Slándáil.
waterfox-blocker-extension-install-anyway = Suiteáil ar aon nós
waterfox-blocker-extension-install-keep-built-in = Coinnigh ort ag úsáid an bhacóra ionsuite
pane-waterfox-blocker-title = Blocáil Fógraí
    .title = { pane-waterfox-blocker-title }
waterfox-blocker-pane-header =
    .heading = Blocáil Fógraí
waterfox-blocker-group =
    .label = Blocáil fógraí
    .description = Cuireann sé bac ar fhógraí, scripteanna rianaithe, agus iarratais eile nach dteastaíonn uait le haghaidh lódálacha leathanaigh níos tapúla agus níos lú seachrán.
waterfox-blocker-enabled-toggle =
    .label = Fógraí agus rianaitheoirí a bhlocáil
    .description = Cuireann sé bac ar fhógraí agus rianaitheoirí agus bíonn tionchar íosta aige ar luchtú leathanaigh.
waterfox-blocker-extension-notice =
    .message = { $extensionName } ag blocáil fógraí freisin. Is féidir fadhbanna a chruthú má ritheann tú dhá bhacadóir fógraí.
waterfox-blocker-partner-select =
    .label = Fógraí comhpháirtithe cuardaigh
    .description = Tá Waterfox saor in aisce, foinse oscailte, agus neamhspleách. Is trí fhógraí a cheadú ar leathanaigh chomhpháirtithe cuardaigh a mhaoiniú Waterfox forbairt agus bonneagar. Is féidir leat é seo a mhúchadh am ar bith, ach is é an bealach is fusa chun tacú leis an tionscadal ná é a choinneáil ar siúl.
waterfox-blocker-lists-group =
    .label = Scag liostaí
waterfox-blocker-manage-lists-button =
    .label = Bainistigh liostaí scagaire
waterfox-blocker-custom-lists-button =
    .label = Liostaí scagaire saincheaptha
waterfox-blocker-my-filters-button =
    .label = Mo scagairí
waterfox-blocker-exceptions-group =
    .label = Eisceachtaí
waterfox-blocker-exceptions-button =
    .label = Bainistigh eisceachtaí
waterfox-blocked-page-title = Chuir Waterfox bac ar an leathanach seo
waterfox-blocked-page-heading = Chuir Waterfox bac ar an leathanach seo
waterfox-blocked-page-description = Cuireadh bac ar an leathanach seo le riail scagaire blocála fógraí.
waterfox-blocked-page-details =
    .aria-label = Sonraí leathanaigh blocáilte
waterfox-blocked-page-blocked-url-label = URL blocáilte
waterfox-blocked-page-matched-rule-label = Riail mheaitseáilte
waterfox-blocked-page-unavailable = Gan a bheith ar fáil
waterfox-blocked-page-hint = Ceadóidh “Lódáil ar aon nós” an suíomh seo go sealadach don chuid eile de do sheisiún.
waterfox-blocked-page-go-back = Téigh ar ais
waterfox-blocked-page-load-anyway = Luchtaigh ar aon nós
waterfox-blocker-panel-hero-count = { $count } blocáilte
waterfox-blocker-panel-hero-paused = Sosaithe
waterfox-blocker-panel-hero-subtitle = ar { $host }
waterfox-blocker-panel-category-ads = Fógraí
waterfox-blocker-panel-category-trackers = Rianaitheoirí
waterfox-blocker-panel-category-popups = Preabfhuinneoga
waterfox-blocker-panel-see-all = Féach ar gach rud atá blocáilte
waterfox-blocker-panel-toggle2 =
    .label = Blocáil fógraí ar an suíomh seo
waterfox-blocker-panel-paused-card = Tá an suíomh seo ar do liosta ceadanna. Is féidir fógraí, fuinneoga aníos agus rianaitheoirí a lódáil go dtí go gcuirfidh tú bac air arís.
waterfox-blocker-panel-allowlist = Bainistigh an liosta ceadanna
waterfox-blocker-panel-allowlist-count =
    { $count ->
        [one] { $count } suíomh
       *[other] { $count } suíomhanna
    }
waterfox-blocker-panel-footer-stats = <b data-l10n-name="total">{ $count }</b> blocáilte an t-am ar fad · { $size } sábháilte
waterfox-blocker-panel-footer-settings = Socruithe
waterfox-blocker-panel-back =
    .aria-label = Ar ais
waterfox-blocker-panel-detail-title = Blocáilte ar an leathanach seo
waterfox-blocker-panel-detail-section-ads = Fógraíocht
waterfox-blocker-panel-detail-section-trackers = Rianaitheoirí
waterfox-blocker-panel-detail-section-popups = Preabfhuinneoga
waterfox-blocker-panel-detail-popup-note =
    { $count ->
        [one] { $count } cuireadh bac ar an bhfuinneog aníos go huathoibríoch.
       *[other] { $count } cuireadh bac ar na fuinneoga aníos go huathoibríoch.
    }
waterfox-blocker-panel-allow-domain = Ceadaigh
    .aria-label = Ceadaigh { $domain }
waterfox-blocker-panel-domain-count = ×{ $count }
