# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-page-title = Leabharmharcanna Beo
feeds-page-description = Liostáil le fothaí RSS agus Atom ag baint úsáide as leabharmharcanna beo.
feeds-private-notice = Tá síntiús a ghlacadh, míreanna a bhaint nó a athlódáil, agus athruithe a dhéanamh ar ailt léite nó sábháilte, díchumasaithe sa bhrabhsáil phríobháideach.
feeds-subscribe-heading = Liostáil le fotha
feeds-url-label = URL an fhíde
feeds-title-label = Teideal (roghnach)
feeds-subscribe-note = Sábháiltear síntiúis chuig an roghchlár Leabharmharcanna ar an bhfeiste seo, ar leithligh ón sioncronú. Déantar na fothaí a nuashonrú sa chúlra gan fianáin ná sonraí logála isteach a sheoladh chuig freastalaí na bhfothaí.
feeds-subscribe-button = Liostáil
    .label = Liostáil
    .accesskey = S
feeds-subscribe-title =
    .value = Ainm
    .accesskey = N
feeds-subscribe-url =
    .value = URL an bheatha
    .accesskey = U
feeds-subscribe-folder =
    .value = Sábháil i
    .accesskey = v
feeds-subscribe-choose-folder =
    .label = Roghnaigh fillteán eile…
feeds-subscribe-untitled-folder =
    .label = Fillteán gan teideal
feeds-subscribe-cancel =
    .label = Cealaigh
    .accesskey = C
feeds-subscribe-private = Ní féidir síntiúis fotha a athrú i bhfuinneog nó i gcluaisín phríobháideach.
feeds-subscribe-busy = Ag clárú… Ní chuirfidh dúnadh an phainéil seo deireadh leis an síntiús.
feeds-subscribe-invalid-url = Cuir isteach URL fotha HTTP nó HTTPS gan ainm úsáideora ná pasfhocal, agus ná húsáid níos mó ná 4,096 carachtar.
feeds-subscribe-invalid-title = Coinnigh an t-ainm ag 1,024 carachtar nó níos lú.
feeds-subscribe-folder-error = Roghnaigh fillteán leabharmharcanna atá ann cheana agus déan iarracht arís.
feeds-subscribe-error = Níorbh fhéidir liostáil leis an bhfotha seo. Seiceáil URL an fhotha agus an fillteán ceann scríbe, agus déan iarracht arís ansin.
feeds-subscribe-setup-error = Níorbh fhéidir an painéal síntiúis a luchtú. Dún é agus bain triail as arís.
feeds-subscriptions-heading = Síntiúis
feeds-import-button = Iompórtáil OPML…
feeds-export-button = Easpórtáil OPML…
feeds-empty = Níl aon síntiús fotha ann go fóill.
feeds-preview-button = Réamhamharc
    .aria-label = Réamhamharc { $title }
feeds-reload-button = Athluchtaigh
    .aria-label = Athluchtaigh { $title }
feeds-remove-button = Bain
    .aria-label = Bain { $title }
feeds-preview-heading = Réamhamharc ar an bhfeed
feeds-preview-note = Ní thaispeántar ach teidil agus naisc atá i dtaisce, suas le 200 mír. Osclaítear naisc chuig ailt i gcluaisín nua.
feeds-preview-empty = Níl aon alt i dtaisce ann. Athluchtaigh síntiús i bhfuinneog neamhphríobháideach chun a sheiceáil an bhfuil aon alt nua ann.
feeds-item-untitled = Mír gan teideal
feeds-status-loading = Ag luchtú na síntiús…
feeds-status-working = Ag obair…
feeds-status-ready = Tá síntiúis luchtaithe.
feeds-status-subscribed = Liostáilte leis an bhfotha.
feeds-status-removed = Baintear an síntiús.
feeds-status-reloaded = Athlódáladh an fotha.
feeds-status-preview = Ábhar fotha sábháilte á thaispeáint.
feeds-status-canceled = Cealaíodh an oibríocht.
feeds-status-exported = Easpórtáladh na síntiúis.
feeds-status-imported =
    { $count ->
        [one] Iompórtáladh síntiús amháin.
       *[other] Iompórtáladh { $count } síntiús.
    }
feeds-error-unavailable = Níl bainistíocht fothaí ar fáil ar an leathanach seo. Oscail about:feeds i gcluaisín nua.
feeds-error-private = Oscail an leathanach seo i bhfuinneog neamhphríobháideach chun síntiúis a athrú nó chun fothaí a athlódáil.
feeds-error-invalid-request = Ní raibh an t-iarratas ar an bhfotha bailí.
feeds-error-invalid-url = Cuir isteach URL fotha HTTP nó HTTPS bailí gan ainm úsáideora ná pasfhocal.
feeds-error-busy = Tá oibríocht bheathaithe eile ar siúl. Bain triail eile as nuair a bheidh sí críochnaithe.
feeds-error-not-found = Níl an síntiús seo ann a thuilleadh.
feeds-error-operation = Níorbh fhéidir an oibríocht fhotha a chur i gcrích. Seiceáil seoladh na fotha agus an nasc. Ní féidir fillteán ina bhfuil leabharmharcanna sábháilte a bhaint anseo.
feeds-error-not-active = Roghnaigh an cluaisín seo sula n-osclaíonn tú an roghnóir comhad.
feeds-error-invalid-opml = Roghnaigh comhad OPML bailí i bhformáid UTF-8, gan DTD ná dearbhuithe eintiteas.
feeds-error-file-too-large = Roghnaigh comhad OPML nach bhfuil níos mó ná 2 MiB ann.
feeds-import-picker-title = Iompórtáil Síntiúis Fothaí
feeds-export-picker-title = Easpórtáil Síntiúis Fothaí
feeds-opml-file-filter = Comhaid OPML
feeds-export-filename = feeds.opml
feeds-page-action = Liostáil le fothaí ar an leathanach seo
feeds-toolbar-button =
    .label = Leabharmharcanna Beo
    .tooltiptext = Faigh fothaí agus bainistigh leabharmharcanna beo
feeds-menu-label =
    .label = Leabharmharcanna Beo
    .accesskey = L
feeds-menu-manage =
    .label = Bainistigh Leabharmharcanna Beo…
feeds-menu-discovering =
    .label = Ag lorg fothaí ar an leathanach seo…
feeds-menu-no-feeds =
    .label = Níl aon fhothaí fógartha ar an leathanach seo
feeds-menu-all-subscribed =
    .label = Tá síntiús agat cheana féin leis na fothaí go léir ar an leathanach seo
feeds-menu-subscribe =
    .label = Liostáil le { $title }…
    .tooltiptext = { $url }
feeds-menu-open-site =
    .label = Oscail Suíomh Gréasáin an Fhíid
    .tooltiptext = { $url }
feeds-menu-reload =
    .label = Athluchtaigh an Leabharmharc Beo
feeds-menu-loading =
    .label = Ag luchtú an fhíde…
feeds-menu-empty =
    .label = Níl aon mhír sa fhuíde seo
feeds-menu-error =
    .label = Níorbh fhéidir an fotha a nuashonrú. Déanfar iarracht eile níos déanaí.
feeds-menu-no-cache =
    .label = Athluchtaigh i bhfuinneog neamhphríobháideach chun míreanna a luchtú
feeds-entry-visited =
    .label = { $title }
    .aria-label = { $title } (tugadh cuairt air)
    .tooltiptext = { $url } (tugadh cuairt air)
feeds-entry-unvisited =
    .label = { $title }
    .aria-label = { $title } (gan cuairt a thabhairt air)
    .tooltiptext = { $url } (gan cuairt a thabhairt air)
feeds-preview-page-title = Fothaí
feeds-reader-page-title = Léitheoir Fothaí
feeds-direct-page-title = Réamhamharc ar an bhFothú
feeds-settings-button = Socruithe Fotha
feeds-subscribe-preview-loading = Ag seiceáil le haghaidh ceannlínte le déanaí…
feeds-subscribe-preview-headlines = Ceannlínte le déanaí
feeds-subscribe-preview-source = { $title } · { $url }
feeds-subscribe-preview-empty = Níl aon cheannlínte le déanaí ar fáil.
feeds-subscribe-preview-invalid = Cuir isteach URL fotha bailí chun réamhamharc a fháil ar na ceannlínte.
feeds-subscribe-preview-error = Níorbh fhéidir na ceannlínte is déanaí a luchtú. Is féidir leat triail a bhaint as síntiús a ghlacadh fós.
feeds-subscribe-preview-open-error = Níorbh fhéidir an réamhamharc iomlán a oscailt.
feeds-subscribe-full-preview = Réamhamharc iomlán
    .label = Réamhamharc iomlán
feeds-subscribe-already = Tá tú cláraithe leis an bhfotha seo cheana féin.
feeds-subscribe-success = Liostáilte leis an bhfotha seo.
feeds-subscribe-destination = Sábháilte i { $folder }
feeds-subscribe-open = Oscail i Mo Fhedanna
    .label = Oscail i Mo Fhedanna
feeds-subscribe-undo = Cealaigh
    .label = Cealaigh
feeds-subscribe-undone = Baintear an síntiús.
feeds-subscribe-undo-error = Níorbh fhéidir an síntiús seo a chealú. D’fhéadfadh sé go bhfuil athrú tagtha air nó go bhfuil leabharmharcanna sábháilte ann.
feeds-subscribe-removing = Ag baint an síntiúis… Ní chuirfidh dúnadh an phainéil seo stop leis an mbaint.
feeds-subscribe-close = Dún
    .label = Dún
    .accesskey = C
feeds-search-label = Cuardaigh síntiúis
feeds-no-matches = Níl aon síntiúis ann a mheaitseálann.
feeds-health-idle = Gan aon nuashonrú le déanaí. Athluchtaigh chun míreanna nua a sheiceáil.
feeds-health-loading = Á nuashonrú…
feeds-health-ready = Tá beatha ar fáil.
feeds-health-error = Níorbh fhéidir an fotha seo a nuashonrú. Athluchtaigh chun triail eile a bhaint as.
feeds-last-updated = Seiceáladh go deireanach: { DATETIME($date, dateStyle: "medium", timeStyle: "short") }
feeds-direct-empty = Níl aon mhír sa fhuíoll seo.
feeds-status-direct-preview = Ag taispeáint réamhamhairc an fhotha.
feeds-error-preview-expired = Níl an réamhamharc seo ar fáil a thuilleadh. Oscail URL an fhíid bhunaidh arís.
feeds-reader-load-error = Níorbh fhéidir an t-alt seo a thaispeáint. Téigh ar ais agus déan iarracht arís, nó roghnaigh 'Oscail an bunleagan' chun é a léamh ar an suíomh gréasáin.
feeds-error-retry-later = D'iarr freastalaí an fhíid orainn fanacht. Déan iarracht é a athlódáil níos déanaí.
feeds-error-saved-limit = Tá an teorainn maidir le hailt shábháilte bainte amach agat. Bain alt sábháilte amháin sula sábhálann tú ceann eile.
feeds-all = Gach fotha
feeds-saved = Sábháilte
feeds-add = Cuir fotha leis
feeds-add-url-label = URL an Fotha
feeds-add-preview = Réamhamharc ar an bhfotha
feeds-add-cancel = Cealaigh
feeds-add-confirm = Cuir fotha leis
feeds-add-name-label = Ainm
feeds-add-folder-label = Sábháil i
feeds-open-feeds = Oscail i Mo Fothaí
feeds-undo = Cealaigh an síntiús
feeds-manage = Bainistigh fothaí
feeds-search-articles = Cuardaigh ailt
feeds-all-filter = Gach rud
feeds-unread-filter = Gan léamh
feeds-display-list = Amharc liosta
feeds-display-cards = Amharc cártaí
feeds-order-newest = Is nuaí ar dtús
feeds-order-oldest = Is sine ar dtús
feeds-open-original = Oscail an bunleagan
feeds-mark-read = Marcáil mar léite
    .title = Marcáil mar léite
feeds-mark-unread = Marcáil mar neamhléite
    .title = Marcáil mar neamhléite
feeds-save = Sábháil an t-alt
    .title = Sábháil an t-alt
feeds-unsave = Bain ó na nithe sábháilte
    .title = Bain ó na nithe sábháilte
feeds-mark-read-button =
    .aria-label = Marcáil mar léite
    .title = Marcáil mar léite
feeds-mark-unread-button =
    .aria-label = Marcáil mar neamhléite
    .title = Marcáil mar neamhléite
feeds-save-button =
    .aria-label = Sábháil an t-alt
    .title = Sábháil an t-alt
feeds-unsave-button =
    .aria-label = Bain ó na nithe sábháilte
    .title = Bain ó na nithe sábháilte
feeds-back = Ar ais
feeds-previous = Roimhe seo
feeds-next = An chéad alt eile
feeds-summary-notice = Cuireadh an t-ábhar seo ar fáil tríd an bhfotha. Oscail an bun-alt más mian leat tuilleadh a léamh.
feeds-no-content = Ní chuireann an fotha seo téacs an ailt ar fáil. Oscail an bunalt chun é a léamh.
feeds-open-article =
    .aria-label = Léigh { $title } i Waterfox
feeds-empty-unread = Tá gach rud cothrom le dáta agat.
feeds-empty-saved = Beidh na hailt shábháilte le feiceáil anseo nuair a shábhálann tú iad ó fhuíoll nuachta.
feeds-empty-results = Níl aon alt comhoiriúnach ann.
feeds-show-all = Taispeáin gach alt
feeds-clear-search = Glan an cuardach
feeds-preview-loading = Ag luchtú réamhamhairc an fotha…
feeds-preview-invalid = Níorbh fhéidir réamhamharc a fháil ar an bhfotha seo. Seiceáil URL an fhotha agus déan iarracht arís.
feeds-subscription-exists = Tá tú cláraithe leis an bhfotha seo cheana féin.
feeds-nav =
    .aria-label = Nascleanúint an fotha
feeds-filter-label =
    .aria-label = Scagaire alt
feeds-order-label =
    .aria-label = Ord na n-alt
feeds-display-label =
    .aria-label = Taispeáint an ailt
feeds-article-count =
    { $count ->
        [one] Alt amháin
       *[other] { $count } alt
    }
feeds-source-count = { $title } ({ $count })
feeds-saved-in = Sábháilte i { $folder }
feeds-show-more = Taispeáin tuilleadh alt
feeds-rail-feeds = Fothaí
feeds-live-bookmarks-heading = Leabharmharcanna Beo
feeds-search-placeholder =
    .placeholder = Cuardaigh ailt
feeds-recent-posts = Poist le déanaí
feeds-back-to-feeds = Ar ais chuig na fothaí
feeds-subscribe-preview-heading = Liostáil leis an bhfotha seo
feeds-feed-url-heading = URL an fotha
feeds-visit-website = Tabhair cuairt ar an suíomh gréasáin
feeds-preview-state-unsubscribed = Réamhamharc ar an fotha · Gan síntiús
feeds-preview-state-subscribed = Réamhamharc ar an fotha · Liostáilte
feeds-close =
    .aria-label = Dún
feeds-source-button =
    .aria-label =
        { $title }, { $count } unread { $count ->
            [one] alt
           *[other] alt
        }
feeds-all-scope-button =
    .aria-label =
        Gach fotha, { $count } gan léamh { $count ->
            [one] alt
           *[other] alt
        }
feeds-article-date = { DATETIME($date, dateStyle: "long") }
feeds-today = Inniu
feeds-yesterday = Inné
feeds-undated = Ailt eile
feeds-reader-position = { $current } as { $total } alt
feeds-subscribe-rename =
    .label = Athainmnigh
feeds-subscribed-heading = Liostáilte
feeds-rail-settings = Socruithe
feeds-add-dialog-title = Cuir fotha leis
feeds-reader-save = Sábháil
feeds-reader-saved = Sábháilte
feeds-back-to-collection = Ar ais go { $title }
feeds-display-list-button =
    .aria-label = Amharc liosta
    .title = Amharc liosta
feeds-display-grid-button =
    .aria-label = Amharc cártaí
    .title = Amharc cártaí
feeds-unread-count =
    { $count }  gan léamh trasna { $feeds } { $feeds ->
        [one] fotha
       *[other] fothaí
    }
