# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-page-title = Leabharmharcanna Beo
feeds-page-description = Liostáil le fothaí RSS agus Atom ag baint úsáide as leabharmharcanna beo.
feeds-private-notice = Tá síntiús a ghlacadh le fothaí, iad a bhaint, iad a athlódáil agus iad a iompórtáil díchumasaithe agus tú ag brabhsáil go príobháideach. Is féidir leat míreanna atá i dtaisce a fheiceáil nó do chuid síntiús a easpórtáil fós.
feeds-subscribe-heading = Liostáil le fotha
feeds-url-label = URL an fhíde
feeds-title-label = Teideal (roghnach)
feeds-subscribe-note = Sábháiltear síntiúis chuig an roghchlár Leabharmharcanna ar an bhfeiste seo, ar leithligh ón sioncronú. Déantar na fothaí a nuashonrú sa chúlra gan fianáin ná sonraí logála isteach a sheoladh chuig freastalaí na bhfothaí.
feeds-subscribe-button = Liostáil
    .label = Liostáil
    .accesskey = S
feeds-subscribe-title =
    .value = Ainm
    .accesskey = N
feeds-subscribe-url =
    .value = URL an bheatha
    .accesskey = U
feeds-subscribe-folder =
    .value = Sábháil i
    .accesskey = v
feeds-subscribe-choose-folder =
    .label = Roghnaigh fillteán eile…
feeds-subscribe-untitled-folder =
    .label = Fillteán gan teideal
feeds-subscribe-cancel =
    .label = Cealaigh
    .accesskey = C
feeds-subscribe-private = Ní féidir síntiúis fhotha a athrú i bhfuinneog phríobháideach.
feeds-subscribe-busy = Ag clárú… Ní chuirfidh dúnadh an phainéil seo deireadh leis an síntiús.
feeds-subscribe-invalid-url = Cuir isteach URL fotha HTTP nó HTTPS gan ainm úsáideora ná pasfhocal, agus ná húsáid níos mó ná 4,096 carachtar.
feeds-subscribe-invalid-title = Coinnigh an t-ainm ag 1,024 carachtar nó níos lú.
feeds-subscribe-folder-error = Roghnaigh fillteán leabharmharcanna atá ann cheana agus déan iarracht arís.
feeds-subscribe-error = Níorbh fhéidir liostáil leis an bhfotha seo. Seiceáil URL an fhotha agus an fillteán ceann scríbe, agus déan iarracht arís ansin.
feeds-subscribe-setup-error = Níorbh fhéidir an painéal síntiúis a luchtú. Dún é agus bain triail as arís.
feeds-subscriptions-heading = Do chuid síntiús
feeds-import-button = Iompórtáil OPML…
feeds-export-button = Easpórtáil OPML…
feeds-empty = Níl aon síntiús fotha ann go fóill.
feeds-preview-button = Réamhamharc
    .aria-label = Réamhamharc { $title }
feeds-reload-button = Athluchtaigh
    .aria-label = Athluchtaigh { $title }
feeds-remove-button = Bain
    .aria-label = Bain { $title }
feeds-preview-heading = Réamhamharc ar an bhfeed
feeds-preview-note = Ní thaispeántar ach teidil agus naisc atá i dtaisce, suas le 200 mír. Osclaítear naisc chuig ailt i gcluaisín nua.
feeds-preview-empty = Níl aon mhír thaiscthe ann. Athluchtaigh an síntiús seo i bhfuinneog neamhphríobháideach chun na míreanna is déanaí a fháil.
feeds-item-untitled = Mír gan teideal
feeds-status-loading = Ag luchtú na síntiús…
feeds-status-working = Ag obair…
feeds-status-ready = Tá síntiúis luchtaithe.
feeds-status-subscribed = Liostáilte leis an bhfotha.
feeds-status-removed = Baintear an síntiús.
feeds-status-reloaded = Athlódáladh an fotha.
feeds-status-preview = Ag taispeáint míreanna taiscthe.
feeds-status-canceled = Cealaíodh an oibríocht.
feeds-status-exported = Easpórtáladh na síntiúis.
feeds-status-imported =
    { $count ->
        [one] Iompórtáladh síntiús amháin.
       *[other] Iompórtáladh { $count } síntiús.
    }
feeds-error-unavailable = Níl bainistíocht fothaí ar fáil ar an leathanach seo. Oscail about:feeds i gcluaisín nua.
feeds-error-private = Oscail an leathanach seo i bhfuinneog neamhphríobháideach chun síntiúis a athrú nó chun fothaí a athlódáil.
feeds-error-invalid-request = Ní raibh an t-iarratas ar an bhfotha bailí.
feeds-error-invalid-url = Cuir isteach URL fotha HTTP nó HTTPS bailí gan ainm úsáideora ná pasfhocal.
feeds-error-busy = Tá oibríocht bheathaithe eile ar siúl. Bain triail eile as nuair a bheidh sí críochnaithe.
feeds-error-not-found = Níl an síntiús seo ann a thuilleadh.
feeds-error-operation = Níorbh fhéidir an oibríocht fhotha a chur i gcrích. Seiceáil seoladh na fotha agus an nasc. Ní féidir fillteán ina bhfuil leabharmharcanna sábháilte a bhaint anseo.
feeds-error-not-active = Roghnaigh an cluaisín seo sula n-osclaíonn tú an roghnóir comhad.
feeds-error-invalid-opml = Roghnaigh comhad OPML bailí i bhformáid UTF-8, gan DTD ná dearbhuithe eintiteas.
feeds-error-file-too-large = Roghnaigh comhad OPML nach bhfuil níos mó ná 2 MiB ann.
feeds-import-picker-title = Iompórtáil Síntiúis Fothaí
feeds-export-picker-title = Easpórtáil Síntiúis Fothaí
feeds-opml-file-filter = Comhaid OPML
feeds-export-filename = feeds.opml
feeds-page-action = Liostáil le fothaí ar an leathanach seo
feeds-toolbar-button =
    .label = Leabharmharcanna Beo
    .tooltiptext = Faigh fothaí agus bainistigh leabharmharcanna beo
feeds-menu-label =
    .label = Leabharmharcanna Beo
    .accesskey = L
feeds-menu-manage =
    .label = Bainistigh Leabharmharcanna Beo…
feeds-menu-discovering =
    .label = Ag lorg fothaí ar an leathanach seo…
feeds-menu-no-feeds =
    .label = Níl aon fhothaí fógartha ar an leathanach seo
feeds-menu-all-subscribed =
    .label = Tá síntiús agat cheana féin leis na fothaí go léir ar an leathanach seo
feeds-menu-subscribe =
    .label = Liostáil le { $title }…
    .tooltiptext = { $url }
feeds-menu-open-site =
    .label = Oscail Suíomh Gréasáin an Fhíid
    .tooltiptext = { $url }
feeds-menu-reload =
    .label = Athluchtaigh an Leabharmharc Beo
feeds-menu-loading =
    .label = Ag luchtú an fhíde…
feeds-menu-empty =
    .label = Níl aon mhír sa fhuíde seo
feeds-menu-error =
    .label = Níorbh fhéidir an fotha a nuashonrú. Déanfar iarracht eile níos déanaí.
feeds-menu-no-cache =
    .label = Athluchtaigh i bhfuinneog neamhphríobháideach chun míreanna a luchtú
feeds-entry-visited =
    .label = { $title }
    .aria-label = { $title } (tugadh cuairt air)
    .tooltiptext = { $url } (tugadh cuairt air)
feeds-entry-unvisited =
    .label = { $title } (gan cuairt a thabhairt air)
    .aria-label = { $title } (gan cuairt a thabhairt air)
    .tooltiptext = { $url } (gan cuairt a thabhairt air)
