# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

onboarding-grassroots-title = Ag tacú leis an bpobal áitiúil
onboarding-grassroots-subtitle = Go raibh maith agat as Waterfox, brabhsálaí neamhspleách, pobail, a úsáid. Le do thacaíocht, táimid ag tógáil rogha inbhuanaithe seachas na himreoirí móra amuigh ansin.
waterfox-onboarding-welcome-title = Fáilte go { -brand-short-name }
waterfox-onboarding-welcome-subtitle = Neamhspleách, gasta, agus tógtha leis na rialuithe Waterfox a mbeifeá ag súil leo.
waterfox-onboarding-start-button = Tosaigh
waterfox-onboarding-import-title = Tabhair do chuid sonraí leat
waterfox-onboarding-import-subtitle = Iompórtáil leabharmharcanna, stair, agus sonraí foirme ó { migration-wizard-migrator-display-name-firefox } nó brabhsálaí eile gan an socrú seo a fhágáil.
waterfox-onboarding-style-title = Roghnaigh do stíl Waterfox
waterfox-onboarding-style-subtitle = Roghnaigh cruth an chluaisín agus an bharra uirlisí agus cé chomh dlúth is a bhraitheann sé.
waterfox-onboarding-style-photon-label = Photon
waterfox-onboarding-style-photon-body = An cuma clasaiceach Waterfox le cróm scagtha.
waterfox-onboarding-style-proton-label = Proton
waterfox-onboarding-style-proton-body = Leagan amach níos ciúine le spásáil nua-aimseartha idir brabhsálaithe.
waterfox-onboarding-style-nova-label = Nova
waterfox-onboarding-style-nova-body = Stíl Waterfox níos géire le líne cluaisíní gníomhach níos gile.
waterfox-onboarding-density-normal-label = Gnáth
waterfox-onboarding-density-compact-label = Dlúth
waterfox-onboarding-density-touch-label = Teagmháil
waterfox-onboarding-theme-color-title = Déan go mbraitheann sé cosúil le do cheann féin
waterfox-onboarding-theme-color-subtitle = Roghnaigh dath téama a fhágann go bhfuil gach fuinneog ina dath pearsanta duit féin.
waterfox-onboarding-theme-mode-system-label = Córas
waterfox-onboarding-theme-mode-light-label = Solas
waterfox-onboarding-theme-mode-dark-label = Dorcha
waterfox-onboarding-color-default-label = Réamhshocrú
waterfox-onboarding-color-smoke-label = Deatach
waterfox-onboarding-color-ash-label = Fuinseog
waterfox-onboarding-color-sun-label = Grian
waterfox-onboarding-color-spark-label = Splanc
waterfox-onboarding-color-flame-label = Lasair
waterfox-onboarding-color-flare-label = Lasadh
waterfox-onboarding-color-lavender-label = Labhandair
waterfox-onboarding-color-dusk-label = Luí na gréine
waterfox-onboarding-color-lagoon-label = Lagún
waterfox-onboarding-color-tide-label = Taoide
waterfox-onboarding-color-pine-label = Péine
waterfox-onboarding-tabs-title = Eagraigh cluaisíní ar do bhealach féin
waterfox-onboarding-tabs-subtitle = Roghnaigh conas a shocraítear do chluaisíní, agus cá háit a suíonn stiall chothrománach cluaisíní. Is féidir leat an dá rud a athrú níos déanaí i Socruithe.
waterfox-onboarding-tabs-horizontal-label = Cluaisíní cothrománacha
waterfox-onboarding-tabs-horizontal-body = Coinnigh an stiall chlasaiceach cluaisín trasna an bharr.
waterfox-onboarding-tabs-vertical-label = Cluaisíní ingearacha
waterfox-onboarding-tabs-vertical-body = Bog cluaisíní isteach sa bharra taoibh mar liosta níos airde.
waterfox-onboarding-tabs-tree-label = Cluaisíní crann
waterfox-onboarding-tabs-tree-body = Cluaisíní ingearacha atá neadaithe faoin gcluaisín a d’oscail iad.
waterfox-onboarding-location-top-above-label = Os cionn an bharra uirlisí
waterfox-onboarding-location-top-below-label = Faoi bhun an bharra uirlisí
waterfox-onboarding-location-bottom-above-label = Os cionn an bharra stádais
waterfox-onboarding-location-bottom-below-label = Faoi bhun an bharra stádais
waterfox-onboarding-privacy-title = Tá uirlisí príobháideachta réidh
waterfox-onboarding-privacy-subtitle = Tosaíonn Waterfox le réamhshocruithe blocála fógraí agus príobháideachta. Is féidir leat iad a choigeartú go mion am ar bith.
waterfox-onboarding-privacy-primary-button = Coinnigh cosaintí ar siúl
waterfox-onboarding-default-title = Déan { -brand-short-name } mar do bhrabhsálaí réamhshocraithe
waterfox-onboarding-default-subtitle = Oscail naisc i { -brand-short-name } de réir réamhshocraithe agus coinnigh do shocrú Waterfox gar duit.
waterfox-onboarding-default-primary-button = Socraigh mar réamhshocrú
waterfox-onboarding-finish-title = Tá tú réidh go léir
waterfox-onboarding-finish-subtitle = Go raibh maith agat as Waterfox a roghnú. Tá do bhrabhsálaí réidh.
waterfox-onboarding-finish-primary-button = Tosaigh ag brabhsáil
waterfox-onboarding-skip-button = Ní anois
waterfox-onboarding-skip-step-button = Seachain an chéim seo
waterfox-onboarding-continue-button = Lean ar aghaidh
waterfox-onboarding-save-continue-button = Sábháil agus lean ar aghaidh
waterfox-onboarding-customize-appearance-button = Saincheap an chuma sna Socruithe
waterfox-onboarding-customize-tabs-button = Saincheap na cluaisíní i Socruithe
waterfox-onboarding-customize-privacy-button = Saincheap socruithe príobháideachais
waterfox-onboarding-language-hint = Is féidir leat é seo a athrú am ar bith sna Socruithe.
waterfox-onboarding-language-error = Níorbh fhéidir le { -brand-short-name } an teanga a athrú. Tá do theanga roimhe seo fós gníomhach.
waterfox-onboarding-step-label = Céim { $current } de { $total }
waterfox-onboarding-tabs-style-legend = Stíl brabhsálaí
waterfox-onboarding-tabs-density-legend = Dlús
waterfox-onboarding-appearance-subtitle = Roghnaigh an cruth, an dlús agus an dath. Is féidir leat gach rud a choigeartú níos déanaí sna Socruithe.
waterfox-onboarding-theme-mode-legend = Scéim dathanna
waterfox-onboarding-theme-color-legend = Dath téama
waterfox-onboarding-tabs-layout-legend = Socrú na gcluaisíní
waterfox-onboarding-tabs-location-label = Suíomh stiall na gcluaisíní
waterfox-onboarding-tabs-location-hint = Baineann sé seo le cluaisíní cothrománacha. Tá níos mó suíomhanna sna Socruithe.
waterfox-onboarding-finish-privacy-note = Tá blocáil fógraí agus cosaint rianaithe ar siúl cheana féin.
waterfox-onboarding-back-button = Ar ais
