# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sidebar-tree-vertical-tabs =
    .label = Cluaisíní ingearacha crann
waterfox-tab-context-collapse-tree =
    .label = Laghdaigh Crann
waterfox-tab-context-expand-tree =
    .label = Leathnaigh an Crann
waterfox-tab-context-close-tree =
    .label = Dún an Crann
waterfox-tab-context-close-descendants =
    .label = Dún Leanaí
waterfox-tab-context-collapse-all-trees =
    .label = Laghdaigh Gach Crann
waterfox-tab-context-expand-all-trees =
    .label = Leathnaigh Gach Crann
waterfox-tabs-tree-heading =
    .label = Cluaisíní crann
waterfox-tabs-tree-enable-toggle =
    .label = Taispeáin cluaisíní mar chrann
    .description = Cuirtear cluaisíní a osclaíonn tú ó chluaisín eile faoi, ionas gur féidir leat grúpaí iomlána a fhilleadh agus a bhogadh ag an am céanna. Casann sé seo cluaisíní ingearacha air freisin.
waterfox-tabs-tree-auto-attach-select =
    .label = Oscail cluaisíní nua
waterfox-tabs-tree-auto-attach-option-root =
    .label = Ar a n-aonar
waterfox-tabs-tree-auto-attach-option-child =
    .label = I bhfolach faoin táb a d’oscail iad
waterfox-tabs-tree-auto-attach-option-sibling =
    .label = In aice leis an táb a d’oscail iad
waterfox-tabs-tree-auto-collapse-on-select-toggle =
    .label = Oscail brainse an chluaisín ghníomhaigh agus fill na cinn eile ar shiúl
waterfox-tabs-tree-auto-collapse-on-attach-toggle =
    .label = Oscail brainse nuair a thagann cluaisín nua isteach ann
waterfox-tabs-tree-close-parent-select =
    .label = Nuair a dhúnann tú cluaisín tuismitheora
waterfox-tabs-tree-close-parent-option-promote-first =
    .label = Cuir a chéad leanbh ina áit
waterfox-tabs-tree-close-parent-option-promote-all =
    .label = Tóg a pháistí suas leibhéal
waterfox-tabs-tree-close-parent-option-close-all =
    .label = Dún an brainse ar fad
waterfox-tabs-tree-close-parent-option-detach =
    .label = Bog a chlann go dtí an leibhéal is airde
waterfox-tabs-tree-double-click-select =
    .label = Cliceáil faoi dhó ar chluaisín
waterfox-tabs-tree-double-click-option-toggle =
    .label = Fillteann nó osclaíonn sé a bhrainse
waterfox-tabs-tree-double-click-option-close =
    .label = Dúnann a bhrainse
waterfox-tabs-tree-double-click-option-none =
    .label = Ní dhéanann sé tada
waterfox-tabs-tree-sticky-active-toggle =
    .label = Coinnigh an cluaisín reatha i radharc nuair a bhíonn a bhrainse fillte ar shiúl
waterfox-tabs-tree-propagate-muted-toggle =
    .label = Balbhaigh páistí cluaisín mar aon leis
waterfox-tabs-tree-max-depth-select =
    .label = Teorainn a chur le cé chomh domhain is féidir le cluaisíní neadaithe
waterfox-tabs-tree-max-depth-option-unlimited =
    .label = Gan teorainn
waterfox-tab-context-reload-tree =
    .label = Athlódáil an Crann
waterfox-tab-context-mute-tree =
    .label = Crann Balbhaigh
waterfox-tab-context-unmute-tree =
    .label = Díbholg Crann
waterfox-tab-context-unload-tree =
    .label = Díluchtaigh Crann
waterfox-tab-context-collapse-tree-recursively =
    .label = Laghdaigh an Crann go hAthchúrsach
waterfox-tab-context-expand-tree-recursively =
    .label = Leathnaigh an Crann go hAthchúrsach
waterfox-tab-context-bookmark-tree =
    .label = Leabharmharc an Crann seo…
waterfox-tab-context-copy-tree-links =
    .label = Cóipeáil Crann mar Naisc
waterfox-tab-context-copy-descendants-links =
    .label = Cóipeáil Sliocht mar Naisc
waterfox-tabs-tree-close-parent-option-group =
    .label = Cuir cluaisín grúpa ina áit
waterfox-tabs-tree-auto-group-pinned-toggle =
    .label = Grúpaigh cluaisíní oscailte ón gcluaisín bioráilte céanna
waterfox-tabs-tree-bookmark-restore-toggle =
    .label = Athchóirigh struchtúr crann agus fillteáin leabharmharcanna á n-oscailt
waterfox-tabs-tree-bookmark-group-toggle =
    .label = Grúpáil crainn iolracha a osclaíodh ó fhillteán leabharmharcanna
waterfox-tree-drop-link-title = Oscail Nasc Scaoilte
waterfox-tree-drop-link-message = Cá háit ar cheart an nasc a scaoilfear a oscailt?
waterfox-tree-drop-link-load = Luchtaigh sa Chluaisín seo
waterfox-tree-drop-link-child = Oscail mar Chluaisín Leanaí
waterfox-tree-drop-link-remember = Cuimhnigh an rogha seo
waterfox-tree-new-tab-action-button =
    .label = Roghnaigh suíomh nua cluaisín
    .tooltiptext = Oscail cluaisín nua ag suíomh crann roghnaithe
waterfox-tree-new-tab-independent =
    .label = Cluaisín neamhspleách
waterfox-tree-new-tab-child =
    .label = Leanbh den chluaisín reatha
waterfox-tree-new-tab-sibling =
    .label = Siblín deireanach an chluaisín reatha
waterfox-tree-new-tab-next-sibling =
    .label = An chéad siblín eile den chluaisín reatha
waterfox-tree-group-default-title = Grúpa
waterfox-tree-group-title-and-more = { $title } agus tuilleadh
waterfox-tree-group-tabs-from = Cluaisíní ó { $title }
waterfox-tree-group-temporary-label = Dún an grúpa seo nuair nach bhfuil aon chluaisíní ann
waterfox-tree-group-temporary-aggressive-label = Dún an grúpa seo nuair a bheidh cluaisín amháin fágtha
