appearance-header = Izskats
font-header = Fonti
icons-header = Ikonas
panels-header = Paneļi
sidebar-header = Sānjosla
theme-header = Motīvs
tree-appearance-header = Izskats
waterfox-blocker-filter-lists-category-privacy = Konfidencialitātes
waterfox-blocked-page-unavailable = Nav pieejams
geolocation-api-header = Ģeolokācijas API
statusbar-header = Statusa josla
bookmark-header = Grāmatzīmju josla
interface-component-header = Saskarnes komponenti
media-player-header = Multimediju atskaņotājs
nav-bar-header = Navigācijas josla
tab-bar-header = Cilņu josla
telemetry-privacy-policy = Konfidencialitātes politika
waterfox-blocker-header = Reklāmu bloķēšana
waterfox-blocker-custom-filters-status-unsaved = Nesaglabātas izmaiņas.
waterfox-blocker-custom-filters-load-error-title = Neizdevās ielādēt
waterfox-blocker-custom-filters-save-error-title = Neizdevās saglabāt
waterfox-blocker-custom-filters-import-error-title = Neizdevās ievietot
waterfox-blocker-custom-filters-export-error-title = Neizdevās izgūt
waterfox-blocker-extension-fallback-name-this = šis papildinājums
waterfox-blocker-extension-fallback-name-your = jūsu papildinājums
waterfox-blocker-spotlight-secondary-button = Pārskatīt iestatījumus
waterfox-blocker-extension-install-anyway = Tomēr uzstādīt
waterfox-blocked-page-blocked-url-label = Bloķētā URL adrese
waterfox-blocked-page-load-anyway = Tomēr ielādēt
bookmarks-bar-position-header = Grāmatzīmju rīkjoslas pozīcija
bookmarks-position-bottom =
    .label = Apakšā
bookmarks-position-top =
    .label = Augšā
geolocation-api-enabled =
    .label = Iespējot
geolocation-api-disabled =
    .label = Atspējots
tab-additional-header = Papildu cilnes iestatījumi
tab-feature-header = Cilnes kontekstizvēlne
tab-position-header = Cilņu joslas pozīcija
pane-theme-title = Izskats un sajūtas
waterfox-blocker-setting-on =
    .label = Ieslēgts
waterfox-blocker-partner-funding-title = Atbalstiet Waterfox izstrādi
waterfox-blocker-setting-off =
    .label = Izslēgts
waterfox-blocker-filter-lists-column-enabled =
    .label = Iespējots
waterfox-blocker-blocks-tracking = Izsekošanas skriptus un pikseļus
waterfox-blocker-panel-disabled = Reklāmu bloķēšana ir izslēgta
waterfox-blocker-filter-lists-last-updated = Atjaunināts { $date }
waterfox-blocked-page-title = Waterfox bloķēja šo lapu
telemetry-page-subtitle = Waterfox neapkopo telemetrijas datus par jūsu uzstādīto pārlūku — visi telemetrijas moduļi ir aizvākti jau pašā pirmkodā. Tas, ko jūs dariet savā pārlūkā, ir zināms tikai jums.
waterfox-blocker-spotlight-subtitle = Mēs konstatējām, ka jums ir uzstādīts { $extensionName } papildinājums. Waterfox tagad ir iebūvēts savs reklāmu bloķētājs. Tā izmantošana palīdz atbalstīt Waterfox, bet lēmumu pieņemiet pilnībā jūs.
waterfox-blocker-reenable-conflict-message = Vienlaicīga Waterfox iebūvēto reklāmu bloķētāja un “{ $extensionName }” papildinājuma darbība var izraisīt lapu kļūdas vai rasties attēlošanas kļūdas. Kuru no tiem jūs vēlaties paturēt?
center-header = Vidū
rounding-header = Noapaļošana
waterfox-blocker-filter-lists-category-regional = Reģionālie
waterfox-blocked-page-heading = Waterfox bloķēja šo lapu
copy-url =
    .label = Kopēt cilnes saiti
statusbar-enabled =
    .label = Rādīt statusa joslu
load-images =
    .label = Automātiski ielādēt attēlus
category-theme =
    .tooltiptext = { pane-theme-title }
auto-blur-tabs =
    .label = Automātiski aizmiglot cilnes
auto-hide-sidebar =
    .label = Automātiski paslēpt sānjoslu
auto-hide-tabs =
    .label = Automātiski paslēpt cilnes
center-tab-content =
    .label = Centrēt (ielikt vidū) cilnes saturu
show-menu-icons =
    .label = Rādīt izvēlnes ikonas
square-button-edges =
    .label = Kvadrātveida pogu stūri
square-tab-edges =
    .label = Kvadrātveida cilnes stūri
waterfox-blocker-blocks-ads = Reklāmas un reklāmu tīklu pieprasījumus
waterfox-blocker-setting-on-summary = Bloķē reklāmas un izsekotājus, būtiski neietekmējot lapas ielādi.
waterfox-blocker-setting-on-description = Waterfox bloķē:
auto-hide-navbar =
    .label = Automātiski paslēpt navigācijas joslu
waterfox-blocker-extension-detected-dismiss =
    .label = Vairs nerādīt
waterfox-blocker-panel-not-available = Nav pieejams šajā lapā
waterfox-blocker-panel-site-excepted = Reklāmas ir atļautas šajā vietnē
waterfox-blocked-page-details =
    .aria-label = Bloķētās lapas informācija
copy-all-urls =
    .label = Kopēt visu ciļņu saites
compact-bookmark-menu =
    .label = Samazināt grāmatzīmju izvēlnes atstarpi
compact-panel-header =
    .label = Samazināt paneļa galvenes atstarpi
enable-waterfox-theme-2 =
    .label = Atspējot Waterfox motīvu pielāgošanu
hide-bookmarkbar-icon =
    .label = Paslēpt grāmatzīmju joslas ikonas
tree-drop-links-on-tab-behavior-newtab =
    .label = Atvērt jaunu apakšcilni
open-all-private =
    .label = Atvērt visu privātajās cilnēs
preferences-doh-setting-ultra =
    .label = Īpaši drošā aizsardzība
    .accesskey = U
square-menu-item =
    .label = Kvadrātveida kontekstizvēlnes vienuma stūri
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Saglabāt izmaiņas
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-next-refresh =
    .value = Plānots atsvaidzināt: { $date }
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Saglabāt izmaiņas
    .buttonaccesskeyaccept = S
open-link-private =
    .label = Atvērt saiti jaunā privātā cilnē
open-private-tab =
    .label = Atvērt jaunā privātā cilnē
insert-after-current =
    .label = Ievietot jaunu cilni aiz pašreizējās cilnes
waterfox-blocker-toolbar-button =
    .label = Reklāmu bloķēšana
    .tooltiptext = Reklāmu bloķēšana
waterfox-blocker-show-badge-pref =
    .label = Rādīt bloķēto reklāmu skaitu rīkjoslas pogā
preferences-doh-ultra-fallback-allowed = Atļaut izmantot sistēmas DNS, ja drošajam DNS neizdodas DNS ierakstu pieprasījumi
enable-waterfox-theme-0 =
    .label = Iespējot Waterfox motīvu pielāgošanu visiem motīviem
enable-waterfox-theme-1 =
    .label = Iespējot Waterfox motīvu pielāgošanu visiem Waterfox motīviem
tree-auto-attach-on-new-tab-command-caption =
    .value = Atvērt jaunu tukšu cilni kā
    .accesskey = n
update-application-manual =
    .label = Neveikt atjauninājumu pārbaudi (nav ieteicams)
    .accesskey = N
waterfox-blocker-extension-install-manage-settings = Reklāmu bloķēšanu variet pārvaldīt sadaļā Iestatījumi > Konfidencialitāte un drošība.
new-private-tab =
    .label = Jauna privāta cilne
    .tooltiptext = Atvērt jaunu privātu cilni
preferences-doh-ultra-detailed-desc-3 = Maksimāla DNS konfidencialitātes aizsardzība — neviens nevar redzēt, kuras vietnes jūs apmeklējiet
waterfox-blocker-extension-detected = Waterfox tagad ir iebūvēta reklāmu bloķēšana. Iestatījumus variet pārskatīt pārlūka iestatījumos.
preferences-doh-ultra-fallback-disabled = Nekad neizmantot sistēmas DNS (vietnes var neielādēt, ja drošajam DNS neizdodas DNS ierakstu pieprasījumi)
enable-javascript =
    .label = Iespējot JavaScript
open-all-links-private =
    .label = Atvērt visas saites privātās cilnēs
status-bar =
    .label = Statusa josla
auto-hide-back =
    .label = Automātiski paslēpt "Atpakaļ" pogu
auto-hide-bookmarkbar =
    .label = Automātiski paslēpt grāmatzīmju joslu
tree-tree-double-click-behavior-toggle-close =
    .label = Aizvērt cilni
waterfox-blocker-intro-description = Bloķē reklāmas, izsekošanas skriptus un citus nevēlamus pieprasījumus, lai ātrāk ielādētu lapas un izvairītos no liekiem uzmanību novērsošiem traucēkļiem.
waterfox-blocker-filter-lists-column-category =
    .label = Kategorija
waterfox-blocker-filter-lists-enable =
    .label = Iespējot
waterfox-blocker-filter-lists-disable =
    .label = Atspējot
waterfox-blocker-panel-settings-button = Reklāmu bloķēšanas iestatījumi
waterfox-blocker-filter-lists-category-core = Noklusējuma
waterfox-blocker-filter-lists-category-annoyances = Kaitinošo elementu
waterfox-blocker-filter-lists-category-optional = Papildu izvēles
waterfox-blocker-extension-install-keep-built-in = Turpināt izmantot iebūvēto bloķētāju
waterfox-blocker-reenable-use-built-in = Izmantot iebūvēto bloķētāju
waterfox-blocker-prompt-title = Waterfox reklāmu bloķēšana
waterfox-blocker-reenable-keep-extension = Paturēt papildinājuma bloķētāju
onboarding-grassroots-subtitle = Paldies, ka izvēlējāties un lietojiet Waterfox — neatkarīgu, cilvēku atbalstītu pārlūku. Ar jūsu atbalstu mēs veidojam ilgtspējīgu alternatīvu lielajām pārlūka kompānijām.
tabbrowser-confirm-session-restore-checkbox = Atvērt iepriekšējos logus un cilnes
enable-menu-transparency =
    .label = Iespējot izvēlnes caurspīdīgumu
enable-panel-transparency =
    .label = Iespējot paneļa caurspīdīgumu
category-tree =
    .tooltiptext = { pane-tree-title }
private-tab =
    .label =
        { $isPrivate ->
            [true] Padarīt par parastu cilni
           *[false] Padarīt par privātu cilni
        }
geolocation-description = Dažu vietņu darbībai ir nepieciešama jūsu atrašanās vietas informācija. Ja vietne nedarbojas, jo nevar noteikt jūsu atrašanās vietu, lūdzu, iespējojiet šo iestatījumu un mēģiniet vēlreiz.
statusbar-show-links =
    .label = Rādīt saites
insert-related-after-current =
    .label = Ievietot radniecīgu jaunu cilni aiz pašreizējās cilnes
