restart-prompt-title = Riavvia { -brand-short-name }
restart-prompt-question = Sei sicuro di voler riavviare { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Riavvia
copy-url =
    .label = Copia Collegamento Scheda
copy-all-urls =
    .label = Copia Tutti I Link Delle Schede
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Apri tutto in schede private
open-all-links-private =
    .label = Apri tutti i link nelle schede private
open-private-tab =
    .label = Apri in una nuova scheda privata
new-private-tab =
    .label = Nuova Scheda Privata
    .tooltiptext = Apre una nuova scheda privata
open-link-private =
    .label = Apri collegamento in una nuova scheda privata
status-bar =
    .label = Barra Di Stato
tab-position-header = Posizione Barra Tab
tab-bar-top-above =
    .label = Top sopra la barra degli indirizzi
tab-bar-top-below =
    .label = Top sotto la barra degli indirizzi
tab-bar-bottom-above =
    .label = Basso sopra la barra di stato
tab-bar-bottom-below =
    .label = In basso sotto la barra di stato
tab-additional-header = Preferenze Di Scheda Aggiuntive
pinned-icon-only =
    .label = Riduci le schede bloccate per visualizzare solo l'icona del sito
insert-after-current =
    .label = Inserisci una nuova scheda dopo la scheda corrente
insert-related-after-current =
    .label = Inserisci una nuova scheda correlata dopo la scheda corrente
dynamic-theme-header = Temi Dinamici
dynamic-theme-dark =
    .label = Forza Modalità Scura
dynamic-theme-light =
    .label = Forza Modalità Luce
dynamic-theme-auto =
    .label = Imposta dinamicamente La Modalità Luce/Scuro
restart-header = Riavvia Elemento Menù
restart-show-button =
    .label = Mostra il pulsante di riavvio nel PanelUI
restart-purge-cache =
    .label = Pulisci la cache di riavvio veloce al riavvio del browser
restart-require-confirmation =
    .label = Richiede conferma riavvio
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Mostra la voce del menu URL della scheda copia
enable-copy-active-tab =
    .label = Copia URL solo dalla scheda attiva
show-copy-all-urls =
    .label = Mostra copia tutti gli URL della scheda
show-unload-tab =
    .label = Mostra la voce del menu scheda di scaricamento
statusbar-enabled =
    .label = Mostra Barra Di Stato
statusbar-show-links =
    .label = Mostra link
statusbar-contrast-text =
    .label = Colore testo barra di stato contrasto
bookmarks-bar-position-header = Posizione Barra Dei Segnalibri
bookmarks-position-top =
    .label = Alto
bookmarks-position-bottom =
    .label = Basso
geolocation-api-header = Geolocalizzazione API
geolocation-description = Alcuni siti web richiedono la tua posizione per funzionare. Se un sito web non funziona a causa di non essere in grado di trovare la tua posizione, abilita questa preferenza e riprova.
geolocation-api-enabled =
    .label = Abilita
geolocation-api-disabled =
    .label = Disabilita
send-referrer-header-0 =
    .label = Non inviare mai l'intestazione del referente
send-referrer-header-1 =
    .label = Invia l'intestazione del referrer solo quando si fa clic sui link e su elementi simili
send-referrer-header-2 =
    .label = Invia l'intestazione del referrer su tutte le richieste (predefinito)
enable-webrtc-p2p =
    .label = Abilita connessione peer WebRTC
load-images =
    .label = Carica automaticamente le immagini
enable-javascript =
    .label = Abilita JavaScript
webrtc-header = Connessione peer WebRTC
ref-header = Intestazione Referrer Http
statusbar-header = Barra Di Stato
private-tab =
    .label =
        { $isPrivate ->
            [true] Esci Dalla Scheda Privata
           *[false] Crea Scheda Privata
        }
preset-title = Presets
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
auto-hide-back =
    .label = Auto Hide Back Button
center-tab-label =
    .label = Center Tab Label Only
square-button-edges =
    .label = Square Button Corners
square-tab-edges =
    .label = Square Tab Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
drag-space =
    .label = Enable Fixed Drag Space
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font =
    .label = Enable monospaced font for page
tab-bar-header = Tab Bar
panels-header = Panels
full-screen-header = Full screen
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
onboarding-grassroots-title = Supporting the grassroots
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = Media Player
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
