# This Source Code Form is subject to the terms of the BrowserWorks Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This file is in the UTF-8 encoding
[Strings]
TitleText=Обновяване на %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% се обновява, ще отнеме минута…
BrowserWorksMaintenanceDescription=Услугата за поддръжка на BrowserWorks осигурява последната и най-безопасна версия на Waterfox за вашия компютър. Поддържането на текуща версия е много важно за вашата безопасност в Интернет пространството и BrowserWorks силно препоръчва да оставяте тази услуга включена.
