restart-prompt-title = { -brand-short-name } neu starten
restart-prompt-question = Möchten Sie { -brand-short-name } wirklich neu starten?
appmenuitem-restart-browser =
    .label = Neu starten
copy-url =
    .label = Tab-Adresse kopieren
copy-all-urls =
    .label = Alle Tab-Adressen kopieren
unload-tab =
    .label = Tab entladen
open-all-private =
    .label = Alle in privaten Tabs öffnen
open-all-links-private =
    .label = Alle Links in privaten Tabs öffnen
open-private-tab =
    .label = In neuem privaten Tab öffnen
new-private-tab =
    .label = Neuer privater Tab
    .tooltiptext = Neuen privaten Tab öffnen
open-link-private =
    .label = Link in neuem privaten Tab öffnen
status-bar =
    .label = Statusleiste
tab-position-header = Position der Tableiste
tab-bar-top-above =
    .label = Oben über der Adressleiste
tab-bar-top-below =
    .label = Oben unter der Adressleiste
tab-bar-bottom-above =
    .label = Unten über der Statusleiste
tab-bar-bottom-below =
    .label = Unten unter der Statusleiste
tab-additional-header = Zusätzliche Tabeinstellungen
pinned-icon-only =
    .label = Angeheftete Tabs verkleinern, um nur das Seitensymbol anzuzeigen
insert-after-current =
    .label = Neuen Tab nach aktuellem Tab einfügen
insert-related-after-current =
    .label = Zugehörigen neuen Tab nach aktuellem Tab einfügen
dynamic-theme-header = Dynamische Themes
dynamic-theme-dark =
    .label = Dunklen Modus erzwingen
dynamic-theme-light =
    .label = Hellen Modus erzwingen
dynamic-theme-auto =
    .label = Dynamisch Hellen/Dunklen Modus einstellen
restart-header = Menüpunkt neu starten
restart-show-button =
    .label = Neustart-Schaltfläche im PanelUI anzeigen
restart-purge-cache =
    .label = Schnellneustart-Cache beim Neustart des Browsers leeren
restart-require-confirmation =
    .label = Benötige Bestätigung für Neustart
tab-feature-header = Tab-Kontextmenü
show-duplicate-tab =
    .label = Zeige „Tab klonen“-Menüpunkt
show-copy-url =
    .label = Zeige „Tab-Adresse kopieren“-Menüpunkt
enable-copy-active-tab =
    .label = Adresse nur vom aktiven Tab kopieren
show-copy-all-urls =
    .label = Zeige „Alle Tab-Adressen kopieren“-Menüpunkt
show-unload-tab =
    .label = Zeige „Tab entladen“-Menüpunkt
statusbar-enabled =
    .label = Zeige Statusleiste
statusbar-show-links =
    .label = Links anzeigen
statusbar-contrast-text =
    .label = Textfarbe der Statusleiste kontrastieren
bookmarks-bar-position-header = Position der Lesezeichen-Symbolleiste
bookmarks-position-top =
    .label = Oben
bookmarks-position-bottom =
    .label = Unten
geolocation-api-header = Geolokalisierungs-API
geolocation-description = Einige Websites benötigen Ihren Standort, um zu funktionieren. Wenn eine Website nicht funktioniert, weil Ihr Standort nicht ermittelt werden kann, aktivieren Sie bitte diese Einstellung und versuchen Sie es erneut.
geolocation-api-enabled =
    .label = Aktivieren
geolocation-api-disabled =
    .label = Deaktivieren
send-referrer-header-0 =
    .label = Referrer-Header nie senden
send-referrer-header-1 =
    .label = Referrer-Header nur beim Klicken auf Links und ähnliche Elemente senden
send-referrer-header-2 =
    .label = Referrer-Header bei allen Anfragen senden (Standard)
enable-webrtc-p2p =
    .label = WebRTC Peer-Verbindung aktivieren
load-images =
    .label = Bilder automatisch laden
enable-javascript =
    .label = JavaScript aktivieren
webrtc-header = WebRTC Peer-Verbindung
ref-header = HTTP-Referrer-Header
statusbar-header = Statusleiste
private-tab =
    .label =
        { $isPrivate ->
            [true] Privaten Tab schließen
           *[false] Privaten Tab erstellen
        }
waterfox-defaults =
    .label = Waterfox Defaults
preset-title = Presets
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
auto-blur-tabs =
    .label = Auto Blur Tabs
enable-panel-transparency =
    .label = Enable panel transparency
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
disable-panel-animate =
    .label = Disable app menu panel animation
auto-hide-tabs =
    .label = Auto Hide Tabs
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
auto-hide-pageaction =
    .label = Auto Hide Page Action
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
center-tab-content =
    .label = Center Tab Content
square-button-edges =
    .label = Square Button Corners
center-navbar-text =
    .label = Center Nav Bar Text
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
drag-space =
    .label = Enable Fixed Drag Space
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
bookmark-header = Bookmarks Bar
font-header = Fonts
tab-context-line =
    .label = Tab Context Line
panels-header = Panels
media-player-header = Media Player
full-screen-header = Full screen
sidebar-header = Sidebar
icons-header = Icons
onboarding-grassroots-title = Supporting the grassroots
telemetry-privacy-policy = Privacy Policy
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
show-mac-menu-icons =
    .label = Show Mac Menu Icons
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
pane-theme-title = Look & Feel
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
category-theme =
    .tooltiptext = { pane-theme-title }
