restart-prompt-title = { -brand-short-name } neu starten
restart-prompt-question = Möchten Sie { -brand-short-name } wirklich neu starten?
appmenuitem-restart-browser =
    .label = Neu starten
copy-url =
    .label = Tab-Adresse kopieren
copy-all-urls =
    .label = Alle Tab-Adressen kopieren
unload-tab =
    .label = Tab entladen
open-all-private =
    .label = Alle in privaten Tabs öffnen
open-all-links-private =
    .label = Alle Links in privaten Tabs öffnen
open-private-tab =
    .label = In neuem privaten Tab öffnen
new-private-tab =
    .label = Neuer privater Tab
    .tooltiptext = Neuen privaten Tab öffnen
open-link-private =
    .label = Link in neuem privaten Tab öffnen
status-bar =
    .label = Statusleiste
tab-position-header = Position der Tableiste
tab-bar-top-above =
    .label = Oben über der Adressleiste
tab-bar-top-below =
    .label = Oben unter der Adressleiste
tab-bar-bottom-above =
    .label = Unten über der Statusleiste
tab-bar-bottom-below =
    .label = Unten unter der Statusleiste
tab-additional-header = Zusätzliche Tab-Einstellungen
pinned-icon-only =
    .label = Angeheftete Tabs verkleinern, um nur das Seitensymbol anzuzeigen
insert-after-current =
    .label = Neuen Tab nach aktuellem Tab einfügen
insert-related-after-current =
    .label = Zugehörigen neuen Tab nach aktuellem Tab einfügen
dynamic-theme-header = Dynamische Themes
dynamic-theme-dark =
    .label = Dunklen Modus erzwingen
dynamic-theme-light =
    .label = Hellen Modus erzwingen
dynamic-theme-auto =
    .label = Hellen/Dunklen Modus dynamisch einstellen
restart-header = Menüpunkt neu starten
restart-show-button =
    .label = Neustart-Schaltfläche im PanelUI anzeigen
restart-purge-cache =
    .label = Schnellneustart-Cache beim Neustart des Browsers leeren
restart-require-confirmation =
    .label = Bestätigung für Neustart erforderlich
tab-feature-header = Tab-Kontextmenü
show-duplicate-tab =
    .label = Menüpunkt „Tab duplizieren“ anzeigen
show-copy-url =
    .label = Menüpunkt „Tab-Adresse kopieren“ anzeigen
enable-copy-active-tab =
    .label = Adresse nur vom aktiven Tab kopieren
show-copy-all-urls =
    .label = Menüpunkt „Alle Tab-Adressen kopieren“ anzeigen
show-unload-tab =
    .label = Menüpunkt „Tab entladen“ anzeigen
statusbar-enabled =
    .label = Statusleiste anzeigen
statusbar-show-links =
    .label = Links anzeigen
statusbar-contrast-text =
    .label = Textfarbe der Statusleiste kontrastieren
bookmarks-bar-position-header = Position der Lesezeichen-Symbolleiste
bookmarks-position-top =
    .label = Oben
bookmarks-position-bottom =
    .label = Unten
geolocation-api-header = Geolokalisierungs-API
geolocation-description = Einige Websites benötigen Ihren Standort, um zu funktionieren. Wenn eine Website nicht funktioniert, weil Ihr Standort nicht ermittelt werden kann, aktivieren Sie bitte diese Einstellung und versuchen Sie es erneut.
geolocation-api-enabled =
    .label = Aktivieren
geolocation-api-disabled =
    .label = Deaktivieren
send-referrer-header-0 =
    .label = Referrer-Header nie senden
send-referrer-header-1 =
    .label = Referrer-Header nur beim Klicken auf Links und ähnliche Elemente übermitteln
send-referrer-header-2 =
    .label = Referrer-Header bei allen Anfragen mitsenden (Standard)
enable-webrtc-p2p =
    .label = WebRTC-Peer-Verbindung aktivieren
load-images =
    .label = Bilder automatisch laden
enable-javascript =
    .label = JavaScript aktivieren
webrtc-header = WebRTC-Peer-Verbindung
ref-header = HTTP-Referrer-Header
statusbar-header = Statusleiste
private-tab =
    .label =
        { $isPrivate ->
            [true] Privaten Tab schließen
           *[false] Privaten Tab erstellen
        }
preferences-doh-ultra-detailed-desc-2 = Bietet eine zusätzliche Verschlüsselungsebene, die über „DNS über HTTPS“ hinausgeht
preferences-doh-ultra-detailed-desc-3 = Maximaler DNS-Datenschutz - niemand kann sehen, welche Websites Sie besuchen
preferences-doh-ultra-fallback-mode = Fallback-Verhalten:
preferences-doh-ultra-fallback-disabled = Nicht auf System-DNS zurückgreifen (Websites werden bei Ausfall des sicheren DNS möglicherweise nicht geladen)
pane-theme-title = Aussehen
animation-header = Animationen
appearance-header = Erscheinungsbild
bookmark-header = Lesezeichenleiste
preferences-doh-ultra-fallback-allowed = Bei Ausfall des sicheren DNS auf System-DNS zurückgreifen
preferences-doh-setting-ultra =
    .label = Ultra-Schutz
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } verwendet für maximalen Schutz sicheres DNS mit Oblivious HTTP über den Datenschutz-Relay von Waterfox.
category-theme =
    .tooltiptext = { pane-theme-title }
preferences-doh-ultra-detailed-desc-1 = Verwendet das Oblivious HTTP-Relay von Waterfox, um DNS-Anfragen sogar vor dem DNS-Anbieter zu verbergen
media-player-header = Medienwiedergabe
nav-bar-header = Navigationsleiste
tab-bar-header = Tableiste
theme-header = Theme
enable-waterfox-theme-0 =
    .label = Waterfox-Theme-Anpassungen für alle Themes aktivieren
enable-waterfox-theme-1 =
    .label = Waterfox-Theme-Anpassungen für alle Waterfox-Themes aktivieren
enable-waterfox-theme-2 =
    .label = Waterfox-Theme-Anpassungen deaktivieren
monospace-font-theme =
    .label = Feste Schriftbreite für Theme aktivieren
tree-appearance-header = Erscheinungsbild
update-application-manual =
    .label = Nie nach Updates suchen (nicht empfohlen)
    .accesskey = N
sidebar-header = Seitenleiste
preset-title = Voreinstellungen
telemetry-privacy-policy = Datenschutzerklärung
tree-tree-double-click-behavior-toggle-close =
    .label = Tab schließen
tree-tree-double-click-behavior-toggle-none =
    .label = Nichts tun
full-screen-header = Vollbild
icons-header = Symbole
hide-all-icons =
    .label = Alle Symbole ausblenden
hide-bookmarkbar-icon =
    .label = Lesezeichenleisten-Symbole ausblenden
hide-tab-icons =
    .label = Tab-Symbole ausblenden
hide-urlbar-iconbox =
    .label = URL-Leisten-Symbolfeld ausblenden
show-mac-menu-icons =
    .label = Mac-Menü-Symbole anzeigen
show-menu-icons =
    .label = Menüsymbole anzeigen
tree-sticky-active-tab =
    .label = Aktiver Tab
    .accesskey = k
tree-faviconize-pinned-tabs =
    .label = Nur angeheftete Tabs mit ihrem Symbol anzeigen
    .accesskey = a
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Einfügeposition neuer untergeordneter Tabs aus angehefteten Tabs (werden als Stamm-Tabs angezeigt)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Das Ende des Baums
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Keine Kontrolle (Entscheidung des Browsers oder anderer Tab-Erweiterungen respektieren)
autohide-hidden-header = Automatisch ausblenden & Ausgeblendet
auto-hide-back =
    .label = Schaltfläche „Zurück“ automatisch ausblenden
auto-hide-bookmarkbar =
    .label = Lesezeichenleiste automatisch ausblenden
auto-hide-forward =
    .label = Schaltfläche „Weiter“ automatisch ausblenden
auto-hide-navbar =
    .label = Navigationsleiste automatisch ausblenden
auto-hide-pageaction =
    .label = Seitenaktion automatisch ausblenden
auto-hide-sidebar =
    .label = Seitenleiste automatisch ausblenden
auto-hide-tabbar =
    .label = Tableiste automatisch ausblenden
auto-hide-tabs =
    .label = Tabs automatisch ausblenden
hide-bookmarkbar-label =
    .label = Beschriftungen der Lesezeichenleiste ausblenden
hide-disabled-menuitems =
    .label = Deaktivierte Menüelemente ausblenden
hide-sidebar-header =
    .label = Seitenleistenkopf ausblenden
monospace-font =
    .label = Feste Schriftbreite für Seite aktivieren
tabbrowser-confirm-session-restore-checkbox = Vorherige Fenster und Tabs öffnen
tree-behavior-header = Baumansicht der Tabs
font-header = Schriftarten
lepton-style =
    .label = Lepton-Stil
proton-style =
    .label = Proton-Stil
waterfox-defaults =
    .label = Waterfox-Standardeinstellungen
center-header = Zentrieren
rounding-header = Rundung
center-tab-content =
    .label = Tab-Inhalt zentrieren
center-tab-label =
    .label = Nur Tab-Beschriftung zentrieren
center-navbar-text =
    .label = Text der Navigationsleiste zentrieren
auto-blur-tabs =
    .label = Tabs automatisch verschleiern
telemetry-page-subtitle = Waterfox sammelt keine Telemetriedaten über Ihre Installation – alle Telemetriemodule werden beim Erstellen des Browsers deaktiviert. Was Sie in Ihrem Browser tun, wissen nur Sie selbst.
tree-auto-attach-no-control =
    .label = (keine Kontrolle)
tree-tree-double-click-behavior-caption =
    .value = Doppelklick auf Tab
    .accesskey = D
close-button-hover =
    .label = Schließen-Schaltfläche beim Bewegen des Mauszeigers über den ausgewählten Tab anzeigen, wenn viele Tabs geöffnet sind
enable-default-accent-color =
    .label = Standard-Akzentfarbe
enable-system-accent-color =
    .label = System-Akzentfarbe
enable-cyan-accent-color =
    .label = Cyan als Akzentfarbe
enable-menu-transparency =
    .label = Menütransparenz aktivieren
enable-panel-transparency =
    .label = Panel-Transparenz aktivieren
square-menu-popup =
    .label = Eckiges Kontextmenü-Panel
square-menu-panel =
    .label = Eckiges Anwendungsmenü-Panel
square-menu-item =
    .label = Eckige Kontextmenü-Einträge
square-field =
    .label = Eckige Eingabefelder
square-button-edges =
    .label = Eckige Schaltflächen
square-panel-item =
    .label = Eckige Anwendungsmenü-Einträge
square-tab-edges =
    .label = Eckige Tabs
square-checkbox =
    .label = Eckige Kontrollkästchen
tab-context-line =
    .label = Tab-Kontextzeile
remove-panel-strip =
    .label = Farbige Trennlinie im Anwendungsmenü entfernen
panels-header = Panels
compact-bookmark-menu =
    .label = Abstand im Lesezeichen-Menü verringern
compact-context-menu =
    .label = Abstand im Kontextmenü verringern
compact-navbar-popup =
    .label = Abstand der Pop-ups in der Navigationsleiste verringern
compact-panel-header =
    .label = Abstand der Panel-Kopfzeilen verringern
disable-panel-animate =
    .label = Animation des Anwendungsmenü-Panels deaktivieren
disable-sidebar-animate =
    .label = Animation des Seitenleisten-Panels deaktivieren
drag-space =
    .label = Festen Ziehenbereich aktivieren
full-panel-strip =
    .label = Anwendungsmenü-Trennlinie in voller Breite
onboarding-grassroots-title = Unterstützung der Basis
onboarding-grassroots-subtitle = Vielen Dank, dass Sie Waterfox, einen unabhängigen Browser aus der Basis, verwenden. Mit Ihrer Unterstützung bauen wir eine nachhaltige Alternative zu den großen Anbietern auf.
tree-auto-sticky-header = Tabs bleiben beim Herausscrollen an den Rändern der Tableiste hängen
tree-sticky-sharing-tab =
    .label = Tabs, die Kamera/Mikrofon/Bildschirm teilen
    .accesskey = t
tree-sticky-sound-playing-tab =
    .label = Tabs für Soundwiedergabe
    .accesskey = S
category-tree =
    .tooltiptext = { pane-tree-title }
tree-drop-links-on-tab-behavior-caption =
    .value = Wenn ein Link oder eine URL-Zeichenfolge auf einen Tab gezogen wird
    .accesskey = L
interface-component-header = Komponenten
pane-tree-title = Vertikale hierarchische Tabs
browser-layout-tree-vertical-tabs =
    .label = Vertikale hierarchische Tabs
sidebar-tree-vertical-tabs =
    .label = Vertikale hierarchische Tabs
tree-header = Vertikale hierarchische Tabs
tree-drop-links-on-tab-behavior-load =
    .label = Auf Tab laden
tree-auto-collapse-expand-subtree-on-select =
    .label = Wenn ein Tab den Fokus erhält, wird dessen Baum automatisch erweitert und die anderen Tabs werden ausgeblendet.
    .accesskey = F
tree-auto-collapse-expand-subtree-on-attach =
    .label = Wenn ein neuer Baum erscheint, werden andere automatisch ausgeblendet
    .accesskey = a
tree-drop-links-on-tab-behavior-ask =
    .label = Immer fragen, wie man es behandelt
tree-drop-links-on-tab-behavior-newtab =
    .label = Neuen untergeordneten Tab öffnen
tree-successor-tab-control-level-caption =
    .value = Wenn der aktuelle Tab als letztes untergeordnetes Element geschlossen wird
    .accesskey = W
tree-successor-tab-control-level-in-tree =
    .label = Fokus auf den vorherigen Tab in der Baumstruktur setzen
tree-successor-tab-control-level-never =
    .label = Fokus immer auf den nächsten Tab setzen (unter Berücksichtigung der Einstellungen des Browsers oder anderer Erweiterungen)
tree-successor-tab-control-level-simulate-default =
    .label = Fokus immer auf den nächsten Tab setzen
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Baum einklappen/aufklappen
tree-auto-attach-header = Automatische Organisation der Tabstruktur
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Neben dem zuletzt geöffneten Tab oder nahe am Ursprung
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = An der Spitze des Baumes (nahe am Ursprung)
tree-auto-attach-independent =
    .label = Unabhängiger Tab
tree-tree-double-click-behavior-toggle-sticky =
    .label = An den Kanten des Tab-Balkens anheften / Von den Kanten des Tab-Balkens lösen
tree-auto-attach-child-end =
    .label = Letztes Element des übergeordneten Tabs
tree-auto-attach-child-next-to-last-related-tab =
    .label = Element des übergeordneten Tabs, neben dem zuletzt geöffneten Element
tree-auto-attach-child-top =
    .label = Erstes Element des übergeordneten Tabs
tree-auto-attach-next-sibling =
    .label = Nächster Nachbar des übergeordneten Tabs
tree-auto-attach-sibling =
    .label = Nachbar des übergeordneten Tabs
tree-auto-attach-on-duplicated-caption =
    .value = Tab duplizieren als
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Für den mittleren Mausklick einen neuen leeren Tab öffnen als
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Neuen leeren Tab öffnen als
    .accesskey = N
tree-auto-attach-on-opened-from-external-caption =
    .value = Neuer Tab aus anderen Anwendungen: Öffnen als
    .accesskey = Ö
tree-auto-attach-on-opened-with-owner-caption =
    .value = Wenn ein Tab aus einem bestehenden Tab geöffnet wird, ihn öffnen als
    .accesskey = g
tree-auto-attach-same-site-orphan-caption =
    .value = Neuer Tab mit derselben Website wie der aktuelle Tab aus Adressleiste, Lesezeichen, Verlauf oder anderen Fällen: Öffnen als
    .accesskey = w
tree-auto-attach-on-any-other-trigger-caption =
    .value = Tabs von anderen Auslösern: Öffnen als
    .accesskey = T
waterfox-blocker-filter-lists-column-name =
    .label = Filterliste
waterfox-blocker-filter-lists-column-category =
    .label = Kategorie
waterfox-blocker-filter-lists-enable =
    .label = Aktivieren
waterfox-blocker-filter-lists-disable =
    .label = Deaktivieren
waterfox-blocker-filter-lists-column-enabled =
    .label = Aktiviert
waterfox-blocker-setting-off =
    .label = Aus
waterfox-blocker-header = Werbeblocker
waterfox-blocker-setting-on =
    .label = Ein
waterfox-blocker-dropdown-option-block-everything =
    .label = Bei Waterfox-Suchpartnern deaktivieren
waterfox-blocker-manage-filter-lists =
    .label = Filterlisten verwalten…
waterfox-blocker-filter-lists-window =
    .title = Filterlisten für Werbeblocker
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Änderungen speichern
    .buttonaccesskeyaccept = s
waterfox-blocker-extension-install-learn-more =
    .label = Mehr erfahren
waterfox-blocker-extension-detected-learn-more =
    .label = Mehr erfahren
waterfox-blocker-extension-detected-dismiss =
    .label = Nicht erneut anzeigen
waterfox-blocker-extension-install-got-it =
    .label = Verstanden
waterfox-blocker-filter-lists-category-core = Standard
waterfox-blocker-filter-lists-category-privacy = Datenschutz
waterfox-blocker-filter-lists-category-optional = Optional
waterfox-blocker-filter-lists-category-regional = Regional
waterfox-blocked-page-blocked-url-label = Blockierte URL
waterfox-blocked-page-unavailable = Nicht verfügbar
waterfox-blocked-page-go-back = Zurück
waterfox-blocked-page-load-anyway = Trotzdem laden
waterfox-blocker-intro-description = Blockiert Werbung, Tracking-Skripte und andere unerwünschte Anfragen, um Seiten schneller zu laden und Ablenkungen zu vermeiden.
waterfox-blocker-setting-off-description = Waterfox blockiert weder Werbung noch Tracker. Erweiterungen von Drittanbietern können Inhalte weiterhin eigenständig blockieren.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } von { $totalCount } aktiv
waterfox-blocker-dropdown-option-partner-exception =
    .label = Bei Waterfox-Suchpartnern zulassen
waterfox-blocker-dropdown-label =
    .value = Werbung von Suchpartnern:
waterfox-blocker-filter-lists-category-annoyances = Belästigungen
waterfox-blocker-extension-fallback-name-this = diese Erweiterung
waterfox-blocker-extension-fallback-name-your = Ihre Erweiterung
waterfox-blocker-spotlight-title = Waterfox verfügt nun über einen Werbeblocker
waterfox-blocker-spotlight-primary-button = Meine aktuelle Konfiguration beibehalten
waterfox-blocker-filter-lists-empty-state = Es sind keine Filterlisten verfügbar.
waterfox-blocker-filter-lists-description =
    .value = Wählen Sie aus, welche Filterlisten aktiv sein sollen.
waterfox-blocker-third-party-notice-description = { $extensionName } blockiert ebenfalls Werbung. Der gleichzeitige Einsatz von zwei Werbeblockern kann zu Problemen führen.
waterfox-blocker-prompt-title = Werbeblocker für Waterfox
waterfox-blocker-reenable-conflict-message = Wenn sowohl der Werbeblocker von Waterfox als auch „{ $extensionName }“ aktiv sind, kann es zu Darstellungsfehlern auf Webseiten kommen. Was möchten Sie beibehalten?
waterfox-blocker-reenable-use-built-in = Integrierten Blocker verwenden
waterfox-blocker-spotlight-secondary-button = Einstellungen überprüfen
waterfox-blocker-reenable-keep-extension = Erweiterungsblocker beibehalten
waterfox-blocker-extension-install-anyway = Trotzdem installieren
waterfox-blocker-extension-install-keep-built-in = Den integrierten Blocker weiterhin verwenden
waterfox-blocked-page-title = Waterfox hat diese Seite blockiert
waterfox-blocked-page-heading = Waterfox hat diese Seite blockiert
waterfox-blocked-page-details =
    .aria-label = Details zur blockierten Seite
waterfox-blocked-page-matched-rule-label = Übereinstimmende Regel
waterfox-blocked-page-hint = Mit „Trotzdem laden“ wird diese Website für den Rest Ihrer Sitzung vorübergehend zugelassen.
waterfox-blocked-page-description = Diese Seite wurde durch eine Regel des Werbeblockers blockiert.
waterfox-blocker-setting-on-description = Waterfox blockiert Folgendes:
waterfox-blocker-extension-detected = Waterfox verfügt nun über einen integrierten Werbeblocker. Sie können Ihre Einstellungen in den Einstellungen überprüfen.
waterfox-blocker-extension-install-warning = Waterfox verfügt bereits über einen integrierten Werbeblocker. Der gleichzeitige Einsatz von zwei Werbeblockern kann dazu führen, dass Webseiten nicht richtig angezeigt werden oder nur langsam geladen werden.
waterfox-blocker-spotlight-subtitle = Wir haben festgestellt, dass Sie { $extensionName } installiert haben. Waterfox verfügt nun über einen eigenen Werbeblocker. Wenn Sie diesen nutzen, unterstützen Sie Waterfox. Die Entscheidung liegt jedoch ganz bei Ihnen.
waterfox-blocker-extension-install-manage-settings = Den Werbeblocker können Sie unter „Einstellungen“ > „Datenschutz & Sicherheit“ verwalten.
waterfox-blocker-panel-disabled = Werbeblocker ist deaktiviert
waterfox-blocker-panel-site-excepted = Werbung ist auf dieser Website erlaubt
waterfox-blocker-panel-partner-allowed = Für Suchpartner ist Werbung erlaubt
waterfox-blocker-panel-not-available = Auf dieser Seite nicht verfügbar
waterfox-blocker-panel-toggle =
    .label = Werbeblocker auf dieser Website
    .description = Werbung und Tracker auf dieser Website blockieren.
waterfox-blocker-toolbar-button =
    .label = Werbeblocker
    .tooltiptext = Werbeblocker
waterfox-blocker-stats =
    { $count ->
        [eine] { $count } Werbung auf dieser Website blockiert
       *[andere] { $count } Werbung auf dieser Website blockiert
    }
waterfox-blocker-panel-settings-button = Einstellungen für Werbeblocker
waterfox-blocker-show-badge-pref =
    .label = Anzahl der blockierten Elemente auf der Symbolleisten-Schaltfläche anzeigen
waterfox-blocker-custom-filter-lists =
    .label = Benutzerdefinierte Filterlisten…
waterfox-blocker-filter-lists-search =
    .placeholder = Filterlisten suchen…
waterfox-blocker-filter-lists-refresh-now =
    .label = Jetzt aktualisieren
waterfox-blocker-filter-lists-last-updated = Aktualisiert am { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Noch nicht aktualisiert
waterfox-blocker-custom-filter-lists-window =
    .title = Benutzerdefinierte Filterlisten
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Änderungen speichern
    .buttonaccesskeyaccept = s
waterfox-blocker-custom-filter-lists-description = Fügen Sie URLs für benutzerdefinierte Filterlisten hinzu. Die Listen werden abgerufen und zusätzlich zu den integrierten Filtern angewendet.
waterfox-blocker-filter-lists-custom-heading =
    .value = Benutzerdefinierte Filterlisten
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Geben Sie die URL der Filterliste ein…
waterfox-blocker-filter-lists-custom-url-label =
    .value = URL der Filterliste
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Hinzufügen
waterfox-blocker-filter-lists-custom-remove =
    .label = Entfernen
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Alle entfernen
waterfox-blocker-filter-lists-custom-empty =
    .value = Es wurden keine benutzerdefinierten Filterlisten hinzugefügt.
waterfox-blocker-setting-on-summary = Blockiert Werbung und Tracker, ohne das Laden der Seite nennenswert zu beeinträchtigen.
waterfox-blocker-blocks-ads = Werbung und Anfragen von Werbenetzwerken
waterfox-blocker-blocks-tracking = Tracking-Skripte und Pixel
waterfox-blocker-blocks-annoyances = Lästige Pop-ups und Einblendungen (bei aktivierten Sperrlisten)
waterfox-blocker-partner-funding-title = Unterstützen Sie die Entwicklung von Waterfox
waterfox-blocker-partner-funding-description = Waterfox ist kostenlos, Open Source und unabhängig. Durch die Anzeige von Werbung auf den Seiten unserer Suchpartner finanziert Waterfox die Entwicklung und die Infrastruktur. Sie können dies jederzeit deaktivieren, doch es eingeschaltet zu lassen, ist der einfachste Weg, das Projekt zu unterstützen.
waterfox-blocker-custom-filters =
    .label = Meine Filter…
waterfox-blocker-custom-filters-window =
    .title = Meine Filter
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Änderungen speichern
    .buttonaccesskeyaccept = s
waterfox-blocker-custom-filters-description = Fügen Sie eigene Regeln zum Blockieren von Werbung hinzu. Diese verwenden die Standard-Filtersyntax von uBlock Origin und werden zusätzlich zu Ihren aktivierten Filterlisten angewendet.
waterfox-blocker-custom-filters-empty =
    .value = Keine benutzerdefinierten Filter.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Keine benutzerdefinierten Filter.
        [one] 1 benutzerdefinierter Filter.
       *[other] { $count } benutzerdefinierte Filter.
    }
waterfox-blocker-custom-filters-status-unsaved = Nicht gespeicherte Änderungen.
waterfox-blocker-custom-filters-import =
    .label = Importieren…
waterfox-blocker-custom-filters-export =
    .label = Exportieren…
waterfox-blocker-custom-filters-load-error-title = Laden fehlgeschlagen
waterfox-blocker-custom-filters-load-error = Benutzerdefinierte Filter konnten nicht geladen werden.
waterfox-blocker-custom-filters-save-error-title = Speichern fehlgeschlagen
waterfox-blocker-custom-filters-save-error = Benutzerdefinierte Filter konnten nicht gespeichert werden.
waterfox-blocker-custom-filters-import-error-title = Import fehlgeschlagen
waterfox-blocker-custom-filters-import-error = Die ausgewählte Datei konnte nicht importiert werden.
waterfox-blocker-custom-filters-export-error-title = Export fehlgeschlagen
waterfox-blocker-custom-filters-export-error = Benutzerdefinierte Filter konnten nicht exportiert werden.
waterfox-blocker-custom-filters-import-picker-title = Benutzerdefinierte Filter importieren
waterfox-blocker-custom-filters-export-picker-title = Benutzerdefinierte Filter exportieren
waterfox-blocker-custom-filters-import-replace-title = Die aktuellen Filter austauschen?
waterfox-blocker-custom-filters-import-replace-message = Durch den Import wird der gesamte derzeit im Editor angezeigte Inhalt überschrieben.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Ausnahmen für Werbeblocker
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Sie können festlegen, auf welchen Websites der Werbeblocker deaktiviert werden soll. Geben Sie die genaue Adresse der Website ein, die Sie verwalten möchten, und klicken Sie dann auf „Ausnahme hinzufügen“.
waterfox-blocker-filter-lists-next-refresh =
    .value = Nächste Aktualisierung: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Nächste Aktualisierung: unbekannt
waterfox-data-collection-header = { -brand-short-name } Datenerhebung und -nutzung
    .searchkeywords = Datenschutz Telemetriedatenerfassung Datenschutzerklärung
waterfox-data-collection-description = { -brand-short-name } erfasst keine Telemetrie- oder Nutzungsdaten. Für optionale Dienste wie Sync gelten möglicherweise eigene Datenschutzhinweise. Die <a data-l10n-name="privacy-notice">Datenschutzerklärung</a> ist hier zur einfachen Einsichtnahme bereitgestellt.
