restart-prompt-title = Reiniciar { -brand-short-name }
restart-prompt-question = ¿Está seguro que desea reiniciar { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Reiniciar
copy-url =
    .label = Copiar enlace pestaña
copy-all-urls =
    .label = Copiar todos los enlaces a la pestaña
unload-tab =
    .label = Descargar pestaña
open-all-private =
    .label = Abrir todo en Pestañas Privadas
open-all-links-private =
    .label = Abrir todos los enlaces en pestañas privadas
open-private-tab =
    .label = Abrir en una nueva pestaña privada
new-private-tab =
    .label = Nueva pestaña privada
    .tooltiptext = Abrir una nueva pestaña privada
open-link-private =
    .label = Abrir enlace en nueva pestaña privada
status-bar =
    .label = Barra de estado
tab-position-header = Posición de la barra de pestaña
tab-bar-top-above =
    .label = Arriba, encima de la barra de direcciones
tab-bar-top-below =
    .label = Arriba, debajo de la barra de direcciones
tab-bar-bottom-above =
    .label = Abajo, encima de la barra de estado
tab-bar-bottom-below =
    .label = Abajo, debajo de la barra de estado
tab-additional-header = Preferencias adicionales de Tab
pinned-icon-only =
    .label = Contraer pestañas fijadas para mostrar sólo el icono del sitio
insert-after-current =
    .label = Insertar nueva pestaña después de la pestaña actual
insert-related-after-current =
    .label = Insertar nueva pestaña relacionada después de la pestaña actual
dynamic-theme-header = Temas Dinámicos
dynamic-theme-dark =
    .label = Forzar Modo Oscuro
dynamic-theme-light =
    .label = Forzar Modo Luz
dynamic-theme-auto =
    .label = Definir dinámicamente el modo Luz/Oscuro
restart-header = Reiniciar elemento de menú
restart-show-button =
    .label = Mostrar botón de reiniciar en PanelUI
restart-purge-cache =
    .label = Borrar caché de reinicio rápido al reiniciar el navegador
restart-require-confirmation =
    .label = Requiere confirmación de reinicio
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Mostrar la opción «Duplicar pestaña»
show-copy-url =
    .label = Mostrar elemento del menú de la pestaña de copia
enable-copy-active-tab =
    .label = Copiar URL sólo desde la pestaña activa
show-copy-all-urls =
    .label = Mostrar copia de todas las urls de la pestaña
show-unload-tab =
    .label = Mostrar elemento de menú de pestaña de descarga
statusbar-enabled =
    .label = Mostrar barra de estado
statusbar-show-links =
    .label = Mostrar enlaces
statusbar-contrast-text =
    .label = Color de texto de la barra de estado contrastar
bookmarks-bar-position-header = Posición de la barra de marcadores
bookmarks-position-top =
    .label = Subir
bookmarks-position-bottom =
    .label = Abajo
geolocation-api-header = API de geolocalización
geolocation-description = Algunos sitios web requieren su ubicación para funcionar. Si un sitio web no funciona porque no puede detectar su ubicación, habilite esta preferencia y vuelva a intentarlo.
geolocation-api-enabled =
    .label = Activar
geolocation-api-disabled =
    .label = Desactivar
send-referrer-header-0 =
    .label = Nunca enviar la cabecera del remitente
send-referrer-header-1 =
    .label = Incluir la cabecera referrer solo al hacer clic en enlaces y elementos similares
send-referrer-header-2 =
    .label = Incluir la cabecera referrer en todas las peticiones (por defecto)
enable-webrtc-p2p =
    .label = Habilitar la conexión entre pares WebRTC
load-images =
    .label = Cargar imágenes automáticamente
enable-javascript =
    .label = Activar JavaScript
webrtc-header = Conexión con pares WebRTC
ref-header = Encabezado de HTTP
statusbar-header = Barra de estado
private-tab =
    .label =
        { $isPrivate ->
            [true] Salir de la pestaña privada
           *[false] Hacer pestaña privada
        }
update-application-manual =
    .label = No buscar actualizaciones nunca (no recomendado)
    .accesskey = N
preferences-doh-setting-ultra =
    .label = Protección Ultra
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } utilizará DNS seguro con Oblivious HTTP a través del relé de privacidad de Waterfox para una protección máxima.
preferences-doh-ultra-detailed-desc-1 = Utiliza el relé Oblivious HTTP de Waterfox para ocultar las consultas DNS incluso del proveedor de DNS
preferences-doh-ultra-detailed-desc-2 = Proporciona una capa adicional de cifrado más allá del estándar DNS sobre HTTPS
preferences-doh-ultra-detailed-desc-3 = Máxima protección de privacidad DNS: nadie puede ver qué sitios visitas
preferences-doh-ultra-fallback-mode = Comportamiento alternativo:
preferences-doh-ultra-fallback-allowed = Permitir el uso del DNS del sistema si falla el DNS seguro
preferences-doh-ultra-fallback-disabled = No recurrir nunca al DNS del sistema (los sitios pueden no cargarse si falla el DNS seguro)
animation-header = Animaciones
appearance-header = Apariencia
autohide-hidden-header = Auto-ocultar y ocultos
bookmark-header = Barra de marcadores
center-header = Centrar
font-header = Fuentes
full-screen-header = Pantalla completa
icons-header = Iconos
interface-component-header = Componentes de la interfaz
media-player-header = Reproductor multimedia
nav-bar-header = Barra de navegación
panels-header = Paneles
rounding-header = Redondeo
sidebar-header = Barra lateral
tab-bar-header = Barra de pestañas
theme-header = Tema
lepton-style =
    .label = Estilo Lepton
proton-style =
    .label = Estilo Proton
close-button-hover =
    .label = Mostrar el botón de cerrar pestaña al pasar el cursor sobre la pestaña seleccionada cuando hay muchas pestañas abiertas
compact-bookmark-menu =
    .label = Reducir el espaciado del menú de marcadores
compact-context-menu =
    .label = Reducir el espaciado del menú contextual
compact-navbar-popup =
    .label = Reducir el espaciado del menú emergente de la barra de navegación
compact-panel-header =
    .label = Reducir el espaciado del encabezado del panel
disable-sidebar-animate =
    .label = Desactivar la animación del panel lateral
drag-space =
    .label = Activar espacio fijo para arrastrar
enable-cyan-accent-color =
    .label = Color de acento cian
enable-default-accent-color =
    .label = Color de acento predeterminado
enable-menu-transparency =
    .label = Activar la transparencia del menú
enable-panel-transparency =
    .label = Activar la transparencia del panel
enable-system-accent-color =
    .label = Color de acento del sistema
enable-waterfox-theme-0 =
    .label = Activar las personalizaciones de tema de Waterfox en todos los temas
enable-waterfox-theme-1 =
    .label = Activar las personalizaciones de tema de Waterfox solo en los temas de Waterfox
enable-waterfox-theme-2 =
    .label = Desactivar las personalizaciones de tema de Waterfox
full-panel-strip =
    .label = Separador del menú de la aplicación de ancho completo
remove-panel-strip =
    .label = Eliminar el separador de color del menú de la aplicación
hide-all-icons =
    .label = Ocultar todos los iconos
hide-bookmarkbar-icon =
    .label = Ocultar los iconos de la barra de marcadores
hide-bookmarkbar-label =
    .label = Ocultar las etiquetas de la barra de marcadores
hide-disabled-menuitems =
    .label = Ocultar los elementos de menú deshabilitados
hide-sidebar-header =
    .label = Ocultar el encabezado de la barra lateral
hide-tab-icons =
    .label = Ocultar los iconos de las pestañas
hide-urlbar-iconbox =
    .label = Ocultar el recuadro de iconos de la barra de direcciones
monospace-font =
    .label = Activar fuente monoespaciada para la página
monospace-font-theme =
    .label = Activar fuente monoespaciada para el tema
show-mac-menu-icons =
    .label = Mostrar iconos del menú en macOS
show-menu-icons =
    .label = Mostrar los iconos del menú
square-button-edges =
    .label = Esquinas cuadradas en los botones
square-checkbox =
    .label = Casilla de verificación cuadrada
square-field =
    .label = Esquinas cuadradas en los campos de entrada
square-menu-item =
    .label = Esquinas cuadradas en los elementos del menú contextual
square-menu-panel =
    .label = Esquinas cuadradas en el panel del menú de la aplicación
square-menu-popup =
    .label = Esquinas cuadradas en el panel del menú contextual
square-panel-item =
    .label = Esquinas cuadradas en los elementos del menú de la aplicación
square-tab-edges =
    .label = Esquinas cuadradas en las pestañas
tab-context-line =
    .label = Línea de contexto de pestañas
telemetry-page-subtitle = Waterfox no recopila telemetría sobre tu instalación: todos los módulos de telemetría se desactivan al compilar el navegador. Lo que haces en tu navegador solo lo sabes tú.
telemetry-privacy-policy = Política de privacidad
onboarding-grassroots-title = Apoyando el movimiento de base
onboarding-grassroots-subtitle = Gracias por usar Waterfox, un navegador independiente y de base comunitaria. Con tu apoyo, estamos construyendo una alternativa sostenible frente a los grandes actores del sector.
tabbrowser-confirm-session-restore-checkbox = Abrir las ventanas y pestañas anteriores
pane-tree-title = Pestañas verticales en árbol
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Pestañas verticales en árbol
sidebar-tree-vertical-tabs =
    .label = Pestañas verticales en árbol
tree-header = Pestañas verticales en árbol
tree-appearance-header = Apariencia
tree-auto-sticky-header = Pestañas fijadas a los bordes de la barra cuando salen de la vista al desplazarse
tree-faviconize-pinned-tabs =
    .label = Mostrar las pestañas ancladas solo con su icono
    .accesskey = S
tree-sticky-active-tab =
    .label = Pestaña activa
    .accesskey = k
tree-sticky-sharing-tab =
    .label = Pestañas que comparten cámara/micrófono/pantalla
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Pestañas con sonido en reproducción
    .accesskey = y
tree-behavior-header = Vista en árbol de las pestañas
tree-auto-collapse-expand-subtree-on-attach =
    .label = Cuando aparece un nuevo árbol, contraer automáticamente los demás
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Al enfocar una pestaña, expandir su árbol y contraer las demás automáticamente
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = Cuando se suelta un enlace o una URL sobre una pestaña
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Preguntarme siempre cómo tratarlo
tree-drop-links-on-tab-behavior-load =
    .label = Cargar en la pestaña
tree-drop-links-on-tab-behavior-newtab =
    .label = Abrir una nueva pestaña hija
tree-successor-tab-control-level-caption =
    .value = Cuando la pestaña actual se cierra siendo la última hija
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = Mover el foco a la pestaña anterior en el árbol
tree-successor-tab-control-level-never =
    .label = Siempre mover el foco a la siguiente pestaña (respetar el control del navegador o de otras extensiones)
tree-successor-tab-control-level-simulate-default =
    .label = Siempre mover el foco a la siguiente pestaña
tree-tree-double-click-behavior-caption =
    .value = Doble clic en una pestaña
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Cerrar pestaña
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Contraer/expandir árbol
tree-tree-double-click-behavior-toggle-none =
    .label = No hacer nada
tree-tree-double-click-behavior-toggle-sticky =
    .label = Fijar a los bordes de la barra de pestañas / Desfijar de los bordes de la barra de pestañas
tree-auto-attach-header = Organización automática del árbol de pestañas
tree-auto-attach-child-end =
    .label = Último hijo de la pestaña principal
tree-auto-attach-child-next-to-last-related-tab =
    .label = Hijo de la pestaña principal, junto al hijo abierto recientemente
tree-auto-attach-child-top =
    .label = Primer hijo de la pestaña principal
tree-auto-attach-independent =
    .label = Pestaña independiente
tree-auto-attach-next-sibling =
    .label = Siguiente hermano de la pestaña principal
tree-auto-attach-no-control =
    .label = (sin control)
tree-auto-attach-sibling =
    .label = Hermano de la pestaña principal
tree-auto-attach-on-any-other-trigger-caption =
    .value = Pestañas desde cualquier otro origen: Abrir como
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = Duplicar la pestaña como
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Al hacer clic central, abrir nueva pestaña en blanco como
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Abrir nueva pestaña en blanco como
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Nueva pestaña desde otras aplicaciones: Abrir como
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = Cuando una pestaña se abre desde otra existente, abrirla como
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Nueva pestaña con el mismo sitio que la actual desde la barra de direcciones, marcadores, historial u otros: Abrir como
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Posición de inserción de nuevas pestañas hijas desde pestañas ancladas (aparecerán como pestañas raíz)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Al final del árbol
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Junto al hijo abierto recientemente o cerca de la pestaña de origen
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Sin control (respetar la decisión del navegador o de otras extensiones)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = En la parte superior del árbol (cerca de la pestaña de origen)
waterfox-blocker-header = Bloqueo de anuncios
waterfox-blocker-intro-description = Bloquea anuncios, scripts de rastreo y otras solicitudes no deseadas para acelerar la carga de las páginas y reducir distracciones.
waterfox-blocker-setting-on =
    .label = Activado
waterfox-blocker-setting-on-description = Waterfox bloquea lo siguiente:
waterfox-blocker-setting-off =
    .label = Desactivado
waterfox-blocker-setting-off-description = Waterfox no bloquea anuncios ni rastreadores. Las extensiones de terceros pueden seguir bloqueando contenido de forma independiente.
waterfox-blocker-dropdown-option-partner-exception =
    .label = Permitir anuncios en los socios de búsqueda de Waterfox
waterfox-blocker-panel-partner-allowed = Anuncios permitidos para los socios de búsqueda
waterfox-blocker-dropdown-label =
    .value = Anuncios de socios de búsqueda:
waterfox-blocker-dropdown-option-block-everything =
    .label = Bloquear en los socios de búsqueda de Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Gestionar listas de filtros…
waterfox-blocker-custom-filter-lists =
    .label = Listas de filtros personalizadas…
waterfox-blocker-filter-lists-window =
    .title = Listas de filtros de bloqueo de anuncios
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Guardar cambios
    .buttonaccesskeyaccept = G
waterfox-blocker-filter-lists-description =
    .value = Elige qué listas de filtros están activas.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } activas de { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Activado
waterfox-blocker-filter-lists-column-name =
    .label = Lista de filtros
waterfox-blocker-filter-lists-column-category =
    .label = Categoría
waterfox-blocker-filter-lists-enable =
    .label = Activar
waterfox-blocker-filter-lists-disable =
    .label = Desactivar
waterfox-blocker-extension-detected = Waterfox ahora incluye bloqueo de anuncios integrado. Puedes revisar tu configuración en los ajustes.
waterfox-blocker-extension-detected-learn-more =
    .label = Más información
waterfox-blocker-extension-detected-dismiss =
    .label = No volver a mostrar
waterfox-blocker-extension-install-warning = Waterfox ya incluye un bloqueador de anuncios integrado. Usar dos bloqueadores de anuncios puede hacer que algunas páginas fallen o se carguen lentamente.
waterfox-blocker-extension-install-got-it =
    .label = Entendido
waterfox-blocker-extension-install-learn-more =
    .label = Más información
waterfox-blocker-third-party-notice-description = { $extensionName } también está bloqueando anuncios. Usar dos bloqueadores de anuncios puede causar problemas.
waterfox-blocker-toolbar-button =
    .label = Bloqueo de anuncios
    .tooltiptext = Bloqueo de anuncios
waterfox-blocker-panel-not-available = No disponible en esta página
waterfox-blocker-panel-toggle =
    .label = Bloqueo de anuncios en este sitio
    .description = Bloquea los anuncios y los rastreadores en este sitio.
waterfox-blocker-panel-disabled = El bloqueo de anuncios está desactivado
waterfox-blocker-panel-site-excepted = Anuncios permitidos en este sitio
waterfox-blocker-stats =
    { $count ->
        [one] { $count } anuncio bloqueado en este sitio
       *[other] { $count } anuncios bloqueados en este sitio
    }
waterfox-blocker-panel-settings-button = Configuración del bloqueo de anuncios
waterfox-blocker-show-badge-pref =
    .label = Mostrar el número de elementos bloqueados en el botón de la barra de herramientas
waterfox-blocker-filter-lists-category-core = Predeterminado
waterfox-blocker-filter-lists-category-privacy = Privacidad
waterfox-blocker-filter-lists-category-annoyances = Molestias
waterfox-blocker-filter-lists-category-optional = Opcional
waterfox-blocker-filter-lists-category-regional = Regional
waterfox-blocker-filter-lists-search =
    .placeholder = Buscar listas de filtros…
waterfox-blocker-filter-lists-empty-state = No hay listas de filtros disponibles.
waterfox-blocker-filter-lists-refresh-now =
    .label = Actualizar ahora
waterfox-blocker-filter-lists-last-updated = Actualizado { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Aún no se ha actualizado
waterfox-blocker-custom-filter-lists-window =
    .title = Listas de filtros personalizadas
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Guardar cambios
    .buttonaccesskeyaccept = G
waterfox-blocker-custom-filter-lists-description = Añade las URL de las listas de filtros personalizadas. Las listas se descargarán y aplicarán junto con los filtros integrados.
waterfox-blocker-filter-lists-custom-heading =
    .value = Listas de filtros personalizadas
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Introduce la URL de la lista de filtros…
waterfox-blocker-filter-lists-custom-url-label =
    .value = URL de la lista de filtros
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Añadir
waterfox-blocker-filter-lists-custom-remove =
    .label = Eliminar
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Eliminar todo
waterfox-blocker-filter-lists-custom-empty =
    .value = No se ha añadido ninguna lista de filtros personalizada.
waterfox-blocker-extension-fallback-name-this = esta extensión
waterfox-blocker-extension-fallback-name-your = tu extensión
waterfox-blocker-spotlight-title = Waterfox ahora incluye bloqueo de anuncios
waterfox-blocker-spotlight-subtitle = Hemos detectado que tienes { $extensionName } instalada. Waterfox ahora incluye su propio bloqueador de anuncios. Usarlo ayuda a apoyar Waterfox, pero la decisión es tuya.
waterfox-blocker-spotlight-primary-button = Mantener mi configuración actual
waterfox-blocker-spotlight-secondary-button = Revisar la configuración
waterfox-blocker-prompt-title = Bloqueo de anuncios de Waterfox
waterfox-blocker-reenable-conflict-message = Usar el bloqueador de anuncios de Waterfox junto con «{ $extensionName }» puede hacer que algunas páginas no funcionen correctamente. ¿Cuál quieres mantener?
waterfox-blocker-reenable-use-built-in = Usar el bloqueador integrado
waterfox-blocker-reenable-keep-extension = Mantener el bloqueador de la extensión
waterfox-blocker-extension-install-manage-settings = Puedes gestionar el bloqueo de anuncios en Ajustes > Privacidad y seguridad.
waterfox-blocker-extension-install-anyway = Instalar de todos modos
waterfox-blocker-extension-install-keep-built-in = Seguir usando el bloqueador integrado
waterfox-blocked-page-title = Waterfox ha bloqueado esta página
waterfox-blocked-page-heading = Waterfox ha bloqueado esta página
waterfox-blocked-page-description = Esta página fue bloqueada por una regla de filtrado de bloqueo de anuncios.
waterfox-blocked-page-details =
    .aria-label = Detalles de la página bloqueada
waterfox-blocked-page-blocked-url-label = URL bloqueada
waterfox-blocked-page-matched-rule-label = Regla coincidente
waterfox-blocked-page-unavailable = No disponible
waterfox-blocked-page-hint = «Cargar de todos modos» permitirá temporalmente este sitio durante el resto de tu sesión.
waterfox-blocked-page-go-back = Volver
waterfox-blocked-page-load-anyway = Cargar de todos modos
waterfox-blocker-setting-on-summary = Bloquea anuncios y rastreadores con un impacto mínimo en la carga de las páginas.
waterfox-blocker-blocks-ads = Anuncios y solicitudes de redes publicitarias
waterfox-blocker-blocks-tracking = Scripts y píxeles de rastreo
waterfox-blocker-blocks-annoyances = Ventanas emergentes y superposiciones molestas (con las listas de molestias activadas)
waterfox-blocker-partner-funding-title = Apoya el desarrollo de Waterfox
waterfox-blocker-partner-funding-description = Waterfox es gratuito, de código abierto e independiente. Permitir anuncios en las páginas de los socios de búsqueda es la forma en que Waterfox financia su desarrollo e infraestructura. Puedes desactivar esta opción en cualquier momento, pero mantenerla activada es la manera más sencilla de apoyar el proyecto.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Excepciones para el bloqueo de anuncios
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Puedes especificar en qué sitios web estará desactivado el bloqueo de anuncios. Escribe la dirección exacta del sitio que quieres gestionar y luego haz clic en «Añadir excepción».
waterfox-blocker-filter-lists-next-refresh =
    .value = Próxima actualización: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Próxima actualización: desconocida
waterfox-blocker-custom-filters =
    .label = Mis filtros…
waterfox-blocker-custom-filters-window =
    .title = Mis filtros
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Guardar cambios
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = Añade tus propias reglas de bloqueo de anuncios. Estas usan la sintaxis estándar de filtros de uBlock Origin y se aplican junto con tus listas de filtros activadas.
waterfox-blocker-custom-filters-empty =
    .value = Sin filtros personalizados.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Sin filtros personalizados.
        [one] 1 filtro personalizado.
       *[other] { $count } filtros personalizados.
    }
waterfox-blocker-custom-filters-status-unsaved = Cambios sin guardar.
waterfox-blocker-custom-filters-import =
    .label = Importar…
waterfox-blocker-custom-filters-export =
    .label = Exportar…
waterfox-blocker-custom-filters-load-error-title = Error al cargar
waterfox-blocker-custom-filters-load-error = No se pudieron cargar los filtros personalizados.
waterfox-blocker-custom-filters-save-error-title = Error al guardar
waterfox-blocker-custom-filters-save-error = No se pudieron guardar los filtros personalizados.
waterfox-blocker-custom-filters-import-error-title = Error al importar
waterfox-blocker-custom-filters-import-error = El archivo seleccionado no se pudo importar.
waterfox-blocker-custom-filters-export-error-title = Error al exportar
waterfox-blocker-custom-filters-export-error = No se pudieron exportar los filtros personalizados.
waterfox-blocker-custom-filters-import-picker-title = Importar filtros personalizados
waterfox-blocker-custom-filters-export-picker-title = Exportar filtros personalizados
waterfox-blocker-custom-filters-import-replace-title = ¿Reemplazar los filtros actuales?
waterfox-blocker-custom-filters-import-replace-message = Importar reemplazará todo lo que hay actualmente en el editor.
waterfox-data-collection-header = { -brand-short-name } Recopilación y uso de datos
    .searchkeywords = privacidad telemetría recopilación de datos aviso de privacidad
waterfox-data-collection-description = { -brand-short-name } no recopila datos de telemetría ni de uso. Los servicios opcionales, como Sync, pueden regirse por sus propios avisos de privacidad. El <a data-l10n-name="privacy-notice">Aviso de privacidad</a> se proporciona aquí para una consulta rápida.
