restart-prompt-title = Reiniciar { -brand-short-name }
restart-prompt-question = ¿Está seguro que desea reiniciar { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Reiniciar
copy-url =
    .label = Copiar enlace pestaña
copy-all-urls =
    .label = Copiar todos los enlaces a la pestaña
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Abrir todo en Pestañas Privadas
open-all-links-private =
    .label = Abrir todos los enlaces en pestañas privadas
open-private-tab =
    .label = Abrir en una nueva pestaña privada
new-private-tab =
    .label = Nueva pestaña privada
    .tooltiptext = Abrir una nueva pestaña privada
open-link-private =
    .label = Abrir enlace en nueva pestaña privada
status-bar =
    .label = Barra de estado
tab-position-header = Posición de la barra de pestaña
tab-bar-top-above =
    .label = Barra de direcciones superior
tab-bar-top-below =
    .label = Barra de direcciones superior
tab-bar-bottom-above =
    .label = Abajo de la barra de estado
tab-bar-bottom-below =
    .label = Abajo de la barra de estado
tab-additional-header = Preferencias adicionales de Tab
pinned-icon-only =
    .label = Contraer pestañas fijadas para mostrar sólo el icono del sitio
insert-after-current =
    .label = Insertar nueva pestaña después de la pestaña actual
insert-related-after-current =
    .label = Insertar nueva pestaña relacionada después de la pestaña actual
dynamic-theme-header = Temas Dinámicos
dynamic-theme-dark =
    .label = Forzar Modo Oscuro
dynamic-theme-light =
    .label = Forzar Modo Luz
dynamic-theme-auto =
    .label = Definir dinámicamente el modo Luz/Oscuro
restart-header = Reiniciar elemento de menú
restart-show-button =
    .label = Mostrar botón de reiniciar en PanelUI
restart-purge-cache =
    .label = Borrar caché de reinicio rápido al reiniciar el navegador
restart-require-confirmation =
    .label = Requiere confirmación de reinicio
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Mostrar elemento del menú de la pestaña de copia
enable-copy-active-tab =
    .label = Copiar URL sólo desde la pestaña activa
show-copy-all-urls =
    .label = Mostrar copia de todas las urls de la pestaña
show-unload-tab =
    .label = Mostrar elemento de menú de pestaña de descarga
statusbar-enabled =
    .label = Mostrar barra de estado
statusbar-show-links =
    .label = Mostrar enlaces
statusbar-contrast-text =
    .label = Color de texto de la barra de estado contrastar
bookmarks-bar-position-header = Posición de la barra de marcadores
bookmarks-position-top =
    .label = Subir
bookmarks-position-bottom =
    .label = Abajo
geolocation-api-header = API de geolocalización
geolocation-description = Algunos sitios web requieren su ubicación para funcionar. Si un sitio web no funciona debido a que no puede encontrar su ubicación, por favor habilite esta preferencia y vuelva a intentarlo.
geolocation-api-enabled =
    .label = Activar
geolocation-api-disabled =
    .label = Desactivar
send-referrer-header-0 =
    .label = Nunca enviar la cabecera del remitente
send-referrer-header-1 =
    .label = Enviar la cabecera del remitente sólo cuando haga clic en enlaces y elementos similares
send-referrer-header-2 =
    .label = Enviar la cabecera del remitente a todas las peticiones (por defecto)
enable-webrtc-p2p =
    .label = Habilitar la conexión entre pares WebRTC
load-images =
    .label = Cargar imágenes automáticamente
enable-javascript =
    .label = Activar JavaScript
webrtc-header = Conexión con pares WebRTC
ref-header = Encabezado de HTTP
statusbar-header = Barra de estado
private-tab =
    .label =
        { $isPrivate ->
            [true] Salir de la pestaña privada
           *[false] Hacer pestaña privada
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
auto-hide-back =
    .label = Auto Hide Back Button
hide-tab-icons =
    .label = Hide Tab Icons
auto-hide-pageaction =
    .label = Auto Hide Page Action
center-navbar-text =
    .label = Center Nav Bar Text
center-tab-content =
    .label = Center Tab Content
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
drag-space =
    .label = Enable Fixed Drag Space
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
font-header = Fonts
tab-context-line =
    .label = Tab Context Line
panels-header = Panels
icons-header = Icons
onboarding-grassroots-title = Supporting the grassroots
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
show-mac-menu-icons =
    .label = Show Mac Menu Icons
square-button-edges =
    .label = Square Button Corners
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
disable-sidebar-animate =
    .label = Disable sidebar panel animation
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
enable-menu-transparency =
    .label = Enable menu transparency
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = Media Player
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
