# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Dynamische Themes
dynamic-theme-dark =
    .label = Dunklen Modus erzwingen
dynamic-theme-light =
    .label = Hellen Modus erzwingen
dynamic-theme-auto =
    .label = Hellen/Dunklen Modus dynamisch einstellen
pane-theme-title = Aussehen
animation-header = Animationen
appearance-header = Erscheinungsbild
bookmark-header = Lesezeichenleiste
category-theme =
    .tooltiptext = { pane-theme-title }
media-player-header = Medienwiedergabe
nav-bar-header = Navigationsleiste
tab-bar-header = Tableiste
theme-header = Theme
enable-waterfox-theme-0 =
    .label = Waterfox-Theme-Anpassungen für alle Themes aktivieren
enable-waterfox-theme-1 =
    .label = Waterfox-Theme-Anpassungen für alle Waterfox-Themes aktivieren
enable-waterfox-theme-2 =
    .label = Waterfox-Theme-Anpassungen deaktivieren
monospace-font-theme =
    .label = Feste Schriftbreite für Theme aktivieren
sidebar-header = Seitenleiste
preset-title = Voreinstellungen
full-screen-header = Vollbild
icons-header = Symbole
hide-all-icons =
    .label = Alle Symbole ausblenden
hide-bookmarkbar-icon =
    .label = Lesezeichenleisten-Symbole ausblenden
hide-tab-icons =
    .label = Tab-Symbole ausblenden
hide-urlbar-iconbox =
    .label = URL-Leisten-Symbolfeld ausblenden
show-mac-menu-icons =
    .label = Mac-Menü-Symbole anzeigen
show-menu-icons =
    .label = Menüsymbole anzeigen
autohide-hidden-header = Automatisch ausblenden & Ausgeblendet
auto-hide-back =
    .label = Schaltfläche „Zurück“ automatisch ausblenden
auto-hide-bookmarkbar =
    .label = Lesezeichenleiste automatisch ausblenden
auto-hide-forward =
    .label = Schaltfläche „Weiter“ automatisch ausblenden
auto-hide-navbar =
    .label = Navigationsleiste automatisch ausblenden
auto-hide-pageaction =
    .label = Seitenaktion automatisch ausblenden
auto-hide-sidebar =
    .label = Seitenleiste automatisch ausblenden
auto-hide-tabbar =
    .label = Tableiste automatisch ausblenden
auto-hide-tabs =
    .label = Tabs automatisch ausblenden
hide-bookmarkbar-label =
    .label = Beschriftungen der Lesezeichenleiste ausblenden
hide-disabled-menuitems =
    .label = Deaktivierte Menüelemente ausblenden
hide-sidebar-header =
    .label = Seitenleistenkopf ausblenden
monospace-font =
    .label = Feste Schriftbreite für Seite aktivieren
font-header = Schriftarten
lepton-style =
    .label = Lepton-Stil
proton-style =
    .label = Proton-Stil
waterfox-defaults =
    .label = Waterfox-Standardeinstellungen
center-header = Zentrieren
rounding-header = Rundung
center-tab-content =
    .label = Tab-Inhalt zentrieren
center-tab-label =
    .label = Nur Tab-Beschriftung zentrieren
center-navbar-text =
    .label = Text der Navigationsleiste zentrieren
auto-blur-tabs =
    .label = Tabs automatisch verschleiern
close-button-hover =
    .label = Schließen-Schaltfläche beim Bewegen des Mauszeigers über den ausgewählten Tab anzeigen, wenn viele Tabs geöffnet sind
enable-default-accent-color =
    .label = Standard-Akzentfarbe
enable-system-accent-color =
    .label = System-Akzentfarbe
enable-cyan-accent-color =
    .label = Cyan als Akzentfarbe
enable-menu-transparency =
    .label = Menütransparenz aktivieren
enable-panel-transparency =
    .label = Panel-Transparenz aktivieren
square-menu-popup =
    .label = Eckiges Kontextmenü-Panel
square-menu-panel =
    .label = Eckiges Anwendungsmenü-Panel
square-menu-item =
    .label = Eckige Kontextmenü-Einträge
square-field =
    .label = Eckige Eingabefelder
square-button-edges =
    .label = Eckige Schaltflächen
square-panel-item =
    .label = Eckige Anwendungsmenü-Einträge
square-tab-edges =
    .label = Eckige Tabs
square-checkbox =
    .label = Eckige Kontrollkästchen
tab-context-line =
    .label = Tab-Kontextzeile
remove-panel-strip =
    .label = Farbige Trennlinie im Anwendungsmenü entfernen
panels-header = Panels
compact-bookmark-menu =
    .label = Abstand im Lesezeichen-Menü verringern
compact-context-menu =
    .label = Abstand im Kontextmenü verringern
compact-navbar-popup =
    .label = Abstand der Pop-ups in der Navigationsleiste verringern
compact-panel-header =
    .label = Abstand der Panel-Kopfzeilen verringern
disable-panel-animate =
    .label = Animation des Anwendungsmenü-Panels deaktivieren
disable-sidebar-animate =
    .label = Animation des Seitenleisten-Panels deaktivieren
drag-space =
    .label = Festen Ziehenbereich aktivieren
full-panel-strip =
    .label = Anwendungsmenü-Trennlinie in voller Breite
interface-component-header = Komponenten
waterfox-appearance-statusbar-heading =
    .label = Statusleiste
waterfox-appearance-statusbar-enabled-toggle =
    .label = Statusleiste anzeigen
    .description = Zeigt eine Symbolleiste am unteren Fensterrand an.
waterfox-appearance-statusbar-links-toggle =
    .label = Linkziele in der Statusleiste anzeigen
waterfox-appearance-theme-mode-picker =
    .label = Theme-Modus
waterfox-appearance-theme-mode-option-system =
    .label = System
waterfox-appearance-theme-mode-option-light =
    .label = Hell
waterfox-appearance-theme-mode-option-dark =
    .label = Dunkel
waterfox-appearance-theme-color-picker =
    .label = Theme-Farbe
waterfox-appearance-theme-color-option-default =
    .label = Standard
waterfox-appearance-theme-color-option-smoke =
    .label = Smoke
waterfox-appearance-theme-color-option-ash =
    .label = Ash
waterfox-appearance-theme-color-option-sun =
    .label = Sun
waterfox-appearance-theme-color-option-spark =
    .label = Spark
waterfox-appearance-theme-color-option-flame =
    .label = Flame
waterfox-appearance-theme-color-option-flare =
    .label = Flare
waterfox-appearance-theme-color-option-lavender =
    .label = Lavender
waterfox-appearance-theme-color-option-dusk =
    .label = Dusk
waterfox-appearance-theme-color-option-lagoon =
    .label = Lagoon
waterfox-appearance-theme-color-option-tide =
    .label = Tide
waterfox-appearance-theme-color-option-pine =
    .label = Pine
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = Der typische Waterfox-Look für die Standard-Browseroberfläche.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = Modernes Design der Standard-Browseroberfläche.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = Klassisches Waterfox-Design mit verfeinerter Oberfläche.
waterfox-appearance-browser-style-group =
    .label = Browser-Stil
    .description = Wählen Sie den allgemeinen Waterfox-Look.
waterfox-appearance-theme-colors-group =
    .label = Farbpalette
    .description = Wählen Sie die Waterfox-Farbpalette aus und legen Sie fest, ob sie dem System-Theme folgen soll.
waterfox-appearance-details-group =
    .label = Weitere Optionen für das Erscheinungsbild
    .description = Feinabstimmung der Waterfox-Benutzeroberfläche.
waterfox-appearance-transparent-toggle =
    .label = Transparente Panels und Menüs
waterfox-appearance-autohide-tabbar-toggle =
    .label = Die Tableiste ausblenden, bis der Mauszeiger darauf zeigt
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Die Lesezeichen-Symbolleiste ausblenden, bis der Mauszeiger darauf zeigt
waterfox-appearance-autohide-sidebar-toggle =
    .label = Die Seitenleiste ausblenden, bis der Mauszeiger darauf zeigt
waterfox-appearance-autohide-navigation-toggle =
    .label = Die Zurück- und Weiter-Schaltflächen ausblenden, wenn sie keine Funktion haben
waterfox-appearance-close-button-hover-toggle =
    .label = Die Schaltfläche zum Schließen des Tabs nur beim Überfahren mit der Maus anzeigen
waterfox-appearance-drag-space-toggle =
    .label = Oberhalb der Tabs Platz zum Ziehen lassen
waterfox-density-group =
    .label = Dichte
    .description = Wie viel Platz den Symbolleisten und Menüs zur Verfügung steht.
waterfox-density-compact =
    .label = Kompakt
waterfox-density-normal =
    .label = Normal
waterfox-density-touch =
    .label = Berührung
waterfox-appearance-chrome-sheet-off =
    .label = Aus
waterfox-appearance-chrome-sheet-all-themes =
    .label = Alle Themes
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = Integrierte Themes
waterfox-appearance-interface-customizations-group =
    .label = Anpassungen der Benutzeroberfläche
    .description = Zusätzliche Steuerelemente für Tabs, Symbolleisten, Symbole und Inhalte.
waterfox-appearance-chrome-sheet =
    .label = Anpassungen der Benutzeroberfläche laden
    .description = Deaktivieren Sie diese Option, um das Stylesheet der Benutzeroberfläche von Waterfox zu deaktivieren und die damit gesteuerten Optionen auszublenden.
waterfox-opt-tabbar-heading =
    .label = Tableiste
    .description = Größe, Abstand und Sichtbarkeit des Streifens, in dem sich Ihre Tabs befinden.
waterfox-opt-tabbar-fill-width =
    .label = Tabs dehnen, um die Breite auszufüllen
waterfox-opt-tabbar-as-titlebar =
    .label = Nur den aktuellen Tab in der Titelleiste anzeigen
waterfox-opt-hidden-tabbar =
    .label = Die Tableiste ausblenden
waterfox-opt-hidden-titlebar-container =
    .label = Den Container der Titelleiste ausblenden
waterfox-opt-autohide-tab =
    .label = Hintergrundtabs verkleinern, bis Sie mit der Maus darauf zeigen
waterfox-opt-autohide-tab-opacity =
    .label = Diese ebenfalls ausblenden
waterfox-opt-autohide-tab-blur =
    .label = Diese ebenfalls verwischen
waterfox-opt-padding-tabbar-width =
    .label = Die Tableiste verkleinern
waterfox-opt-padding-tabbar-height =
    .label = Die Tableiste verkürzen
waterfox-opt-padding-first-tab =
    .label = Vor dem ersten Tab einen Abstand lassen
waterfox-opt-padding-first-tab-always =
    .label = Den Abstand auch bei maximierter Ansicht beibehalten
waterfox-opt-padding-drag-space =
    .label = Über den Tabs einen Bereich zum Ziehen freihalten
waterfox-opt-padding-drag-space-maximized =
    .label = Auch im maximierten Modus beibehalten
waterfox-opt-centered-tab =
    .label = Inhalt des Tabs zentrieren
waterfox-opt-centered-tab-label =
    .label = Nur die Beschriftung zentrieren
waterfox-opt-counter-tab =
    .label = Anzahl der Tabs anzeigen
waterfox-opt-tabs-heading =
    .label = Tabs
    .description = Die Form eines Tabs und was er anzeigt.
waterfox-opt-tab-connect-to-window =
    .label = Den ausgewählten Tab zur Symbolleiste unten hinzufügen
waterfox-opt-tab-color-like-toolbar =
    .label = Den ausgewählten Tab wie die Symbolleiste einfärben
waterfox-opt-tab-box-shadow =
    .label = Unter dem ausgewählten Tab einen Schatten erzeugen
waterfox-opt-tab-selected-bold =
    .label = Die Bezeichnung des ausgewählten Tabs fett formatieren
waterfox-opt-tab-blue-accent =
    .label = Einen blauen Akzent auf dem ausgewählten Tab verwenden
waterfox-opt-tab-contextline-blue-accent =
    .label = Einen blauen Akzent auf der Kontextzeile verwenden
waterfox-opt-tab-bottom-rounded-corner =
    .label = Die unteren Ecken des ausgewählten Tabs abrunden
waterfox-opt-tab-bottom-rounded-corner-all =
    .label = Abgerundete Ecken auf alle Tabs anwenden
waterfox-opt-tab-multi-selected =
    .label = Mehrfach ausgewählte Tabs stärker hervorheben
waterfox-opt-tab-letters-cleary =
    .label = Beschriftungen auf schmalen Tabs gut lesbar halten
waterfox-opt-hidden-tab-icon =
    .label = Tab-Symbole ausblenden
waterfox-opt-hidden-tab-icon-always =
    .label = Auch auf angehefteten Tabs ausblenden
waterfox-opt-tab-close-button-at-hover =
    .label = Die Schaltfläche „Schließen“ erst anzeigen, wenn der Mauszeiger darüber fährt
waterfox-opt-tab-close-button-at-hover-always =
    .label = Aktion unabhängig von der Anzahl der geöffneten Tabs ausführen
waterfox-opt-tab-close-button-at-hover-with-selected =
    .label = Den ausgewählten Tab einschließen
waterfox-opt-tab-close-button-at-pinned =
    .label = Schaltfläche „Schließen“ bei angehefteten Tabs anzeigen
waterfox-opt-tab-close-button-at-pinned-always =
    .label = Anzeigen, ohne mit der Maus darüberzufahren
waterfox-opt-tab-close-button-at-pinned-background =
    .label = Einen Hintergrund hinzufügen
waterfox-opt-tab-container =
    .label = Tabs der Container mit ihrer jeweiligen Farbe markieren
waterfox-opt-tab-container-on-top =
    .label = Markierung über den Tab setzen
waterfox-opt-tab-container-always-long =
    .label = Über die gesamte Breite des Tabs ausführen
waterfox-opt-tab-sound-with-favicons =
    .label = Die Soundanzeige über dem Tab-Symbol anzeigen
waterfox-opt-tab-sound-with-favicons-on-center =
    .label = Auf dem Symbol zentrieren
waterfox-opt-tab-unloaded =
    .label = Nicht geladene Tabs ausblenden
waterfox-opt-tab-padding-default =
    .label = Standard
waterfox-opt-tab-corner-style-default =
    .label = Standard
waterfox-opt-tab-newtab-button-default =
    .label = Standard
waterfox-opt-tab-newtab-button-smaller =
    .label = Kleiner
waterfox-opt-tab-contextline-none =
    .label = Keine
waterfox-opt-tab-separator-none =
    .label = Keinen
waterfox-opt-tab-padding-lepton =
    .label = Geräumig
waterfox-opt-tab-padding-photon =
    .label = Kompakt
waterfox-opt-tab-separator =
    .label = Trennlinie zwischen Tabs
waterfox-opt-tab-separator-dynamic =
    .label = Nur zwischen nicht ausgewählten Tabs
waterfox-opt-tab-separator-static =
    .label = Zwischen jedem Tab
waterfox-opt-tab-separator-bar =
    .label = Eine Leiste in voller Höhe
waterfox-opt-tab-newtab-button =
    .label = Schaltfläche „Neuer Tab“
waterfox-opt-tab-newtab-button-like-tab =
    .label = Hat die Form eines Tabs
waterfox-opt-tab-newtab-button-proton =
    .label = Proton
waterfox-opt-tab-corner-style-australis =
    .label = Australis
waterfox-opt-tab-corner-style-chrome =
    .label = Chrome
waterfox-opt-tab-corner-style-chrome-legacy =
    .label = Chrome (alte Version)
waterfox-opt-tab-corner-style-edge =
    .label = Edge
waterfox-opt-tab-corner-style-wave =
    .label = Welle
waterfox-opt-tab-contextline-photon =
    .label = Linie über dem Tab
waterfox-opt-tab-contextline-supernova =
    .label = Linie unter dem Tab
waterfox-opt-tab-corner-style =
    .label = Form der unteren Ecke
waterfox-opt-tab-contextline =
    .label = Anzeige des ausgewählten Tabs
waterfox-opt-tab-crashed =
    .label = Auf abgestürzten Tabs nur die Absturzanzeige anzeigen
waterfox-opt-tab-pip =
    .label = Tabs markieren, auf denen Bild-in-Bild wiedergegeben wird
waterfox-opt-tab-padding =
    .label = Tab-Abstand
waterfox-opt-tab-static-separator-selected-accent =
    .label = Trennlinie neben dem ausgewählten Tab hervorheben
waterfox-opt-toolbars-heading =
    .label = Symbolleisten
    .description = Navigationsschaltflächen, Abstände in der Symbolleiste und was sich ausblendet.
waterfox-opt-hidden-navbar =
    .label = Navigationsleiste ausblenden
waterfox-opt-autohide-navbar =
    .label = Ausblenden, bis Sie mit dem Mauszeiger darauf zeigen
waterfox-opt-autohide-back-button =
    .label = Die Schaltfläche „Zurück“ ausblenden, wenn sie keine Funktion hat
waterfox-opt-autohide-forward-button =
    .label = Die Schaltfläche „Weiter“ ausblenden, wenn sie keine Funktion hat
waterfox-opt-combined-nav-button =
    .label = Die Navigationsschaltflächen gruppieren
waterfox-opt-combined-nav-button-home-button =
    .label = Die Taste „Pos 1“ einbeziehen
waterfox-opt-padding-toolbar-button =
    .label = Abstand zwischen den Schaltflächen in der Symbolleiste verringern
waterfox-opt-padding-toolbar-button-compact =
    .label = Noch mehr verringern
waterfox-opt-autohide-toolbar-overlap =
    .label = Automatisch ausgeblendete Symbolleisten sollen die Seite überlappen
waterfox-opt-autohide-infobar =
    .label = Benachrichtigungsleisten ausblenden, bis Sie mit dem Mauszeiger darauf zeigen
waterfox-opt-padding-infobar =
    .label = Abstand der Benachrichtigungsleiste verringern
waterfox-opt-findbar-floating-on-top =
    .label = Die Suchleiste über der Seite anzeigen
waterfox-opt-padding-global-menubar =
    .label = Die Menüleiste verkleinern
waterfox-opt-centered-urlbar =
    .label = Den Text in der Adressleiste zentrieren
waterfox-opt-autohide-fill-urlbar =
    .label = Die Symbolleiste mit der Adressleiste ausfüllen, bis Sie mit dem Mauszeiger darauf zeigen
waterfox-opt-autohide-page-action =
    .label = Die Aktionsschaltflächen der Seite ausblenden, bis Sie mit dem Mauszeiger darauf zeigen
waterfox-opt-urlbar-always-show-page-actions =
    .label = Aktionsschaltflächen der Seite immer anzeigen
waterfox-opt-hidden-urlbar-iconbox =
    .label = Das Feld „Website-Identität“ ausblenden
waterfox-opt-hidden-urlbar-iconbox-label-only =
    .label = Nur die Beschriftung ausblenden
waterfox-opt-urlbar-iconbox-with-separator =
    .label = Das Identitätsfeld durch eine Linie abtrennen
waterfox-opt-urlview-focus-item-border =
    .label = Das angestrebte Ergebnis skizzieren
waterfox-opt-padding-urlview-result =
    .label = Ergebniszeilen verkleinern
waterfox-opt-padding-bookmarkbar =
    .label = Die Lesezeichen-Symbolleiste verkleinern
waterfox-opt-hidden-bookmarkbar-icon =
    .label = Lesezeichen-Symbole ausblenden
waterfox-opt-padding-bookmark-menu =
    .label = Das Lesezeichen-Menü verkleinern
waterfox-opt-padding-bookmark-menu-compact =
    .label = Noch mehr verringern
waterfox-opt-counter-bookmark-menu =
    .label = Anzahl der Lesezeichen im Lesezeichenmenü anzeigen
waterfox-opt-hidden-bookmarkbar-label =
    .label = Lesezeichenbeschriftungen ausblenden
waterfox-opt-rounding-square-urlview-item =
    .label = Ergebnisecken rechtwinklig machen
waterfox-opt-bookmarks-heading =
    .label = Lesezeichen
    .description = Die Lesezeichen-Symbolleiste und das Lesezeichen-Menü.
waterfox-opt-bookmarkbar-multi-row =
    .label = Die Lesezeichen-Symbolleiste über mehrere Zeilen anordnen
waterfox-opt-autohide-bookmarkbar =
    .label = Die Lesezeichen-Symbolleiste ausblenden, bis Sie mit dem Mauszeiger darauf zeigen
waterfox-opt-centered-bookmarkbar =
    .label = Die Lesezeichen-Symbolleiste zentrieren
waterfox-opt-decoration-disable-sidebar-animate =
    .label = Die Animation der Seitenleiste deaktivieren
waterfox-opt-icons-heading =
    .label = Symbole
    .description = Wo Symbole angezeigt werden und wie groß sie sind.
waterfox-opt-icon-disabled =
    .label = Alle Menü- und Panel-Symbole ausblenden
waterfox-opt-icon-menu =
    .label = Symbole in Menüs anzeigen
waterfox-opt-icon-menu-full =
    .label = Bei jedem Menüpunkt anzeigen
waterfox-opt-icon-context-menu =
    .label = Symbole in Kontextmenüs anzeigen
waterfox-opt-icon-global-menu =
    .label = Symbole in den Menüs der Menüleiste anzeigen
waterfox-opt-icon-global-menu-mac =
    .label = Auch unter macOS anzeigen
waterfox-opt-icon-global-menubar =
    .label = Symbole in der Menüleiste anzeigen
waterfox-opt-icon-panel =
    .label = Symbole in den Panels anzeigen
waterfox-opt-icon-library =
    .label = Symbole in der Bibliothek anzeigen
waterfox-opt-icon-1-25px-stroke =
    .label = Dickere Linien für Symbole verwenden
waterfox-opt-icon-account-image-to-right =
    .label = Das Profilbild auf der rechten Seite platzieren
waterfox-opt-icon-account-label-to-right =
    .label = Den Kontonamen auf der rechten Seite platzieren
waterfox-opt-panel-icons =
    .label = App-Menüsymbole
    .description = In wie vielen Zeilen des Hauptmenüs zeigt Waterfox ein Symbol an.
waterfox-opt-panel-icons-photon =
    .label = Nur Hauptelemente
waterfox-opt-panel-icons-full =
    .label = Jeder Eintrag
waterfox-opt-rounding-heading =
    .label = Ecken
    .description = Die abgerundeten Ecken der Benutzeroberfläche in rechtwinklige Ecken umwandeln.
waterfox-opt-rounding-square-tab =
    .label = Eckige Tabs
waterfox-opt-rounding-square-toolbar =
    .label = Eckige Symbolleisten
waterfox-opt-rounding-square-button =
    .label = Eckige Schaltflächen
waterfox-opt-rounding-square-field =
    .label = Eckige Textfelder
waterfox-opt-rounding-square-checklabel =
    .label = Eckige Kontrollkästchen
waterfox-opt-rounding-square-dialog =
    .label = Eckige Dialoge
waterfox-opt-rounding-square-infobox =
    .label = Eckige Benachrichtigungen
waterfox-opt-rounding-square-panel =
    .label = Eckige Panels
waterfox-opt-rounding-square-panelitem =
    .label = Eckige Panel-Elemente
waterfox-opt-rounding-square-menupopup =
    .label = Eckige Menüs
waterfox-opt-rounding-square-menuitem =
    .label = Eckige Menüelemente
waterfox-opt-theme-heading =
    .label = Theme und Effekte
    .description = Farben, Transparenz und Animationen in der gesamten Benutzeroberfläche.
waterfox-opt-theme-proton-color =
    .label = Die Proton-Farbpalette auf integrierten Seiten verwenden
    .description = Gilt für „about:“-Seiten und andere integrierte Ansichten, nicht für den Browser-Rahmen.
waterfox-opt-theme-proton-chrome =
    .label = Auf Dialogfelder und Bibliotheksfenster anwenden
waterfox-opt-theme-fully-color =
    .label = Überall anwenden
waterfox-opt-theme-fully-dark =
    .label = Lichtblitze im Dunkelmodus verhindern
waterfox-opt-theme-built-in-contrast =
    .label = Den Kontrast der integrierten Themes erhöhen
waterfox-opt-theme-system-default =
    .label = Dem System-Theme folgen
waterfox-opt-theme-private =
    .label = Private Fenster einfärben
waterfox-opt-hidden-private-indicator =
    .label = Die Anzeige für den privaten Modus ausblenden
waterfox-opt-theme-transparent-panel =
    .label = Panels transparent machen
waterfox-opt-theme-transparent-frame =
    .label = Den Fensterrahmen transparent machen
waterfox-opt-theme-monospace =
    .label = Eine Schriftart mit fester Zeichenbreite in der Benutzeroberfläche verwenden
waterfox-opt-decoration-animate =
    .label = Änderungen an der Benutzeroberfläche animieren
waterfox-opt-decoration-disable-panel-animate =
    .label = Die Animation des App-Menüs deaktivieren
waterfox-opt-content-heading =
    .label = Webseiten
    .description = Das Styling von Waterfox wird auf Webseiten angewendet.
waterfox-opt-page-monospace =
    .label = Eine Schriftart mit fester Zeichenbreite für integrierte Seiten verwenden
waterfox-opt-page-dark-mode-pdf =
    .label = PDFs bei Verwendung eines dunklen Themes abdunkeln
waterfox-opt-newtab-heading =
    .label = Seite „Neuer Tab“
    .description = Das Erscheinungsbild der Seite, die in einem neuen Tab geöffnet wird.
waterfox-opt-newtab-hidden-logo =
    .label = Das Logo ausblenden
waterfox-opt-newtab-full-icon =
    .label = Die Verknüpfungskacheln mit ihrem Symbol füllen
waterfox-opt-newtab-background-image =
    .label = Ein Hintergrundbild anzeigen
waterfox-opt-newtab-animate =
    .label = Die Kacheln animieren
waterfox-opt-player-heading =
    .label = Videoplayer
    .description = Steuerelemente und Größenanpassung für den integrierten Videoplayer.
waterfox-opt-player-ui =
    .label = Die integrierten Videosteuerelemente neu gestalten
waterfox-opt-player-ui-twoline =
    .label = Die Steuerelemente in zwei Zeilen anordnen
waterfox-opt-player-icon =
    .label = Die Waterfox-Steuersymbole verwenden
waterfox-opt-player-size =
    .label = Steuerelemente vergrößern
waterfox-opt-player-noaudio =
    .label = Die Lautstärkeregelung ausblenden, wenn ein Video keinen Ton hat
waterfox-opt-player-click-to-play =
    .label = Gestaltung der Einblendung zum Abspielen per Klick
    .description = Fügt der vorhandenen Einblendung einen Schwebestil und einen Zeiger-Cursor hinzu.
waterfox-opt-player-animate =
    .label = Die Steuerelemente animieren
