# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-page-title = Live-Lesezeichen
feeds-page-description = RSS- und Atom-Feeds mit Live-Lesezeichen abonnieren.
feeds-private-notice = Das Abonnieren, Entfernen, Neuladen und das Ändern von gelesenen oder gespeicherten Artikeln ist im privaten Modus deaktiviert.
feeds-subscribe-heading = Einen Feed abonnieren
feeds-url-label = Feed-URL
feeds-title-label = Titel (optional)
feeds-subscribe-note = Abonnements werden auf diesem Gerät im Lesezeichen-Menü separat von der Synchronisierung gespeichert. Die Feeds werden im Hintergrund aktualisiert, ohne dass Cookies oder Anmeldedaten an den Feed-Server gesendet werden.
feeds-subscribe-button = Abonnieren
    .label = Abonnieren
    .accesskey = A
feeds-subscribe-title =
    .value = Name
    .accesskey = N
feeds-subscribe-url =
    .value = Feed-URL
    .accesskey = U
feeds-subscribe-folder =
    .value = Speichern in
    .accesskey = i
feeds-subscribe-choose-folder =
    .label = Anderen Ordner auswählen…
feeds-subscribe-untitled-folder =
    .label = Unbenannter Ordner
feeds-subscribe-cancel =
    .label = Abbrechen
    .accesskey = b
feeds-subscribe-private = Feed-Abonnements können in einem privaten Fenster oder Tab nicht geändert werden.
feeds-subscribe-busy = Wird abonniert… Das Schließen dieses Fensters führt nicht zur Kündigung des Abonnements.
feeds-subscribe-invalid-url = Geben Sie eine HTTP- oder HTTPS-Feed-URL ohne Benutzernamen oder Passwort ein, die maximal 4096 Zeichen lang ist.
feeds-subscribe-invalid-title = Der Name darf maximal 1024 Zeichen lang sein.
feeds-subscribe-folder-error = Wählen Sie einen vorhandenen Lesezeichenordner aus und versuchen Sie es erneut.
feeds-subscribe-error = Dieser Feed konnte nicht abonniert werden. Überprüfen Sie die Feed-URL und den Zielordner und versuchen Sie es dann erneut.
feeds-subscribe-setup-error = Das Abonnement-Panel konnte nicht geladen werden. Schließen Sie es und versuchen Sie es erneut.
feeds-subscriptions-heading = Abonnements
feeds-import-button = OPML importieren…
feeds-export-button = OPML exportieren…
feeds-empty = Es gibt noch keine Feed-Abonnements.
feeds-preview-button = Vorschau
    .aria-label = Vorschau{ $title }
feeds-reload-button = Neu laden
    .aria-label = Neu laden{ $title }
feeds-remove-button = Entfernen
    .aria-label = Entfernen{ $title }
feeds-preview-heading = Feed-Vorschau
feeds-opml-file-filter = OPML-Dateien
feeds-export-filename = feeds.opml
feeds-import-picker-title = Feed-Abonnements importieren
feeds-export-picker-title = Feed-Abonnements exportieren
feeds-status-loading = Abonnements werden geladen…
feeds-status-working = Wird bearbeitet…
feeds-status-ready = Abonnements wurden geladen.
feeds-status-subscribed = Feed abonniert.
feeds-preview-note = Es werden nur zwischengespeicherte Titel und Links angezeigt, maximal 200 Einträge. Artikel-Links werden in einem neuen Tab geöffnet.
feeds-preview-empty = Es sind keine Artikel im Cache gespeichert. Laden Sie das Abonnement in einem nicht privaten Fenster neu, um nach neuen Artikeln zu suchen.
feeds-item-untitled = Unbenannter Eintrag
feeds-status-removed = Abonnement gekündigt.
feeds-status-reloaded = Feed wurde neu geladen.
feeds-status-preview = Gespeicherte Feed-Inhalte werden angezeigt.
feeds-status-canceled = Vorgang abgebrochen.
feeds-status-exported = Abonnements exportiert.
feeds-status-imported =
    { $count ->
        [one] Ein Abonnement wurde importiert.
       *[other] { $count } Abonnements wurden importiert.
    }
feeds-error-unavailable = Die Feed-Verwaltung ist auf dieser Seite nicht verfügbar. Öffnen Sie „about:feeds“ in einem neuen Tab.
feeds-error-private = Öffnen Sie diese Seite in einem nicht privaten Fenster, um Abonnements zu ändern oder Feeds neu zu laden.
feeds-error-invalid-request = Die Feed-Anfrage war ungültig.
feeds-error-invalid-url = Geben Sie eine gültige HTTP- oder HTTPS-Feed-URL ohne Benutzernamen oder Passwort ein.
feeds-error-busy = Derzeit läuft ein weiterer Feed-Vorgang. Versuchen Sie es erneut, sobald dieser abgeschlossen ist.
feeds-error-not-found = Dieses Abonnement existiert nicht mehr.
feeds-error-operation = Der Feed-Vorgang konnte nicht abgeschlossen werden. Überprüfen Sie die Feed-Adresse und die Verbindung. Ein Ordner mit gespeicherten Lesezeichen kann hier nicht entfernt werden.
feeds-error-not-active = Wählen Sie diesen Tab aus, bevor Sie die Dateiauswahl öffnen.
feeds-error-invalid-opml = Wählen Sie eine gültige UTF-8-OPML-Datei ohne DTD- oder Entitätsdeklarationen aus.
feeds-error-file-too-large = Wählen Sie eine OPML-Datei aus, die nicht größer als 2 MiB ist.
feeds-page-action = Feeds auf dieser Seite abonnieren
feeds-toolbar-button =
    .label = Live-Lesezeichen
    .tooltiptext = Feeds entdecken und Live-Lesezeichen verwalten
feeds-menu-label =
    .label = Live-Lesezeichen
    .accesskey = L
feeds-menu-manage =
    .label = Live-Lesezeichen verwalten…
feeds-menu-discovering =
    .label = Feeds auf dieser Seite suchen…
feeds-menu-no-feeds =
    .label = Auf dieser Seite werden keine Feeds angezeigt
feeds-menu-all-subscribed =
    .label = Alle Feeds auf dieser Seite sind bereits abonniert
feeds-menu-subscribe =
    .label = Abonnieren { $title }…
    .tooltiptext = { $url }
feeds-menu-open-site =
    .label = Website des Feeds öffnen
    .tooltiptext = { $url }
feeds-menu-reload =
    .label = Live-Lesezeichen neu laden
feeds-menu-loading =
    .label = Feed wird geladen…
feeds-menu-empty =
    .label = Dieser Feed enthält keine Einträge
feeds-menu-error =
    .label = Der Feed konnte nicht aktualisiert werden. Der Versuch wird später wiederholt.
feeds-menu-no-cache =
    .label = In einem nicht privaten Fenster neu laden, um Elemente zu laden
feeds-entry-visited =
    .label = { $title }
    .aria-label = { $title } (besucht)
    .tooltiptext = { $url } (besucht)
feeds-entry-unvisited =
    .label = { $title }
    .aria-label = { $title } (nicht besucht)
    .tooltiptext = { $url } (nicht besucht)
feeds-direct-page-title = Feed-Vorschau
feeds-settings-button = Feed-Einstellungen
feeds-preview-page-title = Feeds
feeds-reader-position = { $current } von { $total } Artikeln
feeds-rail-feeds = Feeds
feeds-next = Nächster Artikel
feeds-all-filter = Alle
feeds-unread-filter = Ungelesen
feeds-all = Alle Feeds
feeds-saved = Gespeichert
feeds-add = Feed hinzufügen
feeds-add-url-label = Feed-URL
feeds-add-preview = Feed-Vorschau
feeds-reader-page-title = Feed-Reader
feeds-subscribe-preview-loading = Nach den neuesten Schlagzeilen suchen…
feeds-subscribe-preview-headlines = Aktuelle Schlagzeilen
feeds-subscribe-preview-source = { $title } · { $url }
feeds-subscribe-destination = Gespeichert in { $folder }
feeds-health-ready = Feed verfügbar.
feeds-subscribe-undone = Abonnement gekündigt.
feeds-search-label = Abonnements suchen
feeds-health-loading = Wird aktualisiert…
feeds-direct-empty = Dieser Feed enthält keine Einträge.
feeds-status-direct-preview = Feed-Vorschau anzeigen.
feeds-subscribe-preview-empty = Es sind keine aktuellen Schlagzeilen verfügbar.
feeds-subscribe-preview-open-error = Die vollständige Vorschau konnte nicht geöffnet werden.
feeds-subscribe-full-preview = Vollständige Vorschau
    .label = Vollständige Vorschau
feeds-subscribe-already = Sie haben diesen Feed bereits abonniert.
feeds-subscribe-success = Diesen Feed abonniert.
feeds-subscribe-undo = Rückgängig machen
    .label = Rückgängig machen
feeds-no-matches = Keine passenden Abonnements.
feeds-add-cancel = Abbrechen
feeds-add-confirm = Feed hinzufügen
feeds-add-name-label = Name
feeds-display-list = Listenansicht
feeds-display-cards = Kartenansicht
feeds-back = Zurück
feeds-previous = Vorherige
feeds-clear-search = Suche löschen
feeds-subscribe-preview-invalid = Geben Sie eine gültige Feed-URL ein, um eine Vorschau der Überschriften anzuzeigen.
feeds-subscribe-preview-error = Die neuesten Überschriften konnten nicht geladen werden. Sie können dennoch versuchen, sie zu abonnieren.
feeds-subscribe-open = In „Meine Feeds“ öffnen
    .label = In „Meine Feeds“ öffnen
feeds-subscribe-undo-error = Dieses Abonnement konnte nicht aufgehoben werden. Möglicherweise hat es sich geändert oder enthält gespeicherte Lesezeichen.
feeds-subscribe-removing = Abonnement wird entfernt… Das Schließen dieses Fensters hebt den Löschvorgang nicht auf.
feeds-subscribe-close = Schließen
    .label = Schließen
    .accesskey = S
feeds-health-idle = Es gibt keine aktuellen Updates. Bitte laden Sie die Seite neu, um nach neuen Einträgen zu suchen.
feeds-health-error = Dieser Feed konnte nicht aktualisiert werden. Laden Sie die Seite neu, um es erneut zu versuchen.
feeds-last-updated = Zuletzt geprüft: { DATETIME($date, dateStyle: "medium", timeStyle: "short") }
feeds-error-preview-expired = Diese Vorschau ist nicht mehr verfügbar. Öffnen Sie erneut die URL des Original-Feeds.
feeds-reader-load-error = Dieser Artikel konnte nicht angezeigt werden. Gehen Sie zurück und versuchen Sie es erneut, oder wählen Sie „Original öffnen“, um ihn auf der Website zu lesen.
feeds-error-retry-later = Der Feed-Server hat uns gebeten, zu warten. Versuchen Sie es später noch einmal.
feeds-error-saved-limit = Sie haben das Limit für gespeicherte Artikel erreicht. Löschen Sie einen gespeicherten Artikel, bevor Sie einen weiteren speichern.
feeds-add-folder-label = Speichern unter
feeds-open-feeds = In „Meine Feeds“ öffnen
feeds-undo = Abonnement beenden
feeds-manage = Feeds verwalten
feeds-search-articles = Artikel suchen
feeds-order-newest = Neueste zuerst
feeds-order-oldest = Älteste zuerst
feeds-open-original = Original öffnen
feeds-mark-read = Als gelesen markieren
    .title = Als gelesen markieren
feeds-mark-unread = Als ungelesen markieren
    .title = Als ungelesen markieren
feeds-save = Artikel speichern
    .title = Artikel speichern
feeds-unsave = Aus den gespeicherten Einträgen entfernen
    .title = Aus den gespeicherten Einträgen entfernen
feeds-mark-read-button =
    .aria-label = Als gelesen markieren
    .title = Als gelesen markieren
feeds-mark-unread-button =
    .aria-label = Als ungelesen markieren
    .title = Als ungelesen markieren
feeds-save-button =
    .aria-label = Artikel speichern
    .title = Artikel speichern
feeds-unsave-button =
    .aria-label = Aus den gespeicherten Einträgen entfernen
    .title = Aus den gespeicherten Einträgen entfernen
feeds-summary-notice = Dieser Inhalt wurde über den Feed bereitgestellt. Öffnen Sie den Originalartikel, wenn Sie mehr lesen möchten.
feeds-no-content = Dieser Feed enthält keinen Artikeltext. Öffnen Sie den Originalartikel, um ihn zu lesen.
feeds-open-article =
    .aria-label = { $title } in Waterfox lesen
feeds-empty-unread = Sie sind auf dem neuesten Stand.
feeds-empty-saved = Gespeicherte Artikel werden hier angezeigt, sobald Sie sie aus einem Feed speichern.
feeds-empty-results = Keine passenden Artikel gefunden.
feeds-show-all = Alle Artikel anzeigen
feeds-preview-loading = Feed-Vorschau wird geladen…
feeds-preview-invalid = Dieser Feed konnte nicht in der Vorschau angezeigt werden. Überprüfen Sie die Feed-URL und versuchen Sie es erneut.
feeds-subscription-exists = Sie haben diesen Feed bereits abonniert.
feeds-nav =
    .aria-label = Feed-Navigation
feeds-filter-label =
    .aria-label = Artikel-Filter
feeds-order-label =
    .aria-label = Artikelreihenfolge
feeds-display-label =
    .aria-label = Artikelanzeige
feeds-article-count =
    { $count ->
        [one] Ein Artikel
       *[other] { $count } Artikel
    }
feeds-source-count = { $title } ({ $count })
feeds-saved-in = Gespeichert in { $folder }
feeds-show-more = Weitere Artikel anzeigen
feeds-live-bookmarks-heading = Live-Lesezeichen
feeds-search-placeholder =
    .placeholder = Artikel suchen
feeds-recent-posts = Neueste Beiträge
feeds-back-to-feeds = Zurück zu den Feeds
feeds-subscribe-preview-heading = Diesen Feed abonnieren
feeds-feed-url-heading = Feed-URL
feeds-visit-website = Website besuchen
feeds-preview-state-unsubscribed = Feed-Vorschau · nicht abonniert
feeds-preview-state-subscribed = Feed-Vorschau · abonniert
feeds-close =
    .aria-label = Schließen
feeds-source-button =
    .aria-label =
        { $title }, { $count } ungelesen { $count ->
            [one] Artikel
           *[other] Artikel
        }
feeds-all-scope-button =
    .aria-label =
        Alle Feeds, { $count } ungelesen { $count ->
            [one] Artikel
           *[other] Artikel
        }
feeds-article-date = { DATETIME($date, dateStyle: "long") }
feeds-today = Heute
feeds-yesterday = Gestern
feeds-undated = Weitere Artikel
feeds-subscribe-rename =
    .label = Umbenennen
feeds-subscribed-heading = Abonniert
feeds-rail-settings = Einstellungen
feeds-add-dialog-title = Feed hinzufügen
feeds-reader-save = Speichern
feeds-reader-saved = Gespeichert
feeds-back-to-collection = Zurück zu { $title }
feeds-display-list-button =
    .aria-label = Listenansicht
    .title = Listenansicht
feeds-display-grid-button =
    .aria-label = Kartenansicht
    .title = Kartenansicht
feeds-unread-count =
    { $count } ungelesene Beiträge in { $feeds } { $feeds ->
        [one] Feed
       *[other] Feeds
    }
