# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

onboarding-grassroots-title = Unterstützung der Basis
onboarding-grassroots-subtitle = Vielen Dank, dass Sie Waterfox, einen unabhängigen Browser aus der Basis, verwenden. Mit Ihrer Unterstützung bauen wir eine nachhaltige Alternative zu den großen Anbietern auf.
waterfox-onboarding-welcome-title = Willkommen bei { -brand-short-name }
waterfox-onboarding-welcome-subtitle = Unabhängig, schnell und mit den Waterfox-Steuerelementen ausgestattet, die Sie erwarten.
waterfox-onboarding-start-button = Los geht’s
waterfox-onboarding-import-title = Nehmen Sie Ihre Daten mit
waterfox-onboarding-style-title = Wählen Sie Ihren Waterfox-Stil aus
waterfox-onboarding-style-photon-label = Photon
waterfox-onboarding-style-proton-label = Proton
waterfox-onboarding-style-nova-label = Nova
waterfox-onboarding-density-normal-label = Normal
waterfox-onboarding-density-compact-label = Kompakt
waterfox-onboarding-theme-mode-system-label = System
waterfox-onboarding-color-lavender-label = Lavender
waterfox-onboarding-tabs-horizontal-label = Horizontale Tabs
waterfox-onboarding-tabs-vertical-label = Vertikale Tabs
waterfox-onboarding-continue-button = Weiter
waterfox-onboarding-save-continue-button = Speichern und fortfahren
waterfox-onboarding-skip-step-button = Diesen Schritt überspringen
waterfox-onboarding-location-top-above-label = Über der Symbolleiste
waterfox-onboarding-location-top-below-label = Unter der Symbolleiste
waterfox-onboarding-location-bottom-above-label = Über der Statusleiste
waterfox-onboarding-location-bottom-below-label = Unter der Statusleiste
waterfox-onboarding-privacy-title = Datenschutztools sind bereit
waterfox-onboarding-color-default-label = Standard
waterfox-onboarding-import-subtitle = Importieren Sie Lesezeichen, den Verlauf und Formulardaten aus { migration-wizard-migrator-display-name-firefox } oder einem anderen Browser, ohne diese Einrichtung zu verlassen.
waterfox-onboarding-style-subtitle = Wählen Sie die Form des Tabs und der Symbolleiste aus und legen Sie fest, wie kompakt diese wirken sollen.
waterfox-onboarding-style-photon-body = Der klassische Waterfox-Look mit verfeinerter Oberfläche.
waterfox-onboarding-style-proton-body = Ein ruhigeres Layout mit modernem Browser-Abstand.
waterfox-onboarding-style-nova-body = Ein markanterer Waterfox-Stil mit einer helleren Linie für den aktiven Tab.
waterfox-onboarding-density-touch-label = Touch
waterfox-onboarding-theme-color-title = Geben Sie ihm eine persönliche Note
waterfox-onboarding-theme-color-subtitle = Wählen Sie eine Theme-Farbe aus, mit der Sie jedes Fenster individuell gestalten können.
waterfox-onboarding-theme-mode-light-label = Hell
waterfox-onboarding-theme-mode-dark-label = Dunkel
waterfox-onboarding-color-smoke-label = Rauch
waterfox-onboarding-color-ash-label = Asche
waterfox-onboarding-color-sun-label = Sonne
waterfox-onboarding-color-spark-label = Funke
waterfox-onboarding-color-flame-label = Flamme
waterfox-onboarding-color-flare-label = Leuchtfeuer
waterfox-onboarding-color-dusk-label = Dämmerung
waterfox-onboarding-color-lagoon-label = Lagune
waterfox-onboarding-color-tide-label = Gezeiten
waterfox-onboarding-color-pine-label = Kiefer
waterfox-onboarding-tabs-title = Tabs nach Ihren Wünschen anordnen
waterfox-onboarding-tabs-subtitle = Wählen Sie aus, wie Ihre Tabs angeordnet werden sollen und wo sich die horizontale Tableiste befinden soll. Beides können Sie später in den Einstellungen ändern.
waterfox-onboarding-tabs-horizontal-body = Die klassische Tableiste oben beibehalten.
waterfox-onboarding-tabs-vertical-body = Die Tabs als längere Liste in die Seitenleiste verschieben.
waterfox-onboarding-tabs-tree-label = Baum-Tabs
waterfox-onboarding-tabs-tree-body = Vertikale Tabs, die unter dem Tab verschachtelt sind, über den sie geöffnet wurden.
waterfox-onboarding-default-primary-button = Als Standard festlegen
waterfox-onboarding-finish-title = Alles ist bereit
waterfox-onboarding-finish-subtitle = Vielen Dank, dass Sie sich für Waterfox entschieden haben. Ihr Browser ist nun einsatzbereit.
waterfox-onboarding-finish-primary-button = Browsen beginnen
waterfox-onboarding-skip-button = Nicht jetzt
waterfox-onboarding-customize-appearance-button = Darstellung in den Einstellungen anpassen
waterfox-onboarding-customize-tabs-button = Tabs in den Einstellungen anpassen
waterfox-onboarding-customize-privacy-button = Datenschutzeinstellungen anpassen
waterfox-onboarding-privacy-subtitle = Waterfox ist standardmäßig mit Werbeblocker und Datenschutzeinstellungen ausgestattet. Sie können diese jederzeit individuell anpassen.
waterfox-onboarding-privacy-primary-button = Schutzmaßnahmen beibehalten
waterfox-onboarding-default-title = { -brand-short-name } als Standardbrowser festlegen
waterfox-onboarding-default-subtitle = Links standardmäßig in { -brand-short-name } öffnen und Ihre Waterfox-Einstellungen griffbereit halten.
waterfox-onboarding-language-hint = Das können Sie jederzeit in den Einstellungen ändern.
waterfox-onboarding-language-error = { -brand-short-name } konnte die Sprache nicht ändern. Ihre bisherige Sprache ist weiterhin aktiv.
waterfox-onboarding-step-label = Schritt { $current } von { $total }
waterfox-onboarding-tabs-style-legend = Browser-Stil
waterfox-onboarding-tabs-density-legend = Dichte
waterfox-onboarding-appearance-subtitle = Wählen Sie Form, Dichte und Farbe aus. Sie können alles später in den Einstellungen anpassen.
waterfox-onboarding-theme-mode-legend = Farbschema
waterfox-onboarding-theme-color-legend = Theme-Farbe
waterfox-onboarding-tabs-layout-legend = Tab-Anordnung
waterfox-onboarding-tabs-location-label = Position der Tableiste
waterfox-onboarding-tabs-location-hint = Gilt für horizontale Tabs. Weitere Positionen finden Sie in den Einstellungen.
waterfox-onboarding-finish-privacy-note = Die Werbeblocker- und Tracking-Schutzfunktionen sind bereits aktiviert.
waterfox-onboarding-back-button = Zurück
