# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

tree-appearance-header = Erscheinungsbild
tree-tree-double-click-behavior-toggle-close =
    .label = Tab schließen
tree-tree-double-click-behavior-toggle-none =
    .label = Nichts tun
tree-sticky-active-tab =
    .label = Aktiver Tab
    .accesskey = k
tree-faviconize-pinned-tabs =
    .label = Nur angeheftete Tabs mit ihrem Symbol anzeigen
    .accesskey = a
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Einfügeposition neuer untergeordneter Tabs aus angehefteten Tabs (werden als Stamm-Tabs angezeigt)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Das Ende des Baums
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Keine Kontrolle (Entscheidung des Browsers oder anderer Tab-Erweiterungen respektieren)
tree-behavior-header = Baumansicht der Tabs
tree-auto-attach-no-control =
    .label = (keine Kontrolle)
tree-tree-double-click-behavior-caption =
    .value = Doppelklick auf Tab
    .accesskey = D
tree-auto-sticky-header = Tabs bleiben beim Herausscrollen an den Rändern der Tableiste hängen
tree-sticky-sharing-tab =
    .label = Tabs, die Kamera/Mikrofon/Bildschirm teilen
    .accesskey = t
tree-sticky-sound-playing-tab =
    .label = Tabs für Soundwiedergabe
    .accesskey = S
category-tree =
    .tooltiptext = { pane-tree-title }
tree-drop-links-on-tab-behavior-caption =
    .value = Wenn ein Link oder eine URL-Zeichenfolge auf einen Tab gezogen wird
    .accesskey = L
pane-tree-title = Vertikale hierarchische Tabs
browser-layout-tree-vertical-tabs =
    .label = Vertikale hierarchische Tabs
sidebar-tree-vertical-tabs =
    .label = Vertikale hierarchische Tabs
tree-header = Vertikale hierarchische Tabs
tree-drop-links-on-tab-behavior-load =
    .label = Auf Tab laden
tree-auto-collapse-expand-subtree-on-select =
    .label = Wenn ein Tab den Fokus erhält, wird dessen Baum automatisch erweitert und die anderen Tabs werden ausgeblendet.
    .accesskey = F
tree-auto-collapse-expand-subtree-on-attach =
    .label = Wenn ein neuer Baum erscheint, werden andere automatisch ausgeblendet
    .accesskey = a
tree-drop-links-on-tab-behavior-ask =
    .label = Immer fragen, wie man es behandelt
tree-drop-links-on-tab-behavior-newtab =
    .label = Neuen untergeordneten Tab öffnen
tree-successor-tab-control-level-caption =
    .value = Wenn der aktuelle Tab als letztes untergeordnetes Element geschlossen wird
    .accesskey = W
tree-successor-tab-control-level-in-tree =
    .label = Fokus auf den vorherigen Tab in der Baumstruktur setzen
tree-successor-tab-control-level-never =
    .label = Fokus immer auf den nächsten Tab setzen (unter Berücksichtigung der Einstellungen des Browsers oder anderer Erweiterungen)
tree-successor-tab-control-level-simulate-default =
    .label = Fokus immer auf den nächsten Tab setzen
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Baum einklappen/aufklappen
tree-auto-attach-header = Automatische Organisation der Tabstruktur
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Neben dem zuletzt geöffneten Tab oder nahe am Ursprung
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = An der Spitze des Baumes (nahe am Ursprung)
tree-auto-attach-independent =
    .label = Unabhängiger Tab
tree-tree-double-click-behavior-toggle-sticky =
    .label = An den Kanten des Tab-Balkens anheften / Von den Kanten des Tab-Balkens lösen
tree-auto-attach-child-end =
    .label = Letztes Element des übergeordneten Tabs
tree-auto-attach-child-next-to-last-related-tab =
    .label = Element des übergeordneten Tabs, neben dem zuletzt geöffneten Element
tree-auto-attach-child-top =
    .label = Erstes Element des übergeordneten Tabs
tree-auto-attach-next-sibling =
    .label = Nächster Nachbar des übergeordneten Tabs
tree-auto-attach-sibling =
    .label = Nachbar des übergeordneten Tabs
tree-auto-attach-on-duplicated-caption =
    .value = Tab duplizieren als
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Für den mittleren Mausklick einen neuen leeren Tab öffnen als
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Neuen leeren Tab öffnen als
    .accesskey = N
tree-auto-attach-on-opened-from-external-caption =
    .value = Neuer Tab aus anderen Anwendungen: Öffnen als
    .accesskey = Ö
tree-auto-attach-on-opened-with-owner-caption =
    .value = Wenn ein Tab aus einem bestehenden Tab geöffnet wird, ihn öffnen als
    .accesskey = g
tree-auto-attach-same-site-orphan-caption =
    .value = Neuer Tab mit derselben Website wie der aktuelle Tab aus Adressleiste, Lesezeichen, Verlauf oder anderen Fällen: Öffnen als
    .accesskey = w
tree-auto-attach-on-any-other-trigger-caption =
    .value = Tabs von anderen Auslösern: Öffnen als
    .accesskey = T
waterfox-tabs-tree-heading =
    .label = Baum-Tabs
waterfox-tabs-tree-enable-toggle =
    .label = Tabs als Baumstruktur anzeigen
    .description = Tabs, die Sie aus einem anderen Tab heraus öffnen, werden darunter eingefügt, sodass Sie ganze Gruppen auf einmal ein- und ausklappen sowie verschieben können. Dadurch werden auch vertikale Tabs aktiviert.
waterfox-tab-context-collapse-tree =
    .label = Baumstruktur einklappen
waterfox-tab-context-expand-tree =
    .label = Baumstruktur ausklappen
waterfox-tab-context-close-tree =
    .label = Baum schließen
waterfox-tab-context-collapse-all-trees =
    .label = Alle Baumstrukturen einklappen
waterfox-tab-context-expand-all-trees =
    .label = Alle Baumstrukturen ausklappen
waterfox-tab-context-close-descendants =
    .label = Untergeordnete Elemente schließen
waterfox-tabs-tree-auto-attach-select =
    .label = Neue Tabs öffnen
waterfox-tabs-tree-auto-attach-option-root =
    .label = Eigenständig
waterfox-tabs-tree-double-click-option-none =
    .label = Keine Aktion
waterfox-tabs-tree-max-depth-option-unlimited =
    .label = Kein Limit
waterfox-tabs-tree-double-click-select =
    .label = Doppelklick auf einen Tab
waterfox-tabs-tree-close-parent-select =
    .label = Wenn Sie einen übergeordneten Tab schließen
waterfox-tabs-tree-close-parent-option-detach =
    .label = Seine untergeordneten Elemente auf die oberste Ebene verschieben
waterfox-tabs-tree-auto-attach-option-child =
    .label = Unter dem Tab versteckt, der sie öffnete
waterfox-tabs-tree-auto-attach-option-sibling =
    .label = Neben dem Tab, der sie öffnete
waterfox-tabs-tree-auto-collapse-on-select-toggle =
    .label = Zweig des aktiven Tabs öffnen und die anderen einklappen
waterfox-tabs-tree-auto-collapse-on-attach-toggle =
    .label = Einen Zweig öffnen, wenn ein neuer Tab hinzugefügt wird
waterfox-tabs-tree-close-parent-option-promote-first =
    .label = Das erste untergeordnete Element an seine Platz setzen
waterfox-tabs-tree-close-parent-option-promote-all =
    .label = Untergeordnete Elemente eine Stufe höher bringen
waterfox-tabs-tree-close-parent-option-close-all =
    .label = Den gesamten Zweig schließen
waterfox-tabs-tree-double-click-option-toggle =
    .label = Seinen Zweig ein- oder ausklappen
waterfox-tabs-tree-double-click-option-close =
    .label = Seinen Zweig schließen
waterfox-tabs-tree-sticky-active-toggle =
    .label = Den aktuellen Tab sichtbar lassen, wenn sein Zweig eingeklappt wird
waterfox-tabs-tree-propagate-muted-toggle =
    .label = Einen Tab und dessen untergeordnete Tabs stummschalten
waterfox-tabs-tree-max-depth-select =
    .label = Die Verschachtelungstiefe von Tabs begrenzen
