# In browser/locales/jar.mn
# Localised versions MUST be located in browser/locales/l10n/{locale}/browser/browser/waterfox.ftl


## Restart Prompt

restart-prompt-title = { -brand-short-name } újraindítása
restart-prompt-question = Biztosan újra akarja indítani a(z) { -brand-short-name } alkalmazást?

## App Menu

appmenuitem-restart-browser =
    .label = Újraindítás

## Tab Context Menu

copy-url =
    .label = Laphivatkozás másolása
copy-all-urls =
    .label = Összes laphivatkozás másolása
unload-tab =
    .label = Lap kiürítése

## Private Tab

open-all-private =
    .label = Összes megnyitása privát lapokon
open-all-links-private =
    .label = Összes hivatkozás megnyitása privát lapokon
open-private-tab =
    .label = Megnyitás új privát lapon
new-private-tab =
    .label = Új privát lap
    .tooltiptext = Új privát lap megnyitása
open-link-private =
    .label = Hivatkozás megnyitása új privát lapon
private-tab =
    .label =
        { $isPrivate ->
            [true] Kilépés a privát lapból
           *[false] Privát lappá alakítás
        }

## Status Bar

status-bar =
    .label = Állapotsor

## about:preferences


### Main

tab-position-header = Lapsáv helyzete
tab-bar-top-above =
    .label = Felül, a címsáv felett
tab-bar-top-below =
    .label = Felül, a címsáv alatt
tab-bar-bottom-above =
    .label = Alul, az állapotsáv felett
tab-bar-bottom-below =
    .label = Alul, az állapotsáv alatt
tab-additional-header = További lapbeállítások
pinned-icon-only =
    .label = Rögzített lapok kicsinyítése, hogy csak az oldal ikonja jelenjen meg
insert-after-current =
    .label = Új lap beszúrása az aktuális lap után
insert-related-after-current =
    .label = Kapcsolódó új lap beszúrása az aktuális lap után
dynamic-theme-header = Dinamikus témák
dynamic-theme-dark =
    .label = Sötét mód kényszerítése
dynamic-theme-light =
    .label = Világos mód kényszerítése
dynamic-theme-auto =
    .label = Világos/sötét mód dinamikus beállítása
restart-header = Újraindítás menüpont
restart-show-button =
    .label = Újraindítás gomb megjelenítése a főmenüben
restart-purge-cache =
    .label = A gyors újraindítási gyorsítótár törlése a böngésző újraindításakor
restart-require-confirmation =
    .label = Megerősítés kérése újraindításkor
tab-feature-header = Lap helyi menüje
show-duplicate-tab =
    .label = A lap duplikálása menüpont megjelenítése
show-copy-url =
    .label = A lap URL-jének másolása menüpont megjelenítése
enable-copy-active-tab =
    .label = URL másolása csak az aktív lapról
show-copy-all-urls =
    .label = Az összes lap URL-jének másolása menüpont megjelenítése
show-unload-tab =
    .label = A lap kiürítése menüpont megjelenítése
statusbar-header = Állapotsáv
statusbar-enabled =
    .label = Állapotsáv megjelenítése
statusbar-show-links =
    .label = Hivatkozások megjelenítése
statusbar-contrast-text =
    .label = Állapotsor szövegszínének kontrasztossá tétele
bookmarks-bar-position-header = Könyvjelzősáv helyzete
bookmarks-position-top =
    .label = Felül
bookmarks-position-bottom =
    .label = Alul
geolocation-api-header = Geolocation API
geolocation-description = Egyes weboldalak működéséhez szükség van a helyadataira. Ha egy weboldal azért nem működik, mert nem éri el a helyzetét, engedélyezze ezt a beállítást, majd próbálja újra.
geolocation-api-enabled =
    .label = Engedélyezés
geolocation-api-disabled =
    .label = Letiltás

### Privacy

send-referrer-header-0 =
    .label = Soha ne küldje el a hivatkozó fejlécet
send-referrer-header-1 =
    .label = A hivatkozó fejlécet csak linkekre és hasonló elemekre kattintáskor küldje el
send-referrer-header-2 =
    .label = A hivatkozó fejlécet minden kérésnél küldje el (alapértelmezett)
enable-webrtc-p2p =
    .label = WebRTC közvetlen kapcsolat engedélyezése
load-images =
    .label = Képek automatikus betöltése
enable-javascript =
    .label = JavaScript engedélyezése
webrtc-header = WebRTC közvetlen kapcsolat
ref-header = HTTP hivatkozó fejléc

### Look & Feel

pane-theme-title = Megjelenés
category-theme =
    .tooltiptext = { pane-theme-title }
preset-title = Előbeállítások
waterfox-defaults =
    .label = Waterfox alapbeállítások
lepton-style =
    .label = Lepton stílus
proton-style =
    .label = Proton stílus
enable-waterfox-theme-0 =
    .label = Waterfox téma-testreszabások engedélyezése minden témánál
enable-waterfox-theme-1 =
    .label = Waterfox téma-testreszabások engedélyezése Waterfox témáknál
enable-waterfox-theme-2 =
    .label = Waterfox téma-testreszabások letiltása
enable-default-accent-color =
    .label = Alapértelmezett kiemelőszín
enable-cyan-accent-color =
    .label = Cián kiemelőszín
enable-system-accent-color =
    .label = Rendszer kiemelőszíne
disable-panel-animate =
    .label = Alkalmazásmenü panel animációjának letiltása
disable-sidebar-animate =
    .label = Oldalsáv panel animációjának letiltása
auto-hide-tabs =
    .label = Lapok automatikus elrejtése
auto-blur-tabs =
    .label = Lapok automatikus elhomályosítása
auto-hide-tabbar =
    .label = Lapsáv automatikus elrejtése
auto-hide-navbar =
    .label = Navigációs sáv automatikus elrejtése
auto-hide-bookmarkbar =
    .label = Könyvjelzősáv automatikus elrejtése
auto-hide-sidebar =
    .label = Oldalsáv automatikus elrejtése
auto-hide-back =
    .label = Vissza gomb automatikus elrejtése
auto-hide-forward =
    .label = Előre gomb automatikus elrejtése
auto-hide-pageaction =
    .label = Oldalműveletek automatikus elrejtése
hide-all-icons =
    .label = Összes ikon elrejtése
hide-tab-icons =
    .label = Lap ikonok elrejtése
hide-sidebar-header =
    .label = Oldalsáv fejlécének elrejtése
hide-urlbar-iconbox =
    .label = URL-sáv ikondobozának elrejtése
hide-bookmarkbar-icon =
    .label = Könyvjelzősáv ikonjainak elrejtése
hide-bookmarkbar-label =
    .label = Könyvjelzősáv címkéinek elrejtése
hide-disabled-menuitems =
    .label = Letiltott menüelemek elrejtése
center-tab-content =
    .label = Lap tartalmának középre igazítása
center-tab-label =
    .label = Csak a lap címének középre igazítása
center-navbar-text =
    .label = Navigációs sáv szövegének középre igazítása
square-tab-edges =
    .label = Szögletes lapsarkok
square-button-edges =
    .label = Szögletes gombsarkok
square-menu-panel =
    .label = Szögletes alkalmazásmenü panel sarkok
square-panel-item =
    .label = Szögletes alkalmazásmenü elem sarkok
square-menu-popup =
    .label = Szögletes helyi menü panel sarkok
square-menu-item =
    .label = Szögletes helyi menüelem sarkok
square-field =
    .label = Szögletes beviteli mező sarkok
square-checkbox =
    .label = Szögletes jelölőnégyzet
drag-space =
    .label = Rögzített húzási terület engedélyezése
compact-context-menu =
    .label = Helyi menü térközének csökkentése
compact-bookmark-menu =
    .label = Könyvjelzőmenü térközének csökkentése
compact-panel-header =
    .label = Panel fejlécének térközének csökkentése
compact-navbar-popup =
    .label = Navigációs sáv felugró ablakainak térközének csökkentése
close-button-hover =
    .label = A lapbezáró gomb megjelenítése a kijelölt lapon rámutatáskor, ha sok lap van nyitva
remove-panel-strip =
    .label = Színes alkalmazásmenü elválasztó eltávolítása
full-panel-strip =
    .label = Teljes szélességű alkalmazásmenü elválasztó
show-menu-icons =
    .label = Menüikonok megjelenítése
show-mac-menu-icons =
    .label = Mac menüikonok megjelenítése
monospace-font =
    .label = Rögzített szélességű betűtípus használata az oldalakon
monospace-font-theme =
    .label = Rögzített szélességű betűtípus használata a témában
tab-context-line =
    .label = Lap kontextusvonal
theme-header = Téma
appearance-header = Megjelenés
interface-component-header = Felületi elemek
rounding-header = Lekerekítés
autohide-hidden-header = Automatikus elrejtés és rejtett elemek
center-header = Középre igazítás
tab-bar-header = Lapsáv
nav-bar-header = Navigációs sáv
bookmark-header = Könyvjelzősáv
panels-header = Panelek
sidebar-header = Oldalsáv
font-header = Betűtípusok
icons-header = Ikonok
animation-header = Animációk
full-screen-header = Teljes képernyő
media-player-header = Médialejátszó

## about:telemetry

telemetry-page-subtitle = A Waterfox nem gyűjt telemetriai adatokat a telepítéséről – minden telemetriai modul le van tiltva a böngésző fordításakor. Amit a böngészőben csinál, azt csak Ön ismeri.
telemetry-privacy-policy = Adatvédelmi irányelvek
onboarding-grassroots-title = A közösségi kezdeményezés támogatása
onboarding-grassroots-subtitle = Köszönjük, hogy a Waterfoxot használja, egy független, közösségi böngészőt. A támogatásával fenntartható alternatívát építünk a nagy szereplőkkel szemben.
update-application-manual =
    .label = Frissítések keresésének letiltása (nem ajánlott)
    .accesskey = L
preferences-doh-setting-ultra =
    .label = Ultra védelem
    .accesskey = U
preferences-doh-ultra-desc = A { -brand-short-name } biztonságos DNS-t használ Oblivious HTTP-n keresztül a Waterfox adatvédelmi átjátszójával a maximális védelem érdekében.
preferences-doh-ultra-detailed-desc-1 = A Waterfox Oblivious HTTP átjátszóját használja a DNS-lekérdezések elrejtésére még a DNS-szolgáltató elől is
preferences-doh-ultra-detailed-desc-2 = További titkosítási réteget biztosít a hagyományos DNS over HTTPS felett
preferences-doh-ultra-detailed-desc-3 = Maximális DNS-adatvédelem – senki sem láthatja, milyen oldalakat látogat
preferences-doh-ultra-fallback-mode = Tartalék működés:
preferences-doh-ultra-fallback-allowed = Engedélyezze a rendszer DNS-re való visszaállást, ha a biztonságos DNS nem működik
preferences-doh-ultra-fallback-disabled = Soha ne álljon vissza rendszer DNS-re (az oldalak nem biztos, hogy betöltődnek, ha a biztonságos DNS nem működik)
enable-menu-transparency =
    .label = Menü átlátszóságának engedélyezése
enable-panel-transparency =
    .label = Panel átlátszóságának engedélyezése
tabbrowser-confirm-session-restore-checkbox = Előző ablakok és lapok megnyitása
pane-tree-title = Fa nézetű függőleges lapok
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Fa nézetű függőleges lapok
sidebar-tree-vertical-tabs =
    .label = Fa nézetű függőleges lapok
tree-header = Fa nézetű függőleges lapok
tree-appearance-header = Megjelenés
tree-auto-sticky-header = A lapsáv széleihez rögzített lapok, ha kigörgetődnek
tree-faviconize-pinned-tabs =
    .label = A rögzített lapok megjelenítése csak ikonnal
    .accesskey = M
tree-sticky-active-tab =
    .label = Aktív lap
    .accesskey = a
tree-sticky-sharing-tab =
    .label = Kamerát/mikrofont/képernyőt megosztó lapok
    .accesskey = k
tree-sticky-sound-playing-tab =
    .label = Hangot lejátszó lapok
    .accesskey = h
tree-behavior-header = Lapok fa nézete
tree-auto-collapse-expand-subtree-on-attach =
    .label = Új fa megjelenésekor a többi automatikus összecsukása
    .accesskey = ö
tree-auto-collapse-expand-subtree-on-select =
    .label = Amikor egy lap fókuszt kap, a fája nyíljon ki, a többi pedig csukódjon össze
    .accesskey = f
tree-drop-links-on-tab-behavior-caption =
    .value = Ha egy hivatkozást vagy URL-t egy lapra húz
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Mindig kérdezze meg, hogyan kezelje
tree-drop-links-on-tab-behavior-load =
    .label = Betöltés a lapra
tree-drop-links-on-tab-behavior-newtab =
    .label = Megnyitás új gyermeklapként
tree-successor-tab-control-level-caption =
    .value = Az aktuális lap bezárásakor, ha az az utolsó gyermek
    .accesskey = z
tree-successor-tab-control-level-in-tree =
    .label = Fókusz áthelyezése az előző lapra a fán belül
tree-successor-tab-control-level-never =
    .label = Fókusz mindig a következő lapra (a böngésző vagy más kiegészítők szabályai szerint)
tree-successor-tab-control-level-simulate-default =
    .label = Fókusz mindig a következő lapra
tree-tree-double-click-behavior-caption =
    .value = Dupla kattintás egy lapon
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Lap bezárása
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Fa összecsukása/kibontása
tree-tree-double-click-behavior-toggle-none =
    .label = Ne csináljon semmit
tree-tree-double-click-behavior-toggle-sticky =
    .label = Rögzítés a lapsáv széléhez / rögzítés feloldása
tree-auto-attach-header = Lapfa automatikus rendezése
tree-auto-attach-child-end =
    .label = A szülőlap utolsó gyermeke
tree-auto-attach-child-next-to-last-related-tab =
    .label = A szülőlap gyermeke, a legutóbb megnyitott gyermek mellett
tree-auto-attach-child-top =
    .label = A szülőlap első gyermeke
tree-auto-attach-independent =
    .label = Független lap
tree-auto-attach-next-sibling =
    .label = A szülőlap következő testvérlapja
tree-auto-attach-no-control =
    .label = (nincs vezérlés)
tree-auto-attach-sibling =
    .label = A szülőlap testvérlapja
tree-auto-attach-on-any-other-trigger-caption =
    .value = Minden más esetben megnyitott lapok:
    .accesskey = m
tree-auto-attach-on-duplicated-caption =
    .value = Lap duplikálása:
    .accesskey = d
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Középső kattintás esetén az új üres lap megnyitása:
    .accesskey = k
tree-auto-attach-on-new-tab-command-caption =
    .value = Új üres lap megnyitása:
    .accesskey = ú
tree-auto-attach-on-opened-from-external-caption =
    .value = Más alkalmazásokból nyitott új lap:
    .accesskey = a
tree-auto-attach-on-opened-with-owner-caption =
    .value = Ha egy lap meglévő lapból nyílik meg:
    .accesskey = H
tree-auto-attach-same-site-orphan-caption =
    .value = Az aktuális lappal azonos webhelyről nyitott új lap a címsávból, könyvjelzőkből, előzményekből vagy más esetekben:
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Új gyermeklapok beszúrási helye rögzített lapokból (gyökérlapként jelennek meg)
    .accesskey = r
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = A fa végére
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = A legutóbb megnyitott gyermek mellé vagy a megnyitó közelébe
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Nincs vezérlés (a böngésző vagy más lapkiegészítők döntése szerint)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = A fa tetejére (a megnyitó közelébe)
waterfox-blocker-header = Reklámblokkolás
waterfox-blocker-intro-description = Reklámok, követő parancsfájlok és más nem kívánt kérések blokkolása a gyorsabb oldalbetöltés és kevesebb zavaró elem érdekében.
waterfox-blocker-setting-on =
    .label = Bekapcsolva
waterfox-blocker-setting-on-summary = Reklámok és követők blokkolása minimális hatással az oldalbetöltésre.
waterfox-blocker-setting-on-description = A Waterfox az alábbiakat blokkolja:
waterfox-blocker-blocks-ads = Reklámok és reklámhálózati kérések
waterfox-blocker-blocks-tracking = Követő parancsfájlok és pixelek
waterfox-blocker-blocks-annoyances = Zavaró felugró ablakok és átfedések (ha a kellemetlenségek listái engedélyezve vannak)
waterfox-blocker-partner-funding-title = A Waterfox fejlesztésének támogatása
waterfox-blocker-partner-funding-description = A Waterfox ingyenes, nyílt forráskódú és független. A keresőpartnereknél megjelenített reklámok finanszírozzák a fejlesztést és az infrastruktúrát. Ez bármikor kikapcsolható, de bekapcsolva hagyása a legegyszerűbb módja a projekt támogatásának.
waterfox-blocker-setting-off =
    .label = Kikapcsolva
waterfox-blocker-setting-off-description = A Waterfox nem blokkol reklámokat vagy követőket. Külső kiegészítők ettől függetlenül továbbra is blokkolhatnak tartalmat.
waterfox-blocker-dropdown-label =
    .value = Keresőpartner reklámok:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Engedélyezés a Waterfox keresőpartnereinél
waterfox-blocker-dropdown-option-block-everything =
    .label = Tiltás a Waterfox keresőpartnereinél
waterfox-blocker-manage-filter-lists =
    .label = Szűrőlisták kezelése…
waterfox-blocker-custom-filter-lists =
    .label = Egyéni szűrőlisták…
waterfox-blocker-filter-lists-window =
    .title = Reklámblokkoló szűrőlisták
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Változtatások mentése
    .buttonaccesskeyaccept = M
waterfox-blocker-filter-lists-description =
    .value = Válassza ki, mely szűrőlisták legyenek aktívak.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } aktív / { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Engedélyezve
waterfox-blocker-filter-lists-column-name =
    .label = Szűrőlista
waterfox-blocker-filter-lists-column-category =
    .label = Kategória
waterfox-blocker-filter-lists-enable =
    .label = Engedélyezés
waterfox-blocker-filter-lists-disable =
    .label = Letiltás
waterfox-blocker-extension-detected = A Waterfox most már beépített reklámblokkolóval rendelkezik. A beállításokat a Beállításokban ellenőrizheti.
waterfox-blocker-extension-detected-learn-more =
    .label = További információ
waterfox-blocker-extension-detected-dismiss =
    .label = Többé ne jelenjen meg
waterfox-blocker-extension-install-warning = A Waterfox már rendelkezik beépített reklámblokkolóval. Két reklámblokkoló egyidejű használata hibás vagy lassú oldalbetöltést okozhat.
waterfox-blocker-extension-install-got-it =
    .label = Értem
waterfox-blocker-extension-install-learn-more =
    .label = További információ
waterfox-blocker-third-party-notice-description = A(z) { $extensionName } szintén blokkol reklámokat. Két reklámblokkoló egyidejű használata problémákat okozhat.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Reklámblokkolási kivételek
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Megadhatja, mely webhelyeken legyen kikapcsolva a reklámblokkolás. Írja be a kezelni kívánt oldal pontos címét, majd kattintson a „Kivétel hozzáadása” gombra.
waterfox-blocker-toolbar-button =
    .label = Reklámblokkolás
    .tooltiptext = Reklámblokkolás
waterfox-blocker-panel-not-available = Nem érhető el ezen az oldalon
waterfox-blocker-panel-toggle =
    .label = Reklámblokkolás ezen az oldalon
    .description = Reklámok és követők blokkolása ezen az oldalon.
waterfox-blocker-panel-disabled = A reklámblokkolás ki van kapcsolva
waterfox-blocker-panel-site-excepted = Reklámok engedélyezve ezen az oldalon
waterfox-blocker-panel-partner-allowed = Reklámok engedélyezve a keresőpartnereknél
waterfox-blocker-stats =
    { $count ->
        [one] { $count } reklám blokkolva ezen az oldalon
       *[other] { $count } reklám blokkolva ezen az oldalon
    }
waterfox-blocker-panel-settings-button = Reklámblokkolási beállítások
waterfox-blocker-show-badge-pref =
    .label = Blokkolt elemek számának megjelenítése az eszköztár gombján
waterfox-blocker-filter-lists-category-core = Alapértelmezett
waterfox-blocker-filter-lists-category-privacy = Adatvédelem
waterfox-blocker-filter-lists-category-annoyances = Kellemetlenségek
waterfox-blocker-filter-lists-category-optional = Opcionális
waterfox-blocker-filter-lists-category-regional = Regionális
waterfox-blocker-filter-lists-search =
    .placeholder = Szűrőlisták keresése…
waterfox-blocker-filter-lists-empty-state = Nem érhetők el szűrőlisták.
waterfox-blocker-filter-lists-refresh-now =
    .label = Frissítés most
waterfox-blocker-filter-lists-last-updated = Frissítve: { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Még nem volt frissítve
waterfox-blocker-filter-lists-next-refresh =
    .value = Következő frissítés: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Következő frissítés: ismeretlen
waterfox-blocker-custom-filter-lists-window =
    .title = Egyéni szűrőlisták
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Változtatások mentése
    .buttonaccesskeyaccept = M
waterfox-blocker-custom-filter-lists-description = Egyéni szűrőlisták URL-jeinek hozzáadása. A listák letöltésre kerülnek, és a beépített szűrőkkel együtt lesznek alkalmazva.
waterfox-blocker-filter-lists-custom-heading =
    .value = Egyéni szűrőlisták
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Szűrőlista URL megadása…
waterfox-blocker-filter-lists-custom-url-label =
    .value = Szűrőlista URL
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Hozzáadás
waterfox-blocker-filter-lists-custom-remove =
    .label = Eltávolítás
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Összes eltávolítása
waterfox-blocker-filter-lists-custom-empty =
    .value = Nincsenek hozzáadott egyéni szűrőlisták.
waterfox-blocker-custom-filters =
    .label = Saját szűrők…
waterfox-blocker-custom-filters-window =
    .title = Saját szűrők
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Változtatások mentése
    .buttonaccesskeyaccept = M
waterfox-blocker-custom-filters-description = Saját reklámblokkolási szabályok hozzáadása. Ezek a szabványos uBlock Origin szűrőszintaxist használják, és az engedélyezett szűrőlistákkal együtt kerülnek alkalmazásra.
waterfox-blocker-custom-filters-empty =
    .value = Nincsenek egyéni szűrők.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Nincsenek egyéni szűrők.
        [one] 1 egyéni szűrő.
       *[other] { $count } egyéni szűrő.
    }
waterfox-blocker-custom-filters-status-unsaved = Nem mentett változtatások.
waterfox-blocker-custom-filters-import =
    .label = Importálás…
waterfox-blocker-custom-filters-export =
    .label = Exportálás…
waterfox-blocker-custom-filters-load-error-title = Betöltés sikertelen
waterfox-blocker-custom-filters-load-error = Az egyéni szűrőket nem sikerült betölteni.
waterfox-blocker-custom-filters-save-error-title = Mentés sikertelen
waterfox-blocker-custom-filters-save-error = Az egyéni szűrőket nem sikerült menteni.
waterfox-blocker-custom-filters-import-error-title = Importálás sikertelen
waterfox-blocker-custom-filters-import-error = A kiválasztott fájlt nem sikerült importálni.
waterfox-blocker-custom-filters-export-error-title = Exportálás sikertelen
waterfox-blocker-custom-filters-export-error = Az egyéni szűrőket nem sikerült exportálni.
waterfox-blocker-custom-filters-import-picker-title = Egyéni szűrők importálása
waterfox-blocker-custom-filters-export-picker-title = Egyéni szűrők exportálása
waterfox-blocker-custom-filters-import-replace-title = Lecseréli a jelenlegi szűrőket?
waterfox-blocker-custom-filters-import-replace-message = Az importálás minden jelenlegi tartalmat lecserél a szerkesztőben.
waterfox-blocker-extension-fallback-name-this = ez a kiegészítő
waterfox-blocker-extension-fallback-name-your = a kiegészítője
waterfox-blocker-spotlight-title = A Waterfox most már tartalmaz reklámblokkolást
waterfox-blocker-spotlight-subtitle = Észrevettük, hogy telepítve van a(z) { $extensionName }. A Waterfox most már saját reklámblokkolóval rendelkezik. Használata támogatja a Waterfox fejlesztését, de a döntés az Öné.
waterfox-blocker-spotlight-primary-button = Jelenlegi beállításaim megtartása
waterfox-blocker-spotlight-secondary-button = Beállítások áttekintése
waterfox-blocker-prompt-title = Waterfox reklámblokkoló
waterfox-blocker-reenable-conflict-message = A Waterfox reklámblokkoló és a(z) „{ $extensionName }” együttes használata hibás működést okozhat az oldalakon. Melyiket szeretné megtartani?
waterfox-blocker-reenable-use-built-in = Beépített blokkoló használata
waterfox-blocker-reenable-keep-extension = Kiegészítő blokkoló megtartása
waterfox-blocker-extension-install-manage-settings = A reklámblokkolást a Beállítások > Adatvédelem és biztonság menüben kezelheti.
waterfox-blocker-extension-install-anyway = Telepítés mindenképp
waterfox-blocker-extension-install-keep-built-in = Beépített blokkoló használatának megtartása
waterfox-blocked-page-title = A Waterfox blokkolta ezt az oldalt
waterfox-blocked-page-heading = A Waterfox blokkolta ezt az oldalt
waterfox-blocked-page-description = Ezt az oldalt egy reklámblokkolási szűrőszabály blokkolta.
waterfox-blocked-page-details =
    .aria-label = Blokkolt oldal részletei
waterfox-blocked-page-blocked-url-label = Blokkolt URL
waterfox-blocked-page-matched-rule-label = Egyező szabály
waterfox-blocked-page-unavailable = Nem érhető el
waterfox-blocked-page-hint = A „Betöltés mindenképp” ideiglenesen engedélyezi ezt az oldalt a munkamenet hátralévő részére.
waterfox-blocked-page-go-back = Vissza
waterfox-blocked-page-load-anyway = Betöltés mindenképp
waterfox-data-collection-header = { -brand-short-name } adatgyűjtés és adatfelhasználás
    .searchkeywords = adatvédelem telemetria adatgyűjtés adatkezelési tájékoztató
waterfox-data-collection-description = A { -brand-short-name } nem gyűjt telemetriai vagy használati adatokat. Az opcionális szolgáltatásokra, például a Syncre, saját adatvédelmi tájékoztatóik vonatkozhatnak. Az <a data-l10n-name="privacy-notice">Adatvédelmi tájékoztató</a> itt található a könnyebb elérés érdekében.
