# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-auto =
    .label = Динамічно встановлювати світлий/темний режим
dynamic-theme-dark =
    .label = Примусово темний режим
dynamic-theme-light =
    .label = Примусово світлий режим
dynamic-theme-header = Динамічні теми
pane-theme-title = Зовнішній вигляд і поведінка
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Анімації
appearance-header = Зовнішній вигляд
autohide-hidden-header = Автоховання та приховане
bookmark-header = Рядок закладок
center-header = Вирівняти по центру
font-header = Шрифти
full-screen-header = Повний екран
icons-header = Іконки
interface-component-header = Складники інтерфейсу
media-player-header = Програвач медіа
nav-bar-header = Панель навігації
panels-header = Панелі
rounding-header = Скруглення
sidebar-header = Бічна панель
tab-bar-header = Панель вкладок
theme-header = Тема
preset-title = Пресети
lepton-style =
    .label = Стиль Lepton
proton-style =
    .label = Стиль Proton
waterfox-defaults =
    .label = Стандартно у Waterfox
auto-blur-tabs =
    .label = Автоматично розмивати вкладки
auto-hide-back =
    .label = Автоматично приховувати кнопку «Назад»
auto-hide-bookmarkbar =
    .label = Автоматично приховувати рядок закладок
auto-hide-forward =
    .label = Автоматично приховувати кнопку «Вперед»
auto-hide-navbar =
    .label = Автоматично приховувати панель навігації
auto-hide-pageaction =
    .label = Автоматично приховувати дії сторінки
auto-hide-sidebar =
    .label = Автоматично приховувати бічну панель
auto-hide-tabbar =
    .label = Автоматично приховувати панель вкладок
auto-hide-tabs =
    .label = Автоматично приховувати вкладки
center-navbar-text =
    .label = Вирівняти по центру текст панелі навігації
center-tab-content =
    .label = Вирівняти по центру зміст вкладки
center-tab-label =
    .label = Вирівняти по центру тільки назву
close-button-hover =
    .label = Показувати кнопку «Закрити» при наведенні на обрану вкладку, коли вкладок багато
compact-bookmark-menu =
    .label = Зменшити відступи в меню закладок
compact-context-menu =
    .label = Зменшити відступи в контекстному меню
compact-navbar-popup =
    .label = Зменшити відступи в панелі навігації
compact-panel-header =
    .label = Зменшити відступи в заголовках панелей
disable-panel-animate =
    .label = Вимкнути анімацію панелі меню застосунку
disable-sidebar-animate =
    .label = Вимкнути анімацію бічної панелі
drag-space =
    .label = Увімкнути фіксовану зону перетягування
enable-cyan-accent-color =
    .label = Блакитний колір акценту
enable-default-accent-color =
    .label = Колір акценту за замовчуванням
enable-menu-transparency =
    .label = Увімкнути прозорість меню
enable-panel-transparency =
    .label = Увімкнути прозорість панелей
enable-system-accent-color =
    .label = Системний колір акценту
enable-waterfox-theme-0 =
    .label = Увімкнути налаштування тем Waterfox для усіх тем
enable-waterfox-theme-1 =
    .label = Увімкнути налаштування тем Waterfox для тем Waterfox
enable-waterfox-theme-2 =
    .label = Вимкнути налаштування тем Waterfox
full-panel-strip =
    .label = Роздільник меню застосунку на повну ширину
remove-panel-strip =
    .label = Прибрати кольоровий роздільник меню застосунку
hide-all-icons =
    .label = Приховати усі іконки
hide-bookmarkbar-icon =
    .label = Приховати іконки в рядку закладок
hide-bookmarkbar-label =
    .label = Приховати імена в рядку закладок
hide-disabled-menuitems =
    .label = Приховати неактивні пункти меню
hide-sidebar-header =
    .label = Приховати заголовок бічної панелі
hide-tab-icons =
    .label = Приховати іконки вкладок
hide-urlbar-iconbox =
    .label = Приховати область іконок адресного рядка
monospace-font =
    .label = Ввімкнути моноширинний шрифт для сторінки
monospace-font-theme =
    .label = Ввімкнути моноширинний шрифт для теми
show-mac-menu-icons =
    .label = Показати іконки меню Mac
show-menu-icons =
    .label = Показати іконки меню
square-button-edges =
    .label = Квадратні кути кнопок
square-checkbox =
    .label = Прапорець із квадратними кутами
square-field =
    .label = Квадратні кути полів для введення
square-menu-item =
    .label = Квадратні кути елементів контекстного меню
square-menu-panel =
    .label = Квадратні кути панелі меню застосунку
square-menu-popup =
    .label = Квадратні кути панелі контекстного меню
square-panel-item =
    .label = Квадратні кути елементів меню застосунку
square-tab-edges =
    .label = Квадратні кути вкладок
tab-context-line =
    .label = Контекстна лінія вкладок
waterfox-appearance-statusbar-heading =
    .label = Рядок стану
waterfox-appearance-statusbar-enabled-toggle =
    .label = Показати рядок стану
    .description = Показувати панель інструментів у нижній частині вікна.
waterfox-appearance-statusbar-links-toggle =
    .label = Показувати кінцеві адреси у рядку стану
waterfox-appearance-browser-style-group =
    .label = Стиль браузера
    .description = Оберіть загальний вигляд Waterfox.
waterfox-appearance-browser-style-option-nova =
    .label = Нова
    .title = Фірмовий вигляд Waterfox у типовому інтерфейсі браузера.
waterfox-appearance-browser-style-option-proton =
    .label = Протон
    .title = Стиль сучасного типового браузера.
waterfox-appearance-browser-style-option-photon =
    .label = Фотон
    .title = Класичний стиль Waterfox з витонченим інтерфейсом.
waterfox-appearance-theme-colors-group =
    .label = Колірна палітра
    .description = Виберіть колірну палітру Waterfox та вкажіть, чи має вона відповідати системній темі.
waterfox-appearance-theme-mode-picker =
    .label = Режим теми
waterfox-appearance-theme-mode-option-system =
    .label = Системна
waterfox-appearance-theme-mode-option-light =
    .label = Світла
waterfox-appearance-theme-mode-option-dark =
    .label = Темна
waterfox-appearance-theme-color-picker =
    .label = Колірна тема
waterfox-appearance-theme-color-option-default =
    .label = Типово
waterfox-appearance-theme-color-option-smoke =
    .label = Дим
waterfox-appearance-theme-color-option-ash =
    .label = Попіл
waterfox-appearance-theme-color-option-sun =
    .label = Сонце
waterfox-appearance-theme-color-option-spark =
    .label = Іскра
waterfox-appearance-theme-color-option-flame =
    .label = Полум’я
waterfox-appearance-theme-color-option-flare =
    .label = Спалах
waterfox-appearance-theme-color-option-lavender =
    .label = Лаванда
waterfox-appearance-theme-color-option-dusk =
    .label = Сутінки
waterfox-appearance-theme-color-option-lagoon =
    .label = Лагуна
waterfox-appearance-theme-color-option-tide =
    .label = Приплив
waterfox-appearance-theme-color-option-pine =
    .label = Сосна
waterfox-appearance-details-group =
    .label = Більше параметрів вигляду
    .description = Тонке налаштування інтерфейсу Waterfox.
waterfox-appearance-transparent-toggle =
    .label = Прозорі панелі та меню
waterfox-appearance-autohide-tabbar-toggle =
    .label = Приховати панель вкладок, доки ви не наведете на неї вказівник
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Приховати панель закладок, доки ви не наведете на неї вказівник
waterfox-appearance-autohide-sidebar-toggle =
    .label = Приховати бічну панель, доки ви не наведете на неї вказівник
waterfox-appearance-autohide-navigation-toggle =
    .label = Приховати кнопки «Назад» і «Вперед», якщо вони не виконують жодних дій
waterfox-appearance-close-button-hover-toggle =
    .label = Показувати кнопку закриття вкладки лише при наведенні
waterfox-appearance-drag-space-toggle =
    .label = Залишати місце для перетягування над вкладками
waterfox-density-group =
    .label = Щільність
    .description = Визначає, скільки вільного простору матимуть панелі інструментів і меню.
waterfox-density-compact =
    .label = Компактно
waterfox-density-normal =
    .label = Звичайно
waterfox-density-touch =
    .label = Для сенсорного керування
waterfox-appearance-interface-customizations-group =
    .label = Налаштування інтерфейсу
    .description = Додаткове налаштування вкладок, панелей інструментів, іконок і контенту.
waterfox-appearance-chrome-sheet =
    .label = Завантажити налаштування інтерфейсу
    .description = Вимкніть задля вивантаження таблиці стилів інтерфейсу Waterfox та прибирання опцій, які вона контролює.
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = Вбудовані теми
waterfox-appearance-chrome-sheet-all-themes =
    .label = Усі теми
waterfox-appearance-chrome-sheet-off =
    .label = Вимкнуто
waterfox-opt-tabbar-heading =
    .label = Панель вкладок
    .description = Розмір, інтервал і видимість смужки, у якій розташовані ваші вкладки.
waterfox-opt-tabbar-fill-width =
    .label = Розтягувати вкладки для заповнення усієї ширини
waterfox-opt-tabbar-as-titlebar =
    .label = Показувати тільки поточну вкладку у заголовку програми
waterfox-opt-hidden-tabbar =
    .label = Сховати панель вкладок
waterfox-opt-hidden-titlebar-container =
    .label = Сховати контейнер панелі вкладок
waterfox-opt-autohide-tab =
    .label = Зменшити вкладки на задньому фоні доти, доки ви не наведете на них вказівник
waterfox-opt-autohide-tab-opacity =
    .label = Також зробити їх напівпрозорими
waterfox-opt-autohide-tab-blur =
    .label = Також зробити їх розмитими
waterfox-opt-padding-tabbar-width =
    .label = Звузити панель вкладок
waterfox-opt-padding-tabbar-height =
    .label = Скоротити панель вкладок
waterfox-opt-padding-first-tab =
    .label = Залишати проміжок перед першою вкладкою
waterfox-opt-padding-first-tab-always =
    .label = Зберігати проміжок навіть у розгорнутому вікні
waterfox-opt-padding-drag-space =
    .label = Зберігати простір для перетягування над вкладками
waterfox-opt-padding-drag-space-maximized =
    .label = Зберігати його у розгорнутому вікні також
waterfox-opt-centered-tab =
    .label = Вирівнювати вміст вкладки по центру
waterfox-opt-centered-tab-label =
    .label = Вирівнювати по центру лише назву
waterfox-opt-counter-tab =
    .label = Показувати лічильник вкладок
waterfox-opt-tabs-heading =
    .label = Вкладки
    .description = Фігура вкладок і те, що вони показують.
waterfox-opt-tab-connect-to-window =
    .label = З'єднувати обрану вкладку із панеллю інструментів знизу
waterfox-opt-tab-color-like-toolbar =
    .label = Розфарбовувати вкладку у колір панелі інструментів
waterfox-opt-tab-box-shadow =
    .label = Кидати тінь під обраною вкладкою
waterfox-opt-tab-selected-bold =
    .label = Робити назву вкладки жирною
waterfox-opt-tab-blue-accent =
    .label = Використовувати синє підкреслення на обраній вкладці
waterfox-opt-tab-contextline-blue-accent =
    .label = Використовувати синє підкреслення на контекстній лінії
waterfox-opt-tab-bottom-rounded-corner =
    .label = Округлювати нижні кути обраної вкладки
waterfox-opt-tab-bottom-rounded-corner-all =
    .label = Округлювати кути усіх вкладок
waterfox-opt-tab-multi-selected =
    .label = Виразніше виділяти кілька вибраних вкладок
waterfox-opt-tab-letters-cleary =
    .label = Зберігати назву читабельною на вузьких вкладках
waterfox-opt-hidden-tab-icon =
    .label = Сховати іконки вкладок
waterfox-opt-hidden-tab-icon-always =
    .label = Ховати їх навіть на закріплених вкладках
waterfox-opt-tab-close-button-at-hover =
    .label = Показувати кнопку «Закрити» тільки за наведення
waterfox-opt-tab-close-button-at-hover-always =
    .label = Робити це незалежно від кількості відкритих вкладок
waterfox-opt-tab-close-button-at-hover-with-selected =
    .label = Включно із обраною вкладкою
waterfox-opt-tab-close-button-at-pinned =
    .label = Показувати кнопку «Закрити» на закріплених вкладках
waterfox-opt-tab-close-button-at-pinned-always =
    .label = Показувати її без наведення
waterfox-opt-tab-close-button-at-pinned-background =
    .label = Додати їй тло
waterfox-opt-tab-container =
    .label = Позначати вкладки контейнера їхнім кольором
waterfox-opt-tab-container-on-top =
    .label = Розміщувати маркер над вкладкою
waterfox-opt-tab-container-always-long =
    .label = Розтягнути його на всю ширину вкладки
waterfox-opt-tab-sound-with-favicons =
    .label = Показувати індикатор звуку поверх іконки вкладки
waterfox-opt-tab-sound-with-favicons-on-center =
    .label = Вирівнювати його по центру іконки
waterfox-opt-tab-unloaded =
    .label = Робити вивантажені вкладки напівпрозорими
waterfox-opt-tab-crashed =
    .label = Показувати на аварійно завершених вкладках лише індикатор збою
waterfox-opt-tab-pip =
    .label = Позначати вкладки, що відтворюють відео в режимі «картинка в картинці»
waterfox-opt-tab-padding =
    .label = Відступи вкладок
waterfox-opt-tab-padding-default =
    .label = За замовчуванням
waterfox-opt-tab-padding-lepton =
    .label = Просторі
waterfox-opt-tab-padding-photon =
    .label = Компактні
waterfox-opt-tab-separator =
    .label = Розділювач між вкладками
waterfox-opt-tab-separator-none =
    .label = Нема
waterfox-opt-tab-separator-dynamic =
    .label = Тільки між необраними вкладками
waterfox-opt-tab-separator-static =
    .label = Між кожною вкладкою
waterfox-opt-tab-separator-bar =
    .label = Розділювач у всю висоту
waterfox-opt-tab-newtab-button =
    .label = Кнопка нової вкладки
waterfox-opt-tab-newtab-button-default =
    .label = За замовчуванням
waterfox-opt-tab-newtab-button-like-tab =
    .label = У формі вкладки
waterfox-opt-tab-newtab-button-smaller =
    .label = Менше
waterfox-opt-tab-newtab-button-proton =
    .label = Протон
waterfox-opt-tab-contextline =
    .label = Індикатор обраної вкладки
waterfox-opt-tab-contextline-none =
    .label = Нема
waterfox-opt-tab-contextline-photon =
    .label = Смужка над вкладкою
waterfox-opt-tab-contextline-supernova =
    .label = Смужка під вкладкою
waterfox-opt-tab-corner-style =
    .label = Фігура нижніх кутів
waterfox-opt-tab-corner-style-default =
    .label = За замовчуванням
waterfox-opt-tab-corner-style-australis =
    .label = Australis
waterfox-opt-tab-corner-style-chrome =
    .label = Chrome
waterfox-opt-tab-corner-style-chrome-legacy =
    .label = Chrome (застарілий)
waterfox-opt-tab-corner-style-edge =
    .label = Edge
waterfox-opt-tab-corner-style-wave =
    .label = Хвиля
waterfox-opt-tab-static-separator-selected-accent =
    .label = Виділяти роздільник поряд із обраною вкладкою
waterfox-opt-toolbars-heading =
    .label = Панелі інструментів
    .description = Кнопки навігації, інтервали на панелі інструментів і те, що приховується автоматично.
waterfox-opt-combined-nav-button =
    .label = Групувати кнопки навігації разом
waterfox-opt-hidden-navbar =
    .label = Приховувати панель навігації
waterfox-opt-autohide-navbar =
    .label = Приховувати її доки ви не наведете на неї курсор
waterfox-opt-autohide-back-button =
    .label = Приховувати кнопку «Назад» у разі, якщо їй нема що виконувати
waterfox-opt-autohide-forward-button =
    .label = Приховувати кнопку «Вперед» у разі, якщо їй нема що виконувати
waterfox-opt-combined-nav-button-home-button =
    .label = Включно із кнопкою домівки Waterfox
waterfox-opt-padding-toolbar-button =
    .label = Зменшити проміжки між кнопками панелі інструментів
waterfox-opt-padding-toolbar-button-compact =
    .label = Зменшити проміжки ще більше
waterfox-opt-autohide-toolbar-overlap =
    .label = Дозволити панелям інструментів, що автоматично ховаються, накладатися на сторінку
waterfox-opt-autohide-infobar =
    .label = Приховувати панелі сповіщень доки ви не наведете на них курсор
waterfox-opt-padding-infobar =
    .label = Зменшити проміжки панелі сповіщень
waterfox-opt-findbar-floating-on-top =
    .label = Розмістити панель пошуку поверх сторінки
waterfox-opt-padding-global-menubar =
    .label = Зменшити відступи у панелі меню
waterfox-opt-centered-urlbar =
    .label = Вирівнювати текст у адресному рядку по центру
waterfox-opt-autohide-fill-urlbar =
    .label = Заповнювати панель інструментів адресним рядком доки ви не наведете на неї курсор
waterfox-opt-autohide-page-action =
    .label = Приховувати кнопки дій на сторінці доки ви не наведете курсор
waterfox-opt-urlbar-always-show-page-actions =
    .label = Завжди показувати кнопки дій на сторінці
waterfox-opt-hidden-urlbar-iconbox =
    .label = Приховувати блок ідентифікації сайту
waterfox-opt-hidden-urlbar-iconbox-label-only =
    .label = Приховувати тільки його підпис
waterfox-opt-urlbar-iconbox-with-separator =
    .label = Розділяти блок ідентифікації смугою
waterfox-opt-urlview-focus-item-border =
    .label = Обводити сфокусований результат
waterfox-opt-padding-urlview-result =
    .label = Зменшити відступи між результатами
waterfox-opt-rounding-square-urlview-item =
    .label = Зробити кути результатів прямокутними
waterfox-opt-bookmarks-heading =
    .label = Закладки
    .description = Панель закладок і меню закладок.
waterfox-opt-bookmarkbar-multi-row =
    .label = Розмістити панель закладок у кілька рядків
waterfox-opt-autohide-bookmarkbar =
    .label = Приховати панель закладок, доки ви не наведете на неї вказівник
waterfox-opt-centered-bookmarkbar =
    .label = Центрувати панель закладок
waterfox-opt-padding-bookmarkbar =
    .label = Звузити панель закладок
waterfox-opt-hidden-bookmarkbar-icon =
    .label = Приховати значки закладок
waterfox-opt-hidden-bookmarkbar-label =
    .label = Приховати мітки закладок
waterfox-opt-padding-bookmark-menu =
    .label = Звузити меню закладок
waterfox-opt-padding-bookmark-menu-compact =
    .label = Звузити ще сильніше
waterfox-opt-counter-bookmark-menu =
    .label = Показувати кількість у меню закладок
waterfox-opt-decoration-disable-sidebar-animate =
    .label = Вимкнути анімацію бічної панелі
waterfox-opt-icons-heading =
    .label = Значки
    .description = Де з’являються значки та якого вони розміру.
waterfox-opt-icon-disabled =
    .label = Приховати всі значки меню та панелей
waterfox-opt-icon-menu =
    .label = Показувати значки в меню
waterfox-opt-icon-menu-full =
    .label = Показувати їх у кожному пункті меню
waterfox-opt-icon-context-menu =
    .label = Показувати значки в контекстних меню
waterfox-opt-icon-global-menu =
    .label = Показувати значки в меню на панелі
waterfox-opt-icon-global-menu-mac =
    .label = Також показувати на macOS
waterfox-opt-icon-global-menubar =
    .label = Показувати значки в рядку меню
waterfox-opt-icon-panel =
    .label = Показувати значки в панелях
waterfox-opt-icon-library =
    .label = Показувати значки в бібліотеці
waterfox-opt-icon-1-25px-stroke =
    .label = Використовувати товстіші лінії значків
waterfox-opt-icon-account-image-to-right =
    .label = Розмістити зображення облікового запису праворуч
waterfox-opt-icon-account-label-to-right =
    .label = Розмістіть назву облікового запису праворуч
waterfox-opt-panel-icons =
    .label = Значки меню застосунку
    .description = Скільки рядків головного меню Waterfox містять значки.
waterfox-opt-panel-icons-photon =
    .label = Лише основні елементи
waterfox-opt-panel-icons-full =
    .label = Кожен елемент
waterfox-opt-rounding-heading =
    .label = Кути
    .description = Прибрати заокруглення кутів інтерфейсу.
waterfox-opt-rounding-square-tab =
    .label = Зробити кути вкладок прямими
waterfox-opt-rounding-square-toolbar =
    .label = Зробити кути панелі інструментів прямими
waterfox-opt-rounding-square-button =
    .label = Зробити кути кнопок прямими
waterfox-opt-rounding-square-field =
    .label = Зробити кути текстового поля прямими
waterfox-opt-rounding-square-checklabel =
    .label = Зробити кути прапорців прямими
waterfox-opt-rounding-square-dialog =
    .label = Зробити кути діалогового вікна прямими
waterfox-opt-rounding-square-infobox =
    .label = Зробити кути сповіщень прямими
waterfox-opt-rounding-square-panel =
    .label = Зробити кути панелі прямими
waterfox-opt-rounding-square-panelitem =
    .label = Зробити кути елементів панелі прямими
waterfox-opt-rounding-square-menupopup =
    .label = Зробити кути меню прямими
waterfox-opt-rounding-square-menuitem =
    .label = Зробити кути пунктів меню прямими
waterfox-opt-theme-heading =
    .label = Тема та ефекти
    .description = Колір, прозорість та анімація в інтерфейсі.
waterfox-opt-theme-proton-color =
    .label = Використовувати палітру кольорів Протон на вбудованих сторінках
    .description = Застосовується до сторінок about: та інших вбудованих переглядів, а не до рамки браузера.
waterfox-opt-theme-proton-chrome =
    .label = Застосувати до діалогових вікон та вікон бібліотеки
waterfox-opt-theme-fully-color =
    .label = Застосувати всюди
waterfox-opt-theme-fully-dark =
    .label = Запобігати спалахам світла в темному режимі
waterfox-opt-theme-built-in-contrast =
    .label = Підвищити контрастність вбудованих тем
waterfox-opt-theme-system-default =
    .label = Використовувати системну тему
waterfox-opt-theme-private =
    .label = Затінювати приватні вікна
waterfox-opt-hidden-private-indicator =
    .label = Приховати індикатор приватного перегляду
waterfox-opt-theme-transparent-panel =
    .label = Зробити панелі прозорими
waterfox-opt-theme-transparent-frame =
    .label = Зробити рамку вікна прозорою
waterfox-opt-theme-monospace =
    .label = Використовувати моноширинний шрифт в інтерфейсі
waterfox-opt-decoration-animate =
    .label = Анімувати зміни інтерфейсу
waterfox-opt-decoration-disable-panel-animate =
    .label = Вимкнути анімацію меню застосунку
waterfox-opt-content-heading =
    .label = Вебсторінки
    .description = Стилі, які Waterfox застосовує поверх вебсторінок.
waterfox-opt-page-monospace =
    .label = Використовувати моноширинний шрифт на вбудованих сторінках
waterfox-opt-page-dark-mode-pdf =
    .label = Темний режим для PDF-файлів при використанні темної теми
waterfox-opt-newtab-heading =
    .label = Сторінка нової вкладки
    .description = Вигляд сторінки, на яку ви потрапляєте у новій вкладці.
waterfox-opt-newtab-hidden-logo =
    .label = Приховати логотип
waterfox-opt-newtab-full-icon =
    .label = Заповнити плитки ярликів їхніми значками
waterfox-opt-newtab-background-image =
    .label = Показувати фонове зображення
waterfox-opt-newtab-animate =
    .label = Анімувати плитки
waterfox-opt-player-heading =
    .label = Відеопрогравач
    .description = Елементи керування та налаштування розміру вбудованого відеопрогравача.
waterfox-opt-player-ui =
    .label = Змінити стиль вбудованих елементів керування відео
waterfox-opt-player-ui-twoline =
    .label = Розмістити елементи керування у два рядки
waterfox-opt-player-icon =
    .label = Використовувати значки керування Waterfox
waterfox-opt-player-size =
    .label = Збільшити елементи керування
waterfox-opt-player-noaudio =
    .label = Приховати регулятор гучності, якщо у відео немає звуку
waterfox-opt-player-click-to-play =
    .label = Стилізувати накладання «натисніть для відтворення»
    .description = Додає стилізацію при наведенні та курсор у формі руки до наявного накладання.
waterfox-opt-player-animate =
    .label = Анімувати елементи керування
