# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-page-title = Живі закладки
feeds-page-description = Підписуйтеся на RSS- та Atom-стрічки за допомогою живих закладок.
feeds-private-notice = У режимі приватного перегляду функції підписки на стрічки, їх видалення, оновлення та імпорту вимкнено. Ви все ще можете переглядати кешовані елементи або експортувати свої підписки.
feeds-subscribe-heading = Підписатися на стрічку
feeds-url-label = URL-адреса стрічки
feeds-title-label = Назва (необов'язково)
feeds-subscribe-note = Підписки зберігаються окремо від Sync, у меню закладок на цьому пристрої. Стрічки оновлюються у фоновому режимі без надсилання кукі чи облікових даних на сервер стрічки.
feeds-subscribe-button = Підписатися
    .label = Підписатися
    .accesskey = П
feeds-subscribe-title =
    .value = Назва
    .accesskey = Н
feeds-subscribe-url =
    .value = URL-адреса стрічки
    .accesskey = а
feeds-subscribe-folder =
    .value = Зберегти в
    .accesskey = і
feeds-subscribe-choose-folder =
    .label = Оберіть іншу теку…
feeds-subscribe-untitled-folder =
    .label = Тека без назви
feeds-subscribe-cancel =
    .label = Скасувати
    .accesskey = С
feeds-subscribe-private = Підписки на стрічки не можна змінювати в приватному вікні.
feeds-subscribe-busy = Підписка… Закриття цієї панелі не скасує підписку.
feeds-subscribe-invalid-url = Введіть URL-адресу HTTP або HTTPS стрічки без імені користувача та пароля (не більше 4096 символів).
feeds-subscribe-invalid-title = Обмежте довжину назви до 1024 символів або менше.
feeds-subscribe-folder-error = Виберіть наявну теку закладок і спробуйте ще раз.
feeds-subscribe-error = Не вдалося підписатися на цю стрічку. Перевірте URL-адресу стрічки та теку призначення й спробуйте ще раз.
feeds-subscribe-setup-error = Не вдалося завантажити панель підписок. Закрийте її та спробуйте ще раз.
feeds-subscriptions-heading = Ваші підписки
feeds-import-button = Імпортувати OPML…
feeds-export-button = Експортувати OPML…
feeds-empty = Поки що немає підписок на стрічки.
feeds-preview-button = Прев'ю
    .aria-label = Прев'ю { $title }
feeds-reload-button = Перезавантажити
    .aria-label = Перезавантажити { $title }
feeds-remove-button = Вилучити
    .aria-label = Вилучити { $title }
feeds-preview-heading = Прев'ю стрічки
feeds-preview-note = Відображаються лише кешовані назви та посилання (до 200 елементів). Посилання на статті відкриваються в новій вкладці.
feeds-preview-empty = Немає кешованих елементів. Перезавантажте цю підписку у звичайному вікні (не в режимі приватності), щоб отримати найновіші елементи.
feeds-item-untitled = Елемент без назви
feeds-status-loading = Завантаження підписок…
feeds-status-working = Виконується…
feeds-status-ready = Підписки завантажено.
feeds-status-subscribed = Підписано на стрічку.
feeds-status-removed = Підписку вилучено.
feeds-status-reloaded = Стрічку перезавантажено.
feeds-status-preview = Відображення кешованих елементів.
feeds-status-canceled = Операцію скасовано.
feeds-status-exported = Підписки експортовано.
feeds-status-imported =
    { $count ->
        [one] Імпортовано одну підписку.
        [few] Імпортовано { $count } підписки.
        [many] Імпортовано { $count } підписок.
       *[other] Імпортовано { $count } підписки.
    }
feeds-error-unavailable = На цій сторінці керування стрічками недоступне. Відкрийте about:feeds у новій вкладці.
feeds-error-private = Відкрийте цю сторінку у звичайному (не приватному) вікні, щоб змінити підписки або оновити стрічки.
feeds-error-invalid-request = Запит щодо стрічки був недійсним.
feeds-error-invalid-url = Введіть дійсну URL-адресу HTTP або HTTPS стрічки без імені користувача та пароля.
feeds-error-busy = Наразі триває інша операція з обробки стрічки. Спробуйте ще раз після її завершення.
feeds-error-not-found = Цієї підписки більше не існує.
feeds-error-operation = Не вдалося виконати операцію зі стрічкою. Перевірте адресу стрічки та з’єднання. Тут не можна видалити теку зі збереженими закладками.
feeds-error-not-active = Виберіть цю вкладку перед відкриттям засобу вибору файлів.
feeds-error-invalid-opml = Виберіть дійсний файл OPML у кодуванні UTF-8 без DTD або оголошень сутностей.
feeds-error-file-too-large = Виберіть файл OPML не більше 2 МіБ.
feeds-import-picker-title = Імпорт підписок на стрічки
feeds-export-picker-title = Експорт підписок на стрічки
feeds-opml-file-filter = Файли OPML
feeds-export-filename = feeds.opml
feeds-page-action = Підписатися на стрічки на цій сторінці
feeds-toolbar-button =
    .label = Живі закладки
    .tooltiptext = Знаходьте стрічки та керуйте живими закладками
feeds-menu-label =
    .label = Живі закладки
    .accesskey = Ж
feeds-menu-manage =
    .label = Керувати живими закладками…
feeds-menu-discovering =
    .label = Пошук стрічок на цій сторінці…
feeds-menu-no-feeds =
    .label = На цій сторінці немає доступних стрічок
feeds-menu-all-subscribed =
    .label = Ви вже підписані на всі стрічки на цій сторінці
feeds-menu-subscribe =
    .label = Підписатися на { $title }…
    .tooltiptext = { $url }
feeds-menu-open-site =
    .label = Відкрити сайт стрічки
    .tooltiptext = { $url }
feeds-menu-reload =
    .label = Перезавантажити живу закладку
feeds-menu-loading =
    .label = Завантаження стрічки…
feeds-menu-empty =
    .label = У цій стрічці немає елементів
feeds-menu-error =
    .label = Не вдалося оновити стрічку. Спробую ще раз пізніше.
feeds-menu-no-cache =
    .label = Перезавантажте в звичайному (не приватному) вікні, щоб завантажити елементи
feeds-entry-visited =
    .label = { $title }
    .aria-label = { $title } (відвідано)
    .tooltiptext = { $url } (відвідано)
feeds-entry-unvisited =
    .label = { $title } (не відвідано)
    .aria-label = { $title } (не відвідано)
    .tooltiptext = { $url } (не відвідано)
