# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

onboarding-grassroots-title = Підтримка громадських ініціатив
onboarding-grassroots-subtitle = Щиро дякуємо за використання Waterfox, незалежного браузера, який розвивається завдяки зусиллям громади. Ваша підтримка допомагає нам створювати стабільну альтернативу великим гравцям на ринку.
waterfox-onboarding-welcome-title = Вітаємо у { -brand-short-name }
waterfox-onboarding-welcome-subtitle = Незалежний, швидкий і створений з елементами керування Waterfox, на які ви очікуєте.
waterfox-onboarding-start-button = Розпочнімо
waterfox-onboarding-import-title = Візьміть свої дані із собою
waterfox-onboarding-import-subtitle = Імпортуйте закладки, історію та дані форм із { migration-wizard-migrator-display-name-firefox } або іншого браузера, не виходячи з цього налаштування.
waterfox-onboarding-style-title = Оберіть стиль Waterfox
waterfox-onboarding-style-subtitle = Оберіть форму вкладок і панелі інструментів, а також те, наскільки компактно вони виглядають.
waterfox-onboarding-style-photon-label = Фотон
waterfox-onboarding-style-photon-body = Класичний вигляд Waterfox з удосконаленим інтерфейсом.
waterfox-onboarding-style-proton-label = Протон
waterfox-onboarding-style-proton-body = Лаконічніший макет із сучасними міжрядковими інтервалами браузера.
waterfox-onboarding-style-nova-label = Нова
waterfox-onboarding-style-nova-body = Виразніший стиль Waterfox із яскравішою лінією поточної вкладки.
waterfox-onboarding-density-normal-label = Нормальна
waterfox-onboarding-density-compact-label = Компактна
waterfox-onboarding-density-touch-label = Дотик
waterfox-onboarding-theme-color-title = Зробіть його своїм
waterfox-onboarding-theme-color-subtitle = Виберіть колір теми, щоби зробити кожне вікно особливим.
waterfox-onboarding-theme-mode-system-label = Системна
waterfox-onboarding-theme-mode-light-label = Світла
waterfox-onboarding-theme-mode-dark-label = Темна
waterfox-onboarding-color-default-label = Типовий
waterfox-onboarding-color-smoke-label = Дим
waterfox-onboarding-color-ash-label = Попіл
waterfox-onboarding-color-sun-label = Сонце
waterfox-onboarding-color-spark-label = Іскра
waterfox-onboarding-color-flame-label = Полум’я
waterfox-onboarding-color-flare-label = Спалах
waterfox-onboarding-color-lavender-label = Лаванда
waterfox-onboarding-color-dusk-label = Сутінки
waterfox-onboarding-color-lagoon-label = Лагуна
waterfox-onboarding-color-tide-label = Приплив
waterfox-onboarding-color-pine-label = Сосна
waterfox-onboarding-tabs-title = Впорядковуйте вкладки як вам зручно
waterfox-onboarding-tabs-subtitle = Виберіть спосіб упорядкування вкладок та розташування горизонтальної панелі вкладок. Ви зможете змінити обидва параметри пізніше в налаштуваннях.
waterfox-onboarding-tabs-horizontal-label = Горизонтальні вкладки
waterfox-onboarding-tabs-horizontal-body = Залишити класичну панель вкладок угорі.
waterfox-onboarding-tabs-vertical-label = Вертикальні вкладки
waterfox-onboarding-tabs-vertical-body = Пересувайте вкладки на бічну панель у вигляді вертикального списку.
waterfox-onboarding-tabs-tree-label = Деревоподібні вкладки
waterfox-onboarding-tabs-tree-body = Вертикальні вкладки, що групуються під вкладкою, з якої їх відкрили.
waterfox-onboarding-location-top-above-label = Над панеллю інструментів
waterfox-onboarding-location-top-below-label = Під панеллю інструментів
waterfox-onboarding-location-bottom-above-label = Над рядком стану
waterfox-onboarding-location-bottom-below-label = Під рядком стану
waterfox-onboarding-privacy-title = Інструменти для захисту приватності вже готові
waterfox-onboarding-privacy-subtitle = Waterfox одразу забезпечує блокування реклами та надійний захист приватності. За потреби ви можете налаштувати ці функції будь-коли.
waterfox-onboarding-privacy-primary-button = Залишити захист увімкненим
waterfox-onboarding-default-title = Зробити { -brand-short-name } вашим типовим браузером
waterfox-onboarding-default-subtitle = Зробіть { -brand-short-name } типовим браузером, щоб у ньому відкривати всі посилання та завжди мати доступ до свого Waterfox.
waterfox-onboarding-default-primary-button = Встановити як типовий
waterfox-onboarding-finish-title = Все готово
waterfox-onboarding-finish-subtitle = Дякуємо за вибір Waterfox. Ваш браузер готовий до використання.
waterfox-onboarding-finish-primary-button = Почати перегляд вебсторінок
waterfox-onboarding-skip-button = Не зараз
waterfox-onboarding-skip-step-button = Пропустити цей крок
waterfox-onboarding-continue-button = Продовжити
waterfox-onboarding-save-continue-button = Зберегти та продовжити
waterfox-onboarding-customize-appearance-button = Налаштувати зовнішній вигляд у Налаштуваннях
waterfox-onboarding-customize-tabs-button = Налаштувати вкладки у Налаштуваннях
waterfox-onboarding-customize-privacy-button = Налаштувати параметри приватності
waterfox-onboarding-language-hint = Ви можете змінити це будь-коли в налаштуваннях.
waterfox-onboarding-language-error = { -brand-short-name } не вдалося змінити мову. Ваша попередня мова все ще активна.
waterfox-onboarding-step-label = { $current }-й крок із { $total }
waterfox-onboarding-tabs-style-legend = Стиль браузера
waterfox-onboarding-tabs-density-legend = Густина
waterfox-onboarding-appearance-subtitle = Оберіть форму, густину та колір. Ви зможете точно налаштувати все пізніше в «Налаштуваннях».
waterfox-onboarding-theme-mode-legend = Кольорова схема
waterfox-onboarding-theme-color-legend = Колір теми
waterfox-onboarding-tabs-layout-legend = Розташування вкладок
waterfox-onboarding-tabs-location-label = Розташування панелі вкладок
waterfox-onboarding-tabs-location-hint = Застосовується до горизонтальних вкладок. Більше позицій — у налаштуваннях.
waterfox-onboarding-finish-privacy-note = Блокування реклами та захист від відстеження вже ввімкнено.
waterfox-onboarding-back-button = Назад
