# This Source Code Form is subject to the terms of the BrowserWorks Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This file is in the UTF-8 encoding
[Strings]
TitleText=Actualisation de %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% installa tu actualisationes e se initiara in alcun secundas…
BrowserWorksMaintenanceDescription=Le servicio de mantenimento de BrowserWorks assecura que tu ha le version le plus nove e secur de Waterfox sur tu computator. Mantener Waterfox actual es multo importante pro tu securitate in linea e BrowserWorks recommenda fortemente de mantener iste servicio active.
