# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Tema Dinamis
dynamic-theme-dark =
    .label = Paksa Mode Gelap
dynamic-theme-light =
    .label = Paksa Mode Tenang
dynamic-theme-auto =
    .label = Atur Mode Tenang/Gelap Secara Dinamis
pane-theme-title = Tampilan & Nuansa
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animasi
appearance-header = Tampilan
autohide-hidden-header = Sembunyi Otomatis & Tersembunyi
bookmark-header = Bilah Penanda
center-header = Tengah
font-header = Font
full-screen-header = Layar penuh
icons-header = Ikon
interface-component-header = Komponen Antarmuka
media-player-header = Pemutar Media
nav-bar-header = Bilah Navigasi
panels-header = Panel
rounding-header = Pembulatan
sidebar-header = Bilah Samping
tab-bar-header = Bilah Tab
theme-header = Tema
preset-title = Preset
lepton-style =
    .label = Gaya Lepton
proton-style =
    .label = Gaya Proton
waterfox-defaults =
    .label = Bawaan Waterfox
auto-blur-tabs =
    .label = Kaburkan Tab Otomatis
auto-hide-back =
    .label = Sembunyikan Tombol Kembali Otomatis
auto-hide-bookmarkbar =
    .label = Sembunyikan Bilah Penanda Otomatis
auto-hide-forward =
    .label = Sembunyikan Tombol Maju Otomatis
auto-hide-navbar =
    .label = Sembunyikan Bilah Navigasi Otomatis
auto-hide-pageaction =
    .label = Sembunyikan Tindakan Halaman Otomatis
auto-hide-sidebar =
    .label = Sembunyikan Bilah Samping Otomatis
auto-hide-tabbar =
    .label = Sembunyikan Bilah Tab Otomatis
auto-hide-tabs =
    .label = Sembunyikan Tab Otomatis
center-navbar-text =
    .label = Pusatkan Teks Bilah Navigasi
center-tab-content =
    .label = Pusatkan Konten Tab
center-tab-label =
    .label = Pusatkan Hanya Label Tab
close-button-hover =
    .label = Tampilkan tombol tutup tab saat kursor diarahkan pada tab yang dipilih ketika banyak tab terbuka
compact-bookmark-menu =
    .label = Kurangi Jarak Menu Penanda
compact-context-menu =
    .label = Kurangi Jarak Menu Konteks
compact-navbar-popup =
    .label = Kurangi Jarak Popup Bilah Navigasi
compact-panel-header =
    .label = Kurangi Jarak Header Panel
disable-panel-animate =
    .label = Nonaktifkan animasi panel menu aplikasi
disable-sidebar-animate =
    .label = Nonaktifkan animasi panel bilah samping
drag-space =
    .label = Aktifkan Ruang Seret Tetap
enable-cyan-accent-color =
    .label = Warna Aksen Sian
enable-default-accent-color =
    .label = Warna Aksen Bawaan
enable-menu-transparency =
    .label = Aktifkan transparansi menu
enable-panel-transparency =
    .label = Aktifkan transparansi panel
enable-system-accent-color =
    .label = Warna Aksen Sistem
enable-waterfox-theme-0 =
    .label = Aktifkan kustomisasi tema Waterfox pada semua tema
enable-waterfox-theme-1 =
    .label = Aktifkan kustomisasi tema Waterfox pada tema Waterfox
enable-waterfox-theme-2 =
    .label = Nonaktifkan kustomisasi tema Waterfox
full-panel-strip =
    .label = Pemisah Menu Aplikasi Lebar Penuh
remove-panel-strip =
    .label = Hapus Pemisah Menu Aplikasi Berwarna
hide-all-icons =
    .label = Sembunyikan Semua Ikon
hide-bookmarkbar-icon =
    .label = Sembunyikan Ikon Bilah Penanda
hide-bookmarkbar-label =
    .label = Sembunyikan Label Bilah Penanda
hide-disabled-menuitems =
    .label = Sembunyikan Item Menu Nonaktif
hide-sidebar-header =
    .label = Sembunyikan Header Bilah Samping
hide-tab-icons =
    .label = Sembunyikan Ikon Tab
hide-urlbar-iconbox =
    .label = Sembunyikan Kotak Ikon Bilah URL
monospace-font =
    .label = Aktifkan font monospace untuk halaman
monospace-font-theme =
    .label = Aktifkan font monospace untuk tema
show-mac-menu-icons =
    .label = Tampilkan Ikon Menu Mac
show-menu-icons =
    .label = Tampilkan Ikon Menu
square-button-edges =
    .label = Sudut Tombol Persegi
square-checkbox =
    .label = Kotak Centang Persegi
square-field =
    .label = Sudut Kolom Entri Persegi
square-menu-item =
    .label = Sudut Item Menu Konteks Persegi
square-menu-panel =
    .label = Sudut Panel Menu Aplikasi Persegi
square-menu-popup =
    .label = Sudut Panel Menu Konteks Persegi
square-panel-item =
    .label = Sudut Item Menu Aplikasi Persegi
square-tab-edges =
    .label = Sudut Tab Persegi
tab-context-line =
    .label = Garis Konteks Tab
waterfox-appearance-statusbar-heading =
    .label = Bilah Status
waterfox-appearance-statusbar-enabled-toggle =
    .label = Tampilkan bilah status
    .description = Tampilkan bilah alat di bagian bawah jendela.
waterfox-appearance-statusbar-links-toggle =
    .label = Tampilkan tujuan tautan di bilah status
waterfox-appearance-browser-style-group =
    .label = Gaya browser
    .description = Pilih tampilan Waterfox secara keseluruhan.
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = Tampilan khas Waterfox pada chrome browser standar.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = Gaya browser standar yang modern.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = Gaya Waterfox klasik dengan chrome yang disempurnakan.
waterfox-appearance-theme-colors-group =
    .label = Palet warna
    .description = Pilih palet warna Waterfox dan apakah mengikuti tema sistem Anda.
waterfox-appearance-theme-mode-picker =
    .label = Mode tema
waterfox-appearance-theme-mode-option-system =
    .label = Sistem
waterfox-appearance-theme-mode-option-light =
    .label = Terang
waterfox-appearance-theme-mode-option-dark =
    .label = Gelap
waterfox-appearance-theme-color-picker =
    .label = Warna tema
waterfox-appearance-theme-color-option-default =
    .label = Bawaan
waterfox-appearance-theme-color-option-smoke =
    .label = Smoke
waterfox-appearance-theme-color-option-ash =
    .label = Ash
waterfox-appearance-theme-color-option-sun =
    .label = Sun
waterfox-appearance-theme-color-option-spark =
    .label = Spark
waterfox-appearance-theme-color-option-flame =
    .label = Flame
waterfox-appearance-theme-color-option-flare =
    .label = Flare
waterfox-appearance-theme-color-option-lavender =
    .label = Lavender
waterfox-appearance-theme-color-option-dusk =
    .label = Dusk
waterfox-appearance-theme-color-option-lagoon =
    .label = Lagoon
waterfox-appearance-theme-color-option-tide =
    .label = Tide
waterfox-appearance-theme-color-option-pine =
    .label = Pine
waterfox-appearance-details-group =
    .label = Lebih banyak opsi tampilan
    .description = Sesuaikan antarmuka Waterfox lebih detail.
waterfox-appearance-transparent-toggle =
    .label = Panel dan menu transparan
waterfox-appearance-autohide-tabbar-toggle =
    .label = Sembunyikan bilah tab hingga Anda mengarahkan kursor
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Sembunyikan bilah bookmark hingga Anda mengarahkan kursor
waterfox-appearance-autohide-sidebar-toggle =
    .label = Sembunyikan bilah samping hingga Anda mengarahkan kursor
waterfox-appearance-autohide-navigation-toggle =
    .label = Sembunyikan tombol mundur dan maju ketika tidak berfungsi
waterfox-appearance-close-button-hover-toggle =
    .label = Tampilkan tombol tutup tab hanya saat kursor diarahkan
waterfox-appearance-drag-space-toggle =
    .label = Pertahankan ruang seret di atas tab
waterfox-density-compact =
    .label = Ringkas
waterfox-density-normal =
    .label = Normal
waterfox-density-touch =
    .label = Sentuh
waterfox-appearance-interface-customizations-group =
    .label = Kustomisasi antarmuka
    .description = Kontrol tambahan untuk tab, bilah alat, ikon, dan konten.
waterfox-appearance-chrome-sheet =
    .label = Muat kustomisasi antarmuka
    .description = Matikan untuk melepaskan stylesheet antarmuka Waterfox dan menyembunyikan opsi yang dikendalikannya.
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = Tema bawaan
waterfox-appearance-chrome-sheet-all-themes =
    .label = Semua tema
waterfox-appearance-chrome-sheet-off =
    .label = Mati
waterfox-opt-tabbar-heading =
    .label = Bilah tab
    .description = Ukuran, jarak, dan visibilitas lajur tempat tab Anda berada.
waterfox-opt-tabbar-fill-width =
    .label = Rentangkan tab untuk mengisi lebar
waterfox-opt-tabbar-as-titlebar =
    .label = Tampilkan hanya tab saat ini di bilah judul
waterfox-opt-hidden-tabbar =
    .label = Sembunyikan bilah tab
waterfox-opt-hidden-titlebar-container =
    .label = Sembunyikan kontainer bilah judul
waterfox-opt-autohide-tab =
    .label = Menciutkan tab latar belakang hingga Anda mengarahkan kursor
waterfox-opt-autohide-tab-opacity =
    .label = Redupkan juga
waterfox-opt-autohide-tab-blur =
    .label = Kaburkan juga
waterfox-opt-padding-tabbar-width =
    .label = Persempit bilah tab
waterfox-opt-padding-tabbar-height =
    .label = Persingkat bilah tab
waterfox-opt-padding-first-tab =
    .label = Biarkan celah sebelum tab pertama
waterfox-opt-padding-first-tab-always =
    .label = Pertahankan celah bahkan saat dimaksimalkan
waterfox-opt-padding-drag-space =
    .label = Pertahankan ruang seret di atas tab
waterfox-opt-padding-drag-space-maximized =
    .label = Pertahankan juga saat dimaksimalkan
waterfox-opt-centered-tab =
    .label = Pusatkan konten tab
waterfox-opt-centered-tab-label =
    .label = Pusatkan hanya label
waterfox-opt-counter-tab =
    .label = Tampilkan jumlah tab
waterfox-opt-tabs-heading =
    .label = Tab
    .description = Bentuk tab dan apa yang ditampilkannya.
waterfox-opt-tab-connect-to-window =
    .label = Gabungkan tab yang dipilih dengan bilah alat di bawahnya
waterfox-opt-tab-color-like-toolbar =
    .label = Warnai tab yang dipilih seperti bilah alat
waterfox-opt-tab-box-shadow =
    .label = Berikan bayangan di bawah tab yang dipilih
waterfox-opt-tab-selected-bold =
    .label = Tebalkan label tab yang dipilih
waterfox-opt-tab-blue-accent =
    .label = Gunakan aksen biru pada tab yang dipilih
waterfox-opt-tab-contextline-blue-accent =
    .label = Gunakan aksen biru pada garis konteks
waterfox-opt-tab-bottom-rounded-corner =
    .label = Bulatkan sudut bawah tab yang dipilih
waterfox-opt-tab-bottom-rounded-corner-all =
    .label = Terapkan sudut membulat pada setiap tab
waterfox-opt-tab-multi-selected =
    .label = Sorot tab yang dipilih ganda lebih kuat
waterfox-opt-tab-letters-cleary =
    .label = Pertahankan label tetap terbaca pada tab sempit
waterfox-opt-hidden-tab-icon =
    .label = Sembunyikan ikon tab
waterfox-opt-hidden-tab-icon-always =
    .label = Sembunyikan bahkan pada tab yang disematkan
waterfox-opt-tab-close-button-at-hover =
    .label = Tampilkan tombol tutup hanya saat hover
waterfox-opt-tab-close-button-at-hover-always =
    .label = Lakukan berapa pun tab yang terbuka
waterfox-opt-tab-close-button-at-hover-with-selected =
    .label = Sertakan tab yang dipilih
waterfox-opt-tab-close-button-at-pinned =
    .label = Tampilkan tombol tutup pada tab yang disematkan
waterfox-opt-tab-close-button-at-pinned-always =
    .label = Tampilkan tanpa hover
waterfox-opt-tab-close-button-at-pinned-background =
    .label = Berikan latar belakang
waterfox-opt-tab-container =
    .label = Tandai tab kontainer dengan warnanya
waterfox-opt-tab-container-on-top =
    .label = Letakkan penanda di atas tab
waterfox-opt-tab-container-always-long =
    .label = Jalankan sepanjang lebar tab
waterfox-opt-tab-sound-with-favicons =
    .label = Tampilkan indikator suara di atas ikon tab
waterfox-opt-tab-sound-with-favicons-on-center =
    .label = Pusatkan pada ikon
waterfox-opt-tab-unloaded =
    .label = Redupkan tab yang tidak dimuat
waterfox-opt-tab-crashed =
    .label = Tampilkan hanya indikator crash pada tab yang crash
waterfox-opt-tab-pip =
    .label = Tandai tab yang memutar picture-in-picture
waterfox-opt-tab-padding =
    .label = Padding tab
waterfox-opt-tab-padding-default =
    .label = Default
waterfox-opt-tab-padding-lepton =
    .label = Lapang
waterfox-opt-tab-padding-photon =
    .label = Ringkas
waterfox-opt-tab-separator =
    .label = Pemisah antar tab
waterfox-opt-tab-separator-none =
    .label = Tidak ada
waterfox-opt-tab-separator-dynamic =
    .label = Hanya antar tab yang tidak dipilih
waterfox-opt-tab-separator-static =
    .label = Antar setiap tab
waterfox-opt-tab-separator-bar =
    .label = Bilah setinggi penuh
waterfox-opt-tab-newtab-button =
    .label = Tombol tab baru
waterfox-opt-tab-newtab-button-default =
    .label = Default
waterfox-opt-tab-newtab-button-like-tab =
    .label = Berbentuk seperti tab
waterfox-opt-tab-newtab-button-smaller =
    .label = Lebih kecil
waterfox-opt-tab-newtab-button-proton =
    .label = Proton
waterfox-opt-tab-contextline =
    .label = Indikator tab yang dipilih
waterfox-opt-tab-contextline-none =
    .label = Tidak ada
waterfox-opt-tab-contextline-photon =
    .label = Garis di atas tab
waterfox-opt-tab-contextline-supernova =
    .label = Garis di bawah tab
waterfox-opt-tab-corner-style =
    .label = Bentuk sudut bawah
waterfox-opt-tab-corner-style-default =
    .label = Default
waterfox-opt-tab-corner-style-australis =
    .label = Australis
waterfox-opt-tab-corner-style-chrome =
    .label = Chrome
waterfox-opt-tab-corner-style-chrome-legacy =
    .label = Chrome (warisan)
waterfox-opt-tab-corner-style-edge =
    .label = Edge
waterfox-opt-tab-corner-style-wave =
    .label = Gelombang
waterfox-opt-tab-static-separator-selected-accent =
    .label = Aksenkan pemisah di sebelah tab yang dipilih
waterfox-opt-toolbars-heading =
    .label = Bilah alat
    .description = Tombol navigasi, jarak bilah alat, dan apa yang menyembunyikan dirinya sendiri.
waterfox-opt-hidden-navbar =
    .label = Sembunyikan bilah alat navigasi
waterfox-opt-autohide-navbar =
    .label = Sembunyikan hingga Anda mengarahkan kursor
waterfox-opt-autohide-back-button =
    .label = Sembunyikan tombol kembali saat tidak melakukan apa-apa
waterfox-opt-autohide-forward-button =
    .label = Sembunyikan tombol maju saat tidak melakukan apa-apa
waterfox-opt-combined-nav-button =
    .label = Kelompokkan tombol navigasi bersama
waterfox-opt-combined-nav-button-home-button =
    .label = Sertakan tombol beranda
waterfox-opt-padding-toolbar-button =
    .label = Perketat jarak tombol bilah alat
waterfox-opt-padding-toolbar-button-compact =
    .label = Perketat lebih lanjut
waterfox-opt-autohide-toolbar-overlap =
    .label = Izinkan bilah alat yang disembunyikan otomatis tumpang tindih dengan halaman
waterfox-opt-autohide-infobar =
    .label = Sembunyikan bilah notifikasi hingga Anda mengarahkan kursor
waterfox-opt-padding-infobar =
    .label = Perketat padding bilah notifikasi
waterfox-opt-findbar-floating-on-top =
    .label = Melayangkan bilah temuan di atas halaman
waterfox-opt-padding-global-menubar =
    .label = Perketat bilah menu
waterfox-opt-centered-urlbar =
    .label = Pusatkan teks bilah alamat
waterfox-opt-autohide-fill-urlbar =
    .label = Isi bilah alat dengan bilah alamat hingga Anda mengarahkan kursor
waterfox-opt-autohide-page-action =
    .label = Sembunyikan tombol aksi halaman hingga Anda mengarahkan kursor
waterfox-opt-urlbar-always-show-page-actions =
    .label = Selalu tampilkan tombol aksi halaman
waterfox-opt-hidden-urlbar-iconbox =
    .label = Sembunyikan kotak identitas situs
waterfox-opt-hidden-urlbar-iconbox-label-only =
    .label = Sembunyikan hanya labelnya
waterfox-opt-urlbar-iconbox-with-separator =
    .label = Pisahkan kotak identitas dengan garis
waterfox-opt-urlview-focus-item-border =
    .label = Garisi hasil yang difokuskan
waterfox-opt-padding-urlview-result =
    .label = Perketat baris hasil
waterfox-opt-rounding-square-urlview-item =
    .label = Kotakkan sudut hasil
waterfox-opt-bookmarks-heading =
    .label = Bookmark
    .description = Bilah alat bookmark dan menu bookmark.
waterfox-opt-bookmarkbar-multi-row =
    .label = Bungkus bilah alat bookmark ke beberapa baris
waterfox-opt-autohide-bookmarkbar =
    .label = Sembunyikan bilah alat bookmark hingga Anda mengarahkan kursor
waterfox-opt-centered-bookmarkbar =
    .label = Pusatkan bilah alat bookmark
waterfox-opt-padding-bookmarkbar =
    .label = Perketat bilah alat bookmark
waterfox-opt-hidden-bookmarkbar-icon =
    .label = Sembunyikan ikon bookmark
waterfox-opt-hidden-bookmarkbar-label =
    .label = Sembunyikan label bookmark
waterfox-opt-padding-bookmark-menu =
    .label = Perketat menu bookmark
waterfox-opt-padding-bookmark-menu-compact =
    .label = Perketat lebih lanjut
waterfox-opt-counter-bookmark-menu =
    .label = Tampilkan jumlah di menu bookmark
waterfox-opt-decoration-disable-sidebar-animate =
    .label = Matikan animasi bilah sisi
waterfox-opt-icons-heading =
    .label = Ikon
    .description = Di mana ikon muncul dan seberapa besar ukurannya.
waterfox-opt-icon-disabled =
    .label = Sembunyikan semua ikon menu dan panel
waterfox-opt-icon-menu =
    .label = Tampilkan ikon di menu
waterfox-opt-icon-menu-full =
    .label = Tampilkan di setiap item menu
waterfox-opt-icon-context-menu =
    .label = Tampilkan ikon di menu konteks
waterfox-opt-icon-global-menu =
    .label = Tampilkan ikon di menu bilah menu
waterfox-opt-icon-global-menu-mac =
    .label = Tampilkan juga di macOS
waterfox-opt-icon-global-menubar =
    .label = Tampilkan ikon di bilah menu
waterfox-opt-icon-panel =
    .label = Tampilkan ikon di panel
waterfox-opt-icon-library =
    .label = Tampilkan ikon di perpustakaan
waterfox-opt-icon-1-25px-stroke =
    .label = Gunakan goresan ikon lebih tebal
waterfox-opt-icon-account-image-to-right =
    .label = Letakkan gambar akun di kanan
waterfox-opt-icon-account-label-to-right =
    .label = Letakkan nama akun di kanan
waterfox-opt-panel-icons =
    .label = Ikon menu aplikasi
    .description = Berapa baris menu utama yang diberi ikon oleh Waterfox.
waterfox-opt-panel-icons-photon =
    .label = Hanya item utama
waterfox-opt-panel-icons-full =
    .label = Setiap item
waterfox-opt-rounding-heading =
    .label = Sudut
    .description = Kotakkan sudut membulat di sekitar antarmuka.
waterfox-opt-rounding-square-tab =
    .label = Kotakkan sudut tab
waterfox-opt-rounding-square-toolbar =
    .label = Kotakkan sudut bilah alat
waterfox-opt-rounding-square-button =
    .label = Kotakkan sudut tombol
waterfox-opt-rounding-square-field =
    .label = Kotakkan sudut bidang teks
waterfox-opt-rounding-square-checklabel =
    .label = Kotakkan sudut kotak centang
waterfox-opt-rounding-square-dialog =
    .label = Kotakkan sudut dialog
waterfox-opt-rounding-square-infobox =
    .label = Kotakkan sudut notifikasi
waterfox-opt-rounding-square-panel =
    .label = Kotakkan sudut panel
waterfox-opt-rounding-square-panelitem =
    .label = Kotakkan sudut item panel
waterfox-opt-rounding-square-menupopup =
    .label = Kotakkan sudut menu
waterfox-opt-rounding-square-menuitem =
    .label = Kotakkan sudut item menu
waterfox-opt-theme-heading =
    .label = Tema dan efek
    .description = Warna, transparansi, dan animasi di seluruh antarmuka.
waterfox-opt-theme-proton-color =
    .label = Gunakan palet warna Proton pada halaman bawaan
    .description = Berlaku untuk halaman about: dan tampilan bawaan lainnya, bukan bingkai peramban.
waterfox-opt-theme-proton-chrome =
    .label = Terapkan pada dialog dan jendela Perpustakaan
waterfox-opt-theme-fully-color =
    .label = Terapkan di mana-mana
waterfox-opt-theme-fully-dark =
    .label = Cegah kilatan cahaya dalam mode gelap
waterfox-opt-theme-built-in-contrast =
    .label = Tingkatkan kontras tema bawaan
waterfox-opt-theme-system-default =
    .label = Ikuti tema sistem
waterfox-opt-theme-private =
    .label = Warnai jendela privat
waterfox-opt-hidden-private-indicator =
    .label = Sembunyikan indikator penelusuran privat
waterfox-opt-theme-transparent-panel =
    .label = Buat panel transparan
waterfox-opt-theme-transparent-frame =
    .label = Buat bingkai jendela transparan
waterfox-opt-theme-monospace =
    .label = Gunakan font monospaced di antarmuka
waterfox-opt-decoration-animate =
    .label = Animasikan perubahan antarmuka
waterfox-opt-decoration-disable-panel-animate =
    .label = Matikan animasi menu aplikasi
waterfox-opt-content-heading =
    .label = Halaman web
    .description = Gaya yang diterapkan Waterfox di atas halaman web.
waterfox-opt-page-monospace =
    .label = Gunakan font monospaced pada halaman bawaan
waterfox-opt-page-dark-mode-pdf =
    .label = Gelapkan PDF saat menggunakan tema gelap
waterfox-opt-newtab-heading =
    .label = Halaman tab baru
    .description = Tampilan halaman yang Anda buka di tab baru.
waterfox-opt-newtab-hidden-logo =
    .label = Sembunyikan logo
waterfox-opt-newtab-full-icon =
    .label = Isi ubin pintasan dengan ikonnya
waterfox-opt-newtab-background-image =
    .label = Tampilkan gambar latar belakang
waterfox-opt-newtab-animate =
    .label = Animasikan ubin
waterfox-opt-player-heading =
    .label = Pemutar video
    .description = Kontrol dan ukuran untuk pemutar video bawaan.
waterfox-opt-player-ui =
    .label = Ubah gaya kontrol video bawaan
waterfox-opt-player-ui-twoline =
    .label = Tata kontrol dalam dua baris
waterfox-opt-player-icon =
    .label = Gunakan ikon kontrol Waterfox
waterfox-opt-player-size =
    .label = Perbesar kontrol
waterfox-opt-player-noaudio =
    .label = Sembunyikan kontrol volume saat video tidak memiliki audio
waterfox-opt-player-click-to-play =
    .label = Gaya overlay klik-untuk-mutar
    .description = Menambahkan gaya hover dan kursor penunjuk pada overlay yang ada.
waterfox-opt-player-animate =
    .label = Animasikan kontrol
