# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-page-title = Markah Langsung
feeds-page-description = Berlangganan umpan RSS dan Atom dengan markah langsung.
feeds-private-notice = Berlangganan, menghapus, memuat ulang, dan mengimpor umpan dinonaktifkan dalam penjelajahan privat. Anda tetap dapat melihat item tersimpan dalam cache atau mengekspor langganan Anda.
feeds-subscribe-heading = Berlangganan umpan
feeds-url-label = URL umpan
feeds-title-label = Judul (opsional)
feeds-subscribe-note = Langganan disimpan ke menu Markah pada perangkat ini, terpisah dari Sync. Umpan diperbarui di latar belakang tanpa mengirimkan cookie atau kredensial masuk ke server umpan.
feeds-subscribe-button = Berlangganan
    .label = Berlangganan
    .accesskey = B
feeds-subscribe-title =
    .value = Nama
    .accesskey = N
feeds-subscribe-url =
    .value = URL Umpan
    .accesskey = U
feeds-subscribe-folder =
    .value = Simpan di
    .accesskey = S
feeds-subscribe-choose-folder =
    .label = Pilih folder lain…
feeds-subscribe-untitled-folder =
    .label = Folder tanpa judul
feeds-subscribe-cancel =
    .label = Batal
    .accesskey = B
feeds-subscribe-private = Langganan umpan tidak dapat diubah di jendela privat.
feeds-subscribe-busy = Berlangganan… Menutup panel ini tidak akan membatalkan langganan.
feeds-subscribe-invalid-url = Masukkan URL umpan HTTP atau HTTPS tanpa nama pengguna atau kata sandi, dengan panjang maksimal 4.096 karakter.
feeds-subscribe-invalid-title = Pastikan nama tidak lebih dari 1.024 karakter.
feeds-subscribe-folder-error = Pilih folder markah yang sudah ada, lalu coba lagi.
feeds-subscribe-error = Tidak dapat berlangganan ke umpan ini. Periksa URL umpan dan folder tujuan, lalu coba lagi.
feeds-subscribe-setup-error = Panel langganan tidak dapat dimuat. Tutup panel ini dan coba lagi.
feeds-subscriptions-heading = Langganan Anda
feeds-import-button = Impor OPML…
feeds-export-button = Ekspor OPML…
feeds-empty = Belum ada langganan umpan.
feeds-preview-button = Pratinjau
    .aria-label = Pratinjau { $title }
feeds-reload-button = Muat ulang
    .aria-label = Muat ulang { $title }
feeds-remove-button = Hapus
    .aria-label = Hapus { $title }
feeds-preview-heading = Pratinjau umpan
feeds-preview-note = Hanya judul dan tautan tersimpan dalam cache yang ditampilkan, hingga 200 item. Tautan artikel akan dibuka di tab baru.
feeds-preview-empty = Tidak ada item tersimpan dalam cache. Muat ulang langganan ini di jendela non-privat untuk mengambil item terbarunya.
feeds-item-untitled = Item tanpa judul
feeds-status-loading = Memuat langganan…
feeds-status-working = Memproses…
feeds-status-ready = Langganan dimuat.
feeds-status-subscribed = Berhasil berlangganan ke umpan.
feeds-status-removed = Langganan dihapus.
feeds-status-reloaded = Umpan dimuat ulang.
feeds-status-preview = Menampilkan item tersimpan dalam cache.
feeds-status-canceled = Operasi dibatalkan.
feeds-status-exported = Langganan diekspor.
feeds-status-imported =
    { $count ->
        [one] Satu langganan diimpor.
       *[other] { $count } langganan diimpor.
    }
feeds-error-unavailable = Pengelolaan umpan tidak tersedia di halaman ini. Buka about:feeds di tab baru.
feeds-error-private = Buka halaman ini di jendela non-privat untuk mengubah langganan atau memuat ulang umpan.
feeds-error-invalid-request = Permintaan umpan tidak valid.
feeds-error-invalid-url = Masukkan URL umpan HTTP atau HTTPS yang valid tanpa nama pengguna atau kata sandi.
feeds-error-busy = Operasi umpan lain sedang berlangsung. Coba lagi setelah selesai.
feeds-error-not-found = Langganan ini sudah tidak ada.
feeds-error-operation = Operasi umpan tidak dapat diselesaikan. Periksa alamat umpan dan koneksi. Folder yang berisi markah tersimpan tidak dapat dihapus dari sini.
feeds-error-not-active = Pilih tab ini sebelum membuka pemilih file.
feeds-error-invalid-opml = Pilih file OPML UTF-8 yang valid tanpa deklarasi DTD atau entitas.
feeds-error-file-too-large = Pilih file OPML berukuran tidak lebih dari 2 MiB.
feeds-import-picker-title = Impor Langganan Umpan
feeds-export-picker-title = Ekspor Langganan Umpan
feeds-opml-file-filter = File OPML
feeds-export-filename = feeds.opml
feeds-page-action = Berlangganan umpan di halaman ini
feeds-toolbar-button =
    .label = Markah Langsung
    .tooltiptext = Temukan umpan dan kelola markah langsung
feeds-menu-label =
    .label = Markah Langsung
    .accesskey = M
feeds-menu-manage =
    .label = Kelola Markah Langsung…
feeds-menu-discovering =
    .label = Mencari umpan di halaman ini…
feeds-menu-no-feeds =
    .label = Tidak ada umpan yang diumumkan di halaman ini
feeds-menu-all-subscribed =
    .label = Sudah berlangganan ke semua umpan di halaman ini
feeds-menu-subscribe =
    .label = Berlangganan ke { $title }…
    .tooltiptext = { $url }
feeds-menu-open-site =
    .label = Buka Situs Web Umpan
    .tooltiptext = { $url }
feeds-menu-reload =
    .label = Muat Ulang Markah Langsung
feeds-menu-loading =
    .label = Memuat umpan…
feeds-menu-empty =
    .label = Umpan ini tidak memiliki item
feeds-menu-error =
    .label = Tidak dapat memperbarui umpan. Akan mencoba lagi nanti.
feeds-menu-no-cache =
    .label = Muat ulang di jendela non-privat untuk memuat item
feeds-entry-visited =
    .label = { $title }
    .aria-label = { $title } (telah dikunjungi)
    .tooltiptext = { $url } (telah dikunjungi)
feeds-entry-unvisited =
    .label = { $title }
    .aria-label = { $title } (belum dikunjungi)
    .tooltiptext = { $url } (belum dikunjungi)
