# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

onboarding-grassroots-title = Mendukung akar rumput
onboarding-grassroots-subtitle = Terima kasih telah menggunakan Waterfox, browser independen dan akar rumput. Dengan dukungan Anda, kami membangun alternatif berkelanjutan untuk para pemain besar di luar sana.
waterfox-onboarding-welcome-title = Selamat datang di { -brand-short-name }
waterfox-onboarding-welcome-subtitle = Independen, cepat, dan dibangun dengan kontrol Waterfox yang Anda harapkan.
waterfox-onboarding-start-button = Mulai
waterfox-onboarding-import-title = Bawa data Anda bersama Anda
waterfox-onboarding-import-subtitle = Impor bookmark, riwayat, dan data formulir dari { migration-wizard-migrator-display-name-firefox } atau browser lain tanpa meninggalkan pengaturan ini.
waterfox-onboarding-style-title = Pilih gaya Waterfox Anda
waterfox-onboarding-style-subtitle = Pilih bentuk tab dan bilah alat serta seberapa ringkas rasanya.
waterfox-onboarding-style-photon-label = Photon
waterfox-onboarding-style-photon-body = Tampilan Waterfox klasik dengan chrome yang disempurnakan.
waterfox-onboarding-style-proton-label = Proton
waterfox-onboarding-style-proton-body = Tata letak yang lebih tenang dengan spasi browser modern.
waterfox-onboarding-style-nova-label = Nova
waterfox-onboarding-style-nova-body = Gaya Waterfox yang lebih tajam dengan garis tab aktif yang lebih cerah.
waterfox-onboarding-density-normal-label = Normal
waterfox-onboarding-density-compact-label = Ringkas
waterfox-onboarding-density-touch-label = Sentuh
waterfox-onboarding-theme-color-title = Jadikan terasa seperti milik Anda
waterfox-onboarding-theme-color-subtitle = Pilih warna tema yang membuat setiap jendela menjadi milik Anda.
waterfox-onboarding-theme-mode-system-label = Sistem
waterfox-onboarding-theme-mode-light-label = Terang
waterfox-onboarding-theme-mode-dark-label = Gelap
waterfox-onboarding-color-default-label = Bawaan
waterfox-onboarding-color-smoke-label = Smoke
waterfox-onboarding-color-ash-label = Ash
waterfox-onboarding-color-sun-label = Sun
waterfox-onboarding-color-spark-label = Spark
waterfox-onboarding-color-flame-label = Flame
waterfox-onboarding-color-flare-label = Flare
waterfox-onboarding-color-lavender-label = Lavender
waterfox-onboarding-color-dusk-label = Dusk
waterfox-onboarding-color-lagoon-label = Lagoon
waterfox-onboarding-color-tide-label = Tide
waterfox-onboarding-color-pine-label = Pine
waterfox-onboarding-tabs-title = Atur tab sesuai cara Anda
waterfox-onboarding-tabs-subtitle = Pilih bagaimana tab Anda diatur, dan di mana bilah tab horizontal berada. Anda dapat mengubah keduanya nanti di Pengaturan.
waterfox-onboarding-tabs-horizontal-label = Tab horizontal
waterfox-onboarding-tabs-horizontal-body = Pertahankan bilah tab klasik di bagian atas.
waterfox-onboarding-tabs-vertical-label = Tab vertikal
waterfox-onboarding-tabs-vertical-body = Pindahkan tab ke bilah samping sebagai daftar yang lebih tinggi.
waterfox-onboarding-tabs-tree-label = Tab pohon
waterfox-onboarding-tabs-tree-body = Tab vertikal yang bersarang di bawah tab yang membukanya.
waterfox-onboarding-location-top-above-label = Di atas bilah alat
waterfox-onboarding-location-top-below-label = Di bawah bilah alat
waterfox-onboarding-location-bottom-above-label = Di atas bilah status
waterfox-onboarding-location-bottom-below-label = Di bawah bilah status
waterfox-onboarding-privacy-title = Alat privasi siap digunakan
waterfox-onboarding-privacy-subtitle = Waterfox dimulai dengan pemblokiran iklan dan pengaturan default privasi. Anda dapat menyesuaikannya kapan saja.
waterfox-onboarding-privacy-primary-button = Pertahankan perlindungan
waterfox-onboarding-default-title = Jadikan { -brand-short-name } browser default Anda
waterfox-onboarding-default-subtitle = Buka tautan di { -brand-short-name } secara default dan jaga pengaturan Waterfox Anda tetap dekat.
waterfox-onboarding-default-primary-button = Atur sebagai default
waterfox-onboarding-finish-title = Anda sudah siap
waterfox-onboarding-finish-subtitle = Terima kasih telah memilih Waterfox. Browser Anda siap digunakan.
waterfox-onboarding-finish-primary-button = Mulai menjelajah
waterfox-onboarding-skip-button = Jangan sekarang
waterfox-onboarding-skip-step-button = Lewati langkah ini
waterfox-onboarding-continue-button = Lanjutkan
waterfox-onboarding-save-continue-button = Simpan dan lanjutkan
waterfox-onboarding-customize-appearance-button = Sesuaikan tampilan di Pengaturan
waterfox-onboarding-customize-tabs-button = Sesuaikan tab di Pengaturan
waterfox-onboarding-customize-privacy-button = Sesuaikan pengaturan privasi
waterfox-onboarding-language-hint = Anda dapat mengubah ini kapan saja di Pengaturan.
waterfox-onboarding-language-error = { -brand-short-name } tidak dapat mengubah bahasa. Bahasa sebelumnya Anda masih aktif.
waterfox-onboarding-step-label = Langkah { $current } dari { $total }
waterfox-onboarding-tabs-style-legend = Gaya browser
waterfox-onboarding-tabs-density-legend = Kepadatan
waterfox-onboarding-appearance-subtitle = Pilih bentuk, kepadatan, dan warna. Anda dapat menyesuaikan semua detailnya nanti di Pengaturan.
waterfox-onboarding-theme-mode-legend = Skema warna
waterfox-onboarding-theme-color-legend = Warna tema
waterfox-onboarding-tabs-layout-legend = Penyusunan tab
waterfox-onboarding-tabs-location-label = Posisi bilah tab
waterfox-onboarding-tabs-location-hint = Berlaku untuk tab horizontal. Lebih banyak posisi tersedia di Pengaturan.
waterfox-onboarding-finish-privacy-note = Pemblokiran iklan dan perlindungan pelacakan sudah aktif.
waterfox-onboarding-back-button = Kembali
