; This Source Code Form is subject to the terms of the BrowserWorks Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at http://mozilla.org/MPL/2.0/.
; This file is in the UTF-8 encoding
; All strings must be less than 600 chars.
[Strings]
TitleText=Kaonafatšo ya %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% e lokela dikaonafatšo tša gago gomme e tla thoma go se go ye kae…
BrowserWorksMaintenanceDescription=Tirelo ya Tlhokomelo ya BrowserWorks e netefatša gore o na le tokollo ya moragorago le yeo e šireletšegilego ya Waterfox mo khomphutheng ya gago. Go boloka Waterfox e le nakong go bohlokwa kudu bakeng sa tšhireletšego ya gago ya inthaneteng, gomme BrowserWorks e go hlohleletša ka mo go tiilego gore o dire gore tirelo ye e dule e dumeletšwe.
