restart-prompt-question = Sigur vreți să reporniți { -brand-short-name }?
restart-prompt-title = Repornește { -brand-short-name }
appmenuitem-restart-browser =
    .label = Repornește
copy-all-urls =
    .label = Copiază legăturile tuturor filelor
copy-tab-link =
    .label = Copiază legătura la filă
unload-tab =
    .label = Anulează încărcarea filei
new-private-tab =
    .label = Filă privată nouă
    .tooltiptext = Deschide o nouă filă privată
open-all-links-private =
    .label = Deschide toate legăturile în file private
open-all-private =
    .label = Deschide totul în file private
open-link-private =
    .label = Deschide legătura într-o nouă filă privată
open-private-tab =
    .label = Deschide într-o nouă filă privată
private-tab =
    .label =
        { $isPrivate ->
            [true] Ieși din fila privată
           *[false] Fă fila privată
        }
status-bar =
    .label = Bara de stare
update-application-manual =
    .label = Nu verifica după actualizări (nerecomandabil)
    .accesskey = N
bookmarks-bar-position-header = Poziția barei de semne de carte
bookmarks-position-bottom =
    .label = Jos
bookmarks-position-top =
    .label = Sus
dynamic-theme-header = Teme dinamice
dynamic-theme-auto =
    .label = Stabilește dinamic modul luminos/întunecos
dynamic-theme-dark =
    .label = Forțează modul întunecos
dynamic-theme-light =
    .label = Forțează modul luminos
geolocation-api-header = IPA pentru geolocalizare
geolocation-description = Unele situri WWW vă cer locația pentru a funcționa. Dacă un sit nu funcționează din cauza imposibilității de a vă găsi locația, activați această preferință și reîncercați.
geolocation-api-enabled =
    .label = Activează
geolocation-api-disabled =
    .label = Dezactivează
restart-header = Elementul de repornire din meniu
restart-purge-cache =
    .label = Curăță memoria temporară de repornire rapidă la repornirea navigatorului
restart-require-confirmation =
    .label = Cere confirmarea pentru repornire
restart-show-button =
    .label = Arată butonul de repornire în PanelUI
statusbar-header = Bara de stare
statusbar-contrast-text =
    .label = Adaugă contrast la culoarea textului din bara de stare
statusbar-enabled =
    .label = Arată bara de stare
statusbar-show-links =
    .label = Arată legăturile
tab-additional-header = Preferințe suplimentare pentru file
insert-after-current =
    .label = Inserează o filă nouă după cea actuală
insert-related-after-current =
    .label = Inserează o filă nouă legată de cea actuală, după aceasta
pinned-icon-only =
    .label = Micșorează filele fixate pentru a afișa doar iconița sitului
tab-feature-header = Meniul contextual pentru file
enable-copy-active-tab =
    .label = Copiază URL doar din fila actuală
show-copy-all-urls =
    .label = Arată elementul din meniu pentru copierea adreselor tuturor filelor
show-copy-url =
    .label = Arată elementul din meniu pentru copierea adresei filei
show-duplicate-tab =
    .label = Arată elementul din meniu pentru duplicarea filei
show-unload-tab =
    .label = Arată elementul din meniu pentru anularea încărcării filei
tab-position-header = Poziția barei cu file
tab-bar-bottom-above =
    .label = Jos, deasupra barei de stare
tab-bar-bottom-below =
    .label = Jos, dedesubtul barei de stare
tab-bar-top-above =
    .label = Sus, deasupra barei de adresă
tab-bar-top-below =
    .label = Sus, dedesubtul barei de adresă
enable-javascript =
    .label = Activează JavaScript
load-images =
    .label = Încarcă imaginile automat
preferences-doh-setting-ultra =
    .label = Ultraprotecție
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } va folosi SND securizat cu Oblivious HTTP prin releul de intimitate al Waterfox, pentru protecție maximă.
preferences-doh-ultra-detailed-desc-1 = Folosește releul Oblivious HTTP al Waterfox pentru a ascunde cererile SND chiar și de furnizorul SND
preferences-doh-ultra-detailed-desc-2 = Furnizează un strat suplimentar de criptare, în plus față de SND prin HTTPS standard
preferences-doh-ultra-detailed-desc-3 = Protecție maximă a intimității SND: nimeni nu poate vedea ce situri vizitați
preferences-doh-ultra-fallback-mode = Comportament de rezervă:
preferences-doh-ultra-fallback-allowed = Permite rezerva la SND-ul sistemului dacă cel securizat nu funcționează
preferences-doh-ultra-fallback-disabled = Nu trece niciodată la SND-ul sistemului (siturile ar putea să nu se încarce, dacă SND-ul securizat cedează)
ref-header = Antetul referitor HTTP
send-referrer-header-0 =
    .label = Nu trimite niciodată antetul „referitor”
send-referrer-header-1 =
    .label = Trimite antetul „referitor” doar la apăsarea pe legături și alte elemente asemenea
send-referrer-header-2 =
    .label = Trimite antetul „referitor” cu toate cererile (standard)
webrtc-header = Conexiune prieten WebRTC
enable-webrtc-p2p =
    .label = Permite conectarea cu prieteni în WebRTC
pane-theme-title = Aspect și experiență
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animații
appearance-header = Aspect
autohide-hidden-header = Ascundere automată și ascunse
bookmark-header = Bara de marcaje
center-header = Centru
font-header = Fonturi
full-screen-header = Ecran complet
icons-header = Iconițe
interface-component-header = Componentele interfeței
media-player-header = Lector audiovizual
nav-bar-header = Bara de navigare
panels-header = Panouri
rounding-header = Rotunjire
sidebar-header = Bara laterală
tab-bar-header = Bara cu file
theme-header = Temă
preset-title = Propuneri
lepton-style =
    .label = Stilul Lepton
proton-style =
    .label = Stilul Proton
waterfox-defaults =
    .label = Standard Waterfox
auto-blur-tabs =
    .label = Estompează automat filele
auto-hide-back =
    .label = Ascunde automat butonul „înapoi”
auto-hide-bookmarkbar =
    .label = Ascunde automat bara de marcaje
auto-hide-forward =
    .label = Ascunde automat butonul „înainte”
auto-hide-navbar =
    .label = Ascunde automat bara de navigare
auto-hide-pageaction =
    .label = Ascunde automat acțiunea paginii
auto-hide-sidebar =
    .label = Ascunde automat bara laterală
auto-hide-tabbar =
    .label = Ascunde automat bara cu file
auto-hide-tabs =
    .label = Ascunde automat filele
center-navbar-text =
    .label = Centrează textul barei de navigare
center-tab-content =
    .label = Centrează conținutul filelor
center-tab-label =
    .label = Centrează doar eticheta filelor
close-button-hover =
    .label = Arată butonul de închidere la planarea pe fila selectată, atunci când sunt multe file deschise
compact-bookmark-menu =
    .label = Redu adaosul de spațiu în meniul de marcaje
compact-context-menu =
    .label = Redu adaosul de spațiu în meniul suplimentar
compact-navbar-popup =
    .label = Redu adaosul de spațiu în balonul barei de navigare
compact-panel-header =
    .label = Redu adaosul de spațiu în antetul panoului
disable-panel-animate =
    .label = Dezactivează animația panoului meniului de aplicație
disable-sidebar-animate =
    .label = Dezactivează animația panoului barei laterale
drag-space =
    .label = Activează spațiul de tragere fix
enable-cyan-accent-color =
    .label = Culoare de accent turcoaz
enable-default-accent-color =
    .label = Culoare de accent standard
enable-menu-transparency =
    .label = Activează transparența meniurilor
enable-panel-transparency =
    .label = Activează transparența panourilor
enable-system-accent-color =
    .label = Culoarea de accent a sistemului
enable-waterfox-theme-0 =
    .label = Activează personalizările Waterfox pe toate temele
enable-waterfox-theme-1 =
    .label = Activează personalizările Waterfox pe temele Waterfox
enable-waterfox-theme-2 =
    .label = Dezactivează personalizările Waterfox
full-panel-strip =
    .label = Separator de lățime completă în meniul aplicației
remove-panel-strip =
    .label = Suprimă separatorul colorat din meniul aplicației
hide-all-icons =
    .label = Ascunde toate iconițele
hide-bookmarkbar-icon =
    .label = Ascunde iconițele din bara de marcaje
hide-bookmarkbar-label =
    .label = Ascunde etichetele din bara de marcaje
hide-disabled-menuitems =
    .label = Ascunde elementele dezactivate din meniuri
hide-sidebar-header =
    .label = Ascunde antetul barei laterale
hide-tab-icons =
    .label = Ascunde iconițele filelor
hide-urlbar-iconbox =
    .label = Ascunde caseta cu iconiță din bara de URL
monospace-font =
    .label = Folosește fontul monospațiat pentru pagină
monospace-font-theme =
    .label = Folosește fontul monospațiat pentru temă
show-mac-menu-icons =
    .label = Arată iconițele în meniul Macintosh
show-menu-icons =
    .label = Arată iconițele în meniuri
square-button-edges =
    .label = Colțuri pătrate pe butoane
square-checkbox =
    .label = Casetă de bifare pătrată
square-field =
    .label = Colțuri pătrate pe caseta de scriere
square-menu-item =
    .label = Colțuri pătrate pe elementele din meniul suplimentar
square-menu-panel =
    .label = Colțuri pătrate pe panoul meniului de aplicație
square-menu-popup =
    .label = Colțuri pătrate pe panoul meniului suplimentar
square-panel-item =
    .label = Colțuri pătrate pe elementele din meniul de aplicație
square-tab-edges =
    .label = Colțuri pătrate pe file
tab-context-line =
    .label = Rândul de context în file
telemetry-page-subtitle = Waterfox nu colectează date telemetrice despre instalarea d-voastră: toate modulele de telemetrie sunt dezactivate în producția navigatorului. Ceea ce faceți în navigator știți doar d-voastră.
telemetry-privacy-policy = Politica de confidențialitate
onboarding-grassroots-title = Susțineți dezvoltarea independentă
onboarding-grassroots-subtitle = Vă mulțumim că folosiți Waterfox, un navigator independent. Cu sprijinul d-voastră, creăm o alternativă durabilă la giganții din industrie.
tabbrowser-confirm-session-restore-checkbox = Deschide ferestrele și filele anterioare
pane-tree-title = File verticale arborescente
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = File verticale arborescente
sidebar-tree-vertical-tabs =
    .label = File verticale arborescente
tree-header = File verticale arborescente
tree-appearance-header = Aspect
tree-auto-sticky-header = Filele lipite de marginile barei de file când sunt în afara vizorului
tree-faviconize-pinned-tabs =
    .label = Arată filele fixate doar cu iconița
    .accesskey = S
tree-sticky-active-tab =
    .label = Fila activă
    .accesskey = k
tree-sticky-sharing-tab =
    .label = File care distribuie camera/microfonul/ecranul
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = File care produc sunet
    .accesskey = y
tree-behavior-header = Vizualizarea arborescentă a filelor
tree-auto-collapse-expand-subtree-on-attach =
    .label = Când apare un nou arbore, închide-i automat pe ceilalți
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Când o filă e focalizată, extinde-i arborele și închide-i pe ceilalți automat
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = Când o legătură sau șir URL e aruncată pe o filă
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Întreabă-mă mereu cum să o tratez
tree-drop-links-on-tab-behavior-load =
    .label = Încarcă în filă
tree-drop-links-on-tab-behavior-newtab =
    .label = Deschide o nouă filă subordonată
tree-successor-tab-control-level-caption =
    .value = Când pagina actuală e închisă ca ultim subordonat
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = Focalizează la ultima filă din arbore
tree-successor-tab-control-level-never =
    .label = Focalizează mereu la următoarea filă (respectă controlul navigatorului sau al altei extensii)
tree-successor-tab-control-level-simulate-default =
    .label = Focalizează mereu următoarea filă
tree-tree-double-click-behavior-caption =
    .value = Apăsare dublă pe o filă
    .accesskey = d
tree-tree-double-click-behavior-toggle-close =
    .label = Închide fila
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Închide/extinde arborele
tree-tree-double-click-behavior-toggle-none =
    .label = Nu face nimic
tree-tree-double-click-behavior-toggle-sticky =
    .label = Lipește/dezlipește de marginile barei de file
tree-auto-attach-header = Autoorganizarea arborelui de file
tree-auto-attach-child-end =
    .label = Ultimul subordonat al filei părinte
tree-auto-attach-child-next-to-last-related-tab =
    .label = Subordonatul filei părinte, lângă cel deschis recent
tree-auto-attach-child-top =
    .label = Primul subordonat al filei părinte
tree-auto-attach-independent =
    .label = Filă independentă
tree-auto-attach-next-sibling =
    .label = Următorul vecin al filei părinte
tree-auto-attach-no-control =
    .label = (fără control)
tree-auto-attach-sibling =
    .label = Vecinul filei părinte
tree-auto-attach-on-any-other-trigger-caption =
    .value = File din orice alt declanșator: Deschide ca
    .accesskey = d
tree-auto-attach-on-duplicated-caption =
    .value = Duplică fila ca
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Pentru apăsare mijlocie, deschide o nouă filă goală
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Deschide o nouă filă goală ca
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Filă nouă din alte aplicații: Deschide ca
    .accesskey = a
tree-auto-attach-on-opened-with-owner-caption =
    .value = Când o filă este deschisă dintr-una existentă, deschide-o ca
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Filă nouă cu același sit ca fila actuală din bara de locație, marcaje, istoric sau alte cazuri: Deschide ca
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Punctul de inserare al noilor file subordonate din file fixate (vor apărea ca file principale)
    .accesskey = P
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Sfârșitul arborelui
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Lângă subordonatul deschis recent sau lângă deschizător
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Fără control (respectă decizia navigatorului sau a altor extensii de file)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = Partea de sus a arborelui (lângă deschizător)
