copy-url =
    .label = Cóipeáil Nasc Cluaisín
unload-tab =
    .label = Díluchtaigh Cluaisín
open-link-private =
    .label = Oscail Nasc i gCluaisín Príobháideach Nua
status-bar =
    .label = Barra Stádais
tab-position-header = Seasamh Barra na gCluaisíní
dynamic-theme-dark =
    .label = Mód Dorcha i bhFórsaí
dynamic-theme-auto =
    .label = Socraigh Mód Solais/Dorcha go dinimiciúil
restart-purge-cache =
    .label = Glan taisce atosú tapa ar atosú an bhrabhsálaí
bookmarks-bar-position-header = Post an Bharra Uirlisí Leabharmharcanna
bookmarks-position-top =
    .label = Barr
enable-webrtc-p2p =
    .label = Cumasaigh ceangal piaraí WebRTC
load-images =
    .label = Luchtaigh íomhánna go huathoibríoch
enable-javascript =
    .label = Cumasaigh JavaScript
enable-dooh =
    .label = Úsáid DNS thar HTTP Oblivious
pane-theme-title = Féach & Mothaigh
preset-title = Réamhshocruithe
rounded-corners =
    .label =
        { $isRounded ->
            [true] Scoránaigh Cearnóg Coirnéil
           *[false] Scoránaigh Coirnéil Go Réidh
        }
center-all =
    .label =
        { $isCentered ->
            [true] Scoránaigh Lárnaithe as
           *[false] Scoránaigh Lárnaithe ar
        }
auto-hide-tabs =
    .label = Folaigh Cluaisíní Uathoibríoch
auto-hide-bookmarkbar =
    .label = Folaigh go huathoibríoch Barra na Leabharmharcanna
auto-hide-back =
    .label = Folaigh Uath Cnaipe Ar Ais
auto-hide-pageaction =
    .label = Folaigh Gníomh Leathanaigh Uathoibríoch
hide-urlbar-iconbox =
    .label = Folaigh Bosca Deilbhín Barra URL
square-button-edges =
    .label = Coirnéil Cnaipe Cearnóg
square-menu-panel =
    .label = Coirnéil Phainéil Roghchláir na bhFeidhmchlár Cearnógach
square-panel-item =
    .label = Cúinní Mír Roghchláir Aipe Cearnóg
square-menu-popup =
    .label = Cúinní Painéil Roghchláir Comhthéacs Cearnógach
square-menu-item =
    .label = Cúinní Mír Roghchláir Comhthéacs Cearnógach
compact-context-menu =
    .label = Stuáil Roghchláir Comhthéacs a Laghdú
compact-bookmark-menu =
    .label = Laghdaigh Stuáil Roghchláir Leabharmharcanna
compact-panel-header =
    .label = Laghdaigh Stuáil Ceanntásc an Phainéil
compact-navbar-popup =
    .label = Laghdaigh Stuáil Phreabfhuinneog Barra Nav
show-mac-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir Mac
monospace-font-theme =
    .label = Cumasaigh cló monaspásáilte don téama
tab-context-line =
    .label = Líne Comhthéacs Cluaisíní
tab-bar-header = Barra na gCluaisíní
nav-bar-header = Barra Nav
font-header = Clónna
full-screen-header = Scáileán iomlán
icons-header = Deilbhíní
media-player-header = Seinnteoir meáin
telemetry-privacy-policy = Beartas Príobháideachta
onboarding-grassroots-title = Ag tacú leis an bpobalbhreith
tabbrowser-confirm-session-restore-checkbox = Oscail fuinneoga agus cluaisíní roimhe seo
restart-prompt-title = Atosaigh { -brand-short-name }
copy-all-urls =
    .label = Cóipeáil Gach Nasc Cluaisín
restart-prompt-question = An bhfuil tú cinnte gur mian leat { -brand-short-name } a atosú?
appmenuitem-restart-browser =
    .label = Atosaigh
open-all-private =
    .label = Oscail Gach Rud i gCluaisíní Príobháideacha
open-all-links-private =
    .label = Oscail Gach Nasc i gCluaisíní Príobháideacha
open-private-tab =
    .label = Oscail i gCluaisín Príobháideach Nua
new-private-tab =
    .label = Cluaisín Príobháideach Nua
    .tooltiptext = Oscail cluaisín príobháideach nua
private-tab =
    .label =
        { $isPrivate ->
            [true] Scoir Cluaisín Príobháideach
           *[false] Déan Cluaisín Príobháideach
        }
tab-bar-top-above =
    .label = Barr os cionn an bharra seoltaí
tab-bar-top-below =
    .label = Barr thíos an barra seoltaí
tab-bar-bottom-above =
    .label = Bun os cionn an bharra stádais
tab-bar-bottom-below =
    .label = Bun thíos an barra stádais
tab-additional-header = Sainroghanna Cluaisíní Breise
insert-after-current =
    .label = Ionsáigh cluaisín nua i ndiaidh an chluaisín reatha
pinned-icon-only =
    .label = Laghdaigh cluaisíní pionála chun íocón an tsuímh amháin a thaispeáint
insert-related-after-current =
    .label = Ionsáigh cluaisín nua gaolmhar tar éis an chluaisín reatha
dynamic-theme-header = Téamaí Dinimiciúla
dynamic-theme-light =
    .label = Mód Solais Fórsa
restart-header = Atosaigh Mír Roghchláir
restart-show-button =
    .label = Taispeáin an cnaipe atosaithe i PanelUI
restart-require-confirmation =
    .label = Deimhniú atosú de dhíth
statusbar-contrast-text =
    .label = Dath téacs an bharra stádais i gcodarsnacht
tab-feature-header = Roghchlár Comhthéacs Cluaisíní
show-duplicate-tab =
    .label = Taispeáin mír roghchláir cluaisíní dúblach
show-copy-url =
    .label = Taispeáin cóip de mhír roghchláir url tab
enable-copy-active-tab =
    .label = Cóipeáil URL ón gcluaisín gníomhach amháin
show-copy-all-urls =
    .label = Taispeáin cóip gach mír roghchláir URL cluaisíní
statusbar-enabled =
    .label = Taispeáin Barra Stádais
show-unload-tab =
    .label = Taispeáin mír roghchláir táb díluchtaithe
statusbar-header = Barra Stádais
statusbar-show-links =
    .label = Taispeáin naisc
bookmarks-position-bottom =
    .label = Bun
geolocation-api-header = API Geolocation
geolocation-description = Bíonn do shuíomh ag teastáil ó roinnt suíomhanna gréasáin le go bhfeidhmeoidh siad. Mura bhfuil suíomh Gréasáin ag feidhmiú toisc nach bhfuil tú in ann do shuíomh a aimsiú, cumasaigh an rogha seo agus bain triail eile as.
geolocation-api-enabled =
    .label = Cumasaigh
geolocation-api-disabled =
    .label = Díchumasaigh
send-referrer-header-0 =
    .label = Ná seol ceanntásc an atreoraitheora choíche
waterfox-defaults =
    .label = Réamhshocrú Waterfox
send-referrer-header-1 =
    .label = Seol an ceanntásc tarchuir ach amháin nuair a chliceálann tú ar naisc agus eilimintí cosúla
send-referrer-header-2 =
    .label = Seol an ceanntásc tarchuir ar gach iarratas (Réamhshocrú)
webrtc-header = Ceangal piaraí WebRTC
ref-header = Ceanntásc atreoraithe HTTP
category-theme =
    .tooltiptext = { pane-theme-title }
autohide-all =
    .label =
        { $isAutohide ->
            [true] Scoránaigh Folaigh Uathoibríoch
           *[false] Scoránaigh Folaigh Uathoibríoch Air
        }
disable-sidebar-animate =
    .label = Díchumasaigh beochan phainéil an bharra taoibh
reduce-padding =
    .label =
        { $isPadded ->
            [true] Scoránaigh Dlúth Os
           *[false] Scoránaigh Dlúth Ar
        }
enable-waterfox-theme-0 =
    .label = Cumasaigh saincheaptha téama Waterfox ar gach téama
enable-waterfox-theme-1 =
    .label = Cumasaigh saincheaptha téama Waterfox ar théamaí Waterfox
auto-hide-tabbar =
    .label = Folaigh Barra na gCluaisíní go huathoibríoch
enable-waterfox-theme-2 =
    .label = Díchumasaigh saincheaptha téama Waterfox
enable-panel-transparency =
    .label = Cumasaigh trédhearcacht an phainéil
enable-menu-transparency =
    .label = Cumasaigh trédhearcacht roghchláir
disable-panel-animate =
    .label = Díchumasaigh beochan phainéal roghchláir aipe
auto-blur-tabs =
    .label = Cluaisíní Doiléirigh Uathoibríoch
auto-hide-navbar =
    .label = Folaigh Barra Navanna Uathoibríoch
auto-hide-sidebar =
    .label = Barra Taoibh Folaigh Uathoibríoch
auto-hide-forward =
    .label = Folaigh Cnaipe Ar Aghaidh go Uathoibríoch
hide-tab-icons =
    .label = Folaigh Deilbhíní Cluaisíní
center-navbar-text =
    .label = Lár an Téacs Barra Nav
hide-all-icons =
    .label = Folaigh Gach Deilbhín
hide-sidebar-header =
    .label = Folaigh Ceanntásc an bharra Taoibh
hide-bookmarkbar-icon =
    .label = Folaigh Deilbhíní Barra Leabharmharcanna
hide-bookmarkbar-label =
    .label = Folaigh Lipéid Bharra Leabharmharcanna
hide-disabled-menuitems =
    .label = Folaigh Míreanna Roghchláir Díchumasaithe
center-tab-content =
    .label = Lár Ábhar Cluaisín
square-tab-edges =
    .label = Cúinní Cluaisíní Cearnóg
center-tab-label =
    .label = Lár Lipéad Cluaisín Amháin
drag-space =
    .label = Cumasaigh Spás Tarraingthe Seasta
monospace-font =
    .label = Cumasaigh cló monaspásáilte don leathanach
square-field =
    .label = Coirnéil Réimse Iontrála Cearnóg
close-button-hover =
    .label = Taispeáin an cnaipe cluaisín gar ar ainliú an chluaisín roghnaithe nuair a bhíonn go leor cluaisíní oscailte
square-checkbox =
    .label = ticbhosca cearnógach
remove-panel-strip =
    .label = Bain Deighilteoir Roghchláir Aipe Daite
full-panel-strip =
    .label = Deighilteoir Roghchláir Aipe Lánleithead
show-menu-icons =
    .label = Taispeáin Deilbhíní Roghchláir
bookmark-header = Barra Leabharmharcanna
sidebar-header = Barra Taoibh
panels-header = Painéil
telemetry-page-subtitle = Ní bhailíonn Waterfox teiliméadracht faoi do shuiteáil - díchumasaítear aon mhodúil teiliméadrachta nuair a thógtar an brabhsálaí. Is tusa amháin a bhíonn ar eolas agat cad a dhéanann tú i do bhrabhsálaí.
onboarding-grassroots-subtitle = Go raibh maith agat as Waterfox, brabhsálaí neamhspleách, pobail a úsáid. Le do thacaíocht, táimid ag tógáil rogha eile inbhuanaithe ar na himreoirí móra atá ann.
