restart-prompt-question = Haluatko varmasti käynnistää { -brand-short-name }in uudelleen?
restart-prompt-title = Käynnistä { -brand-short-name } uudelleen
appmenuitem-restart-browser =
    .label = Käynnistä uudelleen
copy-all-urls =
    .label = Kopioi kaikki välilehtien linkit
copy-url =
    .label = Kopioi välilehden linkki
unload-tab =
    .label = Pura välilehden lataus
new-private-tab =
    .label = Uusi yksityinen välilehti
    .tooltiptext = Avaa uusi yksityinen välilehti
open-all-links-private =
    .label = Avaa kaikki linkit yksityisissä välilehdissä
open-all-private =
    .label = Avaa kaikki yksityisissä välilehdissä
open-link-private =
    .label = Avaa linkki uudessa yksityisessä välilehdessä
open-private-tab =
    .label = Avaa uudessa yksityisessä välilehdessä
private-tab =
    .label =
        { $isPrivate ->
            [true] Poistu yksityisestä välilehdestä
           *[false] Tee yksityinen välilehti
        }
status-bar =
    .label = Tilarivi
update-application-manual =
    .label = Älä koskaan tarkista päivityksiä (ei suositeltu)
    .accesskey = N
bookmarks-bar-position-header = Kirjanmerkkien työkalupalkin sijainti
bookmarks-position-bottom =
    .label = Alhaalla
bookmarks-position-top =
    .label = Ylhäällä
dynamic-theme-header = Dynaamiset teemat
dynamic-theme-auto =
    .label = Aseta mukautuen vaalea tai tumma teema
dynamic-theme-dark =
    .label = Pakota tumma tila
dynamic-theme-light =
    .label = Pakota vaalea tila
geolocation-api-header = Paikannuksen rajapinta
geolocation-description = Jotkin verkkosivustot vaativat sijaintitiedon toimiakseen. Jos verkkosivusto ei toimi sen seurauksena, ettei se kykene löytämään sijaintiasi, ota tämä asetus käyttöön ja yritä uudelleen.
geolocation-api-enabled =
    .label = Käytä
geolocation-api-disabled =
    .label = Poista käytöstä
restart-purge-cache =
    .label = Tyhjennä nopean uudelleenkäynnistyksen välimuisti selaimen uudelleenkäynnistyksessä
restart-require-confirmation =
    .label = Vaadi vahvistus uudelleenkäynnistystä varten
restart-show-button =
    .label = Näytä uudelleenkäynnistyksen painike käyttöliittymässä
statusbar-header = Tilarivi
statusbar-enabled =
    .label = Näytä tilarivi
statusbar-show-links =
    .label = Näytä linkit
tab-additional-header = Välilehtien lisäasetukset
insert-after-current =
    .label = Lisää uusi välilehti nykyisen välilehden perään
insert-related-after-current =
    .label = Lisää liittyvä uusi välilehti nykyisen välilehden perään
pinned-icon-only =
    .label = Kutista kiinnitetyt välilehdet ja näytä vain sivuston kuvake
tab-feature-header = Välilehden kontekstivalikko
enable-copy-active-tab =
    .label = Kopioi osoite vain aktiivisesta välilehdestä
show-copy-all-urls =
    .label = Näytä kaikkien välilehtien osoitteet kopioiva valikkotoiminto
show-copy-url =
    .label = Näytä välilehden osoitteen kopioiva valikkotoiminto
show-duplicate-tab =
    .label = Näytä välilehden monistava valikkotoiminto
show-unload-tab =
    .label = Näytä välilehden latauksen purkava valikkotoiminto
tab-position-header = Välilehtipalkin sijainti
tab-bar-bottom-above =
    .label = Alhaalla tilarivin yläpuolella
tab-bar-bottom-below =
    .label = Alhaalla tilarivin alapuolella
tab-bar-top-above =
    .label = Ylhäällä osoitepalkin yläpuolella
tab-bar-top-below =
    .label = Ylhäällä osoitepalkin alapuolella
enable-javascript =
    .label = Käytä JavaScriptiä
load-images =
    .label = Lataa kuvat automaattisesti
preferences-doh-setting-ultra =
    .label = Ultra-suojaus
    .accesskey = U
ref-header = HTTP Referrer -viittajaotsake
send-referrer-header-0 =
    .label = Älä koskaan lähetä viittaajaotsaketta
send-referrer-header-1 =
    .label = Lähetä viittaajaotsake vain linkkejä ja vastaavanlaisia elementtejä napsauttaessa
send-referrer-header-2 =
    .label = Lähetä viittaajaotsake kaikissa pyynnöissä (oletus)
webrtc-header = WebRTC-vertaisyhteys
enable-webrtc-p2p =
    .label = Käytä WebRTC-vertaisyhteyttä
pane-theme-title = Ulkoasu ja kokemus
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animaatiot
appearance-header = Ulkoasu
bookmark-header = Kirjanmerkkipalkki
font-header = Fontit
full-screen-header = Koko näyttö
icons-header = Kuvakkeet
interface-component-header = Käyttöliittymän osat
media-player-header = Mediasoitin
sidebar-header = Sivupalkki
tab-bar-header = Välilehtipalkki
theme-header = Teema
preset-title = Esiasetukset
lepton-style =
    .label = Lepton-tyyli
proton-style =
    .label = Proton-tyyli
waterfox-defaults =
    .label = Waterfox-oletukset
auto-blur-tabs =
    .label = Sumenna välilehdet automaattisesti
auto-hide-back =
    .label = Piilota Taaksepäin-painike automaattisesti
auto-hide-bookmarkbar =
    .label = Piilota kirjanmerkkipalkki automaattisesti
auto-hide-forward =
    .label = Piilota Eteenpäin-painike automaattisesti
auto-hide-sidebar =
    .label = Piilota sivupalkki automaattisesti
auto-hide-tabbar =
    .label = Piilota välilehtipalkki automaattisesti
auto-hide-tabs =
    .label = Piilota välilehdet automaattisesti
enable-cyan-accent-color =
    .label = Syaanin korostusväri
enable-default-accent-color =
    .label = Oletusarvoinen korostusväri
enable-menu-transparency =
    .label = Käytä valikon läpinäkyvyyttä
enable-panel-transparency =
    .label = Käytä paneelin läpinäkyvyyttä
enable-system-accent-color =
    .label = Järjestelmän korostusväri
enable-waterfox-theme-0 =
    .label = Käytä Waterfox-teemamukautuksia kaikissa teemoissa
enable-waterfox-theme-1 =
    .label = Käytä Waterfox-teemamukautuksia Waterfox-teemoissa
enable-waterfox-theme-2 =
    .label = Poista Waterfox-teemamukautukset käytöstä
hide-all-icons =
    .label = Piilota kaikki kuvakkeet
hide-bookmarkbar-icon =
    .label = Piilota kirjanmerkkipalkin kuvakkeet
hide-tab-icons =
    .label = Piilota välilehtien kuvakkeet
show-menu-icons =
    .label = Näytä valikkokuvakkeet
telemetry-page-subtitle = Waterfox ei kerää telemetriatietoa asennuksestasi - kaikki telemetriamoduulit poistetaan käytöstä, kun selain koostetaan. Se, mitä teet selaimellasi, on vain sinun tiedossasi.
telemetry-privacy-policy = Tietosuojakäytäntö
onboarding-grassroots-title = Ruohonjuuritason tukemista
onboarding-grassroots-subtitle = Kiitos, että käytät Waterfoxia, itsenäistä ruohonjuuritason selainta. Tukesi avulla rakennamme kestävää vaihtoehtoa suurille pelureille.
tabbrowser-confirm-session-restore-checkbox = Avaa aiemmat ikkunat ja välilehdet
category-tree =
    .tooltiptext = { pane-tree-title }
tree-appearance-header = Ulkoasu
tree-tree-double-click-behavior-toggle-close =
    .label = Sulje välilehti
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Supista/laajenna puu
tree-tree-double-click-behavior-toggle-none =
    .label = Älä tee mitään
tree-auto-attach-independent =
    .label = Itsenäinen välilehti
preferences-doh-ultra-fallback-mode = Varatoiminnallisuus:
center-tab-content =
    .label = Keskitä välilehden sisältö
hide-bookmarkbar-label =
    .label = Piilota kirjanmerkkipalkin nimikkeet
preferences-doh-ultra-detailed-desc-1 = Käyttää Waterfoxin Oblivious HTTP -välittäjää piilottaakseen DNS-kyselyt jopa DNS-palveluntarjoajalta
preferences-doh-ultra-detailed-desc-2 = Tarjoaa lisäsuojausta tavanomaisen DNS HTTPS:n lisäksi
restart-header = Uudelleenkäynnistä valikon kohde
preferences-doh-ultra-desc = { -brand-short-name } käyttää suojauksen maksimoimiseen turvallista nimipalvelinta Oblivious HTTP:llä Waterfoxin yksityisyysreleoinnin kautta.
preferences-doh-ultra-detailed-desc-3 = Korkein DNS-yksityisyyssuojaus - kukaan ei voi nähdä millä sivuilla vierailet
preferences-doh-ultra-fallback-allowed = Salli järjestelmän DNS:n käyttöön, jos turvallinen DNS ei toimi
preferences-doh-ultra-fallback-disabled = Älä koskaan salli järjestelmän DNS:n käyttöä (sivut eivät ehkä lataudu, jos turvallinen DNS ei toimi)
center-header = Keskellä
nav-bar-header = Navigointipalkki
panels-header = Paneelit
