; This Source Code Form is subject to the terms of the BrowserWorks Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at http://mozilla.org/MPL/2.0/.
; This file is in the UTF-8 encoding
; All strings must be less than 600 chars.
[Strings]
TitleText=Саҥардыы %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% саҥардыыны туруорунар. Сотору бэйэтэ холбонуо…
BrowserWorksMaintenanceDescription=BrowserWorks өйүүр сулууспата Эн көмпүүтэргэр Waterfox тиһэх барыла турарын мэктиэлиир. Waterfox кэмиттэн кэмигэр саҥардыллыахтаах, ол Интэриниэттэн Эйиэхэ куттал суоһаабатыгар улахан суолталаах, онон BrowserWorks бу сулууспаны куруук холбонулла сылдьарын сүбэлиир.
