# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Динамические темы
dynamic-theme-dark =
    .label = Принудительно тёмный режим
dynamic-theme-light =
    .label = Принудительно светлый режим
dynamic-theme-auto =
    .label = Динамически устанавливать светлый/тёмный режим
pane-theme-title = Внешний вид и ощущения
animation-header = Анимации
appearance-header = Внешний вид
autohide-hidden-header = Автоскрытие и скрытие
bookmark-header = Панель закладок
center-header = Центр
font-header = Шрифты
full-screen-header = Полный экран
icons-header = Иконки
interface-component-header = Компоненты интерфейса
media-player-header = Медиаплеер
nav-bar-header = Панель навигации
panels-header = Панели
rounding-header = Скругление
sidebar-header = Боковая панель
tab-bar-header = Панель вкладок
theme-header = Тема
preset-title = Предустановки
lepton-style =
    .label = Стиль лептона
proton-style =
    .label = Стиль протона
waterfox-defaults =
    .label = Умолчания Waterfox
auto-blur-tabs =
    .label = Авторазмытие вкладок
auto-hide-back =
    .label = Автоскрытие кнопки «Назад»
auto-hide-bookmarkbar =
    .label = Автоскрытие панели закладок
auto-hide-forward =
    .label = Автоскрытие кнопки "Вперёд"
auto-hide-navbar =
    .label = Автоскрытие панели навигации
auto-hide-pageaction =
    .label = Автоскрытие действий страницы
auto-hide-sidebar =
    .label = Автоскрытие боковой панели
auto-hide-tabbar =
    .label = Автоскрытие панели закладок
auto-hide-tabs =
    .label = Автоскрытие вкладок
center-navbar-text =
    .label = Центрировать текст панели навигации
center-tab-content =
    .label = Центрировать содержимое вкладки
center-tab-label =
    .label = Только метка центральной вкладки
close-button-hover =
    .label = Показывать кнопку закрытия вкладки при наведении на выбранную вкладку, когда открыто много вкладок
compact-bookmark-menu =
    .label = Уменьшить отступы в меню закладок
compact-context-menu =
    .label = Уменьшить отступы контекстного меню
hide-all-icons =
    .label = Скрывать все иконки
hide-bookmarkbar-icon =
    .label = Скрывать иконки панели закладок
hide-tab-icons =
    .label = Скрывать иконки вкладок
square-button-edges =
    .label = Квадратные углы кнопок
square-checkbox =
    .label = Квадратные чекбоксы
square-tab-edges =
    .label = Квадратные углы вкладок
category-theme =
    .tooltiptext = { pane-theme-title }
disable-sidebar-animate =
    .label = Отключить анимацию боковой панели
drag-space =
    .label = Включить фиксированное пространство для перемещения
enable-cyan-accent-color =
    .label = Голубой акцентный цвет
enable-default-accent-color =
    .label = Акцентный цвет по умолчанию
enable-menu-transparency =
    .label = Включить прозрачность меню
enable-panel-transparency =
    .label = Включить прозрачность панели
enable-system-accent-color =
    .label = Системный акцентный цвет
enable-waterfox-theme-0 =
    .label = Включить кастомизацию тем Waterfox для всех тем
enable-waterfox-theme-1 =
    .label = Включить кастомизацию тем Waterfox для тем Waterfox
enable-waterfox-theme-2 =
    .label = Отключить кастомизацию тем Waterfox
hide-bookmarkbar-label =
    .label = Скрыть названия на панели закладок
hide-disabled-menuitems =
    .label = Скрыть отключенные элементы в меню
hide-sidebar-header =
    .label = Скрыть заголовок боковой панели
hide-urlbar-iconbox =
    .label = Скрыть иконку в панели URL
monospace-font =
    .label = Включить моноширный шрифт для старницы
monospace-font-theme =
    .label = Включить моноширный шрифт для темы
show-menu-icons =
    .label = Показывать иконки в меню
waterfox-appearance-browser-style-group =
    .label = Стиль браузера
    .description = Выберите общий облик Waterfox.
waterfox-appearance-interface-customizations-group =
    .label = Кастомизация интерфейса
    .description = Дополнительная кастомизация для вкладок, панели инструментов, иконок и содержимого.
waterfox-density-group =
    .label = Плотность
    .description = Сколько свободного места отдается на панель инструментов и меню.
waterfox-density-compact =
    .label = Компактный
waterfox-density-normal =
    .label = Нормальный
waterfox-appearance-statusbar-heading =
    .label = Строка состояния
waterfox-appearance-statusbar-enabled-toggle =
    .label = Показывать панель состояния
    .description = Показывать ли строку внизу окна.
waterfox-appearance-statusbar-links-toggle =
    .label = Показывать место назначения ссылки в строке состояния
disable-panel-animate =
    .label = Отключить анимацию панели меню
waterfox-density-touch =
    .label = Touch
compact-navbar-popup =
    .label = Уменьшать отступы во всплывающих окнах панели навигации
compact-panel-header =
    .label = Уменьшать отступы в заголовках панелей
full-panel-strip =
    .label = Разделитель на всю ширину меню приложения
remove-panel-strip =
    .label = Убрать цветной разделитель меню приложения
show-mac-menu-icons =
    .label = Показывать значки в меню Mac
square-field =
    .label = Квадратные углы полей ввода
square-menu-item =
    .label = Квадратные углы пунктов контекстного меню
square-menu-panel =
    .label = Квадратные углы панели меню приложения
square-menu-popup =
    .label = Квадратные углы панели контекстного меню
square-panel-item =
    .label = Квадратные углы пунктов меню приложения
tab-context-line =
    .label = Контекстная линия вкладки
waterfox-appearance-chrome-sheet =
    .label = Загружать настройки внешнего вида
    .description = Отключите, чтобы выгрузить таблицу стилей Waterfox и скрыть все связанные с ней параметры.
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = Встроенные темы
waterfox-appearance-chrome-sheet-all-themes =
    .label = Все темы
waterfox-appearance-chrome-sheet-off =
    .label = Отключено
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = Фирменный стиль Waterfox поверх стандартного оформления браузера.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = Современное стандартное оформление браузера.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = Классическое оформление Waterfox с доработанным интерфейсом браузера.
waterfox-appearance-theme-colors-group =
    .label = Цветовая палитра
    .description = Выберите цветовую палитру Waterfox и то, следует ли она системной теме.
waterfox-appearance-theme-mode-picker =
    .label = Режим темы
waterfox-appearance-theme-mode-option-system =
    .label = Системная
waterfox-appearance-theme-mode-option-light =
    .label = Светлая
waterfox-appearance-theme-mode-option-dark =
    .label = Тёмная
waterfox-appearance-theme-color-picker =
    .label = Цвет темы
waterfox-appearance-theme-color-option-default =
    .label = Стандартный
waterfox-appearance-theme-color-option-smoke =
    .label = Дым
waterfox-appearance-theme-color-option-ash =
    .label = Пепел
waterfox-appearance-theme-color-option-sun =
    .label = Солнце
waterfox-appearance-theme-color-option-spark =
    .label = Искра
waterfox-appearance-theme-color-option-flame =
    .label = Пламя
waterfox-appearance-theme-color-option-flare =
    .label = Вспышка
waterfox-appearance-theme-color-option-lavender =
    .label = Лаванда
waterfox-appearance-theme-color-option-dusk =
    .label = Сумерки
waterfox-appearance-theme-color-option-lagoon =
    .label = Лагуна
waterfox-appearance-theme-color-option-tide =
    .label = Прилив
waterfox-appearance-theme-color-option-pine =
    .label = Сосна
waterfox-appearance-details-group =
    .label = Дополнительные параметры внешнего вида
    .description = Точная настройка интерфейса Waterfox.
waterfox-appearance-transparent-toggle =
    .label = Прозрачные панели и меню
waterfox-appearance-autohide-tabbar-toggle =
    .label = Скрывать панель вкладок, пока на неё не наведён указатель
waterfox-appearance-autohide-bookmarks-toggle =
    .label = Скрывать панель закладок, пока на неё не наведён указатель
waterfox-appearance-autohide-sidebar-toggle =
    .label = Скрывать боковую панель, пока на неё не наведён указатель
waterfox-appearance-autohide-navigation-toggle =
    .label = Скрывать кнопки «Назад» и «Вперёд», когда они бездействуют
waterfox-appearance-close-button-hover-toggle =
    .label = Показывать кнопку закрытия вкладки только при наведении
waterfox-appearance-drag-space-toggle =
    .label = Оставлять место для перетаскивания над вкладками
waterfox-opt-tabbar-heading =
    .label = Панель вкладок
    .description = Размер, отступы и видимость полосы, в которой расположены вкладки.
waterfox-opt-tabbar-fill-width =
    .label = Растягивать вкладки на всю ширину
waterfox-opt-tabbar-as-titlebar =
    .label = Показывать в заголовке окна только текущую вкладку
waterfox-opt-hidden-tabbar =
    .label = Скрыть панель вкладок
waterfox-opt-hidden-titlebar-container =
    .label = Скрыть контейнер заголовка окна
waterfox-opt-autohide-tab =
    .label = Сжимать фоновые вкладки, пока на них не наведён указатель
waterfox-opt-autohide-tab-opacity =
    .label = Также делать их прозрачнее
waterfox-opt-autohide-tab-blur =
    .label = Также размывать их
waterfox-opt-padding-tabbar-width =
    .label = Сузить панель вкладок
waterfox-opt-padding-tabbar-height =
    .label = Уменьшить высоту панели вкладок
waterfox-opt-padding-first-tab =
    .label = Оставлять отступ перед первой вкладкой
waterfox-opt-padding-first-tab-always =
    .label = Сохранять отступ даже в развёрнутом окне
waterfox-opt-padding-drag-space =
    .label = Оставлять место для перетаскивания над вкладками
waterfox-opt-padding-drag-space-maximized =
    .label = Сохранять его и в развёрнутом окне
waterfox-opt-centered-tab =
    .label = Центрировать содержимое вкладки
waterfox-opt-centered-tab-label =
    .label = Центрировать только название
waterfox-opt-counter-tab =
    .label = Показывать счётчик вкладок
waterfox-opt-tabs-heading =
    .label = Вкладки
    .description = Форма вкладки и то, что на ней отображается.
waterfox-opt-tab-connect-to-window =
    .label = Соединять выбранную вкладку с панелью инструментов внизу
waterfox-opt-tab-color-like-toolbar =
    .label = Окрашивать выбранную вкладку в цвет панели инструментов
waterfox-opt-tab-box-shadow =
    .label = Отбрасывать тень под выбранной вкладкой
waterfox-opt-tab-selected-bold =
    .label = Выделять название выбранной вкладки жирным
waterfox-opt-tab-blue-accent =
    .label = Использовать синий акцент на выбранной вкладке
waterfox-opt-tab-contextline-blue-accent =
    .label = Использовать синий акцент на контекстной линии
waterfox-opt-tab-bottom-rounded-corner =
    .label = Скруглять нижние углы выбранной вкладки
waterfox-opt-tab-bottom-rounded-corner-all =
    .label = Применять скругление ко всем вкладкам
waterfox-opt-tab-multi-selected =
    .label = Сильнее выделять вкладки при множественном выборе
waterfox-opt-tab-letters-cleary =
    .label = Сохранять читаемость названий на узких вкладках
waterfox-opt-hidden-tab-icon =
    .label = Скрыть значки вкладок
waterfox-opt-hidden-tab-icon-always =
    .label = Скрывать их даже на закреплённых вкладках
waterfox-opt-tab-close-button-at-hover =
    .label = Показывать кнопку закрытия только при наведении
waterfox-opt-tab-close-button-at-hover-always =
    .label = Делать это независимо от числа открытых вкладок
waterfox-opt-tab-close-button-at-hover-with-selected =
    .label = Включая выбранную вкладку
waterfox-opt-tab-close-button-at-pinned =
    .label = Показывать кнопку закрытия на закреплённых вкладках
waterfox-opt-tab-close-button-at-pinned-always =
    .label = Показывать её без наведения
waterfox-opt-tab-close-button-at-pinned-background =
    .label = Добавить ей фон
waterfox-opt-tab-container =
    .label = Отмечать вкладки контейнеров их цветом
waterfox-opt-tab-container-on-top =
    .label = Помещать отметку над вкладкой
waterfox-opt-tab-container-always-long =
    .label = Растягивать её на всю ширину вкладки
waterfox-opt-tab-sound-with-favicons =
    .label = Показывать индикатор звука поверх значка вкладки
waterfox-opt-tab-sound-with-favicons-on-center =
    .label = Центрировать его на значке
waterfox-opt-tab-unloaded =
    .label = Делать выгруженные вкладки бледнее
waterfox-opt-tab-unloaded-grayscale =
    .label = Делать значки выгруженных вкладок чёрно-белыми
waterfox-opt-tab-crashed =
    .label = Показывать на упавших вкладках только индикатор сбоя
waterfox-opt-tab-pip =
    .label = Отмечать вкладки с картинкой в картинке
waterfox-opt-tab-padding =
    .label = Отступы вкладки
waterfox-opt-tab-padding-default =
    .label = По умолчанию
waterfox-opt-tab-padding-lepton =
    .label = Просторные
waterfox-opt-tab-padding-photon =
    .label = Компактные
waterfox-opt-tab-separator =
    .label = Разделитель между вкладками
waterfox-opt-tab-separator-none =
    .label = Нет
waterfox-opt-tab-separator-dynamic =
    .label = Только между невыбранными вкладками
waterfox-opt-tab-separator-static =
    .label = Между всеми вкладками
waterfox-opt-tab-separator-bar =
    .label = Полоса на всю высоту
waterfox-opt-tab-newtab-button =
    .label = Кнопка новой вкладки
waterfox-opt-tab-newtab-button-default =
    .label = По умолчанию
waterfox-opt-tab-newtab-button-like-tab =
    .label = В форме вкладки
waterfox-opt-tab-newtab-button-smaller =
    .label = Меньше
waterfox-opt-tab-newtab-button-proton =
    .label = Proton
waterfox-opt-tab-contextline =
    .label = Индикатор выбранной вкладки
waterfox-opt-tab-contextline-none =
    .label = Нет
waterfox-opt-tab-contextline-photon =
    .label = Линия над вкладкой
waterfox-opt-tab-contextline-supernova =
    .label = Линия под вкладкой
waterfox-opt-tab-corner-style =
    .label = Форма нижних углов
waterfox-opt-tab-corner-style-default =
    .label = По умолчанию
waterfox-opt-tab-corner-style-australis =
    .label = Australis
waterfox-opt-tab-corner-style-chrome =
    .label = Chrome
waterfox-opt-tab-corner-style-chrome-legacy =
    .label = Chrome (устаревший)
waterfox-opt-tab-corner-style-edge =
    .label = Edge
waterfox-opt-tab-corner-style-wave =
    .label = Wave
waterfox-opt-tab-static-separator-selected-accent =
    .label = Выделять акцентом разделитель рядом с выбранной вкладкой
waterfox-opt-toolbars-heading =
    .label = Панели инструментов
    .description = Кнопки навигации, отступы панелей инструментов и то, что скрывается само.
waterfox-opt-hidden-navbar =
    .label = Скрыть панель навигации
waterfox-opt-autohide-navbar =
    .label = Скрывать её, пока на неё не наведён указатель
waterfox-opt-autohide-back-button =
    .label = Скрывать кнопку «Назад», когда она бездействует
waterfox-opt-autohide-forward-button =
    .label = Скрывать кнопку «Вперёд», когда она бездействует
waterfox-opt-combined-nav-button =
    .label = Объединить кнопки навигации
waterfox-opt-combined-nav-button-home-button =
    .label = Включить кнопку «Домой»
waterfox-opt-padding-toolbar-button =
    .label = Уменьшить отступы кнопок панели инструментов
waterfox-opt-padding-toolbar-button-compact =
    .label = Уменьшить их ещё сильнее
waterfox-opt-autohide-toolbar-overlap =
    .label = Разрешить автоскрываемым панелям перекрывать страницу
waterfox-opt-autohide-infobar =
    .label = Скрывать панели уведомлений, пока на них не наведён указатель
waterfox-opt-padding-infobar =
    .label = Уменьшить отступы панели уведомлений
waterfox-opt-findbar-floating-on-top =
    .label = Отображать панель поиска поверх страницы
waterfox-opt-padding-global-menubar =
    .label = Уменьшить отступы строки меню
waterfox-opt-centered-urlbar =
    .label = Центрировать текст в адресной строке
waterfox-opt-autohide-fill-urlbar =
    .label = Заполнять панель инструментов адресной строкой, пока на неё не наведён указатель
waterfox-opt-autohide-page-action =
    .label = Скрывать кнопки действий страницы, пока на них не наведён указатель
waterfox-opt-urlbar-always-show-page-actions =
    .label = Всегда показывать кнопки действий страницы
waterfox-opt-hidden-urlbar-iconbox =
    .label = Скрыть блок идентификации сайта
waterfox-opt-hidden-urlbar-iconbox-label-only =
    .label = Скрыть только его подпись
waterfox-opt-urlbar-iconbox-with-separator =
    .label = Отделять блок идентификации линией
waterfox-opt-urlview-focus-item-border =
    .label = Обводить рамкой выделенный результат
waterfox-opt-padding-urlview-result =
    .label = Уменьшить отступы строк результатов
waterfox-opt-rounding-square-urlview-item =
    .label = Сделать углы результатов квадратными
waterfox-opt-bookmarks-heading =
    .label = Закладки
    .description = Панель закладок и меню закладок.
waterfox-opt-bookmarkbar-multi-row =
    .label = Переносить панель закладок на несколько строк
waterfox-opt-autohide-bookmarkbar =
    .label = Скрывать панель закладок, пока на неё не наведён указатель
waterfox-opt-centered-bookmarkbar =
    .label = Центрировать панель закладок
waterfox-opt-padding-bookmarkbar =
    .label = Уменьшить отступы панели закладок
waterfox-opt-hidden-bookmarkbar-icon =
    .label = Скрыть значки закладок
waterfox-opt-hidden-bookmarkbar-label =
    .label = Скрыть названия закладок
waterfox-opt-padding-bookmark-menu =
    .label = Уменьшить отступы меню закладок
waterfox-opt-padding-bookmark-menu-compact =
    .label = Уменьшить их ещё сильнее
waterfox-opt-counter-bookmark-menu =
    .label = Показывать счётчик в меню закладок
waterfox-opt-decoration-disable-sidebar-animate =
    .label = Отключить анимацию боковой панели
waterfox-opt-icons-heading =
    .label = Значки
    .description = Где появляются значки и насколько они крупные.
waterfox-opt-icon-disabled =
    .label = Скрыть все значки меню и панелей
waterfox-opt-icon-menu =
    .label = Показывать значки в меню
waterfox-opt-icon-menu-full =
    .label = Показывать их на каждом пункте меню
waterfox-opt-icon-context-menu =
    .label = Показывать значки в контекстных меню
waterfox-opt-icon-global-menu =
    .label = Показывать значки в меню строки меню
waterfox-opt-icon-global-menu-mac =
    .label = Показывать их и на macOS
waterfox-opt-icon-global-menubar =
    .label = Показывать значки в строке меню
waterfox-opt-icon-panel =
    .label = Показывать значки в панелях
waterfox-opt-icon-library =
    .label = Показывать значки в библиотеке
waterfox-opt-icon-1-25px-stroke =
    .label = Использовать более толстые линии значков
waterfox-opt-icon-account-image-to-right =
    .label = Разместить изображение аккаунта справа
waterfox-opt-icon-account-label-to-right =
    .label = Разместить имя аккаунта справа
waterfox-opt-panel-icons =
    .label = Значки меню приложения
    .description = Скольким строкам главного меню Waterfox назначает значок.
waterfox-opt-panel-icons-photon =
    .label = Только основным пунктам
waterfox-opt-panel-icons-full =
    .label = Каждому пункту
waterfox-opt-rounding-heading =
    .label = Углы
    .description = Убрать скругление углов элементов интерфейса.
waterfox-opt-rounding-square-tab =
    .label = Сделать углы вкладок квадратными
waterfox-opt-rounding-square-toolbar =
    .label = Сделать углы панелей инструментов квадратными
waterfox-opt-rounding-square-button =
    .label = Сделать углы кнопок квадратными
waterfox-opt-rounding-square-field =
    .label = Сделать углы текстовых полей квадратными
waterfox-opt-rounding-square-checklabel =
    .label = Сделать углы флажков квадратными
waterfox-opt-rounding-square-dialog =
    .label = Сделать углы диалоговых окон квадратными
waterfox-opt-rounding-square-infobox =
    .label = Сделать углы уведомлений квадратными
waterfox-opt-rounding-square-panel =
    .label = Сделать углы панели квадратными
waterfox-opt-rounding-square-panelitem =
    .label = Сделать углы пунктов панели квадратными
waterfox-opt-rounding-square-menupopup =
    .label = Сделать углы меню квадратными
waterfox-opt-rounding-square-menuitem =
    .label = Сделать углы пунктов меню квадратными
waterfox-opt-theme-heading =
    .label = Тема и эффекты
    .description = Цвет, прозрачность и анимация в интерфейсе.
waterfox-opt-theme-proton-color =
    .label = Использовать цветовую палитру Proton на встроенных страницах
    .description = Применяется к страницам about: и другим встроенным окнам, но не к рамке браузера.
waterfox-opt-theme-proton-chrome =
    .label = Применить её к диалогам и окнам библиотеки
waterfox-opt-theme-fully-color =
    .label = Применить её везде
waterfox-opt-theme-fully-dark =
    .label = Предотвращать световые вспышки в тёмном режиме
waterfox-opt-theme-built-in-contrast =
    .label = Повысить контрастность встроенных тем
waterfox-opt-theme-system-default =
    .label = Следовать системной теме
waterfox-opt-theme-private =
    .label = Тонировать приватные окна
waterfox-opt-hidden-private-indicator =
    .label = Скрыть индикатор приватного просмотра
waterfox-opt-theme-transparent-panel =
    .label = Сделать панели прозрачными
waterfox-opt-theme-transparent-frame =
    .label = Сделать рамку окна прозрачной
waterfox-opt-theme-monospace =
    .label = Использовать моноширинный шрифт в интерфейсе
waterfox-opt-decoration-animate =
    .label = Анимировать изменения интерфейса
waterfox-opt-decoration-disable-panel-animate =
    .label = Отключить анимацию меню приложения
waterfox-opt-content-heading =
    .label = Веб-страницы
    .description = Стилизация, которую Waterfox применяет поверх веб-страниц.
waterfox-opt-page-monospace =
    .label = Использовать моноширинный шрифт на встроенных страницах
waterfox-opt-page-dark-mode-pdf =
    .label = Затемнять PDF при использовании тёмной темы
waterfox-opt-newtab-heading =
    .label = Страница новой вкладки
    .description = Внешний вид страницы, которая открывается в новой вкладке.
waterfox-opt-newtab-hidden-logo =
    .label = Скрыть логотип
waterfox-opt-newtab-full-icon =
    .label = Заполнять плитки быстрого доступа их значком
waterfox-opt-newtab-background-image =
    .label = Показывать фоновое изображение
waterfox-opt-newtab-animate =
    .label = Анимировать плитки
waterfox-opt-player-heading =
    .label = Видеоплеер
    .description = Элементы управления и размеры встроенного видеоплеера.
waterfox-opt-player-ui =
    .label = Изменить стиль встроенных элементов управления видео
waterfox-opt-player-ui-twoline =
    .label = Расположить элементы управления в две строки
waterfox-opt-player-icon =
    .label = Использовать значки управления Waterfox
waterfox-opt-player-size =
    .label = Увеличить элементы управления
waterfox-opt-player-noaudio =
    .label = Скрывать регулятор громкости, если в видео нет звука
waterfox-opt-player-click-to-play =
    .label = Стилизовать оверлей запуска по клику
    .description = Добавляет подсветку при наведении и курсор-указатель к существующему оверлею.
waterfox-opt-player-animate =
    .label = Анимировать элементы управления
