# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Динамические темы
dynamic-theme-dark =
    .label = Принудительно тёмный режим
dynamic-theme-light =
    .label = Принудительно светлый режим
dynamic-theme-auto =
    .label = Динамически устанавливать светлый/тёмный режим
pane-theme-title = Внешний вид и ощущения
animation-header = Анимации
appearance-header = Внешний вид
autohide-hidden-header = Автоскрытие и скрытие
bookmark-header = Панель закладок
center-header = Центр
font-header = Шрифты
full-screen-header = Полный экран
icons-header = Иконки
interface-component-header = Компоненты интерфейса
media-player-header = Медиаплеер
nav-bar-header = Панель навигации
panels-header = Панели
rounding-header = Скругление
sidebar-header = Боковая панель
tab-bar-header = Панель вкладок
theme-header = Тема
preset-title = Предустановки
lepton-style =
    .label = Стиль лептона
proton-style =
    .label = Стиль протона
waterfox-defaults =
    .label = Умолчания Waterfox
auto-blur-tabs =
    .label = Авторазмытие вкладок
auto-hide-back =
    .label = Автоскрытие кнопки «Назад»
auto-hide-bookmarkbar =
    .label = Автоскрытие панели закладок
auto-hide-forward =
    .label = Автоскрытие кнопки "Вперёд"
auto-hide-navbar =
    .label = Автоскрытие панели навигации
auto-hide-pageaction =
    .label = Автоскрытие действий страницы
auto-hide-sidebar =
    .label = Автоскрытие боковой панели
auto-hide-tabbar =
    .label = Автоскрытие панели закладок
auto-hide-tabs =
    .label = Автоскрытие вкладок
center-navbar-text =
    .label = Центрировать текст панели навигации
center-tab-content =
    .label = Центрировать содержимое вкладки
center-tab-label =
    .label = Только метка центральной вкладки
close-button-hover =
    .label = Показывать кнопку закрытия вкладки при наведении на выбранную вкладку, когда открыто много вкладок
compact-bookmark-menu =
    .label = Уменьшить отступы в меню закладок
compact-context-menu =
    .label = Уменьшить отступы контекстного меню
hide-all-icons =
    .label = Скрывать все иконки
hide-bookmarkbar-icon =
    .label = Скрывать иконки панели закладок
hide-tab-icons =
    .label = Скрывать иконки вкладок
square-button-edges =
    .label = Квадратные углы кнопок
square-checkbox =
    .label = Квадратные чекбоксы
square-tab-edges =
    .label = Квадратные углы вкладок
category-theme =
    .tooltiptext = { pane-theme-title }
disable-sidebar-animate =
    .label = Отключить анимацию боковой панели
drag-space =
    .label = Включить фиксированное пространство для перемещения
enable-cyan-accent-color =
    .label = Голубой акцентный цвет
enable-default-accent-color =
    .label = Акцентный цвет по умолчанию
enable-menu-transparency =
    .label = Включить прозрачность меню
enable-panel-transparency =
    .label = Включить прозрачность панели
enable-system-accent-color =
    .label = Системный акцентный цвет
enable-waterfox-theme-0 =
    .label = Включить кастомизацию тем Waterfox для всех тем
enable-waterfox-theme-1 =
    .label = Включить кастомизацию тем Waterfox для тем Waterfox
enable-waterfox-theme-2 =
    .label = Отключить кастомизацию тем Waterfox
hide-bookmarkbar-label =
    .label = Скрыть названия на панели закладок
hide-disabled-menuitems =
    .label = Скрыть отключенные элементы в меню
hide-sidebar-header =
    .label = Скрыть заголовок боковой панели
hide-urlbar-iconbox =
    .label = Скрыть иконку в панели URL
monospace-font =
    .label = Включить моноширный шрифт для старницы
monospace-font-theme =
    .label = Включить моноширный шрифт для темы
show-menu-icons =
    .label = Показывать иконки в меню
waterfox-appearance-browser-style-group =
    .label = Стиль браузера
    .description = Выберите общий облик Waterfox.
waterfox-appearance-interface-customizations-group =
    .label = Кастомизация интерфейса
    .description = Дополнительная кастомизация для вкладок, панели инструментов, иконок и содержимого.
