# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

onboarding-grassroots-title = Поддержка народных инициатив
onboarding-grassroots-subtitle = Спасибо, что используете Waterfox, независимый, народный браузер. С вашей поддержкой мы создаём устойчивую альтернативу крупным игрокам на рынке.
waterfox-onboarding-welcome-title = Добро пожаловать в { -brand-short-name }
waterfox-onboarding-welcome-subtitle = Независимый, быстрый браузер с теми настройками Waterfox, которые вы ожидаете.
waterfox-onboarding-start-button = Начать
waterfox-onboarding-language-hint = Вы можете изменить это в любой момент в настройках.
waterfox-onboarding-language-error = { -brand-short-name } не удалось изменить язык. Ваш прежний язык по-прежнему активен.
waterfox-onboarding-step-label = Шаг { $current } из { $total }
waterfox-onboarding-import-title = Перенесите свои данные
waterfox-onboarding-import-subtitle = Импортируйте закладки, историю и данные форм из { migration-wizard-migrator-display-name-firefox } или другого браузера, не покидая эту настройку.
waterfox-onboarding-style-title = Выберите стиль Waterfox
waterfox-onboarding-style-subtitle = Выберите форму вкладок и панели инструментов, а также насколько компактно всё будет выглядеть.
waterfox-onboarding-tabs-style-legend = Стиль браузера
waterfox-onboarding-style-nova-label = Nova
waterfox-onboarding-style-nova-body = Более чёткий стиль Waterfox с ярче выделенной линией активной вкладки.
waterfox-onboarding-style-proton-label = Proton
waterfox-onboarding-style-proton-body = Более спокойный внешний вид с современными отступами браузера.
waterfox-onboarding-style-photon-label = Photon
waterfox-onboarding-style-photon-body = Классический облик Waterfox с доработанным интерфейсом.
waterfox-onboarding-tabs-density-legend = Плотность
waterfox-onboarding-density-normal-label = Нормальная
waterfox-onboarding-density-compact-label = Компактная
waterfox-onboarding-density-touch-label = Touch
waterfox-onboarding-customize-appearance-button = Настроить внешний вид в настройках
waterfox-onboarding-theme-color-title = Сделайте его своим
waterfox-onboarding-theme-color-subtitle = Выберите цвет темы, который сделает каждое окно по-настоящему вашим.
waterfox-onboarding-appearance-subtitle = Выберите форму, плотность и цвет. Всё остальное можно точно настроить позже в настройках.
waterfox-onboarding-theme-mode-legend = Цветовая схема
waterfox-onboarding-theme-mode-system-label = Системная
waterfox-onboarding-theme-mode-light-label = Светлая
waterfox-onboarding-theme-mode-dark-label = Тёмная
waterfox-onboarding-theme-color-legend = Цвет темы
waterfox-onboarding-color-default-label = Стандартный
waterfox-onboarding-color-smoke-label = Дым
waterfox-onboarding-color-ash-label = Пепел
waterfox-onboarding-color-sun-label = Солнце
waterfox-onboarding-color-spark-label = Искра
waterfox-onboarding-color-flame-label = Пламя
waterfox-onboarding-color-flare-label = Вспышка
waterfox-onboarding-color-lavender-label = Лаванда
waterfox-onboarding-color-dusk-label = Сумерки
waterfox-onboarding-color-lagoon-label = Лагуна
waterfox-onboarding-color-tide-label = Прилив
waterfox-onboarding-color-pine-label = Сосна
waterfox-onboarding-tabs-title = Организуйте вкладки по-своему
waterfox-onboarding-tabs-subtitle = Выберите, как располагаются вкладки и где находится горизонтальная панель вкладок. Оба параметра можно изменить позже в настройках.
waterfox-onboarding-tabs-layout-legend = Расположение вкладок
waterfox-onboarding-tabs-horizontal-label = Горизонтальные вкладки
waterfox-onboarding-tabs-horizontal-body = Классическая панель вкладок сверху.
waterfox-onboarding-tabs-vertical-label = Вертикальные вкладки
waterfox-onboarding-tabs-vertical-body = Перенести вкладки в боковую панель в виде вытянутого списка.
waterfox-onboarding-tabs-tree-label = Древовидные вкладки
waterfox-onboarding-tabs-tree-body = Вертикальные вкладки, вложенные под открывшую их вкладку.
waterfox-onboarding-tabs-location-label = Расположение панели вкладок
waterfox-onboarding-location-top-above-label = Над панелью инструментов
waterfox-onboarding-location-top-below-label = Под панелью инструментов
waterfox-onboarding-location-bottom-above-label = Над строкой состояния
waterfox-onboarding-location-bottom-below-label = Под строкой состояния
waterfox-onboarding-tabs-location-hint = Применяется к горизонтальным вкладкам. Больше вариантов расположения — в настройках.
waterfox-onboarding-customize-tabs-button = Настроить вкладки в настройках
waterfox-onboarding-privacy-title = Инструменты приватности готовы к работе
waterfox-onboarding-privacy-subtitle = Waterfox по умолчанию запускается с блокировкой рекламы и настройками приватности. Вы можете точно настроить их в любой момент.
waterfox-onboarding-privacy-primary-button = Оставить защиту включённой
waterfox-onboarding-customize-privacy-button = Настроить параметры приватности
waterfox-onboarding-default-title = Сделайте { -brand-short-name } браузером по умолчанию
waterfox-onboarding-default-subtitle = Открывайте ссылки в { -brand-short-name } по умолчанию и держите свои настройки Waterfox под рукой.
waterfox-onboarding-default-primary-button = Сделать браузером по умолчанию
waterfox-onboarding-finish-title = Всё готово
waterfox-onboarding-finish-subtitle = Спасибо, что выбрали Waterfox. Ваш браузер готов к работе.
waterfox-onboarding-finish-privacy-note = Блокировка рекламы и защита от отслеживания уже включены.
waterfox-onboarding-finish-primary-button = Начать пользоваться браузером
waterfox-onboarding-continue-button = Продолжить
waterfox-onboarding-save-continue-button = Сохранить и продолжить
waterfox-onboarding-skip-button = Не сейчас
waterfox-onboarding-skip-step-button = Пропустить этот шаг
waterfox-onboarding-back-button = Назад
