# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Thèmes Dynamiques
dynamic-theme-dark =
    .label = Forcer le mode sombre
dynamic-theme-light =
    .label = Forcer le mode clair
sidebar-header = Barre latérale
tab-bar-header = Barre d'onglets
dynamic-theme-auto =
    .label = Définir dynamiquement le mode clair/sombre
appearance-header = Apparence
bookmark-header = Barre de signets
center-header = Centrer
full-screen-header = Plein écran
icons-header = Icônes
interface-component-header = Éléments d'interface
media-player-header = Lecteur multimédia
theme-header = Thème
preset-title = Préréglages
waterfox-appearance-statusbar-enabled-toggle =
    .label = Afficher la barre d'état
    .description = Affichez une barre d'outils au bas de la fenêtre.
waterfox-appearance-statusbar-heading =
    .label = Barre d'état
waterfox-appearance-statusbar-links-toggle =
    .label = Afficher les destinations de liens dans la barre d'état
lepton-style =
    .label = Style Lepton
proton-style =
    .label = Style Proton
auto-blur-tabs =
    .label = Flou automatique sur les onglets
center-tab-label =
    .label = Centrer uniquement le titre d'un onglet
close-button-hover =
    .label = Afficher le bouton de fermeture de l'onglet au survol de l'onglet sélectionné lorsque plusieurs onglets sont ouverts
enable-cyan-accent-color =
    .label = Couleur d'accentuation Cyan
enable-default-accent-color =
    .label = Couleur d'accentuation par défaut
enable-system-accent-color =
    .label = Couleur d'accentuation du systéme
enable-waterfox-theme-0 =
    .label = Activer la customisation de thème Waterfox sur tous les thèmes
enable-waterfox-theme-1 =
    .label = Activé la customisation de thème Waterfox sur les thèmes Waterfox
hide-all-icons =
    .label = Masquer toute les icônes
auto-hide-sidebar =
    .label = Masquer autimatiquement la barre latérale
auto-hide-bookmarkbar =
    .label = Masquer automatiquement la barre des marque-pages
auto-hide-navbar =
    .label = Masquer automatiquement la Barre de Navigation
animation-header = Animations
font-header = Polices
nav-bar-header = Barre de Navigation
panels-header = Panneau
auto-hide-back =
    .label = Masquer automatiquement le bouton Retour
auto-hide-forward =
    .label = Masquer automatiquement le bouton Suivant
auto-hide-tabbar =
    .label = Masquer autimatiquement la barre d'onglets
auto-hide-tabs =
    .label = Masquer autimatiquement les onglets
center-navbar-text =
    .label = Centrer le texte de la barre de navigation
enable-waterfox-theme-2 =
    .label = Désactiver la customisation de thème Waterfox
hide-bookmarkbar-icon =
    .label = Masquer les icônes de la barre de marque-pages
hide-bookmarkbar-label =
    .label = Masquer les titres de la barre des marque-pages
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
hide-sidebar-header =
    .label = Hide Sidebar Header
hide-tab-icons =
    .label = Masquer les icônes des onglets
waterfox-appearance-theme-mode-option-system =
    .label = Système
waterfox-appearance-theme-mode-option-light =
    .label = Clair
waterfox-appearance-theme-mode-option-dark =
    .label = Sombre
waterfox-appearance-theme-color-picker =
    .label = Couleur du thème
waterfox-appearance-theme-color-option-default =
    .label = Par défaut
waterfox-appearance-theme-color-option-smoke =
    .label = Fumée
waterfox-appearance-theme-color-option-ash =
    .label = Cendre
waterfox-appearance-theme-color-option-sun =
    .label = Soleil
waterfox-appearance-theme-color-option-spark =
    .label = Éclat
waterfox-appearance-theme-color-option-flame =
    .label = Flamme
waterfox-appearance-theme-color-option-flare =
    .label = Lueur
waterfox-appearance-theme-color-option-lavender =
    .label = Lavande
waterfox-appearance-theme-color-option-dusk =
    .label = Crépuscule
waterfox-appearance-theme-color-option-lagoon =
    .label = Lagon
waterfox-appearance-theme-color-option-tide =
    .label = Marin
waterfox-appearance-theme-color-option-pine =
    .label = Pin
