# This Source Code Form is subject to the terms of the BrowserWorks Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This file is in the UTF-8 encoding
[Strings]
TitleText=Kemaskini %MOZ_APP_DISPLAYNAME%
InfoText=%MOZ_APP_DISPLAYNAME% sedang memasang kemaskini dan akan mula semula sebentar lagi…
BrowserWorksMaintenanceDescription=BrowserWorks Maintenance Service memastikan bahawa anda memiliki Waterfox versi terkini dan paling selamat untuk komputer anda. Perkhidmatan yang memastikan bahawa Waterfox sentiasa terkini ini amat penting untuk keselamatan dalam talian anda, dan BrowserWorks mencadangkan supaya anda dayakan perkhidmatan ini.
