restart-prompt-question = Ви впевнені, що хочете перезапустити { -brand-short-name }?
restart-prompt-title = Перезапуск { -brand-short-name }
appmenuitem-restart-browser =
    .label = Перезапустити
copy-all-urls =
    .label = Скопіювати посилання всіх вкладок
copy-url =
    .label = Скопіювати посилання вкладки
unload-tab =
    .label = Вивантажити вкладку
new-private-tab =
    .label = Нова приватна вкладка
    .tooltiptext = Відкрити нову приватну вкладку
open-all-links-private =
    .label = Відкрити всі посилання у приватних вкладках
open-all-private =
    .label = Відкрити все у приватних вкладках
dynamic-theme-auto =
    .label = Динамічно встановлювати світлий/темний режим
dynamic-theme-dark =
    .label = Примусово темний режим
dynamic-theme-light =
    .label = Примусово світлий режим
geolocation-api-header = API геолокації
geolocation-description = Для роботи деяких веб-сайтів потрібне ваше місцезнаходження. Якщо веб-сайт не працює через те, що не може визначити ваше місцезнаходження, увімкніть цей параметр і спробуйте ще раз.
geolocation-api-enabled =
    .label = Увімкнено
geolocation-api-disabled =
    .label = Вимкнено
open-link-private =
    .label = Відкрити посилання у новій приватній вкладці
open-private-tab =
    .label = Відкрити у новій приватній вкладці
private-tab =
    .label =
        { $isPrivate ->
            [true] Вийти з приватної вкладки
           *[false] Створити приватну вкладку
        }
status-bar =
    .label = Рядок стану
update-application-manual =
    .label = Ніколи не перевіряти наявність оновлень (не рекомендовано)
    .accesskey = N
bookmarks-bar-position-header = Розташування рядка закладок
bookmarks-position-bottom =
    .label = Знизу
bookmarks-position-top =
    .label = Згори
dynamic-theme-header = Динамічні теми
restart-header = Елемент перезапуску у головному меню
restart-purge-cache =
    .label = Очищати кеш швидкого запуску під час перезапуску браузера
restart-require-confirmation =
    .label = Вимагати підтвердження перезапуску
restart-show-button =
    .label = Показувати кнопку перезапуску у PanelUI
statusbar-header = Рядок стану
statusbar-contrast-text =
    .label = Контрастний колір тексту рядка стану
statusbar-enabled =
    .label = Показувати рядок стану
statusbar-show-links =
    .label = Показувати посилання
tab-additional-header = Додаткові налаштування вкладок
insert-after-current =
    .label = Вставляти нову вкладку після поточної
insert-related-after-current =
    .label = Вставляти пов'язану нову вкладку за поточною
pinned-icon-only =
    .label = Стискати закріплені вкладки, щоб показувати лише іконку сайту
tab-feature-header = Контекстне меню вкладки
enable-copy-active-tab =
    .label = Копіювати URL тільки з активної вкладки
show-copy-all-urls =
    .label = Показувати елемент меню «Скопіювати усі посилання вкладок»
show-copy-url =
    .label = Показувати елемент меню «Скопіювати посилання вкладки»
show-duplicate-tab =
    .label = Показувати елемент меню «Дублювати вкладку»
show-unload-tab =
    .label = Показувати елемент меню «Вивантажити вкладку»
tab-position-header = Розташування панелі вкладок
tab-bar-bottom-above =
    .label = Знизу над рядком стану
tab-bar-bottom-below =
    .label = Знизу під рядком стану
tab-bar-top-above =
    .label = Згори над адресним рядком
tab-bar-top-below =
    .label = Згори під адресним рядком
enable-javascript =
    .label = Увімкнути JavaScript
load-images =
    .label = Автоматично завантажувати зображення
preferences-doh-setting-ultra =
    .label = Надзвичайний захист
    .accesskey = Н
preferences-doh-ultra-desc = { -brand-short-name } використовуватиме захищену DNS з Oblivious HTTP через приватний ретранслятор Waterfox для максимального захисту.
preferences-doh-ultra-detailed-desc-1 = Використовує Oblivious HTTP ретранслятор Waterfox, щоб приховати запити DNS навіть від провайдера DNS
preferences-doh-ultra-detailed-desc-2 = Надає додатковий рівень шифрування понад стандартним DNS over HTTPS
preferences-doh-ultra-detailed-desc-3 = Максимальний захист конфіденційності DNS — ніхто не бачить, які сайти ви відвідуєте
preferences-doh-ultra-fallback-mode = Поведінка у разі відмови:
preferences-doh-ultra-fallback-allowed = Дозволити повернення до системного DNS, якщо безпечний DNS не спрацює
preferences-doh-ultra-fallback-disabled = Ніколи не повертатися до системного DNS (сайти можуть не завантажуватися, якщо безпечний DNS не спрацює)
ref-header = Заголовок Referrer HTTP
send-referrer-header-0 =
    .label = Ніколи не надсилати заголовок Referrer
send-referrer-header-1 =
    .label = Включати заголовок реферера лише під час натискання на посилання та подібні елементи
send-referrer-header-2 =
    .label = Включати заголовок реферера до всіх запитів (за замовчуванням)
webrtc-header = WebRTC peer connection (з’єднання з іншими вузлами WebRTC)
enable-webrtc-p2p =
    .label = Увімкнути WebRTC peer connection
pane-theme-title = Зовнішній вигляд і поведінка
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Анімації
appearance-header = Зовнішній вигляд
autohide-hidden-header = Автоховання та приховане
bookmark-header = Рядок закладок
center-header = Вирівняти по центру
font-header = Шрифти
full-screen-header = Повний екран
icons-header = Іконки
interface-component-header = Складники інтерфейсу
media-player-header = Програвач медіа
nav-bar-header = Панель навігації
panels-header = Панелі
rounding-header = Скруглення
sidebar-header = Бічна панель
tab-bar-header = Панель вкладок
theme-header = Тема
preset-title = Пресети
lepton-style =
    .label = Стиль Lepton
proton-style =
    .label = Стиль Proton
waterfox-defaults =
    .label = Стандартно у Waterfox
auto-blur-tabs =
    .label = Автоматично розмивати вкладки
auto-hide-back =
    .label = Автоматично приховувати кнопку «Назад»
auto-hide-bookmarkbar =
    .label = Автоматично приховувати рядок закладок
auto-hide-forward =
    .label = Автоматично приховувати кнопку «Вперед»
auto-hide-navbar =
    .label = Автоматично приховувати панель навігації
auto-hide-pageaction =
    .label = Автоматично приховувати дії сторінки
auto-hide-sidebar =
    .label = Автоматично приховувати бічну панель
auto-hide-tabbar =
    .label = Автоматично приховувати панель вкладок
auto-hide-tabs =
    .label = Автоматично приховувати вкладки
center-navbar-text =
    .label = Вирівняти по центру текст панелі навігації
center-tab-content =
    .label = Вирівняти по центру зміст вкладки
center-tab-label =
    .label = Вирівняти по центру тільки назву
close-button-hover =
    .label = Показувати кнопку «Закрити» при наведенні на обрану вкладку, коли вкладок багато
compact-bookmark-menu =
    .label = Зменшити відступи в меню закладок
compact-context-menu =
    .label = Зменшити відступи в контекстному меню
compact-navbar-popup =
    .label = Зменшити відступи в панелі навігації
compact-panel-header =
    .label = Зменшити відступи в заголовках панелей
disable-panel-animate =
    .label = Вимкнути анімацію панелі меню застосунку
disable-sidebar-animate =
    .label = Вимкнути анімацію бічної панелі
drag-space =
    .label = Увімкнути фіксовану зону перетягування
enable-cyan-accent-color =
    .label = Блакитний колір акценту
enable-default-accent-color =
    .label = Колір акценту за замовчуванням
enable-menu-transparency =
    .label = Увімкнути прозорість меню
enable-panel-transparency =
    .label = Увімкнути прозорість панелей
enable-system-accent-color =
    .label = Системний колір акценту
enable-waterfox-theme-0 =
    .label = Увімкнути налаштування тем Waterfox для усіх тем
enable-waterfox-theme-1 =
    .label = Увімкнути налаштування тем Waterfox для тем Waterfox
enable-waterfox-theme-2 =
    .label = Вимкнути налаштування тем Waterfox
full-panel-strip =
    .label = Роздільник меню застосунку на повну ширину
remove-panel-strip =
    .label = Прибрати кольоровий роздільник меню застосунку
hide-all-icons =
    .label = Приховати усі іконки
hide-bookmarkbar-icon =
    .label = Приховати іконки в рядку закладок
hide-bookmarkbar-label =
    .label = Приховати імена в рядку закладок
hide-disabled-menuitems =
    .label = Приховати неактивні пункти меню
hide-sidebar-header =
    .label = Приховати заголовок бічної панелі
hide-tab-icons =
    .label = Приховати іконки вкладок
hide-urlbar-iconbox =
    .label = Приховати область іконок адресного рядка
monospace-font =
    .label = Ввімкнути моноширинний шрифт для сторінки
monospace-font-theme =
    .label = Ввімкнути моноширинний шрифт для теми
show-mac-menu-icons =
    .label = Показати іконки меню Mac
show-menu-icons =
    .label = Показати іконки меню
square-button-edges =
    .label = Квадратні кути кнопок
square-checkbox =
    .label = Прапорець із квадратними кутами
square-field =
    .label = Квадратні кути полів для введення
square-menu-item =
    .label = Квадратні кути елементів контекстного меню
square-menu-panel =
    .label = Квадратні кути панелі меню застосунку
square-menu-popup =
    .label = Квадратні кути панелі контекстного меню
square-panel-item =
    .label = Квадратні кути елементів меню застосунку
square-tab-edges =
    .label = Квадратні кути вкладок
tab-context-line =
    .label = Контекстна лінія вкладок
telemetry-page-subtitle = Waterfox не збирає телеметрію про вашу інсталяцію — будь-які модулі телеметрії відключені ще на етапі складання браузера. Те, що ви робите у вашому браузері, відомо лише вам.
telemetry-privacy-policy = Політика конфіденційності
onboarding-grassroots-title = Підтримка громадських ініціатив
onboarding-grassroots-subtitle = Щиро дякуємо за використання Waterfox, незалежного браузера, який розвивається завдяки зусиллям громади. Ваша підтримка допомагає нам створювати стабільну альтернативу великим гравцям на ринку.
tabbrowser-confirm-session-restore-checkbox = Відкрити попередні вікна та вкладки
pane-tree-title = Деревоподібні вертикальні вкладки
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Деревоподібні вертикальні вкладки
sidebar-tree-vertical-tabs =
    .label = Деревоподібні вертикальні вкладки
tree-header = Деревоподібні вертикальні вкладки
tree-appearance-header = Зовнішній вигляд
tree-auto-sticky-header = Закріплення вкладок на краях панелі, коли вони прокручені за її межі
tree-faviconize-pinned-tabs =
    .label = Показувати закріплені вкладки лише іконками
    .accesskey = П
tree-sticky-active-tab =
    .label = Активна вкладка
    .accesskey = к
tree-sticky-sharing-tab =
    .label = Вкладки, що використовують камеру/мікрофон/екран
    .accesskey = т
tree-sticky-sound-playing-tab =
    .label = Вкладки, що відтворюють звук
    .accesskey = и
tree-behavior-header = Деревоподібний перегляд вкладок
tree-auto-collapse-expand-subtree-on-attach =
    .label = Коли з'являється нове дерево, згортати інші автоматично
    .accesskey = з
tree-auto-collapse-expand-subtree-on-select =
    .label = Коли вкладка отримує фокус, розгорнути її дерево та згорнути інші автоматично
    .accesskey = а
tree-drop-links-on-tab-behavior-caption =
    .value = Коли посилання чи стрічка URL перенесена на вкладку
    .accesskey = о
tree-drop-links-on-tab-behavior-ask =
    .label = Завжди питати
tree-drop-links-on-tab-behavior-load =
    .label = Завантажити вкладку
tree-drop-links-on-tab-behavior-newtab =
    .label = Відкрити дочірню вкладку
tree-successor-tab-control-level-caption =
    .value = Коли поточна вкладка закривається як остання дочірня
    .accesskey = л
tree-successor-tab-control-level-in-tree =
    .label = Перемістити фокус на попередню вкладку в дереві
tree-successor-tab-control-level-never =
    .label = Завжди переміщувати фокус на наступну вкладку (враховувати налаштування браузер або іншго розширення)
tree-successor-tab-control-level-simulate-default =
    .label = Завжди переміщувати фокус на наступну вкладку
tree-tree-double-click-behavior-caption =
    .value = Подвійне клацання на вкладці
    .accesskey = д
tree-tree-double-click-behavior-toggle-close =
    .label = Закриє вкладку
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Згорне/розгорне дерево
tree-tree-double-click-behavior-toggle-none =
    .label = Нічого не робитиме
tree-tree-double-click-behavior-toggle-sticky =
    .label = Прикріпить до меж панелі вкладок / Відкріпить від меж панелі вкладок
tree-auto-attach-header = Автоматичне впорядкування дерева вкладок
tree-auto-attach-child-end =
    .label = Останню дочірню вкладку батьківської вкладки
tree-auto-attach-child-next-to-last-related-tab =
    .label = Дочірню вкладку батьківської, поруч із нещодавно відкритою дочірньою
tree-auto-attach-child-top =
    .label = Першу дочірню вкладку батьківської вкладки
tree-auto-attach-independent =
    .label = Незалежну вкладку
tree-auto-attach-next-sibling =
    .label = Наступну сусідню вкладку батьківської вкладки
tree-auto-attach-no-control =
    .label = (не контролювати)
tree-auto-attach-sibling =
    .label = Сусідню вкладку батьківської вкладки
tree-auto-attach-on-any-other-trigger-caption =
    .value = Вкладки з будь-якого іншого джерела: Відкривати як
    .accesskey = б
tree-auto-attach-on-duplicated-caption =
    .value = Дублювати вкладку як
    .accesskey = у
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Для середнього клацання відкривати нову порожню вкладку як
    .accesskey = с
tree-auto-attach-on-new-tab-command-caption =
    .value = Відкривати нову порожню вкладку як
    .accesskey = н
tree-auto-attach-on-opened-from-external-caption =
    .value = Нова вкладка з інших програм: Відкривати як
    .accesskey = і
tree-auto-attach-on-opened-with-owner-caption =
    .value = Коли вкладка відкрита з наявної, відкривати як
    .accesskey = в
tree-auto-attach-same-site-orphan-caption =
    .value = Нова вкладка з тим самим сайтом, що й поточна, відкривана з адресного рядка, закладок, історії або інших джерел: Відкривати як
    .accesskey = щ
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Позиція вставлення нових дочірніх вкладок із закріплених вкладок (будуть відображатися як кореневі)
    .accesskey = р
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Кінець дерева
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Поруч із нещодавно відкритою дочірньою або поруч із вкладкою, що відкрила
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Не контролювати (з урахуванням рішень браузера та інших розширень вкладок)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = Верхівка дерева (поруч із вкладкою, що відкрила)
waterfox-blocker-header = Блокування реклами
waterfox-blocker-intro-description = Блокує рекламу, скрипти відстеження та інші небажані запити для швидшого завантаження сторінок та меншої кількості відволікаючих факторів.
waterfox-blocker-setting-on =
    .label = Увімкнено
waterfox-blocker-setting-on-summary = Блокує рекламу та трекери з мінімальним впливом на завантаження сторінки.
waterfox-blocker-setting-on-description = Waterfox блокує наступне:
waterfox-blocker-blocks-ads = Запити реклами та рекламної мережі
waterfox-blocker-blocks-tracking = Скрипти та пікселі відстеження
waterfox-blocker-blocks-annoyances = Спливаючі вікна та накладання, що викликають незручності (зі списками незручностей, що ввімкнені)
waterfox-blocker-partner-funding-title = Підтримайте розвиток Waterfox
waterfox-blocker-partner-funding-description = Waterfox — безкоштовний, з відкритим кодом та незалежний. Waterfox фінансує розробку та інфраструктуру, дозволяючи показ оголошень на сторінках пошукових партнерів. Ви можете вимкнути цю функцію будь-коли, але найпростіший спосіб підтримати проєкт — залишити її ввімкненою.
waterfox-blocker-setting-off =
    .label = Вимкнено
waterfox-blocker-setting-off-description = Waterfox не блокує жодну рекламу чи трекери. Розширення сторонніх розробників все ще можуть блокувати контент незалежно.
waterfox-blocker-dropdown-label =
    .value = Оголошення пошукових партнерів:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Дозволити на пошукових партнерах Waterfox
waterfox-blocker-dropdown-option-block-everything =
    .label = Заборонити на сайтах пошукових партнерів Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Керувати списками фільтрів…
waterfox-blocker-custom-filter-lists =
    .label = Списки користувацьких фільтрів…
waterfox-blocker-filter-lists-window =
    .title = Списки фільтрів блокування реклами
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Зберегти зміни
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = Виберіть, які списки фільтрів активні.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } активних з { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Увімкнено
waterfox-blocker-filter-lists-column-name =
    .label = Список фільтрів
waterfox-blocker-filter-lists-column-category =
    .label = Категорія
waterfox-blocker-filter-lists-enable =
    .label = Увімкнено
waterfox-blocker-filter-lists-disable =
    .label = Вимкнути
waterfox-blocker-extension-detected = Waterfox тепер має вбудоване блокування реклами. Ви можете переглянути свої параметри в налаштуваннях.
waterfox-blocker-extension-detected-learn-more =
    .label = Дізнатися більше
waterfox-blocker-extension-detected-dismiss =
    .label = Більше не показувати
waterfox-blocker-extension-install-warning = Waterfox вже має вбудований блокувальник реклами. Запуск двох блокувальників реклами може призвести до перебоїв у роботі сторінок або їх повільного завантаження.
waterfox-blocker-extension-install-got-it =
    .label = Зрозуміло
waterfox-blocker-extension-install-learn-more =
    .label = Дізнатися більше
waterfox-blocker-third-party-notice-description = { $extensionName } також блокує рекламу. Запуск двох блокувальників реклами може спричинити проблеми.
waterfox-blocker-exceptions-window =
    .title = Винятки з блокування реклами
waterfox-blocker-exceptions-description = Ви можете вказати, на яких вебсайтах вимкнено блокування реклами. Введіть точну адресу сайту, яким ви хочете керувати, а потім натисніть «Додати».
waterfox-blocker-toolbar-button =
    .label = Блокування реклами
    .tooltiptext = Блокування реклами
waterfox-blocker-panel-not-available = Недоступно на цій сторінці
waterfox-blocker-panel-toggle =
    .label = Блокування реклами на цьому сайті
    .description = Блокуйте рекламу та трекери на цьому сайті.
waterfox-blocker-panel-disabled = Блокування реклами вимкнено
waterfox-blocker-panel-site-excepted = Реклама дозволена на цьому сайті
waterfox-blocker-panel-partner-allowed = Реклама дозволена для пошукових партнерів
waterfox-blocker-stats =
    { $count ->
        [one] { $count } реклама заблокована на цьому сайті
       *[other] { $count } реклам заблоковано на цьому сайті
    }
waterfox-blocker-panel-settings-button = Налаштування блокування реклами
waterfox-blocker-show-badge-pref =
    .label = Показувати кількість заблокованих елементів на кнопці панелі інструментів
waterfox-blocker-filter-lists-category-core = За замовчуванням
waterfox-blocker-filter-lists-category-privacy = Приватність
waterfox-blocker-filter-lists-category-annoyances = Дратівливості
waterfox-blocker-filter-lists-category-optional = Необов'язкове
waterfox-blocker-filter-lists-category-regional = Регіональне
waterfox-blocker-filter-lists-search =
    .placeholder = Списки фільтрів пошуку…
waterfox-blocker-filter-lists-empty-state = Немає доступних списків фільтрів.
waterfox-blocker-filter-lists-refresh-rate-label =
    .value = Перевірити наявність оновлень:
waterfox-blocker-filter-lists-refresh-rate-default =
    .label = Використовувати список за замовчуванням
waterfox-blocker-filter-lists-refresh-rate-4h =
    .label = Кожні 4 години
waterfox-blocker-filter-lists-refresh-rate-8h =
    .label = Кожні 8 годин
waterfox-blocker-filter-lists-refresh-rate-12h =
    .label = Кожні 12 годин
waterfox-blocker-filter-lists-refresh-rate-24h =
    .label = Кожні 24 години
waterfox-blocker-filter-lists-refresh-rate-7d =
    .label = Кожні 7 днів
waterfox-blocker-filter-lists-refresh-now =
    .label = Оновити зараз
waterfox-blocker-filter-lists-last-updated = Оновлено { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Ще не оновлено
waterfox-blocker-custom-filter-lists-window =
    .title = Списки користувацьких фільтрів
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Зберегти зміни
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = Додайте URL-адреси списків користувацьких фільтрів. Списки будуть отримані та застосовані разом із вбудованими фільтрами.
waterfox-blocker-filter-lists-custom-heading =
    .value = Списки користувацьких фільтрів
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Введіть URL-адресу списку фільтрів…
waterfox-blocker-filter-lists-custom-url-label =
    .value = URL-адреса списку фільтрів
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Додати
waterfox-blocker-filter-lists-custom-remove =
    .label = Видалити
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Видалити всі
waterfox-blocker-filter-lists-custom-empty =
    .value = Не додано жодних користувацьких списків фільтрів.
waterfox-blocker-custom-filters =
    .label = Мої фільтри…
waterfox-blocker-custom-filters-window =
    .title = Мої фільтри
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Зберегти зміни
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = Додайте власні правила блокування реклами. Вони використовують стандартний синтаксис фільтра uBlock Origin і застосовуються разом зі списками ввімкнених фільтрів.
waterfox-blocker-custom-filters-empty =
    .value = Без користувацьких фільтрів.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Без користувацьких фільтрів.
        [one] 1 користувацький фільтр.
       *[other] { $count } користувацьких фільтрів.
    }
waterfox-blocker-custom-filters-status-unsaved = Незбережені зміни.
waterfox-blocker-custom-filters-import =
    .label = Імпорт…
waterfox-blocker-custom-filters-export =
    .label = Експорт…
waterfox-blocker-custom-filters-load-error-title = Не вдалося завантажити
waterfox-blocker-custom-filters-load-error = Не вдалося завантажити користувацькі фільтри.
waterfox-blocker-custom-filters-save-error-title = Збереження не вдалося
waterfox-blocker-custom-filters-save-error = Не вдалося зберегти користувацькі фільтри.
waterfox-blocker-custom-filters-import-error-title = Імпорт не вдалося
waterfox-blocker-custom-filters-import-error = Вибраний файл не вдалося імпортувати.
waterfox-blocker-custom-filters-export-error-title = Експорт не вдалося
waterfox-blocker-custom-filters-export-error = Не вдалося експортувати користувацькі фільтри.
waterfox-blocker-custom-filters-import-picker-title = Імпорт користувацьких фільтрів
waterfox-blocker-custom-filters-export-picker-title = Експорт користувацьких фільтрів
waterfox-blocker-custom-filters-import-replace-title = Замінити поточні фільтри?
waterfox-blocker-custom-filters-import-replace-message = Імпорт замінить усе, що зараз знаходиться в редакторі.
waterfox-blocker-extension-fallback-name-this = це розширення
waterfox-blocker-extension-fallback-name-your = ваше розширення
waterfox-blocker-spotlight-title = Waterfox тепер включає блокування реклами
waterfox-blocker-spotlight-subtitle = Ми помітили, що у вас встановлено { $extensionName }. Waterfox тепер має власний блокувальник реклами. Його використання допомагає підтримувати Waterfox, але вирішувати вам.
waterfox-blocker-spotlight-primary-button = Зберегти поточні налаштування
waterfox-blocker-spotlight-secondary-button = Переглянути налаштування
waterfox-blocker-prompt-title = Блокування реклами Waterfox
waterfox-blocker-reenable-conflict-message = Використання блокувальника реклами Waterfox та розширення «{ $extensionName }» може призвести до збоїв у роботі сторінок. Яке з них ви хочете залишити?
waterfox-blocker-reenable-use-built-in = Використовувати вбудований блокувальник
waterfox-blocker-reenable-keep-extension = Залишити розширення блокування
waterfox-blocker-extension-install-manage-settings = Ви можете керувати блокуванням реклами в розділі «Налаштування» > «Приватність і безпека».
waterfox-blocker-extension-install-anyway = Встановити все одно
waterfox-blocker-extension-install-keep-built-in = Продовжувати використовувати вбудований блокувальник
waterfox-blocked-page-title = Waterfox заблокував цю сторінку
waterfox-blocked-page-heading = Waterfox заблокував цю сторінку
waterfox-blocked-page-description = Цю сторінку було заблоковано правилом фільтра блокування реклами.
waterfox-blocked-page-details =
    .aria-label = Деталі заблокованої сторінки
waterfox-blocked-page-blocked-url-label = Заблокована URL-адреса
waterfox-blocked-page-matched-rule-label = Зіставлене правило
waterfox-blocked-page-unavailable = Недоступно
waterfox-blocked-page-hint = «Завантажити все одно» тимчасово дозволить цей сайт до кінця сеансу.
waterfox-blocked-page-go-back = Повернутися назад
waterfox-blocked-page-load-anyway = Завантажити все одно
