restart-prompt-title = Restartovat { -brand-short-name }
restart-prompt-question = Jste si jisti, že chcete restartovat { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Restartovat
copy-url =
    .label = Kopírovat odkaz na záložku
copy-all-urls =
    .label = Kopírovat všechny odkazy záložek
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Otevřít vše v soukromých panelech
open-all-links-private =
    .label = Otevřít všechny odkazy v soukromých panelech
open-private-tab =
    .label = Otevřít v nové soukromé kartě
new-private-tab =
    .label = Nová soukromá karta
    .tooltiptext = Otevřít novou soukromou kartu
open-link-private =
    .label = Otevřít odkaz v nové soukromé kartě
status-bar =
    .label = Stavová lišta
tab-position-header = Pozice panelu záložek
tab-bar-top-above =
    .label = Horní výše uvedený adresní řádek
tab-bar-top-below =
    .label = Horní pod adresním řádkem
tab-bar-bottom-above =
    .label = Dolní část nad stavovou lištou
tab-bar-bottom-below =
    .label = Dolů pod stavovou lištou
tab-additional-header = Nastavení další záložky
pinned-icon-only =
    .label = Zmenšit připnuté panely pro zobrazení pouze ikony webu
insert-after-current =
    .label = Vložit novou kartu za aktuální kartu
insert-related-after-current =
    .label = Vložit související novou kartu za aktuální panel
dynamic-theme-header = Dynamické motivy
dynamic-theme-dark =
    .label = Vynutit tmavý režim
dynamic-theme-light =
    .label = Vynutit světelný režim
dynamic-theme-auto =
    .label = Dynamicky nastavit světlo/tmavý režim
restart-header = Restartovat položku nabídky
restart-show-button =
    .label = Zobrazit tlačítko restartu v panelu
restart-purge-cache =
    .label = Vymazat mezipaměť rychlého restartování při restartu prohlížeče
restart-require-confirmation =
    .label = Vyžadovat potvrzení restartu
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Zobrazit položku menu pro kopírování záložky
enable-copy-active-tab =
    .label = Kopírovat URL pouze z aktivního panelu
show-copy-all-urls =
    .label = Zobrazit kopii všech URL položek nabídky
show-unload-tab =
    .label = Zobrazit položku nabídky nabídky při vykládce
statusbar-enabled =
    .label = Zobrazit stavovou lištu
statusbar-show-links =
    .label = Zobrazit odkazy
statusbar-contrast-text =
    .label = Barva textu ve stavovém řádku kontrastu
bookmarks-bar-position-header = Pozice panelu záložek
bookmarks-position-top =
    .label = Nahoře
bookmarks-position-bottom =
    .label = Spodní
geolocation-api-header = Geolocation API
geolocation-description = Některé webové stránky vyžadují funkci vaší polohy. Pokud webová stránka nefunguje kvůli tomu, že není schopna najít vaši polohu, povolte prosím toto nastavení a zkuste to znovu.
geolocation-api-enabled =
    .label = Povolit
geolocation-api-disabled =
    .label = Zakázat
send-referrer-header-0 =
    .label = Nikdy neposílat odkazující hlavičku
send-referrer-header-1 =
    .label = Odeslat záhlaví odkazujícího pouze při kliknutí na odkazy a podobné prvky
send-referrer-header-2 =
    .label = Odeslat hlavičku referrer na všechny požadavky (výchozí)
enable-webrtc-p2p =
    .label = Povolit připojení WebRTC klientů
load-images =
    .label = Automaticky načíst obrázky
enable-javascript =
    .label = Povolit JavaScript
webrtc-header = WebRTC připojení klienta
ref-header = HTTP reference hlavička
statusbar-header = Stavová lišta
private-tab =
    .label =
        { $isPrivate ->
            [true] Ukončit soukromou kartu
           *[false] Vytvořit soukromou kartu
        }
waterfox-defaults =
    .label = Waterfox Defaults
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
enable-menu-transparency =
    .label = Enable menu transparency
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
enable-panel-transparency =
    .label = Enable panel transparency
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
disable-panel-animate =
    .label = Disable app menu panel animation
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
center-tab-label =
    .label = Center Tab Label Only
square-tab-edges =
    .label = Square Tab Corners
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
square-button-edges =
    .label = Square Button Corners
square-panel-item =
    .label = Square App Menu Item Corners
drag-space =
    .label = Enable Fixed Drag Space
square-menu-item =
    .label = Square Context Menu Item Corners
compact-context-menu =
    .label = Reduce Context Menu Padding
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
monospace-font =
    .label = Enable monospaced font for page
tab-bar-header = Tab Bar
nav-bar-header = Nav Bar
bookmark-header = Bookmarks Bar
font-header = Fonts
media-player-header = Media Player
sidebar-header = Sidebar
icons-header = Icons
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
onboarding-grassroots-title = Supporting the grassroots
telemetry-privacy-policy = Privacy Policy
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
show-mac-menu-icons =
    .label = Show Mac Menu Icons
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
disable-sidebar-animate =
    .label = Disable sidebar panel animation
panels-header = Panels
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
monospace-font-theme =
    .label = Enable monospaced font for theme
enable-dooh =
    .label = Use DNS over Oblivious HTTP
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
pane-theme-title = Look & Feel
preset-title = Presets
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
tab-context-line =
    .label = Tab Context Line
square-menu-panel =
    .label = Square App Menu Panel Corners
