restart-prompt-title = Restartovat { -brand-short-name }
restart-prompt-question = Jste si jisti, že chcete restartovat { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Restartovat
copy-url =
    .label = Kopírovat odkaz karty
copy-all-urls =
    .label = Kopírovat všechny odkazy karet
unload-tab =
    .label = Uvolnit kartu
open-all-private =
    .label = Otevřít vše v soukromých kartách
open-all-links-private =
    .label = Otevřít všechny odkazy v soukromých kartách
open-private-tab =
    .label = Otevřít v nové soukromé kartě
new-private-tab =
    .label = Nová soukromá karta
    .tooltiptext = Otevřít novou soukromou kartu
open-link-private =
    .label = Otevřít odkaz v nové soukromé kartě
status-bar =
    .label = Stavová lišta
tab-position-header = Pozice panelu karet
tab-bar-top-above =
    .label = Nahoře nad adresním řádkem
tab-bar-top-below =
    .label = Nahoře pod adresním řádkem
tab-bar-bottom-above =
    .label = Dole nad stavovou lištou
tab-bar-bottom-below =
    .label = Dole pod stavovou lištou
tab-additional-header = Další předvolby karet
pinned-icon-only =
    .label = Zmenšit připnuté karty, aby se zobrazovala pouze ikona webu
insert-after-current =
    .label = Vložit novou kartu za aktuální kartu
insert-related-after-current =
    .label = Vložit související novou kartu za aktuální kartu
dynamic-theme-header = Dynamické motivy
dynamic-theme-dark =
    .label = Vynutit tmavý režim
dynamic-theme-light =
    .label = Vynutit světlý režim
dynamic-theme-auto =
    .label = Dynamicky nastavit světlý/tmavý režim
restart-header = Restartovat položku nabídky
restart-show-button =
    .label = Zobrazit tlačítko restartovat v PanelUI
restart-purge-cache =
    .label = Vymazat mezipaměť rychlého restartu při restartování prohlížeče
restart-require-confirmation =
    .label = Vyžadovat potvrzení restartu
tab-feature-header = Kontextová nabídka karty
show-duplicate-tab =
    .label = Zobrazit položku nabídky "duplikovat kartu"
show-copy-url =
    .label = Zobrazit položku nabídky "kopírovat URL karty"
enable-copy-active-tab =
    .label = Kopírovat pouze URL z aktivní karty
show-copy-all-urls =
    .label = Zobrazit položku nabídky "kopírovat URL všech karet"
show-unload-tab =
    .label = Zobrazit položku nabídky "Uvolnit kartu"
statusbar-enabled =
    .label = Zobrazit stavovou lištu
statusbar-show-links =
    .label = Zobrazit odkazy
statusbar-contrast-text =
    .label = Barva textu ve stavovém řádku kontrastu
bookmarks-bar-position-header = Pozice panelu záložek
bookmarks-position-top =
    .label = Nahoře
bookmarks-position-bottom =
    .label = Dole
geolocation-api-header = API geolokace
geolocation-description = Některé weby vyžadují vaši polohu, aby fungovaly. Pokud web nefunguje, protože nemůže najít vaši polohu, povolte prosím tuto preferenci a zkuste to znovu.
geolocation-api-enabled =
    .label = Povolit
geolocation-api-disabled =
    .label = Zakázat
send-referrer-header-0 =
    .label = Nikdy neposílat hlavičku Referrer
send-referrer-header-1 =
    .label = Zahrnout hlavičku referrer pouze při kliknutí na odkazy a podobné prvky
send-referrer-header-2 =
    .label = Zahrnout hlavičku referrer na všechny požadavky (výchozí)
enable-webrtc-p2p =
    .label = Povolit připojení WebRTC klientů
load-images =
    .label = Automaticky načíst obrázky
enable-javascript =
    .label = Povolit JavaScript
webrtc-header = WebRTC připojení klienta
ref-header = Hlavička HTTP referrer
statusbar-header = Stavová lišta
private-tab =
    .label =
        { $isPrivate ->
            [true] Ukončit soukromou kartu
           *[false] Vytvořit soukromou kartu
        }
preferences-doh-ultra-detailed-desc-3 = Maximální DNS ochrana soukromí - nikdo nemůže vidět, které stránky navštěvujete
pane-theme-title = Vzhled a chování
animation-header = Animace
bookmark-header = Panel záložek
center-header = Na střed
font-header = Písma
full-screen-header = Celá obrazovka
icons-header = Ikony
update-application-manual =
    .label = Nikdy nekontrolovat aktualizace (není doporučeno)
    .accesskey = N
waterfox-data-collection-header = { -brand-short-name } Sběr a používání dat
    .searchkeywords = ochrana osobních údajů telemetrie sběr dat upozornění na ochranu osobních údajů
waterfox-data-collection-description = { -brand-short-name } neshromažďuje telemetrii ani data o používání. Volitelné služby, jako je Sync, mohou být řízeny vlastními oznámeními o ochraně soukromí. <a data-l10n-name="privacy-notice">Oznámení o ochraně soukromí</a> je zde poskytnuto pro snadnou orientaci.
preferences-doh-setting-ultra =
    .label = Ultra Ochrana
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } bude používat bezpečný DNS s Oblivious HTTP přes Waterfox relay na ochranu soukromí pro maximální ochranu.
preferences-doh-ultra-detailed-desc-1 = Používá Waterfox relay Oblivious HTTP ke skrytí DNS dotazů i před poskytovatelem DNS
preferences-doh-ultra-detailed-desc-2 = Poskytuje další vrstvu šifrování nad rámec standardního DNS over HTTPS
preferences-doh-ultra-fallback-mode = Záložní chování:
preferences-doh-ultra-fallback-allowed = Povolit vrácení se na systémový DNS, pokud selže bezpečný DNS
preferences-doh-ultra-fallback-disabled = Nikdy se nevracet na systémový DNS (stránky se nemusí načíst, pokud selže bezpečný DNS)
category-theme =
    .tooltiptext = { pane-theme-title }
appearance-header = Vzhled
autohide-hidden-header = Automatické skrytí a skryté
interface-component-header = Komponenty rozhraní
media-player-header = Přehrávač médií
nav-bar-header = Navigační panel
panels-header = Panely
rounding-header = Zaoblení
sidebar-header = Postranní panel
tab-bar-header = Lišta karet
theme-header = Motiv
preset-title = Předvolby
lepton-style =
    .label = Lepton styl
proton-style =
    .label = Proton styl
waterfox-defaults =
    .label = Waterfox výchozí
auto-blur-tabs =
    .label = Automatické rozostření karet
auto-hide-back =
    .label = Automaticky skrýt tlačítko zpět
auto-hide-bookmarkbar =
    .label = Automaticky skrýt panel záložek
auto-hide-forward =
    .label = Automaticky skrýt tlačítko vpřed
