restart-prompt-title = Starta om { -brand-short-name }
restart-prompt-question = Är du säker på att du vill starta om { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Starta om
copy-url =
    .label = Kopiera fliklänk
copy-all-urls =
    .label = Kopiera alla fliklänkar
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Öppna alla i privata flikar
open-all-links-private =
    .label = Öppna alla länkar i privata flikar
open-private-tab =
    .label = Öppna i en ny privat flik
new-private-tab =
    .label = Ny privat flik
    .tooltiptext = Öppna en ny privat flik
open-link-private =
    .label = Öppna länk i ny privat flik
status-bar =
    .label = Statusfält
tab-position-header = Placering i flikfältet
tab-bar-top-above =
    .label = Överst ovanför adressfältet
tab-bar-top-below =
    .label = Topp under adressfältet
tab-bar-bottom-above =
    .label = Nedre ovanför statusfältet
tab-bar-bottom-below =
    .label = Nedre statusfältet under
tab-additional-header = Ytterligare flikinställningar
pinned-icon-only =
    .label = Krymp fästa flikar för att visa endast ikonen webbplats
insert-after-current =
    .label = Infoga ny flik efter aktuell flik
insert-related-after-current =
    .label = Infoga relaterad ny flik efter aktuell flik
dynamic-theme-header = Dynamiska teman
dynamic-theme-dark =
    .label = Tvinga mörkt läge
dynamic-theme-light =
    .label = Tvinga ljusläge
dynamic-theme-auto =
    .label = Ställ in ljus/mörkt läge dynamiskt
restart-header = Starta om menyobjekt
restart-show-button =
    .label = Visa omstartsknapp i panelgränssnittet
restart-purge-cache =
    .label = Rensa snabbstart-cache vid omstart av webbläsaren
restart-require-confirmation =
    .label = Kräv omstart bekräftelse
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Visa menyobjekt för kopieringsflik
enable-copy-active-tab =
    .label = Kopiera endast URL från aktiv flik
show-copy-all-urls =
    .label = Visa kopiera alla flikar menyobjekt
show-unload-tab =
    .label = Visa flikmenyobjekt
statusbar-enabled =
    .label = Visa statusfältet
statusbar-show-links =
    .label = Visa länkar
statusbar-contrast-text =
    .label = Textfärg för textfältet i kontrast
bookmarks-bar-position-header = Bokmärken verktygsfält Position
bookmarks-position-top =
    .label = Överst
bookmarks-position-bottom =
    .label = Botten
geolocation-api-header = Geolocation API
geolocation-description = Vissa webbplatser kräver din plats för att fungera. Om en webbplats inte fungerar på grund av att du inte kan hitta din plats, vänligen aktivera denna inställning och försök igen.
geolocation-api-enabled =
    .label = Aktivera
geolocation-api-disabled =
    .label = Inaktivera
send-referrer-header-0 =
    .label = Skicka aldrig hänvisarhuvudet
send-referrer-header-1 =
    .label = Skicka referenshuvudet endast när du klickar på länkar och liknande element
send-referrer-header-2 =
    .label = Skicka referenshuvudet på alla förfrågningar (standard)
enable-webrtc-p2p =
    .label = Aktivera WebRTC peer-anslutning
load-images =
    .label = Ladda bilder automatiskt
enable-javascript =
    .label = Aktivera JavaScript
webrtc-header = Peer-anslutning för WebRTC
ref-header = HTTP Hänvisarhuvud
statusbar-header = Statusfält
private-tab =
    .label =
        { $isPrivate ->
            [true] Avsluta privat flik
           *[false] Skapa privat flik
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
pane-theme-title = Look & Feel
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
hide-tab-icons =
    .label = Hide Tab Icons
show-mac-menu-icons =
    .label = Show Mac Menu Icons
panels-header = Panels
full-screen-header = Full screen
sidebar-header = Sidebar
icons-header = Icons
onboarding-grassroots-title = Supporting the grassroots
media-player-header = Media Player
telemetry-privacy-policy = Privacy Policy
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
square-button-edges =
    .label = Square Button Corners
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
drag-space =
    .label = Enable Fixed Drag Space
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
auto-hide-forward =
    .label = Auto Hide Forward Button
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
