restart-prompt-title = Starta om { -brand-short-name }
restart-prompt-question = Är du säker på att du vill starta om { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Starta om
copy-url =
    .label = Kopiera fliklänk
copy-all-urls =
    .label = Kopiera alla fliklänkar
unload-tab =
    .label = Frigör flik
open-all-private =
    .label = Öppna alla i privata flikar
open-all-links-private =
    .label = Öppna alla länkar i privata flikar
open-private-tab =
    .label = Öppna i en ny privat flik
new-private-tab =
    .label = Ny privat flik
    .tooltiptext = Öppna en ny privat flik
open-link-private =
    .label = Öppna länk i ny privat flik
status-bar =
    .label = Statusfält
tab-position-header = Placering i flikfältet
tab-bar-top-above =
    .label = Överst ovanför adressfältet
tab-bar-top-below =
    .label = Topp under adressfältet
tab-bar-bottom-above =
    .label = Nedre ovanför statusfältet
tab-bar-bottom-below =
    .label = Nedre statusfältet under
tab-additional-header = Ytterligare flikinställningar
pinned-icon-only =
    .label = Krymp fästa flikar för att visa endast ikonen webbplats
insert-after-current =
    .label = Infoga ny flik efter aktuell flik
insert-related-after-current =
    .label = Infoga relaterad ny flik efter aktuell flik
dynamic-theme-header = Dynamiska teman
dynamic-theme-dark =
    .label = Tvinga mörkt läge
dynamic-theme-light =
    .label = Tvinga ljusläge
dynamic-theme-auto =
    .label = Ställ in ljus/mörkt läge dynamiskt
restart-header = Starta om menyobjekt
restart-show-button =
    .label = Visa omstartsknapp i panelgränssnittet
restart-purge-cache =
    .label = Rensa snabbstart-cache vid omstart av webbläsaren
restart-require-confirmation =
    .label = Kräv omstart bekräftelse
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Visa duplicerade flikmeny objekt
show-copy-url =
    .label = Visa menyobjekt för kopieringsflik
enable-copy-active-tab =
    .label = Kopiera endast URL från aktiv flik
show-copy-all-urls =
    .label = Visa kopiera alla flikar menyobjekt
show-unload-tab =
    .label = Visa flikmenyobjekt
statusbar-enabled =
    .label = Visa statusfältet
statusbar-show-links =
    .label = Visa länkar
statusbar-contrast-text =
    .label = Textfärg för textfältet i kontrast
bookmarks-bar-position-header = Bokmärken verktygsfält Position
bookmarks-position-top =
    .label = Överst
bookmarks-position-bottom =
    .label = Botten
geolocation-api-header = Geolokaliserings API
geolocation-description = Vissa webbplatser kräver din plats för att fungera. Om en webbplats inte fungerar på grund av att du inte kan hitta din plats, vänligen aktivera denna inställning och försök igen.
geolocation-api-enabled =
    .label = Aktivera
geolocation-api-disabled =
    .label = Inaktivera
send-referrer-header-0 =
    .label = Skicka aldrig hänvisarhuvudet
send-referrer-header-1 =
    .label = Inkludera referenshuvudet endast när du klickar på länkar och liknande element
send-referrer-header-2 =
    .label = Inkludera referenshuvudet på alla förfrågningar (standard)
enable-webrtc-p2p =
    .label = Aktivera WebRTC peer-anslutning
load-images =
    .label = Ladda bilder automatiskt
enable-javascript =
    .label = Aktivera JavaScript
webrtc-header = Peer-anslutning för WebRTC
ref-header = HTTP Hänvisarhuvud
statusbar-header = Statusfält
private-tab =
    .label =
        { $isPrivate ->
            [true] Avsluta privat flik
           *[false] Skapa privat flik
        }
update-application-manual =
    .label = Sök aldrig efter uppdateringar (rekommenderas inte)
    .accesskey = N
preferences-doh-setting-ultra =
    .label = Ultra skydd
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } kommer att säkra DNS med Oblivious HTTP via Waterfoxs integritetsrelä för maximalt skydd.
preferences-doh-ultra-detailed-desc-1 = Använder Waterfoxs Oblivious HTTP-relä för att dölja DNS-frågor även från DNS-leverantören
preferences-doh-ultra-detailed-desc-2 = Ger ett extra krypteringslager utöver standard-DNS via HTTPS
preferences-doh-ultra-detailed-desc-3 = Maximalt DNS-sekretessskydd – ingen kan se vilka webbplatser du besöker
preferences-doh-ultra-fallback-mode = Reservbeteende:
preferences-doh-ultra-fallback-allowed = Tillåt reservfunktion till system-DNS om säker DNS misslyckas
preferences-doh-ultra-fallback-disabled = Gå aldrig tillbaka till system-DNS (webbplatser kanske inte laddas om säker DNS misslyckas)
pane-theme-title = Utseende & känsla
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animationer
appearance-header = Utseende
autohide-hidden-header = Automatiskt dölj & dold
bookmark-header = Bokmärkesfält
center-header = Mitten
font-header = Teckensnitt
full-screen-header = Helskärm
icons-header = Ikoner
interface-component-header = Gränssnittskomponenter
media-player-header = Mediaspelare
nav-bar-header = Navigeringsfält
panels-header = Paneler
rounding-header = Rundning
sidebar-header = Sidofält
tab-bar-header = Flikfält
theme-header = Tema
preset-title = Förinställningar
lepton-style =
    .label = Lepton stil
proton-style =
    .label = Proton stil
waterfox-defaults =
    .label = Waterfox standardinställningar
auto-blur-tabs =
    .label = Automatiskt oskärpa flikar
auto-hide-back =
    .label = Automatiskt dölj bakåt knappen
auto-hide-bookmarkbar =
    .label = Automatiskt dölj bokmärkesfältet
auto-hide-forward =
    .label = Automatiskt dölj framåt knappen
auto-hide-navbar =
    .label = Automatiskt dölj navigeringsfältet
auto-hide-pageaction =
    .label = Automatiskt dölj sidoåtgärd
auto-hide-sidebar =
    .label = Automatiskt dölj sidofältet
auto-hide-tabbar =
    .label = Automatiskt dölj flikfältet
auto-hide-tabs =
    .label = Automatiskt dölj flikar
center-navbar-text =
    .label = Centrera navigationsfältets text
center-tab-content =
    .label = Centrera flik innehåll
center-tab-label =
    .label = Centrera flik etikett endast
close-button-hover =
    .label = Visa stängningsknappen för flik när du håller muspekaren över den markerade fliken när många flikar är öppna
compact-bookmark-menu =
    .label = Minska utfyllnaden i bokmärkesmenyn
compact-context-menu =
    .label = Minska utfyllnaden i kontextmenyn
compact-navbar-popup =
    .label = Minska utfyllnaden i navigeringsfältets popup-fönster
compact-panel-header =
    .label = Minska utfyllnaden i panelrubriken
disable-panel-animate =
    .label = Inaktivera appens menypanel animering
disable-sidebar-animate =
    .label = Inaktivera sidofältets panel animering
drag-space =
    .label = Aktivera fast draavstånd
enable-cyan-accent-color =
    .label = Cyan accentfärg
enable-default-accent-color =
    .label = Standard accentfärg
enable-menu-transparency =
    .label = Aktivera menytransparens
enable-panel-transparency =
    .label = Aktivera paneltransparens
enable-system-accent-color =
    .label = Systemets accentfärg
enable-waterfox-theme-0 =
    .label = Aktivera Waterfox-temanpassningar på alla teman
enable-waterfox-theme-1 =
    .label = Aktivera Waterfox-temanpassningar på Waterfox-teman
enable-waterfox-theme-2 =
    .label = Inaktivera anpassningar av Waterfox-teman
full-panel-strip =
    .label = Full bredd appmenyavgränsare
remove-panel-strip =
    .label = Ta bort färgad appmenyavgränsare
hide-all-icons =
    .label = Dölj alla ikoner
hide-bookmarkbar-icon =
    .label = Dölj bokmärkesfältets ikoner
hide-bookmarkbar-label =
    .label = Dölj bokmärkesfältets etiketter
hide-disabled-menuitems =
    .label = Dölj inaktiverade menyalternativ
hide-sidebar-header =
    .label = Dölj sidofältets rubrik
hide-tab-icons =
    .label = Dölj flikikoner
hide-urlbar-iconbox =
    .label = Dölj URL-fältets ikonruta
monospace-font =
    .label = Aktivera monospaced-teckensnitt för sida
monospace-font-theme =
    .label = Aktivera monospaced-teckensnitt för tema
show-mac-menu-icons =
    .label = Visa Mac menyikoner
show-menu-icons =
    .label = Visa menyikoner
square-button-edges =
    .label = Fyrkantiga knapphörn
square-checkbox =
    .label = Fyrkantig kryssruta
square-field =
    .label = Fyrkantiga ingångsfälthörn
square-menu-item =
    .label = Fyrkantig kontextmeny hörn
square-menu-panel =
    .label = Fyrkantiga appmenyn panelhörn
square-menu-popup =
    .label = Fyrkantiga kontextmenyn panelhörn
square-panel-item =
    .label = yrkantiga appmenyn objekthörn
square-tab-edges =
    .label = Fyrkantiga flik hörn
tab-context-line =
    .label = Flikens kontextrad
telemetry-page-subtitle = Waterfox samlar inte in telemetridata om din installation – alla telemetrimoduler inaktiveras när webbläsaren byggs. Vad du gör i din webbläsare är bara känt för dig.
telemetry-privacy-policy = Integritetspolicy
onboarding-grassroots-title = Stödjer gräsrötterna
onboarding-grassroots-subtitle = Tack för att du använder Waterfox, en oberoende gräsrotswebbläsare. Med ditt stöd bygger vi ett hållbart alternativ till de stora aktörerna där ute.
tabbrowser-confirm-session-restore-checkbox = Öppna föregående fönster och flikar
pane-tree-title = Träd vertikala flikar
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Träd vertikala flikar
sidebar-tree-vertical-tabs =
    .label = Träd vertikala flikar
tree-header = Träd vertikala flikar
tree-appearance-header = Utseende
tree-auto-sticky-header = Flikarna fastnar vid kanterna på flikfältet när de skrollas ut
tree-faviconize-pinned-tabs =
    .label = Visa fästa flikar endast med deras ikon
    .accesskey = S
tree-sticky-active-tab =
    .label = Aktiv flik
    .accesskey = k
tree-sticky-sharing-tab =
    .label = Flikar som delar kamera/mikrofon/skärm
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Ljuduppspelningsflikar
    .accesskey = y
tree-behavior-header = Trävy av flikar
tree-auto-collapse-expand-subtree-on-attach =
    .label = När ett nytt träd dyker upp, fälls andra ihop automatiskt
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = När en flik får fokus, expandera dess träd och fäll ihop andra automatiskt
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = När en länk eller URL-sträng släpps på en flik
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Fråga mig alltid hur jag ska behandla det
tree-drop-links-on-tab-behavior-load =
    .label = Ladda till fliken
tree-drop-links-on-tab-behavior-newtab =
    .label = Öppna ny underflik
tree-successor-tab-control-level-caption =
    .value = När den aktuella fliken stängs som den sista underordnad fliken
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = Flytta fokus till föregående flik i trädet
tree-successor-tab-control-level-never =
    .label = Flytta alltid fokus till nästa flik (respektera webbläsarens eller ett annats tilläggs kontroll)
tree-successor-tab-control-level-simulate-default =
    .label = Flytta alltid fokus till nästa flik
tree-tree-double-click-behavior-caption =
    .value = Dubbelklicka på en flik
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Stäng flik
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Fäll ihop/expandera träd
tree-tree-double-click-behavior-toggle-none =
    .label = Gör ingenting
tree-tree-double-click-behavior-toggle-sticky =
    .label = Fäst vid fliklistkanterna / lossa från fliklistkanterna
tree-auto-attach-header = Automatisk organisering av flikträd
tree-auto-attach-child-end =
    .label = Sista underordnade fliken
tree-auto-attach-child-next-to-last-related-tab =
    .label = Underordnad flik till den överordnade fliken, bredvid den nyligen öppnade underordnade fliken
tree-auto-attach-child-top =
    .label = Första underordnade fliken
tree-auto-attach-independent =
    .label = Oberoende flik
tree-auto-attach-next-sibling =
    .label = Nästa syskon till den överordnade fliken
tree-auto-attach-no-control =
    .label = (ingen kontroll)
tree-auto-attach-sibling =
    .label = Syskon till den överordnade fliken
tree-auto-attach-on-any-other-trigger-caption =
    .value = Flikar från vilken annan utlösare som helst: Öppna som
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = Duplicera flik som
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = För mittenklick, öppna en ny tom flik som
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Öppna en ny tom flik som
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Ny flik från andra program: öppna som
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = När en flik öppnas från en befintlig flik, öppna den som
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Ny flik med samma webbplats som aktuell flik från adressfältet, bokmärken, historik eller andra fall: öppna som
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Insättningsposition för nya underflikar från fästa flikar (visas som rotflikar)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Trädets slut
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Bredvid det nyligen öppnade underfliken, eller nära öppnaren
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Ingen kontroll (respektera webbläsarens eller andra fliktilläggs beslut)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = Toppen av trädet (nära öppnaren)
waterfox-blocker-header = Annonsblockering
waterfox-blocker-intro-description = Blockerar annonser, spårningsskript och andra oönskade förfrågningar för snabbare sidinläsning och färre distraktioner.
waterfox-blocker-setting-on =
    .label = På
waterfox-blocker-setting-on-description = Waterfox blockerar följande:
waterfox-blocker-setting-off =
    .label = Av
waterfox-blocker-setting-off-description = Inga annonser eller spårare blockeras av Waterfox. Tredjepartstillägg kan fortfarande blockera innehåll oberoende av varandra.
waterfox-blocker-dropdown-label =
    .value = Sökpartners annonser:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Tillåt annonser från Waterfox sökpartners
waterfox-blocker-dropdown-option-block-everything =
    .label = Blockera alla annonser även från Waterfox sökpartners
waterfox-blocker-manage-filter-lists =
    .label = Hantera filter listor…
waterfox-blocker-filter-lists-window =
    .title = Annonsblockeringsfilterlistor
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Spara ändringar
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = Välj vilka filterlistor som är aktiva.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount }aktiv av { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Aktiverad
waterfox-blocker-filter-lists-column-name =
    .label = Filterlista
waterfox-blocker-filter-lists-column-category =
    .label = Kategori
waterfox-blocker-filter-lists-enable =
    .label = Aktivera
waterfox-blocker-filter-lists-disable =
    .label = Inaktivera
waterfox-blocker-extension-detected = Waterfox har nu inbyggd annonsblockering. Du kan granska dina inställningar i inställningarna.
waterfox-blocker-extension-detected-learn-more =
    .label = Läs mer
waterfox-blocker-extension-detected-dismiss =
    .label = Visa inte igen
waterfox-blocker-extension-install-warning = Waterfox har redan en inbyggd annonsblockerare. Att köra två annonsblockerare kan göra att sidor inte fungerar eller laddas långsamt.
waterfox-blocker-extension-install-got-it =
    .label = Jag förstår
waterfox-blocker-extension-install-learn-more =
    .label = Läs mer
waterfox-blocker-third-party-notice-description = { $extensionName } blockerar även annonser. Att köra två annonsblockerare kan orsaka problem.
waterfox-blocker-filter-lists-category-core = Standard
waterfox-blocker-filter-lists-category-privacy = Integritet
waterfox-blocker-filter-lists-category-annoyances = Irritationer
waterfox-blocker-filter-lists-category-optional = Valfritt
waterfox-blocker-filter-lists-category-regional = Regionalt
waterfox-blocker-filter-lists-empty-state = Inga filterlistor tillgängliga.
waterfox-blocker-extension-fallback-name-this = detta tillägg
waterfox-blocker-extension-fallback-name-your = ditt tillägg
waterfox-blocker-spotlight-title = Waterfox inkluderar nu annonsblockering
waterfox-blocker-spotlight-subtitle = Vi har märkt att du har { $extensionName } installerat. Waterfox har nu sin egen annonsblockerare. Att använda den hjälper till att stödja Waterfox, men det är upp till dig att bestämma.
waterfox-blocker-spotlight-primary-button = Behåll mina nuvarande inställningar
waterfox-blocker-spotlight-secondary-button = Granska inställningar
waterfox-blocker-prompt-title = Waterfox annonsblockering
waterfox-blocker-reenable-conflict-message = Att köra både Waterfox-annonsblockering och "{ $extensionName }" kan orsaka att sidor inte fungerar. Vilken vill du behålla?
waterfox-blocker-reenable-use-built-in = Använd inbyggd blockerare
waterfox-blocker-reenable-keep-extension = Behåll tilläggsblockerare
waterfox-blocker-extension-install-manage-settings = Du kan hantera annonsblockering i Inställningar > Sekretess och säkerhet.
waterfox-blocker-extension-install-anyway = Installera ändå
waterfox-blocker-extension-install-keep-built-in = Fortsätt använda den inbyggda blockeraren
waterfox-blocked-page-title = Waterfox blockerade den här sidan
waterfox-blocked-page-heading = Waterfox blockerade den här sidan
waterfox-blocked-page-description = Den här sidan blockerades av en filterregel för annonsblockering.
waterfox-blocked-page-details =
    .aria-label = Information om blockerad sida
waterfox-blocked-page-blocked-url-label = Blockerad URL
waterfox-blocked-page-matched-rule-label = Matchad regel
waterfox-blocked-page-unavailable = Inte tillgänglig
waterfox-blocked-page-hint = “Ladda ändå” kommer tillfälligt att tillåta den här webbplatsen under resten av din session.
waterfox-blocked-page-go-back = Gå tillbaka
waterfox-blocked-page-load-anyway = Ladda ändå
waterfox-blocker-toolbar-button =
    .label = Annonsblockering
    .tooltiptext = Annonsblockering
waterfox-blocker-panel-not-available = Inte tillgängligt på den här sidan
waterfox-blocker-panel-toggle =
    .label = Annonsblockering på den här webbplatsen
    .description = Blockera annonser och spårare på den här webbplatsen.
waterfox-blocker-panel-disabled = Annonsblockering är avstängt
waterfox-blocker-panel-site-excepted = Annonser tillåtna på denna webbplats
waterfox-blocker-panel-partner-allowed = Annonser tillåtna för sökpartners
waterfox-blocker-stats =
    { $count ->
        [one] { $count } annons blockerad på denna webbplats
       *[other] { $count }annonser blockerade på denna webbplats
    }
waterfox-blocker-panel-settings-button = Annonsblockeringsinställningar
waterfox-blocker-show-badge-pref =
    .label = Visa blockerat antal på verktygsfältsknappen
waterfox-blocker-custom-filter-lists =
    .label = Anpassade filterlistor…
waterfox-blocker-filter-lists-search =
    .placeholder = Sök filter listor…
waterfox-blocker-filter-lists-refresh-now =
    .label = Uppdatera nu
waterfox-blocker-filter-lists-last-updated = Uppdaterad { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Ännu inte uppdaterad
waterfox-blocker-custom-filter-lists-window =
    .title = Anpassade filterlistor
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Spara ändringar
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = Lägg till webbadresser för anpassade filterlistor. Listor kommer att hämtas och tillämpas tillsammans med inbyggda filter.
waterfox-blocker-filter-lists-custom-heading =
    .value = Anpassade filterlistor
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Ange filterlistans URL…
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Lägg till
waterfox-blocker-filter-lists-custom-remove =
    .label = Ta bort
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Ta bort alla
waterfox-blocker-setting-on-summary = Blockerar annonser och spårare med minimal påverkan på sidinläsning.
waterfox-blocker-blocks-ads = Annonser och annonsnätverksförfrågningar
waterfox-blocker-blocks-tracking = Spårningsskript och pixlar
waterfox-blocker-blocks-annoyances = Störande popup-fönster och överlägg (med störande listan aktiverat)
waterfox-blocker-partner-funding-title = Stöd Waterfoxs utveckling
waterfox-blocker-partner-funding-description = Waterfox är gratis, öppen källkod och oberoende. Genom att tillåta annonser på sökpartners sidor finansierar du Waterfox utveckling och infrastruktur. Du kan stänga av detta när som helst, men att hålla det påslaget är det enklaste sättet att stödja projektet.
waterfox-blocker-filter-lists-custom-url-label =
    .value = Filterlistans URL
waterfox-blocker-filter-lists-custom-empty =
    .value = Inga anpassade filterlistor har lagts till.
waterfox-blocker-custom-filters =
    .label = Mina filter…
waterfox-blocker-custom-filters-window =
    .title = Mina filter
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Spara ändringar
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = Lägg till dina egna regler för annonsblockering. Dessa använder standard uBlock Origin-filtersyntax och tillämpas tillsammans med dina aktiverade filterlistor.
waterfox-blocker-custom-filters-empty =
    .value = Inga anpassade filter.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Inga anpassade filter.
        [one] 1 anpassat filter.
       *[other] { $count } anpassade filter.
    }
waterfox-blocker-custom-filters-status-unsaved = Osparade ändringar.
waterfox-blocker-custom-filters-import =
    .label = Importera…
waterfox-blocker-custom-filters-export =
    .label = Exportera…
waterfox-blocker-custom-filters-load-error-title = Laddning misslyckades
waterfox-blocker-custom-filters-load-error = Anpassade filter kunde inte laddas.
waterfox-blocker-custom-filters-save-error-title = Sparning misslyckades
waterfox-blocker-custom-filters-save-error = Anpassade filter kunde inte sparas.
waterfox-blocker-custom-filters-import-error-title = Import misslyckades
waterfox-blocker-custom-filters-import-error = Den valda filen kunde inte importeras.
waterfox-blocker-custom-filters-export-error-title = Export misslyckades
waterfox-blocker-custom-filters-export-error = Anpassade filter kunde inte exporteras.
waterfox-blocker-custom-filters-import-picker-title = Importera anpassade filter
waterfox-blocker-custom-filters-export-picker-title = Exportera anpassade filter
waterfox-blocker-custom-filters-import-replace-title = Ersätt nuvarande filter?
waterfox-blocker-custom-filters-import-replace-message = Importen kommer att ersätta allt som för närvarande finns i redigeraren.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Undantag för annonsblockering
    .style = { permissions-window2.style }
waterfox-blocker-filter-lists-next-refresh =
    .value = Nästa uppdatering: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Nästa uppdatering: okänd
permissions-exceptions-manage-waterfox-blocker-desc = Du kan specificera vilka webbplatser som har annonsblockering avstängd. Skriv den exakta adressen till webbplatsen du vill hantera och klicka sedan på Lägg till undantag.
