# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Дынамічныя тэмы
dynamic-theme-auto =
    .label = Аўтаматычны выбар рэжыму
dynamic-theme-dark =
    .label = Толькі цёмны рэжым
dynamic-theme-light =
    .label = Толькі светлы рэжым
waterfox-appearance-statusbar-heading =
    .label = Паліца статусу
waterfox-appearance-statusbar-enabled-toggle =
    .label = Паказваць паліцу статусу
    .description = Паказваць паліцу прылад унізе акна.
waterfox-appearance-statusbar-links-toggle =
    .label = Паказваць кірункі спасылак на паліцы статусу
pane-theme-title = Дапасаванне
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Анімацыі
appearance-header = Выгляд
bookmark-header = Паліца закладак
font-header = Шрыфты
full-screen-header = Поўны экран
icons-header = Значкі
interface-component-header = Кампаненты інтэрфейсу
media-player-header = Прайгравальнік
nav-bar-header = Паліца навігацыі
panels-header = Паліцы
sidebar-header = Бакавая паліца
tab-bar-header = Паласа картак
theme-header = Тэма
preset-title = Нарыхтоўкі
lepton-style =
    .label = Стыль Lepton
proton-style =
    .label = Стыль Proton
waterfox-defaults =
    .label = Прадвызначаныя налады
auto-blur-tabs =
    .label = Аўтаматычна размываць карткі
auto-hide-back =
    .label = Аўтаматычна хаваць кнопку «Назад»
auto-hide-bookmarkbar =
    .label = Аўтаматычна хаваць паліцу закладак
auto-hide-forward =
    .label = Аўтаматычна хаваць кнопку «Уперад»
auto-hide-navbar =
    .label = Аўтаматычна хаваць паліцу навігацыі
auto-hide-pageaction =
    .label = Аўтаматычна хаваць дзеянні старонкі
auto-hide-sidebar =
    .label = Аўтаматычна хаваць бакавую паліцу
auto-hide-tabbar =
    .label = Аўтаматычна хаваць паласу картак
auto-hide-tabs =
    .label = Аўтаматычна хаваць карткі
center-navbar-text =
    .label = Цэнтраваць тэкст паліцы навігацыі
center-tab-content =
    .label = Цэнтраваць змесціва карткі
center-tab-label =
    .label = Цэнтраваць толькі назву карткі
close-button-hover =
    .label = Паказваць кнопку закрыцця вылучанай карткі пры навядзенні на яе, калі адкрыта шмат картак
compact-bookmark-menu =
    .label = Зменшыць водступы меню закладак
compact-context-menu =
    .label = Зменшыць водступы кантэкстнага меню
compact-navbar-popup =
    .label = Зменшыць водступы меню паліцы навігацыі
disable-sidebar-animate =
    .label = Адключыць анімацыю бакавой паліцы
