restart-prompt-title = Herstart { -brand-short-name }
restart-prompt-question = Weet u zeker dat u { -brand-short-name } wilt herstarten?
appmenuitem-restart-browser =
    .label = Herstarten
copy-url =
    .label = Kopieer Tabblad Link
copy-all-urls =
    .label = Kopieer alle tablinks
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Alles openen in privétabbladen
open-all-links-private =
    .label = Open Alle Links in Privé Tabs
open-private-tab =
    .label = Openen in een nieuw privétabblad
new-private-tab =
    .label = Nieuw privétabblad
    .tooltiptext = Een nieuw privé tabblad openen
open-link-private =
    .label = Koppeling openen in nieuw privétabblad
status-bar =
    .label = Status Balk
tab-position-header = Positie tabbalk
tab-bar-top-above =
    .label = Bovenaan de adresbalk
tab-bar-top-below =
    .label = Bovenaan de adresbalk
tab-bar-bottom-above =
    .label = Onderaan boven statusbalk
tab-bar-bottom-below =
    .label = Onderaan de statusbalk
tab-additional-header = Aanvullende Tabblad voorkeuren
pinned-icon-only =
    .label = Vaste tabbladen verkleinen om alleen het pictogram van de site weer te geven
insert-after-current =
    .label = Nieuw tabblad invoegen na huidige tabblad
insert-related-after-current =
    .label = Plaats gerelateerd nieuw tabblad na huidige tabblad
dynamic-theme-header = Dynamische thema's
dynamic-theme-dark =
    .label = Donkere modus forceren
dynamic-theme-light =
    .label = Lichte modus forceren
dynamic-theme-auto =
    .label = Dynamisch licht/donker modus instellen
restart-header = Herstart menu-item
restart-show-button =
    .label = Herstartknop weergeven in PanelUI
restart-purge-cache =
    .label = Verwijder snelle herstartcache bij herstart van browser
restart-require-confirmation =
    .label = Bevestiging opnieuw starten vereist
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Toon kopieer tab url menu-item
enable-copy-active-tab =
    .label = Kopieer URL alleen vanuit actieve tab
show-copy-all-urls =
    .label = Toon kopieer alle tab urls menu-item
show-unload-tab =
    .label = Menu item uitladen tonen
statusbar-enabled =
    .label = Toon statusbalk
statusbar-show-links =
    .label = Links tonen
statusbar-contrast-text =
    .label = Contrast statusbalk tekstkleur
bookmarks-bar-position-header = Bladwijzerwerkbalkpositie
bookmarks-position-top =
    .label = Bovenkant
bookmarks-position-bottom =
    .label = Onderaan
geolocation-api-header = Geolocatie API
geolocation-description = Sommige websites hebben je locatie nodig om te functioneren. Als een website niet werkt als gevolg van het niet vinden van uw locatie, schakel deze voorkeur dan in en probeer het opnieuw.
geolocation-api-enabled =
    .label = Inschakelen
geolocation-api-disabled =
    .label = Uitschakelen
send-referrer-header-0 =
    .label = Nooit verzenden van de referrer header
send-referrer-header-1 =
    .label = Stuur de referrer header alleen bij het klikken op links en vergelijkbare elementen
send-referrer-header-2 =
    .label = Stuur de referrer header op alle aanvragen (standaard)
enable-webrtc-p2p =
    .label = WebRTC peer verbinding inschakelen
load-images =
    .label = Afbeeldingen automatisch laden
enable-javascript =
    .label = JavaScript inschakelen
webrtc-header = WebRTC peer verbinding
ref-header = HTTP Referrer Header
statusbar-header = Status Balk
private-tab =
    .label =
        { $isPrivate ->
            [true] Verlaat privé tabblad
           *[false] Maak een privétabblad
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
auto-blur-tabs =
    .label = Auto Blur Tabs
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
hide-tab-icons =
    .label = Hide Tab Icons
drag-space =
    .label = Enable Fixed Drag Space
compact-context-menu =
    .label = Reduce Context Menu Padding
square-checkbox =
    .label = Square Checkbox
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
full-panel-strip =
    .label = Full Width App Menu Separator
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font =
    .label = Enable monospaced font for page
tab-bar-header = Tab Bar
monospace-font-theme =
    .label = Enable monospaced font for theme
show-menu-icons =
    .label = Show Menu Icons
nav-bar-header = Nav Bar
onboarding-grassroots-title = Supporting the grassroots
square-button-edges =
    .label = Square Button Corners
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
panels-header = Panels
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = Media Player
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
square-menu-popup =
    .label = Square Context Menu Panel Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
hide-sidebar-header =
    .label = Hide Sidebar Header
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
