restart-prompt-title = Mulai ulang { -brand-short-name }
restart-prompt-question = Anda yakin bahwa Anda ingin memulai ulang { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Mulai ulang
copy-url =
    .label = Salin Tautan Tab
copy-all-urls =
    .label = Salin Semua Tautan Tab
unload-tab =
    .label = Bongkar Tab
open-all-private =
    .label = Buka Semua di Tab Pribadi
open-all-links-private =
    .label = Buka Semua Tautan di Tab Pribadi
open-private-tab =
    .label = Buka di Tab Pribadi Baru
new-private-tab =
    .label = Tab Pribadi Baru
    .tooltiptext = Buka tab pribadi baru
open-link-private =
    .label = Buka Tautan di Tab Pribadi Baru
status-bar =
    .label = Bilah Status
tab-position-header = Posisi Bilah Tab
tab-bar-top-above =
    .label = Teratas atas bilah alamat
tab-bar-top-below =
    .label = Teratas di bawah bilah alamat
tab-bar-bottom-above =
    .label = Terbawah di atas bilah status
tab-bar-bottom-below =
    .label = Terbawah di bawah bilah status
tab-additional-header = Preferensi Tab Tambahan
pinned-icon-only =
    .label = Kecilkan tab yang disematkan agar hanya menampilkan ikon situs
insert-after-current =
    .label = Sisipkan tab baru setelah tab saat ini
insert-related-after-current =
    .label = Masukkan tab baru yang terkait setelah tab saat ini
dynamic-theme-header = Tema Dinamis
dynamic-theme-dark =
    .label = Paksa Mode Gelap
dynamic-theme-light =
    .label = Paksa Mode Tenang
dynamic-theme-auto =
    .label = Atur Mode Tenang/Gelap Secara Dinamis
restart-header = Mulai Ulang Item Menu
restart-show-button =
    .label = Tampilkan tombol mulai ulang di PanelUI
restart-purge-cache =
    .label = Hapus cache mulai ulang cepat pada mulai ulang browser
restart-require-confirmation =
    .label = Memerlukan konfirmasi mulai ulang
tab-feature-header = Menu Konteks Tab
show-duplicate-tab =
    .label = Tampilkan item menu tab duplikat
show-copy-url =
    .label = Tampilkan item menu salin url tab
enable-copy-active-tab =
    .label = Salin URL hanya dari tab aktif
show-copy-all-urls =
    .label = Tampilkan salin semua item menu urls tab
show-unload-tab =
    .label = Tampilkan item menu tab bongkar muatan
statusbar-enabled =
    .label = Tampilkan Bilah Status
statusbar-show-links =
    .label = Tampilkan tautan
statusbar-contrast-text =
    .label = Warna teks bilah status kontras
bookmarks-bar-position-header = Posisi Bilah Alat Bookmark
bookmarks-position-top =
    .label = Atas
bookmarks-position-bottom =
    .label = Bawah
geolocation-api-header = API Geolokasi
geolocation-description = Beberapa situs web memerlukan lokasi anda untuk berfungsi. Jika situs web tidak berfungsi karena tidak dapat menemukan lokasi anda, aktifkan preferensi ini dan coba lagi.
geolocation-api-enabled =
    .label = Aktifkan
geolocation-api-disabled =
    .label = Nonaktifkan
send-referrer-header-0 =
    .label = Jangan mengirim header perujuk
send-referrer-header-1 =
    .label = Mengirimkan header perujuk hanya ketika mengklik tautan dan elemen serupa
send-referrer-header-2 =
    .label = Mengirimkan header perujuk pada semua permintaan (Bawaan)
enable-webrtc-p2p =
    .label = Aktifkan koneksi rekan WebRTC
load-images =
    .label = Muat gambar secara otomatis
enable-javascript =
    .label = Aktifkan JavaScript
webrtc-header = Koneksi rekan WebRTC
ref-header = Header Perujuk HTTP
statusbar-header = Bilah Status
private-tab =
    .label =
        { $isPrivate ->
            [true] Keluar dari Tab Pribadi
           *[false] Jadikan Tab Pribadi
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
pane-theme-title = Look & Feel
preset-title = Presets
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
auto-blur-tabs =
    .label = Auto Blur Tabs
enable-panel-transparency =
    .label = Enable panel transparency
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
auto-hide-forward =
    .label = Auto Hide Forward Button
auto-hide-navbar =
    .label = Auto Hide Nav Bar
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
hide-tab-icons =
    .label = Hide Tab Icons
hide-sidebar-header =
    .label = Hide Sidebar Header
auto-hide-pageaction =
    .label = Auto Hide Page Action
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
center-tab-content =
    .label = Center Tab Content
square-button-edges =
    .label = Square Button Corners
square-tab-edges =
    .label = Square Tab Corners
square-menu-item =
    .label = Square Context Menu Item Corners
square-menu-popup =
    .label = Square Context Menu Panel Corners
square-field =
    .label = Square Entry Field Corners
compact-context-menu =
    .label = Reduce Context Menu Padding
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font-theme =
    .label = Enable monospaced font for theme
tab-bar-header = Tab Bar
media-player-header = Media Player
icons-header = Icons
onboarding-grassroots-title = Supporting the grassroots
hide-all-icons =
    .label = Hide All Icons
waterfox-defaults =
    .label = Waterfox Defaults
panels-header = Panels
drag-space =
    .label = Enable Fixed Drag Space
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
monospace-font =
    .label = Enable monospaced font for page
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
full-screen-header = Full screen
square-checkbox =
    .label = Square Checkbox
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
nav-bar-header = Nav Bar
sidebar-header = Sidebar
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
auto-hide-tabs =
    .label = Auto Hide Tabs
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
