restart-prompt-title = Mulai ulang { -brand-short-name }
restart-prompt-question = Anda yakin bahwa Anda ingin memulai ulang { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Mulai ulang
copy-url =
    .label = Salin Tautan Tab
copy-all-urls =
    .label = Salin Semua Tautan Tab
unload-tab =
    .label = Bongkar Tab
open-all-private =
    .label = Buka Semua di Tab Pribadi
open-all-links-private =
    .label = Buka Semua Tautan di Tab Pribadi
open-private-tab =
    .label = Buka di Tab Pribadi Baru
new-private-tab =
    .label = Tab Pribadi Baru
    .tooltiptext = Buka tab pribadi baru
open-link-private =
    .label = Buka Tautan di Tab Pribadi Baru
status-bar =
    .label = Bilah Status
tab-position-header = Posisi Bilah Tab
tab-bar-top-above =
    .label = Teratas atas bilah alamat
tab-bar-top-below =
    .label = Teratas di bawah bilah alamat
tab-bar-bottom-above =
    .label = Terbawah di atas bilah status
tab-bar-bottom-below =
    .label = Terbawah di bawah bilah status
tab-additional-header = Preferensi Tab Tambahan
pinned-icon-only =
    .label = Kecilkan tab yang disematkan agar hanya menampilkan ikon situs
insert-after-current =
    .label = Sisipkan tab baru setelah tab saat ini
insert-related-after-current =
    .label = Masukkan tab baru yang terkait setelah tab saat ini
dynamic-theme-header = Tema Dinamis
dynamic-theme-dark =
    .label = Paksa Mode Gelap
dynamic-theme-light =
    .label = Paksa Mode Tenang
dynamic-theme-auto =
    .label = Atur Mode Tenang/Gelap Secara Dinamis
restart-header = Mulai Ulang Item Menu
restart-show-button =
    .label = Tampilkan tombol mulai ulang di PanelUI
restart-purge-cache =
    .label = Hapus cache mulai ulang cepat pada mulai ulang browser
restart-require-confirmation =
    .label = Memerlukan konfirmasi mulai ulang
tab-feature-header = Menu Konteks Tab
show-duplicate-tab =
    .label = Tampilkan item menu tab duplikat
show-copy-url =
    .label = Tampilkan item menu salin url tab
enable-copy-active-tab =
    .label = Salin URL hanya dari tab aktif
show-copy-all-urls =
    .label = Tampilkan salin semua item menu urls tab
show-unload-tab =
    .label = Tampilkan item menu tab bongkar muatan
statusbar-enabled =
    .label = Tampilkan Bilah Status
statusbar-show-links =
    .label = Tampilkan tautan
statusbar-contrast-text =
    .label = Warna teks bilah status kontras
bookmarks-bar-position-header = Posisi Bilah Alat Bookmark
bookmarks-position-top =
    .label = Atas
bookmarks-position-bottom =
    .label = Bawah
geolocation-api-header = API Geolokasi
geolocation-description = Beberapa situs web memerlukan lokasi anda untuk berfungsi. Jika situs web tidak berfungsi karena tidak dapat menemukan lokasi anda, aktifkan preferensi ini dan coba lagi.
geolocation-api-enabled =
    .label = Aktifkan
geolocation-api-disabled =
    .label = Nonaktifkan
send-referrer-header-0 =
    .label = Jangan mengirim header perujuk
send-referrer-header-1 =
    .label = Sertakan header perujuk hanya ketika mengklik tautan dan elemen serupa
send-referrer-header-2 =
    .label = Sertakan header perujuk pada semua permintaan (Bawaan)
enable-webrtc-p2p =
    .label = Aktifkan koneksi rekan WebRTC
load-images =
    .label = Muat gambar secara otomatis
enable-javascript =
    .label = Aktifkan JavaScript
webrtc-header = Koneksi rekan WebRTC
ref-header = Header Perujuk HTTP
statusbar-header = Bilah Status
private-tab =
    .label =
        { $isPrivate ->
            [true] Keluar dari Tab Pribadi
           *[false] Jadikan Tab Pribadi
        }
update-application-manual =
    .label = Jangan pernah memeriksa pembaruan (tidak disarankan)
    .accesskey = N
preferences-doh-setting-ultra =
    .label = Perlindungan Ultra
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } akan menggunakan DNS aman dengan Oblivious HTTP melalui relai privasi Waterfox untuk perlindungan maksimal.
preferences-doh-ultra-detailed-desc-1 = Menggunakan relai Oblivious HTTP Waterfox untuk menyembunyikan permintaan DNS bahkan dari penyedia DNS
preferences-doh-ultra-detailed-desc-2 = Memberikan lapisan enkripsi tambahan di luar DNS melalui HTTPS standar
preferences-doh-ultra-detailed-desc-3 = Perlindungan privasi DNS maksimal - tidak ada yang dapat melihat situs yang Anda kunjungi
preferences-doh-ultra-fallback-mode = Perilaku cadangan:
preferences-doh-ultra-fallback-allowed = Izinkan kembali ke DNS sistem jika DNS aman gagal
preferences-doh-ultra-fallback-disabled = Jangan pernah kembali ke DNS sistem (situs mungkin tidak dimuat jika DNS aman gagal)
pane-theme-title = Tampilan & Nuansa
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animasi
appearance-header = Tampilan
autohide-hidden-header = Sembunyi Otomatis & Tersembunyi
bookmark-header = Bilah Penanda
center-header = Tengah
font-header = Font
full-screen-header = Layar penuh
icons-header = Ikon
interface-component-header = Komponen Antarmuka
media-player-header = Pemutar Media
nav-bar-header = Bilah Navigasi
panels-header = Panel
rounding-header = Pembulatan
sidebar-header = Bilah Samping
tab-bar-header = Bilah Tab
theme-header = Tema
preset-title = Preset
lepton-style =
    .label = Gaya Lepton
proton-style =
    .label = Gaya Proton
waterfox-defaults =
    .label = Bawaan Waterfox
auto-blur-tabs =
    .label = Kaburkan Tab Otomatis
auto-hide-back =
    .label = Sembunyikan Tombol Kembali Otomatis
auto-hide-bookmarkbar =
    .label = Sembunyikan Bilah Penanda Otomatis
auto-hide-forward =
    .label = Sembunyikan Tombol Maju Otomatis
auto-hide-navbar =
    .label = Sembunyikan Bilah Navigasi Otomatis
auto-hide-pageaction =
    .label = Sembunyikan Tindakan Halaman Otomatis
auto-hide-sidebar =
    .label = Sembunyikan Bilah Samping Otomatis
auto-hide-tabbar =
    .label = Sembunyikan Bilah Tab Otomatis
auto-hide-tabs =
    .label = Sembunyikan Tab Otomatis
center-navbar-text =
    .label = Pusatkan Teks Bilah Navigasi
center-tab-content =
    .label = Pusatkan Konten Tab
center-tab-label =
    .label = Pusatkan Hanya Label Tab
close-button-hover =
    .label = Tampilkan tombol tutup tab saat kursor diarahkan pada tab yang dipilih ketika banyak tab terbuka
compact-bookmark-menu =
    .label = Kurangi Jarak Menu Penanda
compact-context-menu =
    .label = Kurangi Jarak Menu Konteks
compact-navbar-popup =
    .label = Kurangi Jarak Popup Bilah Navigasi
compact-panel-header =
    .label = Kurangi Jarak Header Panel
disable-panel-animate =
    .label = Nonaktifkan animasi panel menu aplikasi
disable-sidebar-animate =
    .label = Nonaktifkan animasi panel bilah samping
drag-space =
    .label = Aktifkan Ruang Seret Tetap
enable-cyan-accent-color =
    .label = Warna Aksen Sian
enable-default-accent-color =
    .label = Warna Aksen Bawaan
enable-menu-transparency =
    .label = Aktifkan transparansi menu
enable-panel-transparency =
    .label = Aktifkan transparansi panel
enable-system-accent-color =
    .label = Warna Aksen Sistem
enable-waterfox-theme-0 =
    .label = Aktifkan kustomisasi tema Waterfox pada semua tema
enable-waterfox-theme-1 =
    .label = Aktifkan kustomisasi tema Waterfox pada tema Waterfox
enable-waterfox-theme-2 =
    .label = Nonaktifkan kustomisasi tema Waterfox
full-panel-strip =
    .label = Pemisah Menu Aplikasi Lebar Penuh
remove-panel-strip =
    .label = Hapus Pemisah Menu Aplikasi Berwarna
hide-all-icons =
    .label = Sembunyikan Semua Ikon
hide-bookmarkbar-icon =
    .label = Sembunyikan Ikon Bilah Penanda
hide-bookmarkbar-label =
    .label = Sembunyikan Label Bilah Penanda
hide-disabled-menuitems =
    .label = Sembunyikan Item Menu Nonaktif
hide-sidebar-header =
    .label = Sembunyikan Header Bilah Samping
hide-tab-icons =
    .label = Sembunyikan Ikon Tab
hide-urlbar-iconbox =
    .label = Sembunyikan Kotak Ikon Bilah URL
monospace-font =
    .label = Aktifkan font monospace untuk halaman
monospace-font-theme =
    .label = Aktifkan font monospace untuk tema
show-mac-menu-icons =
    .label = Tampilkan Ikon Menu Mac
show-menu-icons =
    .label = Tampilkan Ikon Menu
square-button-edges =
    .label = Sudut Tombol Persegi
square-checkbox =
    .label = Kotak Centang Persegi
square-field =
    .label = Sudut Kolom Entri Persegi
square-menu-item =
    .label = Sudut Item Menu Konteks Persegi
square-menu-panel =
    .label = Sudut Panel Menu Aplikasi Persegi
square-menu-popup =
    .label = Sudut Panel Menu Konteks Persegi
square-panel-item =
    .label = Sudut Item Menu Aplikasi Persegi
square-tab-edges =
    .label = Sudut Tab Persegi
tab-context-line =
    .label = Garis Konteks Tab
telemetry-page-subtitle = Waterfox tidak mengumpulkan telemetri tentang instalasi Anda - semua modul telemetri dinonaktifkan saat peramban dibuat. Apa yang Anda lakukan di peramban hanya diketahui oleh Anda.
telemetry-privacy-policy = Kebijakan Privasi
onboarding-grassroots-title = Dukungan untuk gerakan akar rumput
onboarding-grassroots-subtitle = Terima kasih telah menggunakan Waterfox, peramban independen yang berasal dari komunitas. Dengan dukungan Anda, kami membangun alternatif berkelanjutan bagi para pemain besar di luar sana.
tabbrowser-confirm-session-restore-checkbox = Buka jendela dan tab sebelumnya
pane-tree-title = Tab Vertikal Berstruktur Pohon
category-tree =
    .tooltiptext = { pane-tree-title }
browser-layout-tree-vertical-tabs =
    .label = Tab vertikal berstruktur pohon
sidebar-tree-vertical-tabs =
    .label = Tab vertikal berstruktur pohon
tree-header = Tab Vertikal Berstruktur Pohon
tree-appearance-header = Tampilan
tree-auto-sticky-header = Tab yang menempel di tepi bilah tab ketika digulir keluar
tree-faviconize-pinned-tabs =
    .label = Tampilkan tab yang disematkan hanya dengan ikonnya
    .accesskey = S
tree-sticky-active-tab =
    .label = Tab Aktif
    .accesskey = k
tree-sticky-sharing-tab =
    .label = Tab yang Berbagi Kamera/Mikrofon/Layar
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = Tab yang Memutar Suara
    .accesskey = y
tree-behavior-header = Tampilan pohon tab
tree-auto-collapse-expand-subtree-on-attach =
    .label = Saat pohon baru muncul, lipat yang lain secara otomatis
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = Saat tab mendapat fokus, perluas pohonnya dan lipat yang lain secara otomatis
    .accesskey = x
tree-drop-links-on-tab-behavior-caption =
    .value = Saat tautan atau string URL dijatuhkan ke tab
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = Selalu tanyakan bagaimana menanganinya
tree-drop-links-on-tab-behavior-load =
    .label = Muat ke tab
tree-drop-links-on-tab-behavior-newtab =
    .label = Buka tab anak baru
tree-successor-tab-control-level-caption =
    .value = Saat tab saat ini ditutup sebagai anak terakhir
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = Pindahkan fokus ke tab sebelumnya di pohon
tree-successor-tab-control-level-never =
    .label = Selalu pindahkan fokus ke tab berikutnya (ikuti kontrol browser atau ekstensi lain)
tree-successor-tab-control-level-simulate-default =
    .label = Selalu pindahkan fokus ke tab berikutnya
tree-tree-double-click-behavior-caption =
    .value = Klik ganda pada tab
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = Tutup tab
tree-tree-double-click-behavior-toggle-collapsed =
    .label = Lipat/perluas pohon
tree-tree-double-click-behavior-toggle-none =
    .label = Jangan lakukan apa pun
tree-tree-double-click-behavior-toggle-sticky =
    .label = Tempelkan ke tepi bilah tab / Lepaskan dari tepi bilah tab
tree-auto-attach-header = Pengaturan otomatis pohon tab
tree-auto-attach-child-end =
    .label = Anak terakhir dari tab induk
tree-auto-attach-child-next-to-last-related-tab =
    .label = Anak dari tab induk, di samping anak yang baru dibuka
tree-auto-attach-child-top =
    .label = Anak pertama dari tab induk
tree-auto-attach-independent =
    .label = Tab independen
tree-auto-attach-next-sibling =
    .label = Saudara berikutnya dari tab induk
tree-auto-attach-no-control =
    .label = (tidak ada kontrol)
tree-auto-attach-sibling =
    .label = Saudara dari tab induk
tree-auto-attach-on-any-other-trigger-caption =
    .value = Tab dari pemicu lain mana pun: Buka sebagai
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = Gandakan tab sebagai
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = Untuk klik tengah, buka tab kosong baru sebagai
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = Buka tab kosong baru sebagai
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = Tab baru dari Aplikasi Lain: Buka sebagai
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = Saat tab dibuka dari tab yang ada, buka sebagai
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = Tab baru dengan situs yang sama seperti tab saat ini dari bilah lokasi, penanda, riwayat, atau kasus lainnya: Buka sebagai
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = Posisi penyisipan tab anak baru dari tab yang disematkan (akan muncul sebagai tab akar)
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = Akhir dari pohon
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = Di samping anak yang baru dibuka, atau dekat pembukanya
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = Tidak ada kontrol (menghormati keputusan peramban atau ekstensi tab lainnya)
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = Puncak pohon (dekat pembuka)
waterfox-blocker-intro-description = Memblokir iklan, skrip pelacak, dan permintaan yang tidak diinginkan untuk pemuatan halaman yang lebih cepat dan lebih sedikit gangguan.
waterfox-blocker-setting-on =
    .label = Aktif
waterfox-blocker-setting-on-description = Waterfox memblokir hal berikut:
waterfox-blocker-setting-off =
    .label = Nonaktif
waterfox-blocker-setting-off-description = Tidak ada iklan atau pelacak yang diblokir oleh Waterfox. Ekstensi pihak ketiga masih dapat memblokir konten secara mandiri.
waterfox-blocker-dropdown-label =
    .value = Iklan mitra pencarian:
waterfox-blocker-dropdown-option-partner-exception =
    .label = Izinkan di mitra pencarian Waterfox
waterfox-blocker-dropdown-option-block-everything =
    .label = Larang di mitra pencarian Waterfox
waterfox-blocker-manage-filter-lists =
    .label = Kelola Daftar Filter…
waterfox-blocker-filter-lists-window =
    .title = Daftar filter pemblokir iklan
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = Simpan Perubahan
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = Pilih daftar filter mana yang aktif.
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } aktif dari { $totalCount }
waterfox-blocker-filter-lists-column-enabled =
    .label = Diaktifkan
waterfox-blocker-filter-lists-column-name =
    .label = Daftar Filter
waterfox-blocker-filter-lists-column-category =
    .label = Kategori
waterfox-blocker-filter-lists-enable =
    .label = Aktifkan
waterfox-blocker-filter-lists-disable =
    .label = Nonaktifkan
waterfox-blocker-extension-detected = Waterfox kini memiliki pemblokir iklan bawaan. Anda dapat meninjau pengaturan di setelan.
waterfox-blocker-extension-detected-learn-more =
    .label = Pelajari lebih lanjut
waterfox-blocker-extension-detected-dismiss =
    .label = Jangan tampilkan lagi
waterfox-blocker-extension-install-warning = Waterfox sudah memiliki pemblokir iklan bawaan. Menjalankan dua pemblokir iklan dapat menyebabkan halaman rusak atau memuat dengan lambat.
waterfox-blocker-extension-install-got-it =
    .label = Mengerti
waterfox-blocker-extension-install-learn-more =
    .label = Pelajari lebih lanjut
waterfox-blocker-third-party-notice-description = { $extensionName } juga memblokir iklan. Menjalankan dua pemblokir iklan dapat menimbulkan masalah.
waterfox-blocker-filter-lists-category-core = Baku
waterfox-blocker-filter-lists-category-privacy = Privasi
waterfox-blocker-filter-lists-category-annoyances = Gangguan
waterfox-blocker-filter-lists-category-optional = Opsional
waterfox-blocker-filter-lists-category-regional = Regional
waterfox-blocker-filter-lists-empty-state = Tidak ada daftar filter yang tersedia.
waterfox-blocker-extension-fallback-name-this = ekstensi ini
waterfox-blocker-extension-fallback-name-your = ekstensi Anda
waterfox-blocker-spotlight-title = Waterfox kini menyertakan pemblokiran iklan
waterfox-blocker-spotlight-subtitle = Kami mendeteksi Anda telah memasang { $extensionName }. Waterfox kini memiliki pemblokir iklan sendiri. Menggunakannya membantu mendukung Waterfox, tetapi keputusan ada di tangan Anda.
waterfox-blocker-spotlight-primary-button = Pertahankan pengaturan saya saat ini
waterfox-blocker-spotlight-secondary-button = Tinjau pengaturan
waterfox-blocker-prompt-title = Pemblokiran iklan Waterfox
waterfox-blocker-reenable-conflict-message = Menjalankan pemblokiran iklan Waterfox dan "{ $extensionName }" secara bersamaan dapat menyebabkan halaman rusak. Mana yang ingin Anda pertahankan?
waterfox-blocker-reenable-use-built-in = Gunakan pemblokir bawaan
waterfox-blocker-reenable-keep-extension = Tetap gunakan pemblokir ekstensi
waterfox-blocker-extension-install-manage-settings = Anda dapat mengelola pemblokiran iklan di Pengaturan > Privasi & Keamanan.
waterfox-blocker-extension-install-anyway = Pasang saja
waterfox-blocker-extension-install-keep-built-in = Tetap gunakan pemblokir bawaan
waterfox-blocked-page-title = Waterfox memblokir halaman ini
waterfox-blocked-page-heading = Waterfox memblokir halaman ini
waterfox-blocked-page-description = Halaman ini diblokir oleh aturan filter pemblokiran iklan.
waterfox-blocked-page-details =
    .aria-label = Detail halaman yang diblokir
waterfox-blocked-page-blocked-url-label = URL yang diblokir
waterfox-blocked-page-matched-rule-label = Aturan yang cocok
waterfox-blocked-page-unavailable = Tidak tersedia
waterfox-blocked-page-hint = "Muat tetap" akan mengizinkan situs ini untuk sementara hingga sesi Anda berakhir.
waterfox-blocked-page-go-back = Kembali
waterfox-blocked-page-load-anyway = Muat saja
waterfox-blocker-header = Pemblokiran Iklan
waterfox-blocker-toolbar-button =
    .label = Pemblokiran iklan
    .tooltiptext = Pemblokiran iklan
waterfox-blocker-panel-not-available = Tidak tersedia di halaman ini
waterfox-blocker-panel-toggle =
    .label = Pemblokiran iklan di situs ini
    .description = Blokir iklan dan pelacak di situs ini.
waterfox-blocker-panel-disabled = Pemblokiran iklan nonaktif
waterfox-blocker-panel-site-excepted = Iklan diizinkan di situs ini
waterfox-blocker-panel-partner-allowed = Iklan diizinkan untuk mitra penelusuran
waterfox-blocker-stats =
    { $count ->
        [one] { $count } iklan diblokir di situs ini
       *[other] { $count } iklan diblokir di situs ini
    }
waterfox-blocker-panel-settings-button = Pengaturan pemblokiran iklan
waterfox-blocker-show-badge-pref =
    .label = Tampilkan jumlah yang diblokir pada tombol bilah alat
waterfox-blocker-custom-filter-lists =
    .label = Daftar Filter Kustom…
waterfox-blocker-filter-lists-search =
    .placeholder = Cari daftar filter…
waterfox-blocker-filter-lists-refresh-now =
    .label = Perbarui Sekarang
waterfox-blocker-filter-lists-last-updated = Diperbarui { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = Belum diperbarui
waterfox-blocker-custom-filter-lists-window =
    .title = Daftar Filter Kustom
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = Simpan Perubahan
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = Tambahkan URL daftar filter kustom. Daftar akan diambil dan diterapkan bersama filter bawaan.
waterfox-blocker-filter-lists-custom-heading =
    .value = Daftar Filter Kustom
waterfox-blocker-filter-lists-custom-input =
    .placeholder = Masukkan URL daftar filter…
waterfox-blocker-filter-lists-custom-url-label =
    .value = URL daftar filter
waterfox-blocker-filter-lists-custom-col =
    .label = URL
waterfox-blocker-filter-lists-custom-add =
    .label = Tambah
waterfox-blocker-filter-lists-custom-remove =
    .label = Hapus
waterfox-blocker-filter-lists-custom-remove-all =
    .label = Hapus Semua
waterfox-blocker-filter-lists-custom-empty =
    .value = Tidak ada daftar filter kustom yang ditambahkan.
waterfox-blocker-setting-on-summary = Memblokir iklan dan pelacak dengan dampak minimal pada pemuatan halaman.
waterfox-blocker-blocks-ads = Iklan dan permintaan jaringan iklan
waterfox-blocker-blocks-tracking = Skrip dan piksel pelacak
waterfox-blocker-blocks-annoyances = Popup dan hamparan yang mengganggu (dengan daftar gangguan diaktifkan)
waterfox-blocker-partner-funding-title = Dukung pengembangan Waterfox
waterfox-blocker-partner-funding-description = Waterfox gratis, sumber terbuka, dan independen. Mengizinkan iklan di halaman mitra pencarian adalah cara Waterfox mendanai pengembangan dan infrastruktur. Anda dapat mematikannya kapan saja, tetapi membiarkannya aktif adalah cara termudah untuk mendukung proyek ini.
permissions-exceptions-waterfox-blocker-window2 =
    .title = Pengecualian untuk Pemblokiran Iklan
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = Anda dapat menentukan situs web mana yang pemblokiran iklannya dinonaktifkan. Ketik alamat lengkap situs yang ingin Anda kelola lalu klik Tambah Pengecualian.
waterfox-blocker-filter-lists-next-refresh =
    .value = Pembaruan berikutnya: { $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = Pembaruan berikutnya: tidak diketahui
waterfox-blocker-custom-filters =
    .label = Filter Saya…
waterfox-blocker-custom-filters-window =
    .title = Filter Saya
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = Simpan Perubahan
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = Tambahkan aturan pemblokiran iklan Anda sendiri. Aturan ini menggunakan sintaksis filter uBlock Origin standar dan diterapkan bersama daftar filter yang Anda aktifkan.
waterfox-blocker-custom-filters-empty =
    .value = Tidak ada filter kustom.
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] Tidak ada filter kustom.
        [one] 1 filter kustom.
       *[other] { $count } filter kustom.
    }
waterfox-blocker-custom-filters-status-unsaved = Perubahan belum disimpan.
waterfox-blocker-custom-filters-import =
    .label = Impor…
waterfox-blocker-custom-filters-export =
    .label = Ekspor…
waterfox-blocker-custom-filters-load-error-title = Gagal memuat
waterfox-blocker-custom-filters-load-error = Filter kustom tidak dapat dimuat.
waterfox-blocker-custom-filters-save-error-title = Gagal menyimpan
waterfox-blocker-custom-filters-save-error = Filter kustom tidak dapat disimpan.
waterfox-blocker-custom-filters-import-error-title = Gagal mengimpor
waterfox-blocker-custom-filters-import-error = File yang dipilih tidak dapat diimpor.
waterfox-blocker-custom-filters-export-error-title = Gagal mengekspor
waterfox-blocker-custom-filters-export-error = Filter kustom tidak dapat diekspor.
waterfox-blocker-custom-filters-import-picker-title = Impor filter kustom
waterfox-blocker-custom-filters-export-picker-title = Ekspor filter kustom
waterfox-blocker-custom-filters-import-replace-title = Ganti filter saat ini?
waterfox-blocker-custom-filters-import-replace-message = Mengimpor akan mengganti semua konten yang saat ini ada di editor.
