restart-prompt-title = Reiniciar o { -brand-short-name }
restart-prompt-question = Tem certeza que deseja reiniciar o { -brand-short-name }?
appmenuitem-restart-browser =
    .label = Reiniciar
copy-url =
    .label = Copiar Link da Guia
copy-all-urls =
    .label = Copiar Todos os Links da Guia
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = Abrir Tudo em Abas Privadas
open-all-links-private =
    .label = Abrir Todos os Links em Abas Privadas
open-private-tab =
    .label = Abrir em uma Nova Aba Privada
new-private-tab =
    .label = Nova aba privada
    .tooltiptext = Abrir uma nova aba privada
open-link-private =
    .label = Abrir Link em Nova Aba Privada
status-bar =
    .label = Barra de status
tab-position-header = Posição da barra
tab-bar-top-above =
    .label = Acima da barra de endereços
tab-bar-top-below =
    .label = Barra de endereços superior abaixo
tab-bar-bottom-above =
    .label = Inferior acima da barra de status
tab-bar-bottom-below =
    .label = Barra de status inferior
tab-additional-header = Preferências Adicionais de Abas
pinned-icon-only =
    .label = Diminuir as abas fixadas para exibir apenas o ícone do site
insert-after-current =
    .label = Inserir nova aba depois da aba atual
insert-related-after-current =
    .label = Inserir nova aba relacionada depois da aba atual
dynamic-theme-header = Temas Dinâmicos
dynamic-theme-dark =
    .label = Forçar o Modo Escuro
dynamic-theme-light =
    .label = Forçar Modo Claro
dynamic-theme-auto =
    .label = Definir dinamicamente Modo Luz/Escuro
restart-header = Reiniciar Item de Menu
restart-show-button =
    .label = Mostrar botão reiniciar na interface do usuário
restart-purge-cache =
    .label = Limpar cache de reinicialização rápida ao reiniciar o navegador
restart-require-confirmation =
    .label = Exigir confirmação de reinicialização
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = Mostrar copiar item de menu de guia de url
enable-copy-active-tab =
    .label = Copiar URL apenas da aba ativa
show-copy-all-urls =
    .label = Mostrar copiar todas as urls do item de menu
show-unload-tab =
    .label = Mostrar descarregar item do menu de Abas
statusbar-enabled =
    .label = Mostrar barra de status
statusbar-show-links =
    .label = Mostrar links
statusbar-contrast-text =
    .label = Cor do texto na barra de status
bookmarks-bar-position-header = Posição na Barra de Favoritos
bookmarks-position-top =
    .label = Superior
bookmarks-position-bottom =
    .label = Inferior
geolocation-api-header = API Geolocalização
geolocation-description = Alguns sites requerem sua localização para funcionar. Se um site não estiver funcionando como resultado de não ser capaz de encontrar sua localização, por favor, ative esta preferência e tente novamente.
geolocation-api-enabled =
    .label = Habilitado
geolocation-api-disabled =
    .label = Desligado
send-referrer-header-0 =
    .label = Nunca enviar o cabeçalho referrer
send-referrer-header-1 =
    .label = Enviar o cabeçalho de referência apenas ao clicar nos links e elementos similares
send-referrer-header-2 =
    .label = Enviar cabeçalho de referência em todas as solicitações (Padrão)
enable-webrtc-p2p =
    .label = Ativar conexão de pares WebRTC
load-images =
    .label = Carregar imagens automaticamente
enable-javascript =
    .label = Ativar JavaScript
webrtc-header = Conexão de pares WebRTC
ref-header = Cabeçalho de Referência HTTP
statusbar-header = Barra de status
private-tab =
    .label =
        { $isPrivate ->
            [true] Sair da aba privada
           *[false] Fazer Aba Privada
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
waterfox-defaults =
    .label = Waterfox Defaults
preset-title = Presets
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
auto-hide-sidebar =
    .label = Auto Hide Sidebar
drag-space =
    .label = Enable Fixed Drag Space
square-checkbox =
    .label = Square Checkbox
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font =
    .label = Enable monospaced font for page
monospace-font-theme =
    .label = Enable monospaced font for theme
panels-header = Panels
media-player-header = Media Player
onboarding-grassroots-title = Supporting the grassroots
auto-hide-back =
    .label = Auto Hide Back Button
square-button-edges =
    .label = Square Button Corners
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
auto-hide-forward =
    .label = Auto Hide Forward Button
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
