restart-prompt-title = { -brand-short-name } を再起動
restart-prompt-question = { -brand-short-name } を再起動してもよろしいですか？
appmenuitem-restart-browser =
    .label = 再起動
copy-url =
    .label = タブのリンクをコピー
copy-all-urls =
    .label = すべてのタブのリンクをコピー
unload-tab =
    .label = タブをアンロード
open-all-private =
    .label = すべてのタブをプライベートで開く
open-all-links-private =
    .label = すべてのタブをプライベートで開く
open-private-tab =
    .label = 新しいプライベートタブで開く
new-private-tab =
    .label = 新しいプライベートタブ
    .tooltiptext = 新しいプライベートタブを開く
open-link-private =
    .label = リンクを新しいプライベートタブで開く
status-bar =
    .label = ステータスバー
tab-position-header = タブバーの位置
tab-bar-top-above =
    .label = アドレスバーの上
tab-bar-top-below =
    .label = アドレスバーの下
tab-bar-bottom-above =
    .label = ステータスバー上
tab-bar-bottom-below =
    .label = ステータスバーの下
tab-additional-header = タブの追加設定
pinned-icon-only =
    .label = ピン留めされたタブを縮小してサイトアイコンだけを表示する
insert-after-current =
    .label = 現在のタブの後ろに新しいタブを挿入
insert-related-after-current =
    .label = 現在のタブの後に関連する新しいタブを挿入
dynamic-theme-header = システムテーマのデザイン設定
dynamic-theme-dark =
    .label = ダークモードを強制
dynamic-theme-light =
    .label = ライトモードを強制
dynamic-theme-auto =
    .label = 自動的にライト/ダークモードを設定する
restart-header = メニューアイテムの再起動の項目
restart-show-button =
    .label = パネルUIに再起動ボタンを表示する
restart-purge-cache =
    .label = ブラウザ再起動時に起動時キャッシュ（高速起動のための一時的なファイル）をクリアする
restart-require-confirmation =
    .label = 再起動時に確認する
tab-feature-header = タブのコンテキスト メニュー
show-duplicate-tab =
    .label = 重複しているタブのメニュー項目を表示する
show-copy-url =
    .label = コピーしたタブの URL メニュー項目を表示する
enable-copy-active-tab =
    .label = アクティブなタブからのみURLをコピー
show-copy-all-urls =
    .label = すべてのタブの URL のコピーボタンをメニューアイテムに表示する
show-unload-tab =
    .label = タブのアンロードボタンをメニューアイテムに表示する
statusbar-enabled =
    .label = ステータスバーを表示
statusbar-show-links =
    .label = リンクを表示
statusbar-contrast-text =
    .label = コントラストステータスバーの文字色
bookmarks-bar-position-header = ブックマークツールバーの位置
bookmarks-position-top =
    .label = 上部
bookmarks-position-bottom =
    .label = 下部
geolocation-api-header = ジオロケーションAPI
geolocation-description = 一部のウェブサイトは動作するためにあなたの位置情報を必要とします。 位置情報を使用することができないために、ウェブサイトが動作しない場合は、この設定を有効にして、もう一度お試しください。
geolocation-api-enabled =
    .label = 有効
geolocation-api-disabled =
    .label = 無効
send-referrer-header-0 =
    .label = リファラーヘッダーを送信しない
send-referrer-header-1 =
    .label = リンクや類似の要素をクリックしたときにのみリファラーヘッダーを送信します
send-referrer-header-2 =
    .label = すべてのリクエストにリファラーヘッダーを送信する (デフォルト)
enable-webrtc-p2p =
    .label = WebRTCピア接続を有効にする
load-images =
    .label = 画像を自動的に読み込む
enable-javascript =
    .label = JavaScript を有効にする
webrtc-header = WebRTC ピア接続
ref-header = HTTP リファラヘッダー
statusbar-header = ステータスバー
private-tab =
    .label =
        { $isPrivate ->
            [true] プライベートタブを終了する
           *[false] 新しいプライベートタブを作成
        }
disable-sidebar-animate =
    .label = Disable sidebar panel animation
enable-menu-transparency =
    .label = Enable menu transparency
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-back =
    .label = Auto Hide Back Button
auto-hide-sidebar =
    .label = Auto Hide Sidebar
auto-hide-forward =
    .label = Auto Hide Forward Button
auto-blur-tabs =
    .label = Auto Blur Tabs
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-button-edges =
    .label = Square Button Corners
show-mac-menu-icons =
    .label = Show Mac Menu Icons
hide-tab-icons =
    .label = タッブのアイコンを消える
hide-all-icons =
    .label = すべてのアイコンを消える
center-tab-label =
    .label = Center Tab Label Only
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
waterfox-defaults =
    .label = Waterfox Defaults
panels-header = パネル
drag-space =
    .label = Enable Fixed Drag Space
onboarding-grassroots-title = Supporting the grassroots
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
media-player-header = メディアプレイヤー
monospace-font =
    .label = Enable monospaced font for page
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
telemetry-privacy-policy = Privacy Policy
square-menu-item =
    .label = Square Context Menu Item Corners
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
compact-context-menu =
    .label = Reduce Context Menu Padding
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
tab-bar-header = Tab Bar
full-screen-header = Full screen
square-checkbox =
    .label = Square Checkbox
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
monospace-font-theme =
    .label = Enable monospaced font for theme
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
enable-dooh =
    .label = Use DNS over Oblivious HTTP
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = サイドバー
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = プリセット
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = アイコン
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
tab-context-line =
    .label = Tab Context Line
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
