restart-prompt-title = { -brand-short-name } を再起動
restart-prompt-question = { -brand-short-name } を再起動してもよろしいですか？
appmenuitem-restart-browser =
    .label = 再起動
copy-url =
    .label = タブのリンクをコピー
copy-all-urls =
    .label = すべてのタブのリンクをコピー
unload-tab =
    .label = タブをアンロード
open-all-private =
    .label = すべてのタブをプライベートで開く
open-all-links-private =
    .label = すべてのタブをプライベートで開く
open-private-tab =
    .label = 新しいプライベートタブで開く
new-private-tab =
    .label = 新しいプライベートタブ
    .tooltiptext = 新しいプライベートタブを開く
open-link-private =
    .label = リンクを新しいプライベートタブで開く
status-bar =
    .label = ステータスバー
tab-position-header = タブバーの位置
tab-bar-top-above =
    .label = アドレスバーの上
tab-bar-top-below =
    .label = アドレスバーの下
tab-bar-bottom-above =
    .label = ステータスバー上
tab-bar-bottom-below =
    .label = ステータスバーの下
tab-additional-header = タブの追加設定
pinned-icon-only =
    .label = ピン留めされたタブを縮小してサイトアイコンだけを表示する
insert-after-current =
    .label = 現在のタブの後ろに新しいタブを挿入
insert-related-after-current  =
    .label = 現在のタブの後に関連する新しいタブを挿入
dynamic-theme-header = システムテーマのデザイン設定
dynamic-theme-dark =
    .label = ダークモードを強制
dynamic-theme-light =
    .label = ライトモードを強制
dynamic-theme-auto =
    .label = 自動的にライト/ダークモードを設定する
restart-header = メニューアイテムの再起動の項目
restart-show-button =
    .label = パネルUIに再起動ボタンを表示する
restart-purge-cache =
    .label = ブラウザ再起動時に起動時キャッシュ（高速起動のための一時的なファイル）をクリアする
restart-require-confirmation =
    .label = 再起動時に確認する
tab-feature-header = タブのコンテキスト メニュー
show-duplicate-tab =
    .label = 重複しているタブのメニュー項目を表示する
show-copy-url =
    .label = コピーしたタブの URL メニュー項目を表示する
enable-copy-active-tab =
    .label = アクティブなタブからのみURLをコピー
show-copy-all-urls =
    .label = すべてのタブの URL のコピーボタンをメニューアイテムに表示する
show-unload-tab =
    .label = タブのアンロードボタンをメニューアイテムに表示する
statusbar-enabled =
    .label = ステータスバーを表示
statusbar-show-links =
    .label = リンクを表示
statusbar-contrast-text =
    .label = コントラストステータスバーの文字色

bookmarks-bar-position-header = ブックマークツールバーの位置
bookmarks-position-top =
    .label = 上部
bookmarks-position-bottom =
    .label = 下部
geolocation-api-header = ジオロケーションAPI
geolocation-description = 一部のウェブサイトは動作するためにあなたの位置情報を必要とします。 位置情報を使用することができないために、ウェブサイトが動作しない場合は、この設定を有効にして、もう一度お試しください。
geolocation-api-enabled =
    .label = 有効
geolocation-api-disabled =
    .label = 無効
send-referrer-header-0 =
    .label = リファラーヘッダーを送信しない
send-referrer-header-1 =
    .label = リンクや類似の要素をクリックしたときにのみリファラーヘッダーを送信します
send-referrer-header-2 =
    .label = すべてのリクエストにリファラーヘッダーを送信する (デフォルト)
enable-webrtc-p2p =
    .label = WebRTCピア接続を有効にする
load-images =
    .label = 画像を自動的に読み込む
enable-javascript =
    .label = JavaScript を有効にする
webrtc-header = WebRTC ピア接続
ref-header = HTTP リファラヘッダー
update-updateCheckDisabled =
    .label = アップデートの確認は現在無効になっています
statusbar-header = ステータスバー
private-tab =
    .label =
        { $isPrivate ->
            [true] プライベートタブを終了する
            *[false] 新しいプライベートタブを作成
        }

## Tree Vertical Tabs

sidebar-tree-vertical-tabs =
    .label = ツリー垂直タブ
browser-layout-tree-vertical-tabs =
    .label = ツリー垂直タブ
pane-tree-title = ツリー垂直タブ
category-tree =
    .tooltiptext = { pane-tree-title }
tree-header = ツリー垂直タブ
tree-appearance-header = タブの外観
tree-faviconize-pinned-tabs =
    .label = ピン留めされたタブはアイコンのみ表示する
    .accesskey = S
tree-auto-sticky-header = 以下のタブが画面外にスクロールアウトしたときにタブバーの端に貼り付ける
tree-sticky-active-tab =
    .label = 現在のタブ
    .accesskey = K
tree-sticky-sound-playing-tab =
    .label = 音声を再生中のタブ
    .accesskey = Y
tree-sticky-sharing-tab =
    .label = カメラ/マイク/画面を共有中のタブ
    .accesskey = G
tree-behavior-header = タブのツリー表示
tree-auto-collapse-expand-subtree-on-attach =
    .label = 新しいツリーが作られた時は、自動的に他のツリーを折りたたむ
    .accesskey = C
tree-auto-collapse-expand-subtree-on-select =
    .label = タブを切り替えた時は、フォーカスされたタブのツリーを自動的に展開して、他のツリーを折りたたむ
    .accesskey = X
tree-tree-double-click-behavior-caption =
    .value = タブのダブルクリック
    .accesskey = D
tree-tree-double-click-behavior-toggle-collapsed =
    .label = ツリーを開閉する
tree-tree-double-click-behavior-toggle-sticky =
    .label = タブバー端に貼り付ける/貼り付けを解除
tree-tree-double-click-behavior-toggle-close =
    .label = タブを閉じる
tree-tree-double-click-behavior-toggle-none =
    .label = 何もしない
tree-successor-tab-control-level-caption =
    .value = 現在のタブが最後の子タブだった時に、現在のタブを閉じた後は
    .accesskey = H
tree-successor-tab-control-level-in-tree =
    .label = ツリー内の1つ前のタブにフォーカスを移す
tree-successor-tab-control-level-simulate-default =
    .label = 次のタブにフォーカスを移す
tree-successor-tab-control-level-never =
    .label = フォーカスを制御しない（ブラウザーまたは他の拡張機能による制御を尊重）
tree-drop-links-on-tab-behavior-caption =
    .value = タブにリンクやURL文字列をドロップしたとき
    .accesskey = L
tree-drop-links-on-tab-behavior-ask =
    .label = どうするか常に訊ねる
tree-drop-links-on-tab-behavior-load =
    .label = そのタブに読み込む
tree-drop-links-on-tab-behavior-newtab =
    .label = 新しい子タブで開く
tree-auto-attach-header = タブのツリーの自動形成
tree-auto-attach-no-control =
    .label = （制御せず既定の位置に開く）
tree-auto-attach-independent =
    .label = 独立したタブとして開く
tree-auto-attach-child-top =
    .label = 現在のタブの最初の子として開く
tree-auto-attach-child-end =
    .label = 現在のタブの最後の子として開く
tree-auto-attach-child-next-to-last-related-tab =
    .label = 親のタブの子として、直近に開いた子タブの隣に開く
tree-auto-attach-sibling =
    .label = 現在のタブと同階層に開く
tree-auto-attach-next-sibling =
    .label = 現在のタブと同階層で隣に開く
tree-auto-attach-on-opened-with-owner-caption =
    .value = 既存のタブからタブが開かれた場合、
    .accesskey = D
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = ピン留めされたタブから（最上位のタブとして表れる）新しい子タブを開く位置
    .accesskey = P
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = 制御しない（ブラウザーや他の拡張機能の判断に任せる）
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = 直近に開いた子タブの隣、もしくは親タブの近く
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = ツリーの先頭（親タブの近く）
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = ツリーの末尾
tree-auto-attach-on-new-tab-command-caption =
    .value = 新しい空のタブを
    .accesskey = N
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = 中クリックした時、新しい空のタブを
    .accesskey = M
tree-auto-attach-on-duplicated-caption =
    .value = 複製されたタブを
    .accesskey = U
tree-auto-attach-same-site-orphan-caption =
    .value = アドレスバー、ブックマーク、履歴、およびその他のきっかけから開かれた、現在のタブと同じWebサイトのタブ
    .accesskey = W
tree-auto-attach-on-opened-from-external-caption =
    .value = 他のアプリケーションから開かれたタブ
    .accesskey = A
tree-auto-attach-on-any-other-trigger-caption =
    .value = それ以外の契機で開かれたタブ
    .accesskey = T
