# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = 动态主题
dynamic-theme-dark =
    .label = 强制暗色模式
dynamic-theme-light =
    .label = 强制光线模式
dynamic-theme-auto =
    .label = 动态设置灯光/暗色模式
pane-theme-title = 外观
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = 动画
appearance-header = 外观
autohide-hidden-header = 自动影响
bookmark-header = 书签栏
center-header = 中心
font-header = 字体
full-screen-header = 全屏
icons-header = 图标
interface-component-header = 组件接口
media-player-header = 媒体播放器
nav-bar-header = 导航条
panels-header = 面板
rounding-header = 圆角
sidebar-header = 侧栏
tab-bar-header = 菜单
theme-header = 主题
preset-title = 默认值
lepton-style =
    .label = Lepton 风格
proton-style =
    .label = Proton 风格
waterfox-defaults =
    .label = Waterfox 默认
auto-blur-tabs =
    .label = 标签自动模糊
auto-hide-back =
    .label = 自动隐藏后退按钮
auto-hide-bookmarkbar =
    .label = 自动隐藏书签栏
auto-hide-forward =
    .label = 自动隐藏前进按钮
auto-hide-navbar =
    .label = 自动隐藏导航栏
auto-hide-pageaction =
    .label = 自动隐藏页面操作
auto-hide-sidebar =
    .label = 自动隐藏侧栏
auto-hide-tabbar =
    .label = 自动隐藏标签栏
auto-hide-tabs =
    .label = 自动隐藏标签页
center-navbar-text =
    .label = 使导航栏文字居中
center-tab-content =
    .label = 使页面内容居中
hide-all-icons =
    .label = 隐藏所有图标
hide-bookmarkbar-icon =
    .label = 隐藏书签栏图标
hide-bookmarkbar-label =
    .label = 隐藏书签栏标签
hide-disabled-menuitems =
    .label = 隐藏禁用的菜单项
hide-sidebar-header =
    .label = 隐藏侧栏标题
hide-tab-icons =
    .label = 隐藏标签页图标
hide-urlbar-iconbox =
    .label = 隐藏地址栏图标框
monospace-font =
    .label = 对页面启用等宽字体
monospace-font-theme =
    .label = 对主题启用等宽字体
show-mac-menu-icons =
    .label = 显示 Mac 菜单图标
show-menu-icons =
    .label = 显示菜单图标
square-button-edges =
    .label = 方块按钮边角
square-checkbox =
    .label = 方形复选框
square-field =
    .label = 方形条目字段边角
center-tab-label =
    .label = 仅居中标签页标签
close-button-hover =
    .label = 在打开多个标签页时当悬停于选定标签页时显示关闭标签页按钮
enable-menu-transparency =
    .label = 启用菜单透明
enable-panel-transparency =
    .label = 启用面板透明化
enable-waterfox-theme-0 =
    .label = 在所有主题上启用 Waterfox 主题定制
enable-waterfox-theme-1 =
    .label = 在 Waterfox 主题上启用 Waterfox 主题定制
enable-waterfox-theme-2 =
    .label = 禁用 Waterfox 主题定制
full-panel-strip =
    .label = 全宽应用菜单分隔符
remove-panel-strip =
    .label = 移除彩色应用菜单分隔符
square-menu-item =
    .label = 方形上下文菜单项边角
square-menu-panel =
    .label = 方形应用菜单面板边角
square-menu-popup =
    .label = 方形上下文菜单边角
square-panel-item =
    .label = 方形应用菜单项边角
square-tab-edges =
    .label = 方形标签页边角
tab-context-line =
    .label = 标签页上下文行
compact-bookmark-menu =
    .label = 缩小书签菜单间距
compact-context-menu =
    .label = 缩小右键菜单间距
compact-navbar-popup =
    .label = 缩小导航栏弹出菜单间距
compact-panel-header =
    .label = 缩小面板标题栏间距
disable-panel-animate =
    .label = 关闭应用菜单面板动画效果
disable-sidebar-animate =
    .label = 关闭侧边栏面板动画效果
drag-space =
    .label = 启用固定拖动区域
enable-cyan-accent-color =
    .label = 青色主题强调色
enable-default-accent-color =
    .label = 默认主题强调色
enable-system-accent-color =
    .label = 跟随系统强调色
waterfox-appearance-statusbar-heading =
    .label = 状态栏
waterfox-appearance-theme-color-picker =
    .label = 主题配色
waterfox-appearance-theme-mode-option-system =
    .label = 系统主题
waterfox-appearance-theme-mode-option-light =
    .label = 亮色模式
waterfox-density-touch =
    .label = 触摸
waterfox-appearance-theme-color-option-sun =
    .label = 太阳
waterfox-appearance-theme-color-option-default =
    .label = 默认
waterfox-appearance-theme-mode-picker =
    .label = 主题模式
waterfox-density-compact =
    .label = 紧凑
waterfox-density-normal =
    .label = 正常
waterfox-appearance-statusbar-enabled-toggle =
    .label = 显示状态栏
    .description = 在窗口底部显示工具栏。
waterfox-appearance-statusbar-links-toggle =
    .label = 在状态栏上预览链接的目标网址
waterfox-appearance-chrome-sheet-off =
    .label = 关
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = 更现代的浏览器原生样式。
waterfox-appearance-theme-colors-group =
    .label = 色彩方案
    .description = 选择Waterfox色彩方案，以及是否跟随系统改变主题。
waterfox-appearance-browser-style-group =
    .label = 浏览器样式
    .description = 选择Waterfox的整体外观。
waterfox-appearance-interface-customizations-group =
    .label = 界面自定义
    .description = 针对标签页、工具栏、图标和内容的额外控制项。
waterfox-appearance-chrome-sheet =
    .label = 加载界面自定义项
    .description = 关闭选项以卸载Waterfox界面样式，并隐藏其控制的选项。
waterfox-appearance-chrome-sheet-built-in-themes =
    .label = 内置主题
waterfox-appearance-chrome-sheet-all-themes =
    .label = 所有主题
waterfox-appearance-theme-mode-option-dark =
    .label = 暗色模式
waterfox-appearance-details-group =
    .label = 更多外观选项
    .description = 微调Waterfox界面。
waterfox-appearance-transparent-toggle =
    .label = 透明面板与菜单
waterfox-appearance-autohide-tabbar-toggle =
    .label = 隐藏标签页栏，点击后显示
waterfox-appearance-autohide-bookmarks-toggle =
    .label = 隐藏书签栏，点击后显示
waterfox-appearance-autohide-sidebar-toggle =
    .label = 隐藏侧边栏，点击后显示
waterfox-appearance-close-button-hover-toggle =
    .label = 只在鼠标移至标签页上方时才显示关闭按钮
waterfox-appearance-drag-space-toggle =
    .label = 在标签页上方保留拖动空间
waterfox-opt-tabbar-heading =
    .label = 标签页栏
    .description = 放置标签页的条状区域的尺寸、空间和可见性。
waterfox-opt-tabbar-fill-width =
    .label = 拉伸标签页来填充宽度
waterfox-opt-tab-prevent-audio-widening =
    .label = 避免在加宽的水平标签页里显示音频指示器
waterfox-opt-tabbar-as-titlebar =
    .label = 只在标题栏里显示当前标签页
waterfox-opt-hidden-tabbar =
    .label = 隐藏标签页栏
waterfox-opt-hidden-titlebar-container =
    .label = 隐藏标题栏容器
waterfox-opt-autohide-tab =
    .label = 缩小后台标签页，点击后还原
waterfox-opt-autohide-tab-opacity =
    .label = 同时淡出后台标签页
waterfox-opt-autohide-tab-blur =
    .label = 同时模糊后台标签页
waterfox-opt-padding-tabbar-width =
    .label = 缩窄标签栏
waterfox-opt-padding-tabbar-height =
    .label = 缩短标签栏
waterfox-opt-padding-first-tab =
    .label = 在首个标签页前保留空隙
waterfox-opt-padding-first-tab-always =
    .label = 最大化后仍保留空隙
waterfox-opt-padding-drag-space =
    .label = 在标签页上方保留拖动空间
waterfox-opt-padding-drag-space-maximized =
    .label = 最大化后仍保留空间
waterfox-opt-centered-tab =
    .label = 居中标签页内容
waterfox-opt-centered-tab-label =
    .label = 仅居中标签页标题
waterfox-opt-counter-tab =
    .label = 显示标签页数量
