# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

waterfox-blocker-header = 广告拦截
waterfox-blocker-intro-description = 拦截广告、跟踪脚本和其他不必要的请求，以加快页面加载速度并减少干扰。
waterfox-blocker-setting-on =
    .label = 开启
waterfox-blocker-setting-on-description = Waterfox 拦截了以下内容：
waterfox-blocker-setting-off =
    .label = 关闭
waterfox-blocker-setting-off-description = Waterfox 不拦截任何广告或跟踪器。第三方扩展仍可独立拦截内容。
waterfox-blocker-dropdown-label =
    .value = 搜索合作伙伴广告：
waterfox-blocker-dropdown-option-partner-exception =
    .label = 允许 Waterfox 搜索合作伙伴的广告
waterfox-blocker-dropdown-option-block-everything =
    .label = 禁止 Waterfox 搜索合作伙伴的广告
waterfox-blocker-manage-filter-lists =
    .label = 管理过滤器列表…
waterfox-blocker-filter-lists-window =
    .title = 广告拦截过滤列表
waterfox-blocker-filter-lists-dialog =
    .buttonlabelaccept = 保存更改
    .buttonaccesskeyaccept = S
waterfox-blocker-filter-lists-description =
    .value = 选择要启用的过滤列表。
waterfox-blocker-filter-lists-active-count =
    .value = { $activeCount } / { $totalCount } 已启用
waterfox-blocker-filter-lists-column-enabled =
    .label = 已启用
waterfox-blocker-filter-lists-column-name =
    .label = 过滤器列表
waterfox-blocker-filter-lists-column-category =
    .label = 类别
waterfox-blocker-filter-lists-enable =
    .label = 启用
waterfox-blocker-filter-lists-disable =
    .label = 关闭
waterfox-blocker-extension-detected = Waterfox 现已内置广告拦截功能。您可以在设置中查看您的配置。
waterfox-blocker-extension-detected-learn-more =
    .label = 了解更多
waterfox-blocker-extension-detected-dismiss =
    .label = 不再显示
waterfox-blocker-extension-install-warning = Waterfox 已内置广告拦截器。同时运行两个广告拦截器可能导致页面出错或加载缓慢。
waterfox-blocker-extension-install-got-it =
    .label = 知道了
waterfox-blocker-extension-install-learn-more =
    .label = 了解更多
waterfox-blocker-third-party-notice-description = { $extensionName } 也在拦截广告。同时运行两个广告拦截器可能会引发问题。
waterfox-blocker-filter-lists-category-core = 默认
waterfox-blocker-filter-lists-category-annoyances = 干扰元素
waterfox-blocker-filter-lists-category-optional = 可选
waterfox-blocker-filter-lists-category-regional = 特定语言
waterfox-blocker-filter-lists-empty-state = 没有可用的过滤列表。
waterfox-blocker-extension-fallback-name-this = 此扩展
waterfox-blocker-extension-fallback-name-your = 您的扩展
waterfox-blocker-spotlight-title = Waterfox 现已包含广告拦截功能
waterfox-blocker-spotlight-subtitle = 我们注意到您安装了 { $extensionName }。Waterfox 现已内置广告拦截器。使用内置拦截器有助于支持 Waterfox，但最终由您决定。
waterfox-blocker-spotlight-primary-button = 保留我当前的设置
waterfox-blocker-spotlight-secondary-button = 查看设置
waterfox-blocker-prompt-title = Waterfox 广告拦截
waterfox-blocker-reenable-conflict-message = 同时运行 Waterfox 广告拦截和"{ $extensionName }"可能导致页面出错。您想保留哪一个？
waterfox-blocker-filter-lists-category-privacy = 隐私
waterfox-blocker-reenable-use-built-in = 使用内置拦截器
waterfox-blocker-reenable-keep-extension = 保留扩展拦截器
waterfox-blocker-extension-install-manage-settings = 您可以在"设置 > 隐私与安全"中管理广告拦截。
waterfox-blocker-extension-install-anyway = 仍然安装
waterfox-blocker-extension-install-keep-built-in = 继续使用内置拦截器
waterfox-blocked-page-title = Waterfox 拦截了此页面
waterfox-blocked-page-heading = Waterfox 拦截了此页面
waterfox-blocked-page-description = 此页面被广告拦截过滤规则拦截。
waterfox-blocked-page-details =
    .aria-label = 已拦截页面详情
waterfox-blocked-page-blocked-url-label = 已拦截的网址
waterfox-blocked-page-matched-rule-label = 匹配规则
waterfox-blocked-page-unavailable = 不可用
waterfox-blocked-page-hint = "仍然加载"将在此会话期间临时允许该网站。
waterfox-blocked-page-go-back = 返回
waterfox-blocked-page-load-anyway = 仍然加载
waterfox-blocker-toolbar-button =
    .label = 广告拦截
    .tooltiptext = 广告拦截
waterfox-blocker-panel-not-available = 此页面不可用
waterfox-blocker-panel-toggle =
    .label = 此网站的广告拦截
    .description = 拦截此网站上的广告和跟踪器。
waterfox-blocker-panel-disabled = 广告拦截已关闭
waterfox-blocker-panel-site-excepted = 允许此网站显示广告
waterfox-blocker-panel-partner-allowed = 允许搜索合作伙伴显示广告
waterfox-blocker-stats =
    { $count ->
        [one] 已在此网站拦截 { $count } 个广告
       *[other] 已在此网站拦截 { $count } 个广告
    }
waterfox-blocker-panel-settings-button = 广告拦截设置
waterfox-blocker-show-badge-pref =
    .label = 在工具栏按钮上显示已拦截数量
waterfox-blocker-setting-on-summary = 拦截广告和跟踪器，对页面加载影响最小。
waterfox-blocker-blocks-ads = 广告和广告网络请求
waterfox-blocker-blocks-tracking = 跟踪脚本和像素
waterfox-blocker-blocks-annoyances = 干扰弹窗和覆盖层（启用干扰元素列表后）
waterfox-blocker-partner-funding-title = 支持 Waterfox 的开发
waterfox-blocker-partner-funding-description = Waterfox 是免费、开源且独立的浏览器。允许搜索合作伙伴页面上的广告是 Waterfox 为开发和基础设施提供资金的方式。您可以随时关闭此功能，但保持开启是支持该项目的最简单方式。
waterfox-blocker-custom-filter-lists =
    .label = 自定义过滤列表…
permissions-exceptions-waterfox-blocker-window2 =
    .title = 广告拦截例外
    .style = { permissions-window2.style }
permissions-exceptions-manage-waterfox-blocker-desc = 您可以指定哪些网站关闭广告拦截。输入要管理的网站的确切地址，然后点击添加例外。
waterfox-blocker-filter-lists-search =
    .placeholder = 搜索过滤列表…
waterfox-blocker-filter-lists-refresh-now =
    .label = 立即刷新
waterfox-blocker-filter-lists-last-updated = 更新于 { $date }
waterfox-blocker-filter-lists-never-updated =
    .value = 尚未更新
waterfox-blocker-filter-lists-next-refresh =
    .value = 下次刷新时间：{ $date }
waterfox-blocker-filter-lists-next-refresh-unknown =
    .value = 下次刷新时间：未知
waterfox-blocker-custom-filter-lists-window =
    .title = 自定义过滤列表
waterfox-blocker-custom-filter-lists-dialog =
    .buttonlabelaccept = 保存更改
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filter-lists-description = 添加自定义过滤列表的网址。这些列表将被获取并与内置过滤器一起应用。
waterfox-blocker-filter-lists-custom-heading =
    .value = 自定义过滤列表
waterfox-blocker-filter-lists-custom-input =
    .placeholder = 输入过滤列表网址…
waterfox-blocker-filter-lists-custom-url-label =
    .value = 过滤列表网址
waterfox-blocker-filter-lists-custom-col =
    .label = 网址
waterfox-blocker-filter-lists-custom-add =
    .label = 添加
waterfox-blocker-filter-lists-custom-remove =
    .label = 删除
waterfox-blocker-filter-lists-custom-remove-all =
    .label = 删除所有
waterfox-blocker-filter-lists-custom-empty =
    .value = 未添加自定义过滤列表。
waterfox-blocker-custom-filters =
    .label = 我的过滤器…
waterfox-blocker-custom-filters-window =
    .title = 我的过滤器
waterfox-blocker-custom-filters-dialog =
    .buttonlabelaccept = 保存修改
    .buttonaccesskeyaccept = S
waterfox-blocker-custom-filters-description = 添加您自己的广告拦截规则。这些规则使用标准的 uBlock Origin 过滤语法，并与您已启用的过滤列表一起应用。
waterfox-blocker-custom-filters-empty =
    .value = 没有自定义过滤器。
waterfox-blocker-custom-filters-status =
    { $count ->
        [0] 没有自定义过滤器。
        [one] 1 条自定义过滤器。
       *[other] { $count } 条自定义过滤器。
    }
waterfox-blocker-custom-filters-status-unsaved = 有未保存的更改。
waterfox-blocker-custom-filters-import =
    .label = 导入…
waterfox-blocker-custom-filters-export =
    .label = 导出…
waterfox-blocker-custom-filters-load-error-title = 加载失败
waterfox-blocker-custom-filters-load-error = 无法加载自定义过滤器。
waterfox-blocker-custom-filters-save-error-title = 保存失败
waterfox-blocker-custom-filters-save-error = 无法保存自定义过滤器。
waterfox-blocker-custom-filters-import-error-title = 导入失败
waterfox-blocker-custom-filters-import-error = 无法导入所选文件。
waterfox-blocker-custom-filters-export-error-title = 导出失败
waterfox-blocker-custom-filters-export-error = 无法导出自定义过滤器。
waterfox-blocker-custom-filters-import-picker-title = 导入自定义过滤器
waterfox-blocker-custom-filters-export-picker-title = 导出自定义过滤器
waterfox-blocker-custom-filters-import-replace-title = 是否替换当前过滤器？
waterfox-blocker-custom-filters-import-replace-message = 导入将替换编辑器中的所有当前内容。
waterfox-blocker-panel-hero-count = 已拦截{ $count }个
waterfox-blocker-panel-hero-paused = 已暂停拦截
waterfox-blocker-panel-hero-subtitle = 位于{ $host }
waterfox-blocker-panel-category-ads = 广告
waterfox-blocker-panel-category-trackers = 跟踪器
waterfox-blocker-panel-category-popups = 弹窗
waterfox-blocker-panel-see-all = 查看所有拦截的内容
waterfox-blocker-panel-toggle2 =
    .label = 拦截此网站的广告
waterfox-blocker-panel-paused-card = 此网站在您的放行名单内。广告、弹窗与跟踪器可以加载，直到您开启拦截为止。
waterfox-blocker-panel-allowlist = 管理放行名单
waterfox-blocker-panel-allowlist-count =
    { $count ->
        [one] { $count } 个网站
       *[other] { $count } 个网站
    }
waterfox-blocker-panel-footer-settings = 设置
waterfox-blocker-panel-back =
    .aria-label = 返回
waterfox-blocker-panel-detail-title = 对此页面进行拦截
waterfox-blocker-panel-detail-section-ads = 广告
waterfox-blocker-panel-detail-section-trackers = 跟踪器
waterfox-blocker-panel-detail-section-popups = 弹窗
waterfox-blocker-panel-detail-popup-note =
    { $count ->
        [one] { $count } 个弹窗已被自动拦截。
       *[other] { $count } 个弹窗已被自动拦截。
    }
waterfox-blocker-panel-allow-domain = 允许
    .aria-label = 允许{ $domain }
waterfox-blocker-panel-domain-count = { $count }个
pane-waterfox-blocker-title = 广告拦截
    .title = { pane-waterfox-blocker-title }
waterfox-blocker-pane-header =
    .heading = 广告拦截
waterfox-blocker-group =
    .label = 广告拦截
    .description = 拦截广告、跟踪器脚本以及其他无用请求，已加快页面加载并减少造成分心。
waterfox-blocker-enabled-toggle =
    .label = 拦截广告与跟踪器
    .description = 感觉对页面加载造成轻度影响的广告与跟踪器。
waterfox-blocker-extension-notice =
    .message = { $extensionName }也在拦截广告。运行两个广告拦截器可能会造成问题。
waterfox-blocker-partner-select =
    .label = 搜索引擎合作伙伴广告
    .description = Waterfox属于自由、开源、独立的项目。允许展示搜索引擎合作伙伴页面的广告属于Waterfox开发和基础设施的资助方式。您可以随时关闭这个选项，但是最容易支持此项目的方法是保持这个选项打开。
waterfox-blocker-lists-group =
    .label = 过滤列表
waterfox-blocker-manage-lists-button =
    .label = 管理过滤列表
waterfox-blocker-custom-lists-button =
    .label = 自定义过滤列表
waterfox-blocker-my-filters-button =
    .label = 我的过滤器
waterfox-blocker-exceptions-group =
    .label = 例外
waterfox-blocker-exceptions-button =
    .label = 管理例外列表
waterfox-blocker-panel-footer-stats = <b data-l10n-name="total">{ $count }</b> 次拦截记录 · 已节省 { $size } 流量
