# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

pane-tree-title = 树状垂直标签页
browser-layout-tree-vertical-tabs =
    .label = 树状垂直标签页
sidebar-tree-vertical-tabs =
    .label = 树状垂直标签页
tree-header = 树状垂直标签页
tree-sticky-active-tab =
    .label = 活动标签页
    .accesskey = k
tree-successor-tab-control-level-caption =
    .value = 在当前标签页作为最后的子标签页关闭时
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = 聚焦到树中的上一个标签页
tree-successor-tab-control-level-never =
    .label = 始终聚焦到下一个标签页（遵循浏览器或其它扩展的控制）
tree-successor-tab-control-level-simulate-default =
    .label = 始终聚焦到下一个标签页
tree-appearance-header = 外观
tree-faviconize-pinned-tabs =
    .label = 仅用标签页的图标显示固定的标签页
    .accesskey = S
tree-sticky-sharing-tab =
    .label = 标签页分享摄像头/麦克风/屏幕
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = 声音播放标签页
    .accesskey = y
tree-behavior-header = 标签页的树状视图
tree-auto-collapse-expand-subtree-on-attach =
    .label = 在出现新树时，自动折叠其它的
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = 当标签页获得焦点时，自动展开它所在的树并折叠其它的
    .accesskey = x
category-tree =
    .tooltiptext = { pane-tree-title }
tree-auto-sticky-header = 标签页滚动超出时吸附在标签栏边缘
tree-drop-links-on-tab-behavior-caption =
    .value = 当链接或 URL 字符串拖放到标签页上时
    .accesskey = l
tree-drop-links-on-tab-behavior-ask =
    .label = 始终询问我如何处理
tree-drop-links-on-tab-behavior-load =
    .label = 加载到标签页
tree-drop-links-on-tab-behavior-newtab =
    .label = 新建子标签页
tree-tree-double-click-behavior-caption =
    .value = 双击标签页
    .accesskey = D
tree-tree-double-click-behavior-toggle-close =
    .label = 关闭标签页
tree-tree-double-click-behavior-toggle-collapsed =
    .label = 折叠/展开标签树
tree-tree-double-click-behavior-toggle-none =
    .label = 无操作
tree-tree-double-click-behavior-toggle-sticky =
    .label = 贴靠标签栏边缘 / 取消贴靠
tree-auto-attach-header = 自动整理标签树
tree-auto-attach-child-end =
    .label = 父标签页的最后一个子标签页
tree-auto-attach-child-next-to-last-related-tab =
    .label = 父标签页的子标签页，紧邻最近打开的子标签页
tree-auto-attach-child-top =
    .label = 父标签页的第一个子标签页
tree-auto-attach-independent =
    .label = 独立标签页
tree-auto-attach-next-sibling =
    .label = 父标签页的下一个同级标签页
tree-auto-attach-no-control =
    .label = （无控制）
tree-auto-attach-sibling =
    .label = 父标签页的同级标签页
tree-auto-attach-on-any-other-trigger-caption =
    .value = 来自其他任何触发方式的标签页：打开为
    .accesskey = t
tree-auto-attach-on-duplicated-caption =
    .value = 将标签页复制为
    .accesskey = u
tree-auto-attach-on-new-tab-button-middle-click-caption =
    .value = 对于中键点击，打开新的空白标签页为
    .accesskey = m
tree-auto-attach-on-new-tab-command-caption =
    .value = 打开新的空白标签页为
    .accesskey = n
tree-auto-attach-on-opened-from-external-caption =
    .value = 来自其他应用程序的新标签页：打开为
    .accesskey = A
tree-auto-attach-on-opened-with-owner-caption =
    .value = 从现有标签页打开新标签页时，打开为
    .accesskey = D
tree-auto-attach-same-site-orphan-caption =
    .value = 从地址栏、书签、历史记录或其他位置打开与当前标签页相同网站的新标签页时：打开为
    .accesskey = w
tree-insert-new-tab-from-pinned-tab-at-caption =
    .value = 来自固定标签页的新子标签页插入位置（将显示为根标签页）
    .accesskey = p
tree-insert-new-tab-from-pinned-tab-at-end =
    .label = 树形结构的末尾
tree-insert-new-tab-from-pinned-tab-at-next-to-last-related-tab =
    .label = 紧邻最近打开的子标签页，或靠近打开源标签页
tree-insert-new-tab-from-pinned-tab-at-no-control =
    .label = 无控制（遵循浏览器或其他标签页扩展的决定）
tree-insert-new-tab-from-pinned-tab-at-top =
    .label = 树形结构的顶部（靠近打开源标签页）
waterfox-tree-disclosure-collapse = 为{ $tabTitle }折叠标签页树
waterfox-tree-disclosure-expand = 为{ $tabTitle }展开标签页树
waterfox-tab-context-reload-tree =
    .label = 重载此标签页树
waterfox-tab-context-mute-tree =
    .label = 将此标签页树静音
waterfox-tab-context-unmute-tree =
    .label = 将此标签页树取消静音
waterfox-tab-context-unload-tree =
    .label = 卸载此标签页树
waterfox-tab-context-collapse-tree =
    .label = 折叠标签页树
waterfox-tab-context-expand-tree =
    .label = 展开标签页树
waterfox-tab-context-close-tree =
    .label = 关闭标签页树
waterfox-tab-context-close-descendants =
    .label = 关闭子标签页
waterfox-tab-context-bookmark-tree =
    .label = 为标签页树添加书签…
waterfox-tab-context-copy-tree-links =
    .label = 复制标签页树为链接
waterfox-tab-context-collapse-all-trees =
    .label = 折叠所有树形标签页
waterfox-tab-context-expand-all-trees =
    .label = 展开所有树形标签页
waterfox-tabs-tree-heading =
    .label = 树形标签页
waterfox-tabs-tree-enable-toggle =
    .label = 将标签页显示为树形
    .description = 从另一个标签页打开的标签页将放在其底下，您就可以一次性折叠并移动一整组标签页。此选项同样会打开垂直标签页功能。
waterfox-tabs-tree-auto-attach-select =
    .label = 打开新标签页的方式
waterfox-tabs-tree-auto-attach-option-child =
    .label = 隐藏在打开它们的标签页之下
waterfox-tab-context-copy-descendants-links =
    .label = 复制子集为链接
waterfox-tab-context-collapse-tree-recursively =
    .label = 递归折叠标签页树
waterfox-tab-context-expand-tree-recursively =
    .label = 递归展开标签页树
waterfox-tabs-tree-auto-attach-option-root =
    .label = 各自打开
waterfox-tabs-tree-auto-attach-option-sibling =
    .label = 与打开它的标签页相邻
waterfox-tabs-tree-auto-collapse-on-select-toggle =
    .label = 选择标签页后，自动展开当前标签页分支并折叠其他分支
