restart-prompt-title = إعادة تشغيل { -brand-short-name }
restart-prompt-question = هل أنت متأكد من أنك تريد إعادة تشغيل { -brand-short-name }؟
appmenuitem-restart-browser =
    .label = إعادة التشغيل
copy-url =
    .label = نسخ رابط التبويب
copy-all-urls =
    .label = نسخ جميع روابط التبويب
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = فتح الكل في علامات التبويب الخاصة
open-all-links-private =
    .label = فتح جميع الروابط في علامات التبويب الخاصة
open-private-tab =
    .label = فتح في علامة تبويب خاصة جديدة
new-private-tab =
    .label = علامة تبويب خاصة جديدة
    .tooltiptext = فتح علامة تبويب خاصة جديدة
open-link-private =
    .label = فتح الرابط في علامة تبويب خاصة جديدة
status-bar =
    .label = شريط الحالة
tab-position-header = موقع شريط التبويب
tab-bar-top-above =
    .label = أعلى شريط العناوين أعلاه
tab-bar-top-below =
    .label = أعلى شريط العناوين أدناه
tab-bar-bottom-above =
    .label = أسفل شريط الحالة أعلاه
tab-bar-bottom-below =
    .label = أسفل شريط الحالة
tab-additional-header = تفضيلات علامة التبويب الإضافية
pinned-icon-only =
    .label = أقل علامات التبويب المثبتة لعرض رمز الموقع فقط
insert-after-current =
    .label = إدراج علامة تبويب جديدة بعد علامة التبويب الحالية
insert-related-after-current =
    .label = إدراج علامة تبويب جديدة ذات صلة بعد علامة التبويب الحالية
dynamic-theme-header = سمات ديناميكية
dynamic-theme-dark =
    .label = فرض الوضع المظلم
dynamic-theme-light =
    .label = وضع الإضاءة الإجبارية
dynamic-theme-auto =
    .label = تعيين الوضع الضوئي/الظلام بشكل ديناميكي
restart-header = إعادة تشغيل عنصر القائمة
restart-show-button =
    .label = إظهار زر إعادة التشغيل في واجهة المستخدم
restart-purge-cache =
    .label = مسح الذاكرة المؤقتة لإعادة التشغيل السريع عند إعادة تشغيل المتصفح
restart-require-confirmation =
    .label = يتطلب تأكيد إعادة التشغيل
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = إظهار عنصر رابط نسخ علامة التبويب
enable-copy-active-tab =
    .label = نسخ الرابط فقط من علامة التبويب النشطة
show-copy-all-urls =
    .label = إظهار نسخ كل عناصر قائمة عناوين علامات التبويب
show-unload-tab =
    .label = إظهار إلغاء تحميل عنصر قائمة التبويب
statusbar-enabled =
    .label = إظهار شريط الحالة
statusbar-show-links =
    .label = إظهار الروابط
statusbar-contrast-text =
    .label = لون نص شريط الحالة المتباين
bookmarks-bar-position-header = موضع شريط المفضلة
bookmarks-position-top =
    .label = أعلى
bookmarks-position-bottom =
    .label = أسفل
geolocation-api-header = API تحديد الموقع الجغرافي
geolocation-description = بعض المواقع تتطلب موقعك للعمل. إذا كان الموقع لا يعمل نتيجة لعدم القدرة على العثور على موقعك، يرجى تمكين هذا التفضيل وحاول مرة أخرى.
geolocation-api-enabled =
    .label = تمكين
geolocation-api-disabled =
    .label = تعطيل
send-referrer-header-0 =
    .label = عدم إرسال ترويسة المحال مطلقاً
send-referrer-header-1 =
    .label = إرسال ترويسة الإحالة فقط عند النقر على الروابط والعناصر المماثلة
send-referrer-header-2 =
    .label = إرسال ترويسة الإحالة على جميع الطلبات (الافتراضي)
enable-webrtc-p2p =
    .label = تمكين اتصال نظير WebRTC
load-images =
    .label = تحميل الصور تلقائياً
enable-javascript =
    .label = تمكين جافا سكريبت
webrtc-header = اتصال أقران WebRTC
ref-header = رأس مرجع HTTP
statusbar-header = شريط الحالة
private-tab =
    .label =
        { $isPrivate ->
            [true] الخروج من علامة التبويب الخاصة
           *[false] إنشاء علامة تبويب خاصة
        }
enable-dooh =
    .label = Use DNS over Oblivious HTTP
waterfox-defaults =
    .label = Waterfox Defaults
enable-menu-transparency =
    .label = Enable menu transparency
auto-hide-tabbar =
    .label = Auto Hide Tab Bar
auto-hide-sidebar =
    .label = Auto Hide Sidebar
auto-hide-back =
    .label = Auto Hide Back Button
drag-space =
    .label = Enable Fixed Drag Space
square-menu-item =
    .label = Square Context Menu Item Corners
compact-context-menu =
    .label = Reduce Context Menu Padding
square-checkbox =
    .label = Square Checkbox
compact-panel-header =
    .label = Reduce Panel Header Padding
compact-bookmark-menu =
    .label = Reduce Bookmarks Menu Padding
show-mac-menu-icons =
    .label = Show Mac Menu Icons
monospace-font =
    .label = Enable monospaced font for page
monospace-font-theme =
    .label = Enable monospaced font for theme
tab-context-line =
    .label = Tab Context Line
panels-header = Panels
tab-bar-header = Tab Bar
full-screen-header = Full screen
onboarding-grassroots-title = Supporting the grassroots
media-player-header = Media Player
telemetry-privacy-policy = Privacy Policy
telemetry-page-subtitle = Waterfox does not collect telemetry about your installation - any telemetry modules are disabled when the browser is built. What you do in your browser is only known by you.
onboarding-grassroots-subtitle = Thank you for using Waterfox, an independent, grassroots browser. With your support, we’re building a sustainable alternative to the big players out there.
tabbrowser-confirm-session-restore-checkbox = Open previous windows and tabs
square-button-edges =
    .label = Square Button Corners
hide-tab-icons =
    .label = Hide Tab Icons
hide-all-icons =
    .label = Hide All Icons
center-tab-label =
    .label = Center Tab Label Only
disable-sidebar-animate =
    .label = Disable sidebar panel animation
hide-bookmarkbar-label =
    .label = Hide Bookmarks Bar Labels
hide-urlbar-iconbox =
    .label = Hide URL Bar Icon Box
square-tab-edges =
    .label = Square Tab Corners
hide-bookmarkbar-icon =
    .label = Hide Bookmarks Bar Icons
rounded-corners =
    .label =
        { $isRounded ->
            [true] Toggle Square Corners
           *[false] Toggle Smooth Corners
        }
hide-sidebar-header =
    .label = Hide Sidebar Header
square-menu-popup =
    .label = Square Context Menu Panel Corners
auto-hide-forward =
    .label = Auto Hide Forward Button
enable-waterfox-theme-2 =
    .label = Disable Waterfox theme customisations
auto-blur-tabs =
    .label = Auto Blur Tabs
full-panel-strip =
    .label = Full Width App Menu Separator
show-menu-icons =
    .label = Show Menu Icons
hide-disabled-menuitems =
    .label = Hide Disabled Menu Items
remove-panel-strip =
    .label = Remove Coloured App Menu Separator
nav-bar-header = Nav Bar
sidebar-header = Sidebar
enable-panel-transparency =
    .label = Enable panel transparency
compact-navbar-popup =
    .label = Reduce Nav Bar Popup Padding
enable-waterfox-theme-0 =
    .label = Enable Waterfox theme customisations on all themes
auto-hide-navbar =
    .label = Auto Hide Nav Bar
square-field =
    .label = Square Entry Field Corners
enable-waterfox-theme-1 =
    .label = Enable Waterfox theme customisations on Waterfox themes
bookmark-header = Bookmarks Bar
disable-panel-animate =
    .label = Disable app menu panel animation
pane-theme-title = Look & Feel
preset-title = Presets
font-header = Fonts
center-navbar-text =
    .label = Center Nav Bar Text
close-button-hover =
    .label = Display close tab button on hover of selected tab when many tabs are open
autohide-all =
    .label =
        { $isAutohide ->
            [true] Toggle Autohide Off
           *[false] Toggle Autohide On
        }
center-tab-content =
    .label = Center Tab Content
auto-hide-tabs =
    .label = Auto Hide Tabs
auto-hide-bookmarkbar =
    .label = Auto Hide Bookmarks Bar
center-all =
    .label =
        { $isCentered ->
            [true] Toggle Centered Off
           *[false] Toggle Centered On
        }
auto-hide-pageaction =
    .label = Auto Hide Page Action
category-theme =
    .tooltiptext = { pane-theme-title }
reduce-padding =
    .label =
        { $isPadded ->
            [true] Toggle Compact Off
           *[false] Toggle Compact On
        }
icons-header = Icons
square-panel-item =
    .label = Square App Menu Item Corners
square-menu-panel =
    .label = Square App Menu Panel Corners
