# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = Dünaamiline kujundus
dynamic-theme-auto =
    .label = Vali hele või tume kujundus dünaamiliselt
dynamic-theme-dark =
    .label = Kasuta sundkorras tumedat kujundust
dynamic-theme-light =
    .label = Kasuta sundkorras heledat kujundust
waterfox-appearance-statusbar-heading =
    .label = Olekuriba
waterfox-appearance-statusbar-enabled-toggle =
    .label = Näita olekuriba
    .description = Näita akna alumises ääres oleku- ja tarvikute riba.
waterfox-appearance-statusbar-links-toggle =
    .label = Näita olekuribal linkide sihtaadresse
pane-theme-title = Välimus ja tunnetus
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = Animatsioonid
appearance-header = Välimus
bookmark-header = Järjehoidjate riba
center-header = Keskel
font-header = Kirjatüübid
full-screen-header = Täisekraanivaade
icons-header = Ikoonid
interface-component-header = Kasutajaliidese komponendid
media-player-header = Mediapleier
panels-header = Ribad
sidebar-header = Külgpaan
tab-bar-header = Vahekaartide paan/riba
theme-header = Kujundus
preset-title = Eelseadistused
lepton-style =
    .label = Lepton-stiil
proton-style =
    .label = Proton-stiil
waterfox-defaults =
    .label = Waterfoxi vaikimisi seadistused
enable-default-accent-color =
    .label = Vaikimisi aktsentvärv
enable-menu-transparency =
    .label = Lülita menüüde läbipaistvus sisse
enable-panel-transparency =
    .label = Lülita ribade/paneelide läbipaistvus sisse
enable-system-accent-color =
    .label = Süsteemi aktsentvärv
hide-all-icons =
    .label = Peida kõik ikoonid
hide-bookmarkbar-icon =
    .label = Peida järjehoidjate riba ikoonid
hide-bookmarkbar-label =
    .label = Peida järjehoidjate riba sildid
hide-disabled-menuitems =
    .label = Peida kasutuselt eemaldatud menüükirjed
hide-sidebar-header =
    .label = Peida külgriba päis
hide-tab-icons =
    .label = Peida vahekaartide ikoonid
waterfox-appearance-theme-mode-picker =
    .label = Kujundus
waterfox-appearance-theme-mode-option-system =
    .label = Süsteemi kujundus
waterfox-appearance-theme-mode-option-light =
    .label = Hele kujundus
waterfox-appearance-theme-mode-option-dark =
    .label = Tume kujundus
waterfox-appearance-theme-color-picker =
    .label = Kujunduse värv
waterfox-appearance-theme-color-option-default =
    .label = Vaikimisi värv
waterfox-appearance-theme-color-option-smoke =
    .label = Suitsukarva
waterfox-appearance-theme-color-option-ash =
    .label = Tuhakarva
waterfox-appearance-theme-color-option-sun =
    .label = Päikeseline
waterfox-appearance-theme-color-option-spark =
    .label = Sädemetes
waterfox-appearance-theme-color-option-flame =
    .label = Leegitsev
waterfox-appearance-theme-color-option-lavender =
    .label = Lavendlikarva
waterfox-appearance-theme-color-option-dusk =
    .label = Hämarduv
waterfox-appearance-theme-color-option-flare =
    .label = Lõõmav
waterfox-appearance-theme-color-option-lagoon =
    .label = Laguun
waterfox-appearance-theme-color-option-tide =
    .label = Madalvesi
waterfox-appearance-theme-color-option-pine =
    .label = Männikarva
waterfox-appearance-transparent-toggle =
    .label = Läbipaistvad ribad/paanid ja menüüd
show-menu-icons =
    .label = Näita menüüde ikoone
show-mac-menu-icons =
    .label = Näita Maci menüüde ikoone
monospace-font-theme =
    .label = Kasuta kujunduses fikseeritud laiusega kirjatüüpi
monospace-font =
    .label = Kasuta lehtedel fikseeritud laiusega kirjatüüpi
auto-hide-sidebar =
    .label = Peida külgpaan automaatselt
auto-hide-tabbar =
    .label = Peida vahekaartide riba automaatselt
auto-hide-tabs =
    .label = Peida vahekaardid automaatselt
compact-bookmark-menu =
    .label = Vähenda järjehoidjate menüü veeriseid
compact-context-menu =
    .label = Vähenda kontekstimenüü veeriseid
compact-panel-header =
    .label = Vähenda riba päise veeriseid
waterfox-density-group =
    .label = Tihedus
    .description = Kui ruumikad peaks olema menüüd ja tööriistaribad.
waterfox-density-compact =
    .label = Kompaktne
waterfox-density-normal =
    .label = Tavaline
waterfox-density-touch =
    .label = Sobilik puuteekraani jaoks
hide-urlbar-iconbox =
    .label = Peida aadressiriba ikoonikast
waterfox-opt-tabbar-heading =
    .label = Vahekaartide riba
    .description = Sinu vahekaartide riba suurus, vahed ja nähtavus.
waterfox-opt-tabbar-fill-width =
    .label = Venita vahekaardid kogu laiusele
waterfox-opt-hidden-tabbar =
    .label = Peida vahekaartide riba
waterfox-opt-tabbar-as-titlebar =
    .label = Näita pealkirjaribal vaid praegust vahekaarti
waterfox-opt-hidden-titlebar-container =
    .label = Peida pealkirjariba konteiner
