# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

feeds-subscribe-button = Telli
    .label = Telli
    .accesskey = S
feeds-subscribe-title =
    .value = Nimi
    .accesskey = N
feeds-subscribe-url =
    .value = Uudisvoo võrguaadress
    .accesskey = U
feeds-subscribe-folder =
    .value = Salvesta asukohta
    .accesskey = v
feeds-subscribe-choose-folder =
    .label = Vali muu kaust…
feeds-subscribe-untitled-folder =
    .label = Nimetu kaust
feeds-subscribe-cancel =
    .label = Katkesta
    .accesskey = C
feeds-preview-page-title = Uudisvood
feeds-reader-page-title = Uudisvoogude lugeja
feeds-direct-page-title = Uudisvoo eelvaade
feeds-settings-button = Uudisvoo seadistused
feeds-private-notice = Privaatses režiimis on loetud või salvestatud artklite tellimine, eemaldamine, uuesti laadimine ja muutmine lülitatud välja.
feeds-subscribe-heading = Telli uudisvoog
feeds-subscribe-open = Ava minu uudisvoogudes
    .label = Ava minu uudisvoogudes
feeds-subscribe-undo = Pööra tegevus tagasi
    .label = Pööra tegevus tagasi
feeds-subscribe-undone = Tellimus on eemaldatud.
feeds-direct-empty = Selles uudisvoos pole ühtegi kirjet.
feeds-status-loading = Laadin tellimusi…
feeds-status-working = Töös…
feeds-status-ready = Tellimused on laaditud.
feeds-status-subscribed = Sa tellisid uudisvoo.
feeds-status-removed = Tellimus on eemaldatud.
feeds-status-reloaded = Uudisvoog on uuesti laaditud.
feeds-status-preview = Näitan uudisvoo salvestatud sisu.
feeds-status-direct-preview = Näitan uudisvoo eelvaadet.
feeds-error-unavailable = Sellel lehel pole uudisvoo haldus saadaval. Ava about:feeds leht uuel vahekaardil.
feeds-all = Kõik uudisvood
feeds-saved = Salvestatud
feeds-add = Lisa uudisvoog
feeds-add-url-label = Uudisvoo võrguaadress
feeds-add-preview = Uudisvoo eelvaade
feeds-add-cancel = Katkesta
feeds-add-confirm = Lisa uudisvoog
feeds-add-name-label = Nimi
feeds-add-folder-label = Salvesta kausta
feeds-open-feeds = Ava minu uudisvoogudes
feeds-undo = Võta tellimine tagasi
feeds-manage = Halda uusidvooge
feeds-search-articles = Otsi artikleid
feeds-all-filter = Kõik
feeds-unread-filter = Lugemata
feeds-display-list = Loendivaade
feeds-display-cards = Vahekaartide vaade
feeds-order-newest = Esmalt uuemad
feeds-order-oldest = Esmalt vanemad
feeds-open-original = Ava algne sisu
feeds-mark-read = Märgi loetuks
    .title = Märgi loetuks
feeds-mark-unread = Märgi mitteloetuks
    .title = Märgi mitteloetuks
feeds-save = Salvesta artikkel
    .title = Salvesta artikkel
feeds-unsave = Eemalda salvestatute seast
    .title = Eemalda salvestatute seast
feeds-mark-read-button =
    .aria-label = Märgi loetuks
    .title = Märgi loetuks
feeds-mark-unread-button =
    .aria-label = Märgi mitteloetuks
    .title = Märgi mitteloetuks
feeds-save-button =
    .aria-label = Salvesta artikkel
    .title = Salvesta artikkel
feeds-unsave-button =
    .aria-label = Eemalda salvestatute seast
    .title = Eemalda salvestatute seast
feeds-back = Tagasi
feeds-previous = Eelmine
feeds-next = Näita järgmist artiklit
feeds-reader-load-error = Selle artikli kuvamine ei õnnestunud. Mine tagasi ja proovi uuesti või lugemaks sisu antud saidis vali „Ava algne sisu“.
feeds-subscribe-folder-error = Vali olemasolev järjehoidjate kaust ja proovi uuesti.
