# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dynamic-theme-header = ທິມທີ່ປັບປ່ຽນໄດ້
dynamic-theme-auto =
    .label = ຕັ້ງຄ່າໂໝດສະຫວ່າງ/ມືດ ແບບໄດນາມິກ
dynamic-theme-dark =
    .label = ບັງຄັບໃຊ້ໂໝດມືດ
dynamic-theme-light =
    .label = ບັງຄັບໃຊ້ໂໝດສະຫວ່າງ
waterfox-appearance-statusbar-heading =
    .label = ແຖບສະຖານະ
waterfox-appearance-statusbar-enabled-toggle =
    .label = ສະແດງແຖບສະຖານະ
    .description = ສະແດງແຖບເຄື່ອງມືຢູ່ທາງລຸ່ມຂອງໜ້າຕ່າງ.
waterfox-appearance-statusbar-links-toggle =
    .label = ສະແດງປາຍທາງຂອງລິ້ງໃນແຖບສະຖານະ
pane-theme-title = ຮູບລັກສະນະ ແລະ ຄວາມຮູ້ສຶກ
category-theme =
    .tooltiptext = { pane-theme-title }
animation-header = ແອນິເມຊັນ
appearance-header = ຮູບລັກສະນະ
autohide-hidden-header = ເຊື່ອງອັດຕະໂນມັດ ແລະ ສິ່ງທີ່ເຊື່ອງໄວ້
bookmark-header = ແຖບບຸກມາກ
center-header = ກາງ
font-header = ຟອນ
full-screen-header = ເຕັມຈໍ
icons-header = ໄອຄອນ
interface-component-header = ສ່ວນປະກອບຂອງອິນເຕີເຟດ
media-player-header = ເຄື່ອງຫຼິ້ນສື່
nav-bar-header = ແຖບນຳທາງ
panels-header = ແຜງຄວບຄຸມ
rounding-header = ຄວາມໂຄ້ງມົນ
sidebar-header = ແຖບຂ້າງ
tab-bar-header = ແຖບແທັບ
theme-header = ທິມ
preset-title = ຄ່າທີ່ຕັ້ງໄວ້ກ່ອນ
lepton-style =
    .label = ສະໄຕລ໌ Lepton
proton-style =
    .label = ສະໄຕລ໌ Proton
waterfox-defaults =
    .label = ຄ່າເລີ່ມຕົ້ນຂອງ Waterfox
auto-blur-tabs =
    .label = ເຮັດໃຫ້ແທັບມົວອັດຕະໂນມັດ
auto-hide-back =
    .label = ເເຊື່ອງປຸ່ມຍ້ອນກັບອັດຕະໂນມັດ
auto-hide-bookmarkbar =
    .label = ເຊື່ອງແຖບບຸກມາກອັດຕະໂນມັດ
auto-hide-forward =
    .label = ເຊື່ອງປຸ່ມໄປຂ້າງໜ້າອັດຕະໂນມັດ
auto-hide-navbar =
    .label = ເຊື່ອງແຖບນຳທາງອັດຕະໂນມັດ
auto-hide-pageaction =
    .label = ເຊື່ອງການກະທຳຂອງໜ້າອັດຕະໂນມັດ
auto-hide-sidebar =
    .label = ເຊື່ອງແຖບຂ້າງອັດຕະໂນມັດ
auto-hide-tabbar =
    .label = ເຊື່ອງແຖບແທັບອັດຕະໂນມັດ
auto-hide-tabs =
    .label = ເຊື່ອງແທັບອັດຕະໂນມັດ
center-navbar-text =
    .label = ຈັດຂໍ້ຄວາມແຖບນຳທາງໄວ້ກາງ
center-tab-content =
    .label = ຈັດເນື້ອຫາແທັບໄວ້ກາງ
center-tab-label =
    .label = ຈັດປ້າຍຊື່ແທັບໄວ້ກາງເທົ່ານັ້ນ
close-button-hover =
    .label = ສະແດງປຸ່ມປິດແທັບເມື່ອວາງເມົາສ໌ໃສ່ແທັບທີ່ເລືອກ ໃນຂະນະທີ່ມີຫຼາຍແທັບເປີດຢູ່
compact-bookmark-menu =
    .label = ຫຼຸດໄລຍະຫ່າງຂອງເມນູບຸກມາກ
compact-context-menu =
    .label = ຫຼຸດໄລຍະຫ່າງຂອງເມນູຄລິກຂວາ
compact-navbar-popup =
    .label = ຫຼຸດໄລຍະຫ່າງຂອງປັອບອັບແຖບນຳທາງ
compact-panel-header =
    .label = ຫຼຸດໄລຍະຫ່າງຂອງສ່ວນຫົວແຜງຄວບຄຸມ
disable-panel-animate =
    .label = ປິດການໃຊ້ງານແອນິເມຊັນຂອງແຜງເມນູແອັບ
disable-sidebar-animate =
    .label = ປິດການໃຊ້ງານແອນິເມຊັນຂອງແຜງແຖບຂ້າງ
drag-space =
    .label = ເປີດໃຊ້ງານພື້ນທີ່ລາກແບບຄົງທີ່
enable-cyan-accent-color =
    .label = ສີເນັ້ນແບບຟ້າຂຽວ
enable-default-accent-color =
    .label = ສີເນັ້ນເລີ່ມຕົ້ນ
enable-menu-transparency =
    .label = ເປີດໃຊ້ຄວາມໂປ່ງໃສຂອງເມນູ
enable-panel-transparency =
    .label = ເປີດໃຊ້ຄວາມໂປ່ງໃສຂອງແຜງຄວບຄຸມ
enable-system-accent-color =
    .label = ສີເນັ້ນຕາມລະບົບ
enable-waterfox-theme-0 =
    .label = ເປີດໃຊ້ການປັບແຕ່ງທິມ Waterfox ໃນທຸກໆທິມ
enable-waterfox-theme-1 =
    .label = ເປີດໃຊ້ການປັບແຕ່ງທິມ Waterfox ໃນທິມຂອງ Waterfox ເທົ່ານັ້ນ
enable-waterfox-theme-2 =
    .label = ປິດການໃຊ້ງານການປັບແຕ່ງທິມ Waterfox
full-panel-strip =
    .label = ເສັ້ນຂັ້ນເມນູແອັບແບບເຕັມຄວາມກວ້າງ
remove-panel-strip =
    .label = ເອົາເສັ້ນຂັ້ນເມນູແອັບທີ່ມີສີອອກ
hide-all-icons =
    .label = ເຊື່ອງໄອຄອນທັງໝົດ
hide-bookmarkbar-icon =
    .label = ເຊື່ອງໄອຄອນແຖບບຸກມາກ
hide-bookmarkbar-label =
    .label = ເຊື່ອງປ້າຍຊື່ແຖບບຸກມາກ
hide-disabled-menuitems =
    .label = ເຊື່ອງລາຍການເມນູທີ່ຖືກປິດໃຊ້ງານ
hide-sidebar-header =
    .label = ເຊື່ອງສ່ວນຫົວຂອງແຖບຂ້າງ
hide-tab-icons =
    .label = ເຊື່ອງໄອຄອນແທັບ
hide-urlbar-iconbox =
    .label = ເຊື່ອງກ່ອງໄອຄອນໃນແຖບ URL
monospace-font =
    .label = ເປີດໃຊ້ຟອນແບບ Monospaced ສໍາລັບໜ້າເວັບ
monospace-font-theme =
    .label = ເປີດໃຊ້ຟອນແບບ Monospaced ສໍາລັບທິມ
show-mac-menu-icons =
    .label = ສະແດງໄອຄອນເມນູແບບ Mac
show-menu-icons =
    .label = ສະແດງໄອຄອນເມນູ
square-button-edges =
    .label = ມຸມປຸ່ມແບບຫຼ່ຽມ
square-checkbox =
    .label = ຊ່ອງໝາຍຕິກແບບຫຼ່ຽມ
square-field =
    .label = ມຸມຊ່ອງປ້ອນຂໍ້ມູນແບບຫຼ່ຽມ
square-menu-item =
    .label = ມຸມລາຍການເມນູຄລິກຂວາແບບຫຼ່ຽມ
square-menu-panel =
    .label = ມຸມແຜງເມນູແອັບແບບຫຼ່ຽມ
square-menu-popup =
    .label = ມຸມແຜງເມນູຄລິກຂວາແບບຫຼ່ຽມ
square-panel-item =
    .label = ມຸມລາຍການເມນູແອັບແບບຫຼ່ຽມ
square-tab-edges =
    .label = ມຸມແທັບແບບຫຼ່ຽມ
tab-context-line =
    .label = ເສັ້ນສະຖານະແທັບ
waterfox-appearance-browser-style-group =
    .label = ສະໄຕລ໌ບຣາວເຊີ
    .description = ເລືອກຮູບລັກສະນະໂດຍລວມຂອງ Waterfox.
waterfox-appearance-browser-style-option-nova =
    .label = Nova
    .title = ຮູບລັກສະນະທີ່ເປັນເອກະລັກຂອງ Waterfox ໃນບຣາວເຊີມາດຕະຖານ.
waterfox-appearance-browser-style-option-proton =
    .label = Proton
    .title = ຮູບແບບບຣາວເຊີມາດຕະຖານທີ່ທັນສະໄໝ.
waterfox-appearance-browser-style-option-photon =
    .label = Photon
    .title = ຮູບແບບ Waterfox ແບບຄລາດສິກ ທີ່ຖືກປັບແຕ່ງໃໝ່.
waterfox-appearance-theme-colors-group =
    .label = ໂທນສີ
    .description = ເລືອກໂທນສີຂອງ Waterfox ແລະ ກໍານົດວ່າໃຫ້ມັນປ່ຽນຕາມທິມຂອງລະບົບຫຼືບໍ່.
waterfox-appearance-theme-mode-picker =
    .label = ໂໝດທິມ
waterfox-appearance-theme-mode-option-system =
    .label = ລະບົບ
waterfox-appearance-theme-mode-option-light =
    .label = ສະຫວ່າງ
waterfox-appearance-theme-mode-option-dark =
    .label = ມືດ
waterfox-appearance-theme-color-picker =
    .label = ສີທິມ
waterfox-appearance-theme-color-option-default =
    .label = ຄ່າເລີ່ມຕົ້ນ
waterfox-appearance-theme-color-option-smoke =
    .label = ຄວັນໄຟ
waterfox-appearance-theme-color-option-ash =
    .label = ຂີ້ເຖົ່າ
waterfox-appearance-theme-color-option-sun =
    .label = ດວງອາທິດ
waterfox-appearance-theme-color-option-spark =
    .label = ປະກາຍໄຟ
waterfox-appearance-theme-color-option-flame =
    .label = ແປວໄຟ
waterfox-appearance-theme-color-option-flare =
    .label = ແສງວາບ
waterfox-appearance-theme-color-option-lavender =
    .label = ລາເວນເດີ
waterfox-appearance-theme-color-option-dusk =
    .label = ຍາມຄໍ່າຄືນ
waterfox-appearance-theme-color-option-lagoon =
    .label = ທະເລສາບ
waterfox-appearance-theme-color-option-tide =
    .label = ນ້ຳຂຶ້ນນ້ຳລົງ
waterfox-appearance-theme-color-option-pine =
    .label = ຕົ້ນສົນ
waterfox-appearance-details-group =
    .label = ຕົວເລືອກຮູບລັກສະນະເພີ່ມເຕີມ
    .description = ປັບແຕ່ງອິນເຕີເຟດຂອງ Waterfox ໃຫ້ລະອຽດຂຶ້ນ.
waterfox-appearance-transparent-toggle =
    .label = ແຜງຄວບຄຸມ ແລະ ເມນູແບບໂປ່ງໃສ
waterfox-appearance-autohide-tabbar-toggle =
    .label = ເຊື່ອງແຖບແທັບໄວ້ຈົນກວ່າເຈົ້າຈະວາງເມົາສ໌ໃສ່
waterfox-appearance-autohide-bookmarks-toggle =
    .label = ເຊື່ອງແຖບເຄື່ອງມືບຸກມາກໄວ້ຈົນກວ່າເຈົ້າຈະວາງເມົາສ໌ໃສ່
waterfox-appearance-autohide-sidebar-toggle =
    .label = ເຊື່ອງແຖບຂ້າງໄວ້ຈົນກວ່າເຈົ້າຈະວາງເມົາສ໌ໃສ່
waterfox-appearance-autohide-navigation-toggle =
    .label = ເຊື່ອງປຸ່ມຍ້ອນກັບ ແລະ ໄປຂ້າງໜ້າ ເມື່ອບໍ່ສາມາດກົດໄດ້
waterfox-appearance-close-button-hover-toggle =
    .label = ສະແດງປຸ່ມປິດແທັບເມື່ອວາງເມົາສ໌ໃສ່ເທົ່ານັ້ນ
waterfox-appearance-drag-space-toggle =
    .label = ເປີດໃຊ້ພື້ນທີ່ລາກໄວ້ເທິງແຖບແທັບ
